#let images = (
  "4-1": (
    caption: [Structure of the enzyme chymotrypsin, a globular protein. A molecule of glycine (gray) is shown for size comparison. The known three-dimensional structures of proteins are archived in the Protein Data Bank, or PDB (see Box 4–4). The image shown here was made using data from the entry with PDB ID 6GCH.],
    path: "../fig/fig-2025-09-26-11-01-58.png"
  ),
  "4-2": (
    caption: [The planar peptide group. (a) Each peptide bond has some double-bond character due to resonance and cannot rotate. Although the N atom in a peptide bond is often represented with a partial positive charge, careful consideration of bond orbitals and quantum mechanics indicates that the N has a net charge that is neutral or slightly negative. (b) Three bonds separate sequential α carbons in a polypeptide chain. The N—Cα and Cα—C bonds can rotate, described by dihedral angles designated φ and ψ, respectively. The peptide C—N bond is not free to rotate. Other single bonds in the backbone may also be rotationally hindered, depending on the size and charge of the R groups. (c) The atoms and planes defining φ. (d) By convention, φ and ψ are 180° (or –180°) when the first and fourth atoms are farthest apart and the peptide is fully extended. As the viewer looks out along the bond undergoing rotation (from either direction), the φ and ψ angles increase as the fourth atom rotates clockwise relative to the first. In a protein, some of the conformations shown here (e.g., 0°) are prohibited by steric overlap of atoms. In (b) through (d), the balls representing atoms are smaller than the van der Waals radii for this scale.],
    path: "../fig/fig-2025-09-26-11-03-11.png"
  ),
  "4-3": (
    caption: [Ramachandran plot for L-Ala residues. Peptide conformations are defined by the values of φ and ψ. Conformations deemed possible are those that involve little or no steric interference, based on calculations using known van der Waals radii and dihedral angles. The areas shaded dark blue represent conformations that involve no steric overlap if the van der Waals radii of each atom are modeled as a hard sphere and thus are fully allowed; medium blue indicates conformations permitted if atoms are allowed to approach each other by an additional 0.1 nm, a slight clash; the lightest blue indicates conformations that are permissible if a very modest flexibility (a few degrees) is allowed in the ω dihedral angle that describes the peptide bond itself (generally constrained to 180°). The white regions are conformations that are not allowed. The asymmetry of the plot results from the L stereochemistry of the amino acid residues. The plots for other L residues with unbranched side chains are nearly identical. Allowed ranges for branched residues such as Val, Ile, and Thr are somewhat smaller than for Ala. The Gly residue, which is less sterically hindered, has a much broader range of allowed conformations. The range for Pro residues is greatly restricted because φ is limited by the cyclic side chain to the range of –35° to –85°.],
    path: "../fig/fig-2025-09-26-11-03-49.png"
  ),
  "4-4": (
    caption: [Models of the α helix, showing different aspects of its structure. (a) Ball-and-stick model showing the intrachain hydrogen bonds. The repeat unit is a single turn of the helix, 3.6 residues. (b) The α helix viewed from one end, looking down the longitudinal axis (derived from PDB ID 4TNC). Note the positions of the R groups, represented by purple spheres. This ball-and-stick model, which emphasizes the helical arrangement, gives the false impression that the helix is hollow, because the balls do not represent the van der Waals radii of the individual atoms. (c) As this space-filling model shows, the atoms in the center of the helix are in very close contact. (d) Helical wheel projection of an α helix. This representation can be colored to identify surfaces with particular properties. The yellow residues, for example, could be hydrophobic and conform to an interface between the helix shown here and another part of the same or another polypeptide. The red (negative) and blue (positive) residues illustrate the potential for interaction of oppositely charged side chains separated by two residues in the helix.],
    path: "../fig/fig-2025-09-26-11-04-30.png"
  ),
  "4-5": (
    caption: [Helix dipole. The electric dipole of a peptide bond (see Fig. 4–2a) is transmitted along an α-helical segment through the intrachain hydrogen bonds, resulting in an overall helix dipole. In this illustration, the amino and carbonyl constituents of each peptide bond are indicated by + and – symbols, respectively. Non–hydrogen-bonded amino and carbonyl constituents of the peptide bonds near each end of the α-helical region are circled and shown in color.],
    path: "../fig/fig-2025-09-26-11-05-00.png"
  ),
  "4-6": (
    caption: [The β conformation of polypeptide chains. These (a) side and (b, c) top views reveal the R groups extending out from the β sheet and emphasize the pleated shape formed by the planes of the peptide bonds. (An alternative name for this structure is β-pleated sheet.) Hydrogen-bond cross-links between adjacent chains are also shown. The amino-terminal to carboxyl-terminal orientations of adjacent chains (arrows) can be the same or opposite, forming (b) an antiparallel β sheet or (c) a parallel β sheet.],
    path: "../fig/fig-2025-09-26-11-06-27.png"
  ),
  "4-7": (
    caption: [Structures of β turns. Type I and type II turns are most common, distinguished by the φ and ψ angles taken up by the peptide backbone in the turn (see Table 4–1). Type I turns occur more than twice as frequently as type II. Type II turns usually have Gly as the third residue. Note the hydrogen bond between the peptide groups of the first and fourth residues of the bends. (Individual amino acid residues are framed by large blue circles. Not all H atoms are shown in these depictions.)],
    path: "../fig/fig-2025-09-26-11-07-00.png"
  ),
  "4-8": (
    caption: [Trans and cis isomers of a peptide bond involving the imino nitrogen of proline. Of the peptide bonds between amino acid residues other than Pro, more than 99.95% are in the trans configuration. For peptide bonds involving the imino nitrogen of proline, however, about 6% are in the cis configuration; many of these occur at β turns.],
    path: "../fig/fig-2025-09-26-11-07-50.png"
  ),
  "4-9": (
    caption: [Ramachandran plots showing a variety of structures. (a) The values of φ and ψ for various allowed secondary structures are overlaid on the plot from Figure 4–3. Although left-handed α helices extending over several amino acid residues are theoretically possible, they have not been observed in proteins. (b) The values of φ and ψ for all the amino acid residues except Gly in the enzyme pyruvate kinase (isolated from rabbit) are overlaid on the plot of theoretically allowed conformations (Fig. 4–3). The small, flexible Gly residues were excluded because they frequently fall outside the expected (blue) ranges.],
    path: "../fig/fig-2025-09-26-11-08-48.png"
  ),
  "4-10": (
    caption: [Circular dichroism spectroscopy. These spectra show polylysine entirely as α helix, as β conformation, or as a denatured, random coil. The y axis unit is a simplified version of the units most commonly used in CD experiments. Since the curves are different for α helix, β conformation, and random coil, the CD spectrum for a given protein can provide a rough estimate for the fraction of the protein made up of the two most common secondary structures. The CD spectrum of the native protein can serve as a benchmark for the folded state, useful for monitoring denaturation or conformational changes brought about by changes in solution conditions.],
    path: "../fig/fig-2025-09-26-11-09-23.png"
  ),
  "4-11": (
    caption: [Structure of hair. (a) Hair α-keratin is an elongated α helix with somewhat thicker elements near the amino and carboxyl termini. Pairs of these helices are interwound in a left-handed sense to form two-chain coiled coils. These then combine in higher-order structures called protofilaments and protofibrils. About four protofibrils—32 strands of α-keratin in all—combine to form an intermediate filament. The individual two-chain coiled coils in the various substructures also seem to be interwound, but the handedness of the interwinding and other structural details are unknown. (b) A hair is an array of many α-keratin filaments, made up of the substructures shown in (a).],
    path: "../fig/fig-2025-09-26-11-13-10.png"
  ),
  "4-12": (
    caption: [Structure of collagen. (Derived from PDB ID 1CGD) (a) The α chain of collagen has a repeating secondary structure unique to this protein. The repeating tripeptide sequence Gly–X–Pro or Gly–X–4-Hyp adopts a left-handed helical structure with three residues per turn. The repeating sequence used to generate this model is Gly–Pro–4-Hyp. (b) Space-filling model of the same α chain. (c) Three of these helices (shown here in gray, blue, and purple) wrap around one another with a right-handed twist. (d) The three-stranded collagen superhelix shown from one end, in a ball-and-stick representation. Gly residues are shown in red. Glycine, because of its small size, is required at the tight junction where the three chains are in contact. The balls in this illustration do not represent the van der Waals radii of the individual atoms. The center of the three-stranded superhelix is not hollow, as it appears here, but very tightly packed.],
    path: "../fig/fig-2025-09-26-11-18-08.png"
  ),
  "4-13": (
    caption: [Structure of collagen fibrils. Collagen (Mr 300,000) is a rod-shaped molecule, about 3,000 Å long and only 15 Å thick. Its three helically intertwined α chains may have different sequences; each chain has about 1,000 amino acid residues. Collagen fibrils are made up of collagen molecules aligned in a staggered fashion and cross-linked for strength. The specific alignment and degree of cross-linking vary with the tissue and produce characteristic cross-striations in an electron micrograph. In the example shown here, alignment of the head groups of every fourth molecule produces striations 640 Å (64 nm) apart.],
    path: "../fig/fig-2025-09-26-11-18-50.png"
  ),
  "4-14": (
    caption: [Structure of silk. The fibers in silk cloth and in a spiderweb are made up primarily of the protein fibroin. (a) Fibroin consists of layers of antiparallel β sheets rich in Ala and Gly residues. The small side chains interdigitate and allow close packing of the sheets, as shown in the ball-and-stick view. The segments shown would be just a small part of the fibroin strand. (b) Strands of silk (blue) emerge from the spinnerets of a spider in this colorized scanning electron micrograph.],
    path: "../fig/fig-2025-09-26-11-21-13.png"
  ),
  "4-15": (
    caption: [Globular protein structures are compact and varied. Human serum albumin (Mr 64,500) has 585 residues in a single chain. Given here are the approximate dimensions its single polypeptide chain would have if it occurred entirely in extended β conformation or as an α helix. Also shown is the size of the protein in its native globular form, as determined by x-ray crystallography; the polypeptide chain must be very compactly folded to fit into these dimensions.],
    path: "../fig/fig-2025-09-26-11-22-07.png"
  ),
  "4-16": (
    caption: [Tertiary structure of sperm whale myoglobin. (PDB ID 1MBO) Orientation of the protein is similar in (a) through (d); the heme group is shown in red. In addition to illustrating the myoglobin structure, this figure provides examples of several different ways to display protein structure. (a) The polypeptide backbone in a ribbon representation of a type introduced by Jane Richardson, which highlights regions of secondary structure. The α-helical regions are evident. (b) Surface contour image; this is useful for visualizing pockets in the protein where other molecules might bind. (c) Ribbon representation including side chains (yellow) for the hydrophobic residues Leu, Ile, Val, and Phe. (d) Space-filling model with all amino acid side chains. Each atom is represented by a sphere encompassing its van der Waals radius. The hydrophobic residues are again shown in yellow; most are buried in the interior of the protein and thus not visible.],
    path: "../fig/fig-2025-09-26-11-22-32.png"
  ),
  "4-17": (
    caption: [The heme group. This group is present in myoglobin, hemoglobin, cytochromes, and many other proteins (the heme proteins). (a) Heme consists of a complex organic ring structure, protoporphyrin, which binds an iron atom in its ferrous (Fe2+) state. The iron atom has six coordination bonds, four in the plane of, and bonded to, the flat porphyrin molecule and two perpendicular to it. (b) In myoglobin and hemoglobin, one of the perpendicular coordination bonds is bound to a nitrogen atom of a His residue. The other is “open” and serves as the binding site for an O2 molecule.],
    path: "../fig/fig-2025-09-26-11-23-19.png"
  ),
  "4-18": (
    caption: [Motifs. (a) A simple motif, the β-α-β loop. (b) A more elaborate motif, the β barrel. This β barrel is a single domain of α-hemolysin (a toxin that kills a cell by creating a hole in its membrane) from the bacterium Staphylococcus aureus (derived from PDB ID 7AHL).],
    path: "../fig/fig-2025-09-26-11-24-27.png"
  ),
  "4-19": (
    caption: [Structural domains in the polypeptide troponin C. (PDB ID 4TNC) This calcium-binding protein, associated with muscle, has two separate calcium-binding domains, shown here in brown and blue.],
    path: "../fig/fig-2025-09-26-11-24-54.png"
  ),
  "4-20": (
    caption: [Stable folding patterns in proteins. (a) Connections between β strands in layered β sheets. The strands here are viewed from one end, with no twisting. Thick lines represent connections at the ends nearest the viewer; thin lines are connections at the far ends of the β strands. The connections at a given end (e.g., near the viewer) rarely cross one another. An example of such a rare crossover is illustrated by the yellow strand in the structure on the right. (b) Because of the right-handed twist in β strands, connections between strands are generally right-handed. Left-handed connections must traverse sharper angles and are harder to form. (c) This twisted β sheet is from a domain of photolyase (a protein that repairs certain types of DNA damage) from E. coli (derived from PDB ID 1DNP). Connecting loops have been removed so as to focus on the folding of the β sheet.],
    path: "../fig/fig-2025-09-26-11-25-19.png"
  ),
  "4-21": (
    caption: [Constructing large motifs from smaller ones. The α/β barrel is a commonly occurring motif constructed from repetitions of the β-α-β loop motif. This α/β barrel is a domain of pyruvate kinase (a glycolytic enzyme) from rabbit (derived from PDB ID 1PKN).],
    path: "../fig/fig-2025-09-26-11-25-42.png"
  ),
  "4-22": (
    caption: [Organization of proteins based on motifs. Shown here are a few of the hundreds of known stable motifs divided into four classes: all α, all β, α/β, and α + β. Structural classification data from the SCOP (Structural Classification of Proteins) database (http://scop.mrc-lmb.cam.ac.uk/scop) are also provided (see the color key). The PDB identifier (listed first for each structure) is the unique accession code given to each structure archived in the Protein Data Bank (www.pdb.org). The α/β barrel (see Fig. 4–21) is another particularly common α/β motif.],
    path: "../fig/fig-2025-09-26-11-26-29.png"
  ),
  "4-23": (
    caption: [Quaternary structure of deoxyhemoglobin. (PDB ID 2HHB) X-ray diffraction analysis of deoxyhemoglobin (hemoglobin without oxygen molecules bound to the heme groups) shows how the four polypeptide subunits are packed together. (a) A ribbon representation reveals the secondary structural elements of the structure and the positioning of all the heme cofactors. (b) A surface contour model shows the pockets in which the heme cofactors are bound and helps to visualize subunit packing. The α subunits are shown in shades of gray; the β subunits in shades of blue. Note that the heme groups (red) are relatively far apart.],
    path: "../fig/fig-2025-09-26-11-27-05.png"
  ),
  "4-24": (
    caption: [Binding of the intrinsically disordered carboxyl terminus of p53 protein to its binding partners. (a) The p53 protein is made up of several different segments (PDB ID 1XQH). Only the central domain is well ordered. (b) The linear sequence of the p53 protein is depicted as a colored bar. The overlaid graph presents a plot of the PONDR (Predictor of Natural Disordered Regions) score versus the protein sequence. PONDR is one of the best available algorithms for predicting the likelihood that a given amino acid residue is in a region of intrinsic disorder, based on the surrounding amino acid sequence and amino acid composition. A score of 1.0 indicates a probability of 100% that a protein will be disordered. In the actual protein structure, the tan central domain is ordered. The amino-terminal (blue) and carboxyl-terminal (red) regions are disordered. The very end of the carboxyl-terminal region has multiple binding partners and folds when it binds to each of them; however, the three-dimensional structure that is assumed when binding occurs is different for each of the interactions shown, and thus the color of this carboxyl-terminal segment (11 to 20 residues) is shown in a different color in each complex (cyclin A, PDB ID 1H26; sirtuin, PDB ID 1MA3; CBP bromo domain, PDB ID 1JSP; s100B(ββ), PDB ID 1DT7).],
    path: "../fig/fig-2025-09-26-11-27-32.png"
  ),
  "4-25": (
    caption: [Pathways that contribute to proteostasis. Three kinds of processes contribute to proteostasis, in some cases with multiple contributing pathways. First, proteins are synthesized on a ribosome. Second, multiple pathways contribute to protein folding, many of which involve the activity of complexes called chaperones. Chaperones (including chaperonins) also contribute to the refolding of proteins that are partially and transiently unfolded. Finally, proteins that are irreversibly unfolded are subject to sequestration and degradation by several additional pathways. Partially unfolded proteins and protein-folding intermediates that escape the quality-control activities of the chaperones and degradative pathways may aggregate, forming both disordered aggregates and ordered amyloid-like aggregates that contribute to disease and aging processes.],
    path: "../fig/fig-2025-09-26-11-27-59.png"
  ),
  "4-26": (
    caption: [Protein denaturation. Results are shown for proteins denatured by two different environmental changes. In each case, the transition from the folded to the unfolded state is abrupt, suggesting cooperativity in the unfolding process. (a) Thermal denaturation of horse apomyoglobin (myoglobin without the heme prosthetic group) and ribonuclease A (with its disulfide bonds intact; see Fig. 4–27). The midpoint of the temperature range over which denaturation occurs is called the melting temperature, or Tm. Denaturation of apomyoglobin was monitored by circular dichroism (see Fig. 4–10), which measures the amount of helical structure in the protein. Denaturation of ribonuclease A was tracked by monitoring changes in the intrinsic fluorescence of the protein, which is affected by changes in the environment of Trp residues. (b) Denaturation of disulfide-intact ribonuclease A by guanidine hydrochloride (GdnHCl), monitored by circular dichroism.],
    path: "../fig/fig-2025-09-26-11-28-19.png"
  ),
  "4-27": (
    caption: [Renaturation of unfolded, denatured ribonuclease. Urea denatures the ribonuclease, and mercaptoethanol (HOCH2CH2SH) reduces and thus cleaves the disulfide bonds to yield eight Cys residues. Renaturation involves reestablishing the correct disulfide cross-links.],
    path: "../fig/fig-2025-09-26-11-28-59.png"
  ),
  "4-28": (
    caption: [A protein-folding pathway as defined for a small protein. A hierarchical pathway is shown, based on computer modeling. Small regions of secondary structure are assembled first and then gradually incorporated into larger structures. The program used for this model has been highly successful in predicting the three-dimensional structure of small proteins from their amino acid sequence. The numbers indicate the amino acid residues in this 56 residue peptide that have acquired their final structure in each of the steps shown.],
    path: "../fig/fig-2025-09-26-11-29-19.png"
  ),
  "4-29": (
    caption: [The thermodynamics of protein folding depicted as free-energy funnels. As proteins fold, the conformational space that can be explored by the structure is constrained. This is modeled as a three-dimensional thermodynamic funnel, with ΔG represented as depth and with the native structure (N) at the bottom (lowest free-energy point) of the funnel. The funnel for a given protein can have a variety of shapes, depending on the number and types of folding intermediates in the folding pathways. Any folding intermediate with significant stability and a finite lifetime would be represented as a local free-energy minimum—a depression on the surface of the funnel. (a) A simple but relatively wide and smooth funnel represents a protein that has multiple folding pathways (that is, the order in which different parts of the protein fold would be somewhat random), but it assumes its three-dimensional structure with no folding intermediates that have significant stability. (b) This funnel represents a more typical protein that has multiple possible folding intermediates with significant stability on the multiple pathways leading to the native structure. (c) A protein with one stable native structure, essentially no other folded intermediates with significant stability, and only one or a very few productive folding pathways is shown as a funnel with one narrow depression leading to the native form. (d) A protein with folding intermediates of substantial stability on virtually every pathway leading to the native state (that is, a protein in which a particular motif or domain always folds quickly, but other parts of the protein fold more slowly and in a random order) is depicted by a funnel with a major depression surrounding the depression leading to the native form.],
    path: "../fig/fig-2025-09-26-11-29-46.png"
  ),
  "4-30": (
    caption: [Chaperones in protein folding. The pathway by which Hsp70-class chaperones bind and release polypeptides is illustrated for the eukaryotic chaperones Hsp70 and Hsp40. The chaperones do not actively promote the folding of the substrate protein, but instead prevent aggregation of unfolded peptides. The unfolded or partly folded proteins bind first to the open, ATP-bound form of Hsp70 (PDB ID 2QXL). Hsp40 then interacts with this complex and triggers ATP hydrolysis that produces the closed form of the complex (derived from PDB IDs 2KHO and 1DKZ), where the domains colored orange and yellow come together like the two parts of a jaw, trapping parts of the unfolded protein inside. Dissociation of ADP and recycling of the Hsp70 requires interaction with another protein, nucleotide-exchange factor (NEF). For a population of polypeptide molecules, some fraction of the molecules released after the transient binding of partially folded proteins by Hsp70 will take up the native conformation. The remainder are rebound by Hsp70 or diverted to the chaperonin system (Hsp60; see Fig. 4–31). In bacteria, the Hsp70 and Hsp40 chaperones are called DnaK and DnaJ, respectively. DnaK and DnaJ were first identified as proteins required for in vitro replication of certain viral DNA molecules (hence the “Dna” designation).],
    path: "../fig/fig-2025-09-26-11-30-24.png"
  ),
  "4-31": (
    caption: [Chaperonins in protein folding. (a) A proposed pathway for the action of the E. coli chaperonins GroEL (a member of the Hsp60 protein family) and GroES. Each GroEL complex consists of two large chambers formed by two heptameric rings (each subunit Mr 57,000). GroES, also a heptamer (subunit Mr 10,000), blocks one of the GroEL chambers after an unfolded protein is bound inside. The chamber with the unfolded protein is referred to as cis; the opposite one is trans. Folding occurs within the cis chamber, during the time it takes to hydrolyze the 7 ATP bound to the subunits in the heptameric ring. The GroES and the ADP molecules then dissociate, and the protein is released. The two chambers of the GroEL/Hsp60 systems alternate in the binding and facilitated folding of client proteins. (b) Surface and cutaway images of the GroEL/GroES complex (PDB ID 1AON). The cutaway (below) illustrates the large interior space within which other proteins are bound.],
    path: "../fig/fig-2025-09-26-11-30-54.png"
  ),
  "4-32": (
    caption: [Formation of disease-causing amyloid fibrils. (a) Protein molecules whose normal structure includes regions of β sheet undergo partial folding. In a small number of the molecules, before folding is complete, the β-sheet regions of one polypeptide associate with the same region in another polypeptide, forming the nucleus of an amyloid. Additional protein molecules slowly associate with the amyloid and extend it to form a fibril. (b) The amyloid-β peptide begins as two α-helical segments of a larger protein. Proteolytic cleavage of this larger protein leaves the relatively unstable amyloid-β peptide, which loses its α-helical structure. It can then assemble slowly into amyloid fibrils (c), which contribute to the characteristic plaques on the exterior of nervous tissue in people with Alzheimer disease. The aromatic side chains shown here play a significant role in stabilizing the amyloid structure. Amyloid is rich in β sheet, with the β strands arranged perpendicular to the axis of the amyloid fibril. Amyloid-β peptide takes the form of two layers of extended parallel β sheet. Some amyloid-forming peptides may fold to form left-handed β-helices (see Fig. 4–22).],
    path: "../fig/fig-2025-09-26-11-34-13.png"
  ),
)
