#import "@preview/touying:0.6.1": *
#import themes.stargazer: *
#import "../image_list/2_Water_images.typ": images
#import "@preview/typsium:0.3.0": *

#set text(font: "Arial")

#show: stargazer-theme.with(
  config-info(
    title: "Chapter 2: Water",
    subtitle: "Biochemistry",
    author: "Generated by Cline",
    date: "September 24, 2025",
  )
)

#title-slide()

#outline-slide()

= Weak Interactions in Aqueous Systems

== Hydrogen Bonding Gives Water Its Unusual Properties
#slide[
  - Water constitutes 70% or more of the weight of most organisms.
  - *Unusual Properties*: High melting point (0 °C), boiling point (100 °C), and heat of vaporization (2,260 J/g) due to strong intermolecular attractions. (See Table 2-1)
  - *Molecular Structure*:
    - #ce("H_2O") has a tetrahedral geometry with `sp^3` hybrid orbitals.
    - The H-O-H bond angle is 104.5°.
  - *Polarity*: Unequal electron sharing creates a permanent dipole ($2delta^-$ on O, $delta^+$ on H).
][
  #figure(
    image(images.at("2-1").path),
  )
]

== Hydrogen Bonding and Structure of Ice
#slide[
  - *Hydrogen Bond*: Electrostatic attraction between water molecules (23 kJ/mol).
  - *Flickering Clusters*: In liquid water, H-bonds are transient (1-20 ps), with each molecule bonding to ~3.4 others.
  - *Structure of Ice*: Each water molecule forms four stable H-bonds, creating a regular crystal lattice.
  - This ordered lattice makes ice less dense than liquid water.
][
  #figure(
    image(images.at("2-2").path,width: 60%)
  )
]

== Water Forms Hydrogen Bonds with Polar Solutes
#slide[
  - Hydrogen bonds form between a hydrogen donor (H on an electronegative atom) and a hydrogen acceptor (O or N).
  - Polar biomolecules (sugars, alcohols, etc.) dissolve in water by forming H-bonds.
  - *Directionality*: H-bonds are strongest when the donor, hydrogen, and acceptor are collinear, which is critical for macromolecular structure.
][
  #figure(
    image(images.at("2-3").path)
  )
  #figure(
    image(images.at("2-5").path)
  )
]

== Water Interacts Electrostatically with Charged Solutes
#slide[
  - Water is a polar solvent for hydrophilic (charged or polar) compounds.
  - It dissolves salts (e.g., NaCl) by hydrating and screening the ions (#ce("Na^+"), #ce("Cl^-")).
  - *High Dielectric Constant* ($epsilon$ = 78.5): Water weakens electrostatic interactions between dissolved ions, described by $F = (Q_1 Q_2) / (epsilon r^2)$.
][
  #figure(
    image(images.at("2-6").path)
  )
]

== The Hydrophobic Effect
#slide[
  - *Nonpolar Compounds*: Poorly soluble in water as they force an ordered, entropically unfavorable "cage" of water molecules around them.
  - *Hydrophobic Effect*: The tendency of nonpolar substances to aggregate in aqueous solution to minimize contact with water.
  - *Amphipathic Compounds*: Contain both polar (hydrophilic) and nonpolar (hydrophobic) regions.
  - In water, they form *micelles*, with hydrophobic tails hidden inside and hydrophilic heads facing outwards. This process is driven by the increase in entropy of the surrounding water.
][
  #figure(
    image(images.at("2-7").path, width: 40%)
  )
]

== Weak Interactions in Biological Systems
#slide[
  - Four major types of noncovalent ("weak") interactions:
    1. Hydrogen Bonds
    2. Ionic Interactions
    3. Hydrophobic Interactions
    4. van der Waals Interactions
  - *Bound Water*: Water molecules can be tightly bound to macromolecules and are often essential for their function.
][
  #figure(
    image(images.at("2-9").path)
  )
]

== Colligative Properties and Osmosis
#slide[
  - *Colligative Properties*: Depend on the number of solute particles, not their identity (e.g., boiling point, freezing point).
  - *Osmosis*: The movement of water across a semipermeable membrane from a region of high water concentration to low water concentration.
  - *Osmotic Pressure* ($Psi$ / $Pi$): The pressure required to stop osmosis, given by the van't Hoff equation: $Pi = i c R T$.
][
  #figure(
    image(images.at("2-12").path)
  )
]

== Tonicity and Cells
#slide[
  - *Isotonic*: Solution osmolarity equals cell's cytosol; no net water movement.
  - *Hypertonic*: Solution osmolarity is higher; water moves out, and the cell shrinks.
  - *Hypotonic*: Solution osmolarity is lower; water moves in, and the cell swells and may burst (lysis).
  - Cells must maintain osmotic balance to survive.
][
  #figure(
    image(images.at("2-13").path, width: 70%),
  )
]

= Ionization of Water, Weak Acids, and Weak Bases

== Ionization of Water and the pH Scale
#slide[
  - Water autoionizes: #ce("H_2O <=> H^+ + OH^-").
  - Protons exist as hydronium ions (#ce("H_3O^+")).
  - *Ion Product of Water* ($K_w$): $K_w = [H^+]["OH"^-] = 1.0 * 10^(-14) M^2$ at 25 °C.
  - *pH Scale*: A logarithmic scale for $[H^+]$.
    - $"pH" = -log[H^+]$
    - pH 7 is neutral.
    - pH < 7 is acidic.
    - pH > 7 is basic.
][
  #figure(
    image(images.at("2-15").path, width: 50%)
  )
]

== Weak Acids, Weak Bases, and pK_a
#slide[
  - *Weak acids* and *bases* only partially dissociate in water.
  - A *conjugate acid-base pair* consists of a proton donor and its corresponding proton acceptor.
  - *Acid Dissociation Constant* ($K_a$): Measures the strength of an acid. $K_a = ([H^+][A^-]) / (["HA"])$.
  - *$p K_a$*: The negative logarithm of $K_a$.
    - $"p"K_a = -log(K_a)$
    - A smaller $"p"K_a$ indicates a stronger acid.
]

#slide[
  #figure(
    image(images.at("2-16").path, width: 75%),
  )
]

== Titration Curves
#slide[
  - A *titration curve* plots pH against the amount of base added to an acid.
  - The flat region of the curve is the *buffering region*.
  - At the midpoint of the titration, $["HA"] = ["A"^-]$, and the pH is numerically equal to the $"p"K_a$.
][
  #figure(
    image(images.at("2-17").path, width: 90%)
  )
]

= Buffering against pH Changes in Biological Systems

== Buffers and the Henderson-Hasselbalch Equation
#slide[
  - A *buffer* is a mixture of a weak acid and its conjugate base that resists pH changes.
  - Buffering capacity is maximal at the $"p"K_a$ and effective within $"p"K_a plus.minus 1$ pH unit.
  - *Henderson-Hasselbalch Equation*:
    $"pH" = "p"K_a + log((["A"^-]) / (["HA"]))$
  - This equation relates pH, $"p"K_a$, and the buffer component ratio.
][
  #figure(
    image(images.at("2-19").path)
  )
]

== Biological Buffer Systems
#slide[
  - Biological fluids are buffered to maintain a constant pH.
  - *Phosphate Buffer System*:
    - Main intracellular buffer.
    - Pair: #ce("H_2PO_4^- / HPO_4^2-")
    - $"p"K_a$ = 6.86, effective near neutral pH.
  - *Bicarbonate Buffer System*:
    - Main blood plasma buffer.
    - Equilibrium: #ce("CO_2 + H_2O <=> H_2CO_3 <=> H^+ + HCO_3^-")
][
  #figure(
    image(images.at("2-21").path)
  )
]

== Water as a Reactant
#slide[
  #figure(
    image(images.at("2-23").path)
  )
  - Water is a direct participant in many metabolic reactions.
  - *Hydrolysis*: Cleavage of a bond by adding water.
  - *Condensation*: Formation of a bond by removing water.
  - Example: ATP is formed from ADP and phosphate via condensation.
]
