#let images = (
  "11.1": (
    caption: [Scanning electron micrographs of the leaf anatomy of a legume (Thermopsis montana) grown in different light environments. The sun leaf (A) is much thicker than the shade leaf (B), and the palisade (column-like) cells are much longer in leaves grown in sunlight. Layers of spongy mesophyll cells can be seen below the palisade cells.],
    path: "../fig/image_place_holder.png"
  ),
  "11.2": (
    caption: [Conversion of solar energy into carbohydrates by a leaf. Of the total incident solar energy reaching the leaf surface, approximately 50% is of non-absorbable wavelengths, 15% is lost through reflection and transmission, 10% is dissipated as heat, and 20% is consumed by metabolism. Only about 5% is ultimately converted into carbohydrates through photosynthesis.],
    path: "../fig/image_place_holder.png"
  ),
  "11.3": (
    caption: [Optical properties of a bean leaf showing the percentages of light absorbed, reflected, and transmitted as a function of wavelength. The transmitted and reflected green light in the wave band at 500-600 nm gives leaves their green color. Most light above 700 nm is not absorbed by the leaf.],
    path: "../fig/image_place_holder.png"
  ),
  "11.4": (
    caption: [Relative spectral distributions of sunlight at the top of a canopy and in the shade under the canopy. Most photosynthetically active radiation (PAR) is absorbed by leaves in the canopy, with dramatically reduced light intensity reaching the forest floor.],
    path: "../fig/image_place_holder.png"
  ),
  "11.5": (
    caption: [Leaf movement in a sun-tracking plant, the lupine Lupinus succulentus. (A) Initial leaf orientation with no direct sunlight. (B) Leaf orientation 4 hours after exposure to oblique light. Movement is generated by asymmetric swelling of a pulvinus at the junction between the lamina and the petiole. In natural conditions, leaves track the sun's trajectory in the sky.],
    path: "../fig/image_place_holder.png"
  ),
  "11.6": (
    caption: [Response of photosynthesis to light in a C3 plant. In darkness, respiration causes net CO2 efflux. The light compensation point is reached when photosynthetic CO2 assimilation equals respiratory CO2 evolution. Increasing light above this point proportionally increases photosynthesis in the light-limited region. Further increases are eventually limited by carboxylation capacity of Rubisco or regeneration of RuBP.],
    path: "../fig/image_place_holder.png"
  ),
  "11.7": (
    caption: [Light-response curves of photosynthetic carbon fixation in sun and shade plants. Triangle orache (Atriplex triangularis) is a sun plant, and wild ginger (Asarum caudatum) is a shade plant. Shade plants typically have low light compensation points and lower maximum photosynthetic rates than sun plants.],
    path: "../fig/image_place_holder.png"
  ),
  "11.8": (
    caption: [Light-response curve of photosynthesis of a sun plant (Atriplex triangularis) grown under sun versus shade conditions. The leaf grown at high PPFD (upper curve) has much higher photosynthetic capacity than the shade-grown leaf (lower curve), demonstrating that photosynthetic properties depend on growing conditions and acclimation.],
    path: "../fig/image_place_holder.png"
  ),
  "11.9": (
    caption: [Changes in photosynthesis in individual needles, a complex shoot, and a forest canopy of Sitka spruce (Picea sitchensis) as a function of PPFD. Complex shoots consist of groupings of needles that shade each other. Due to mutual shading, much higher PPFD levels are needed to saturate photosynthesis at the shoot and canopy levels compared to individual needles.],
    path: "../fig/image_place_holder.png"
  ),
  "11.10": (
    caption: [Excess light energy in relation to a light-response curve of photosynthetic oxygen evolution in a shade leaf. At PPFD levels up to 150 μmol m⁻² s⁻¹, the shade plant can use absorbed light efficiently. Above this level, photosynthesis saturates and an increasingly larger amount of absorbed light energy must be dissipated as excess energy to prevent photodamage.],
    path: "../fig/image_place_holder.png"
  ),
  "11.11": (
    caption: [Diurnal changes in xanthophyll content as a function of PPFD in sunflower (Helianthus annuus). As incident light increases, a greater proportion of violaxanthin is converted to antheraxanthin and zeaxanthin through the xanthophyll cycle, thereby dissipating excess excitation energy and protecting the photosynthetic apparatus.],
    path: "../fig/image_place_holder.png"
  ),
  "11.12": (
    caption: [Chloroplast distribution in photosynthesizing cells of the duckweed Lemna under three conditions: (A) darkness, (B) weak blue light, and (C) strong blue light. In darkness and weak light, chloroplasts position near the upper surface to maximize light absorption. Under strong light, chloroplasts move to side walls where they shade each other, minimizing absorption of excess light.],
    path: "../fig/image_place_holder.png"
  ),
  "11.13": (
    caption: [Changes over the course of a day in the allocation of photons absorbed by sunlight. Contrasts show how photons striking a leaf are either involved in photochemistry or thermally dissipated as excess energy under favorable conditions (A) versus stress conditions (B), illustrating dynamic and chronic photoinhibition.],
    path: "../fig/image_place_holder.png"
  ),
  "11.14": (
    caption: [Absorption and dissipation of energy from sunlight by the leaf. The imposed heat load must be dissipated to avoid leaf damage. Heat is dissipated through emission of long-wavelength radiation, sensible heat loss to surrounding air, and evaporative cooling caused by transpiration.],
    path: "../fig/image_place_holder.png"
  ),
  "11.15": (
    caption: [Photosynthesis as a function of leaf temperature at normal atmospheric CO2 concentrations for a C3 plant grown in its natural cool habitat and a C4 plant growing in its natural hot habitat. The temperature response curves show optimal ranges and the effects of thermal stress at extreme temperatures.],
    path: "../fig/image_place_holder.png"
  ),
  "11.16": (
    caption: [Quantum yield of photosynthetic carbon fixation in C3 and C4 plants as a function of leaf temperature. Photorespiration increases with temperature in C3 plants, reflected in lower quantum yields at higher temperatures. In contrast, C4 plants show minimal photorespiration and quantum yield remains relatively constant with temperature. At lower temperatures, C3 plants have higher quantum yields than C4 plants.],
    path: "../fig/image_place_holder.png"
  ),
  "11.17": (
    caption: [Relative rates of photosynthetic carbon gain predicted for identical C3 and C4 grass canopies as a function of latitude across the Great Plains of North America. C4 grasses dominate in warmer southern latitudes while C3 grasses are more competitive at cooler northern latitudes due to differences in photorespiration rates.],
    path: "../fig/image_place_holder.png"
  ),
  "11.18": (
    caption: [Concentration of atmospheric CO2 from 420,000 years ago to the present. (A) Past atmospheric CO2 concentrations determined from ice core bubbles were much lower than current levels, cycling between 180-280 ppm. (B) In the last 1000 years, atmospheric CO2 has risen dramatically, coinciding with the Industrial Revolution and increased fossil fuel burning. (C) Current concentrations show seasonal oscillations superimposed on the increasing trend.],
    path: "../fig/image_place_holder.png"
  ),
  "11.19": (
    caption: [Points of resistance to the diffusion and fixation of CO2 from outside the leaf to the chloroplasts. The stomatal aperture represents the major point of resistance to CO2 diffusion into the leaf. Additional resistances occur at the boundary layer, mesophyll cell walls, plasma membrane, cytoplasm, and chloroplast envelope.],
    path: "../fig/image_place_holder.png"
  ),
  "11.20": (
    caption: [Changes in photosynthesis as a function of intercellular CO2 concentrations in Arizona honeysweet (Tidestromia oblongifolia), a C4 plant, and creosote bush (Larrea tridentata), a C3 plant. The intercellular CO2 concentration at which net CO2 assimilation is zero defines the CO2 compensation point, which is much lower in C4 plants than in C3 plants.],
    path: "../fig/image_place_holder.png"
  ),
  "11.21": (
    caption: [Combination of global atmospheric CO2 concentrations and daytime growing-season temperatures that favor C3 versus C4 grasses. At any point in time, Earth has a single atmospheric CO2 concentration, with C4 plants most competitive in habitats with the warmest growing seasons. As atmospheric CO2 declined in Earth's history, C4 photosynthesis became advantageous in warm climates.],
    path: "../fig/image_place_holder.png"
  ),
  "11.22": (
    caption: [Photosynthetic net CO2 uptake, H2O transpiration, and stomatal conductance of a CAM plant, the orchid Doritaenopsis, during a 24-hour period. (A) Photosynthetic rate, (B) water loss, and (C) stomatal conductance are shown. Unlike C3 and C4 plants, CAM plants open their stomata and fix CO2 at night, then close stomata during the day, greatly reducing water loss.],
    path: "../fig/image_place_holder.png"
  ),
  "11.23": (
    caption: [Free Air CO2 Enrichment (FACE) experiments used to study how plants and ecosystems will respond to future CO2 concentrations. FACE experiments in (A) a deciduous forest and (B) a crop canopy. (C) Under elevated CO2 concentrations, leaf stomata are more closed, resulting in higher leaf temperatures as shown by infrared imaging.],
    path: "../fig/image_place_holder.png"
  ),
  "11.24": (
    caption: [Frequency histograms for observed carbon isotope ratios (δ¹³C) in C3 and C4 plant taxa from around the world. C3 plants show an average δ¹³C of approximately -28‰ while C4 plants average -14‰. This reflects the greater discrimination against ¹³C during photosynthesis in C3 plants compared to C4 plants.],
    path: "../fig/image_place_holder.png"
  ),
  "11.25": (
    caption: [Vegetation changes occur along rainfall gradients in southern Queensland, Australia. Carbon isotope ratios of vegetation are strongly related to precipitation amounts, with δ¹³C values highest in arid regions and progressively lower along a precipitation gradient. This reflects decreased stomatal conductance and reduced CO2 discrimination under water stress in C3 species.],
    path: "../fig/image_place_holder.png"
  )
)
