#let images = (
  "13.1": (
    caption: [Overview of respiration showing how substrates generated by other cellular processes enter the respiratory pathways. Glycolysis and the oxidative pentose phosphate pathways in the cytosol and plastids convert sugars into organic acids such as pyruvate via hexose phosphates and triose phosphates, generating NADH or NADPH. The diagram illustrates the integration of respiratory metabolism with other major metabolic processes including photosynthesis, nitrogen assimilation, and biosynthesis.],
    path: "../fig/image_place_holder.png"
  ),
  "13.2": (
    caption: [Structures and reactions of the major electron-carrying nucleotides involved in respiratory bioenergetics. (A) Reduction of NAD(P)+ to NAD(P)H, where a hydrogen is replaced by a phosphate group to convert NAD+ to NADP+. (B) Reduction of flavin adenine dinucleotide (FAD) to FADH2. These electron carriers are essential for capturing energy from oxidation reactions in respiration.],
    path: "../fig/image_place_holder.png"
  ),
  "13.3": (
    caption: [Reactions of plant glycolysis and fermentation. (A) Structures of the carbon intermediates with phosphate groups indicated. (B) The main glycolytic pathway showing how sucrose is oxidized via hexose phosphates and triose phosphates to pyruvate, along with alternative reactions unique to plants. Double arrows denote reversible reactions while single arrows indicate essentially irreversible reactions. This pathway generates ATP and NADH while breaking down sugars.],
    path: "../fig/image_place_holder.png"
  ),
  "13.4": (
    caption: [Reactions of the oxidative pentose phosphate pathway in plants. The first two oxidizing reactions are essentially irreversible and supply NADPH to the cytosol and plastids in the absence of photosynthesis. The downstream reversible portion (shown by double-headed arrows) can supply five-carbon substrates for biosynthesis even when the oxidizing reactions are inhibited, such as in chloroplasts during light conditions.],
    path: "../fig/image_place_holder.png"
  ),
  "13.5": (
    caption: [Structure of mitochondria from animals and plants. Three-dimensional tomography image showing the invaginations of the inner membrane called cristae, along with the locations of the matrix and intermembrane space. Plant mitochondria display distinctive structural features that accommodate their unique metabolic functions including the alternative oxidase pathway.],
    path: "../fig/image_place_holder.png"
  ),
  "13.6": (
    caption: [The plant tricarboxylic acid (TCA) cycle and associated reactions. The diagram displays the reactions and enzymes of the TCA cycle along with the associated reactions of pyruvate dehydrogenase and malic enzyme. Pyruvate is completely oxidized to three molecules of CO2, and malic enzyme enables plant mitochondria to completely oxidize malate. The electrons released during these oxidations reduce four molecules of NAD+ to NADH and one molecule of FAD to FADH2, which are then used for ATP synthesis.],
    path: "../fig/image_place_holder.png"
  ),
  "13.7": (
    caption: [Malic enzyme and PEP carboxylase provide plants with metabolic flexibility for the metabolism of phosphoenolpyruvate (PEP) and pyruvate. These alternative pathways allow plants to regulate organic acid levels, replenish TCA cycle intermediates, and adapt to different metabolic conditions. The reactions are particularly important during fruit ripening and in tissues that carry out crassulacean acid metabolism.],
    path: "../fig/image_place_holder.png"
  ),
  "13.8": (
    caption: [Organization of the electron transport chain and ATP synthesis in the inner membrane of the plant mitochondrion. The diagram shows the four standard protein complexes (I, II, III, and IV) found in mitochondria from nearly all eukaryotes, along with additional enzymes unique to plant mitochondria. These complexes work together to pump protons across the membrane and generate the electrochemical gradient used for ATP synthesis.],
    path: "../fig/image_place_holder.png"
  ),
  "13.9": (
    caption: [Non-energy-conserving electron transport pathways in plant mitochondria. The internal rotenone-insensitive NADH dehydrogenase and the alternative oxidase are both homodimers embedded in the inner leaflet of the inner mitochondrial membrane. These enzymes provide alternative pathways that do not pump protons but instead dissipate energy as heat, allowing plants to maintain metabolic flexibility under various conditions.],
    path: "../fig/image_place_holder.png"
  ),
  "13.10": (
    caption: [Transmembrane transport in plant mitochondria. The diagram illustrates the electrochemical proton gradient (Δμ̃H+) consisting of an electrical potential component (ΔE, approximately -200 mV, negative inside) and a chemical potential component (ΔpH). This gradient drives ATP synthesis and various transport processes across the inner mitochondrial membrane including the uptake of ADP and phosphate and the export of ATP.],
    path: "../fig/image_place_holder.png"
  ),
  "13.11": (
    caption: [Metabolic interactions between mitochondria and cytosol. Mitochondrial activities influence the cytosolic levels of redox and energy molecules involved in stress defense and central carbon metabolism such as growth processes and photosynthesis. The diagram shows the interconnected nature of mitochondrial metabolism with other cellular processes, highlighting the role of mitochondria in coordinating cellular responses to environmental and developmental signals.],
    path: "../fig/image_place_holder.png"
  ),
  "13.12": (
    caption: [Glycolysis, the oxidative pentose phosphate pathway, and the TCA cycle contribute precursors to many biosynthetic pathways in plants. The pathways shown illustrate the extensive dependence of plant biosynthesis on the flux of carbon through these pathways, emphasizing that not all carbon entering the glycolytic pathway is oxidized to CO2. Instead, intermediates are diverted to produce amino acids, nucleotides, lipids, and secondary metabolites.],
    path: "../fig/image_place_holder.png"
  ),
  "13.13": (
    caption: [Model of bottom-up regulation of plant respiration. The diagram shows how substrates for respiration (such as ADP) stimulate while products of respiration (such as ATP) inhibit upstream reactions in a stepwise fashion. For instance, ATP inhibits the electron transport chain leading to NADH accumulation, which then inhibits TCA cycle enzymes. This feedback regulation ensures efficient coordination of respiratory metabolism with cellular energy demands.],
    path: "../fig/image_place_holder.png"
  ),
  "13.14": (
    caption: [Metabolic regulation of pyruvate dehydrogenase (PDH) activity through direct effects and reversible phosphorylation. Upstream and downstream metabolites control PDH activity either by direct actions on the enzyme itself or by regulating its protein kinase or protein phosphatase. This complex regulation allows plants to coordinate the entry of carbon into the TCA cycle with cellular metabolic status.],
    path: "../fig/image_place_holder.png"
  ),
  "13.15": (
    caption: [Structural features of triacylglycerols and polar glycerolipids in higher plants. The carbon chain lengths of fatty acids always have an even number of carbons, ranging from 8 to 30 but typically 16 or 18 carbons. The diagram shows the general structure with glycerol backbone and attached fatty acid chains, illustrating the fundamental building blocks of plant lipids used for energy storage and membrane structure.],
    path: "../fig/image_place_holder.png"
  ),
  "13.16": (
    caption: [Major polar glycerolipid classes found in plant membranes. (A) Glyceroglycolipids and sphingolipids. (B) Glycerophospholipids. Two of at least six different fatty acids may be attached to the glycerol backbone, with one common molecular species shown for each class. The numbers indicate the number of carbons (before the colon) and the number of double bonds (after the colon) in the fatty acid chains.],
    path: "../fig/image_place_holder.png"
  ),
  "13.17": (
    caption: [Cycle of fatty acid synthesis in plastids of plant cells. The diagram shows the sequential addition of two-carbon units from malonyl-CoA to the growing fatty acid chain attached to acyl carrier protein (ACP). Each cycle involves condensation, reduction, dehydration, and a second reduction step, producing saturated fatty acids typically 16 or 18 carbons in length. This process is essential for membrane lipid biosynthesis and oil accumulation in seeds.],
    path: "../fig/image_place_holder.png"
  ),
  "13.18": (
    caption: [The two pathways for glycerolipid synthesis in the chloroplast and endoplasmic reticulum of Arabidopsis leaf cells. The major membrane components are shown with desaturases in the chloroplast and ER converting 16:0 and 18:1 fatty acids into polyunsaturated forms. This diagram illustrates the cooperation between different cellular compartments in producing the diverse array of membrane lipids found in plant cells.],
    path: "../fig/image_place_holder.png"
  ),
  "13.19": (
    caption: [Conversion of fats into sugars during germination in oil-storing seeds. (A) Carbon flow during fatty acid breakdown via β-oxidation in glyoxysomes and gluconeogenesis, showing how acetyl-CoA from lipid breakdown is converted to sucrose through the glyoxylate cycle and mitochondrial metabolism. (B) Electron micrograph of a cell from an oil-storing cotyledon showing glyoxysomes, mitochondria, and oil bodies, illustrating the cellular organization supporting lipid-to-sugar conversion during seedling establishment.],
    path: "../fig/image_place_holder.png"
  ),
)
