#let images = (
  "14.1": (
    caption: [Nitrogen cycles through the atmosphere, changing from a gas to soluble ions before it is incorporated into organic compounds in living organisms. The diagram illustrates key processes including atmospheric fixation by lightning, biological nitrogen fixation by prokaryotes, industrial fixation, plant acquisition and assimilation, denitrification returning nitrogen to the atmosphere, ammonification by bacteria and fungi, immobilization by microbes, nitrification converting ammonium to nitrate, and anammox processes. This cycle demonstrates how nitrogen moves between inorganic and organic forms in ecosystems.],
    path: "../fig/image_place_holder.png"
  ),
  "14.2": (
    caption: [Ammonium (#ce("NH_4^+")) dissipation of pH gradients across membranes. The diagram shows how ammonia (#ce("NH_3")) can cross biological membranes (thylakoid, inner mitochondrial, or tonoplast membranes) and react with protons (#ce("H^+")) to form ammonium ions, thereby dissipating pH gradients. The left side represents high pH environments (stroma, matrix, or cytoplasm) while the right side represents low pH environments (lumen, intermembrane space, or vacuole). This mechanism explains why high ammonium concentrations can be toxic by disrupting essential pH gradients required for ATP synthesis and other processes. Ammonia movement across membranes can occur through aquaporins.],
    path: "../fig/image_place_holder.png"
  ),
  "14.3": (
    caption: [Overview of nitrogen assimilation pathways in plant cells. Nitrate (#ce("NO_3^-")) is actively taken up across the plasma membrane by proton-coupled symporters NRT1 or NRT2, using the electrochemical proton gradient as driving force. In the cytosol, nitrate reductase reduces nitrate to nitrite (#ce("NO_2^-")), which is then transported into plastids where nitrite reductase converts it to ammonium (#ce("NH_4^+")). Nitrate can also be transported into vacuoles via the proton-nitrate antiporter CLC for storage at concentrations up to 70 mM. Ammonium, either taken up by AMT1 transporters or generated from nitrate reduction, is rapidly assimilated into amino acids via the GS-GOGAT pathway to avoid toxicity. The diagram integrates membrane transport, enzymatic reduction, and amino acid biosynthesis.],
    path: "../fig/image_place_holder.png"
  ),
  "14.4": (
    caption: [Structural model of the nitrate reductase dimer showing the three conserved binding domains in eukaryotes: FAD-binding domain, heme-binding domain, and molybdenum cofactor (MoCo) binding domain. Each subunit contains these three domains arranged sequentially. NAD(P)H binds at the FAD-binding region at the carboxyl (C) terminus of each subunit and initiates a two-electron transfer cascade. Electrons flow from NAD(P)H to FAD, then to heme, and finally to the molybdenum center where nitrate is reduced to nitrite. The dimer structure facilitates efficient electron transfer and catalytic activity. This enzyme represents the first and rate-limiting step in nitrate assimilation.],
    path: "../fig/image_place_holder.png"
  ),
  "14.5": (
    caption: [Model illustrating the coupling of photosynthetic electron flow to nitrite reduction in chloroplasts. Photosystem I (PSI) reduces ferredoxin (Fd) using light energy. Reduced ferredoxin then donates electrons to nitrite reductase, which contains two prosthetic groups: an iron-sulfur cluster (#ce("Fe_4S_4")) and a heme group. These prosthetic groups participate sequentially in the six-electron reduction of nitrite (#ce("NO_2^-")) to ammonium (#ce("NH_4^+")). This pathway directly links photosynthetic light reactions to nitrogen assimilation, explaining why nitrite reduction occurs primarily in illuminated chloroplasts and why it competes with carbon fixation for reducing power.],
    path: "../fig/image_place_holder.png"
  ),
  "14.6": (
    caption: [Relative amounts of nitrate and various organic nitrogen compounds in xylem sap of different plant species. The bar chart compares nitrogen transport forms across species including barley, ryegrass, white clover, tomato, common bean, pea, and others. Plants were grown with roots exposed to nitrate solutions, and xylem sap was collected by stem severing. The data reveal species-specific differences in nitrogen transport strategies: some species transport primarily nitrate (e.g., barley, tomato), others transport mainly amino acids and amides (asparagine, glutamine), and tropical legumes like common bean and pea transport significant amounts of ureides (allantoin and allantoic acid). These differences reflect evolutionary adaptations and metabolic specializations for nitrogen transport and distribution.],
    path: "../fig/image_place_holder.png"
  ),
  "14.7": (
    caption: [Overview of nitrate transport pathways in whole plants. The diagram illustrates bidirectional nitrate movement through vascular tissues. Root-to-shoot nitrate transport occurs via xylem, driven by transpiration and root pressure. Phloem-mediated nitrate transport distributes nitrate from source leaves to nitrogen-demanding sink tissues including young leaves, flowers, fruits, and developing seeds. Nitrate transporters (NRT family) facilitate uptake from soil, loading into xylem and phloem, and redistribution within the plant. This dual transport system allows plants to balance nitrogen supply with demand across different developmental stages and environmental conditions, ensuring efficient nitrogen utilization and storage.],
    path: "../fig/image_place_holder.png"
  ),
  "14.8": (
    caption: [The primary nitrate response mediated by the transceptor CHL1. Panel (A) shows time-dependent and concentration-dependent expression patterns of nitrate-related genes including nitrate reductase, demonstrating rapid transcriptional responses to nitrate availability. Panel (B) illustrates how the transceptor CHL1 (a transporter with receptor function) uses dual-affinity binding to sense a wide range of nitrate concentrations in soil. At low nitrate concentrations, CHL1 functions as a high-affinity transporter; at high concentrations, it switches to low-affinity mode and simultaneously triggers signaling cascades that regulate gene expression. Phosphorylation of CHL1 modulates its transport and sensing activities, allowing plants to coordinate nitrate uptake with metabolic capacity and optimize nitrogen nutrition under fluctuating soil conditions.],
    path: "../fig/image_place_holder.png"
  ),
  "14.9": (
    caption: [Structure and pathways of ammonium assimilation and metabolism in plants. Panel (A) depicts the GS-GOGAT pathway (glutamine synthetase-glutamate synthase cycle) which is the primary route for ammonium assimilation. Glutamine synthetase (GS) catalyzes ATP-dependent condensation of ammonium with glutamate to form glutamine. Glutamate synthase (GOGAT) then transfers the amide group from glutamine to 2-oxoglutarate, generating two molecules of glutamate. The pathway requires reduced cofactors: ferredoxin (Fd) in photosynthetic tissues and NADH in non-photosynthetic tissues. This cycle rapidly assimilates ammonium while regenerating glutamate, preventing ammonium toxicity. The resulting amino acids (glutamine and glutamate) serve as nitrogen donors for biosynthesis of other amino acids, nucleotides, and nitrogenous compounds throughout the plant.],
    path: "../fig/image_place_holder.png"
  ),
  "14.10": (
    caption: [Biosynthetic pathways showing how carbon skeletons for all 20 standard amino acids derive from intermediates of glycolysis and the tricarboxylic acid (TCA) cycle. The diagram maps amino acid families to their respective precursors: 3-phosphoglycerate produces serine family amino acids; pyruvate generates alanine, valine, and leucine; oxaloacetate yields aspartate family amino acids including asparagine, methionine, threonine, and lysine; 2-oxoglutarate produces glutamate family amino acids including glutamine, proline, and arginine; phosphoenolpyruvate and erythrose-4-phosphate combine to form aromatic amino acids (phenylalanine, tyrosine, tryptophan); and ribose-5-phosphate contributes to histidine biosynthesis. The diagram also indicates nitrogen sources (AspN for aspartate, GlnN for glutamine), sulfur sources for cysteine and methionine, and additional carbon sources required for complete amino acid synthesis, illustrating the integration of carbon, nitrogen, and sulfur metabolism.],
    path: "../fig/image_place_holder.png"
  ),
  "14.11": (
    caption: [Root nodules on common bean (Phaseolus vulgaris) resulting from symbiotic infection by Rhizobium bacteria. The photograph shows multiple spherical nodule structures attached to the root system. These specialized organs house nitrogen-fixing rhizobia bacteria (bacteroids) that convert atmospheric nitrogen (#ce("N_2")) into ammonia. The nodules provide an oxygen-regulated microenvironment essential for nitrogenase activity, while the plant supplies photosynthates to fuel the energy-intensive nitrogen fixation process. This mutualistic relationship allows legumes to thrive in nitrogen-poor soils and contributes significantly to agricultural nitrogen inputs and soil fertility.],
    path: "../fig/image_place_holder.png"
  ),
  "14.12": (
    caption: [A heterocyst within a filament of the nitrogen-fixing cyanobacterium Anabaena, which forms symbiotic associations with the aquatic water fern Azolla. The micrograph shows the thick-walled heterocyst interspersed among normal vegetative cells. Heterocysts are specialized cells that create an anaerobic internal environment necessary for nitrogen fixation in otherwise aerobic conditions. They achieve this by eliminating oxygen-producing photosystem II activity, increasing respiration rates, and synthesizing a thick peptidoglycan layer that limits oxygen diffusion. Typically, one heterocyst occurs per ten vegetative cells, with vegetative cells performing photosynthesis and providing carbohydrates while heterocysts fix nitrogen, creating a metabolically efficient division of labor in the filament.],
    path: "../fig/image_place_holder.png"
  ),
  "14.13": (
    caption: [Chemical structure of Nod factors (Nodulation factors), which are lipochitin oligosaccharides that serve as essential molecular signals in legume-rhizobia symbiosis. The structure consists of a backbone of N-acetylglucosamine residues (typically n = 2 or 3 repeating units) with a fatty acid chain (usually 16-18 carbons) attached to the non-reducing end. Various substitutions on the sugar residues create species-specific recognition signals. Nod factors are synthesized by rhizobia in response to plant-released flavonoids and trigger multiple developmental responses in host plants including root hair curling, cortical cell division, and nodule organogenesis. The specific structure of Nod factors determines host specificity, ensuring that only compatible rhizobia-legume pairs form effective symbioses.],
    path: "../fig/image_place_holder.png"
  ),
  "14.14": (
    caption: [Simplified intracellular signaling cascade initiated upon Nod factor perception in legume root cells. Nod factor receptors NFR1 and NFR5 (LysM receptor kinases) bind compatible Nod factors at the plasma membrane. This triggers a complex signaling network involving: SYMRK (symbiotic receptor kinase), CASTOR and POLLUX (cation channels in the nuclear envelope), calcium oscillations (calcium spiking) in the nucleus and cytoplasm, CCaMK (calcium and calmodulin-dependent protein kinase), CYCLOPS (transcription factor), CNGCs (cyclic nucleotide-gated channels), NUPs (nucleoporins), NIN (Nodule Inception protein), and other transcription factors (TF). This cascade ultimately activates genes required for infection thread formation, nodule development, and preparation for hosting nitrogen-fixing bacteroids. The calcium spiking pattern serves as a specific signature that distinguishes symbiotic signaling from other stress responses.],
    path: "../fig/image_place_holder.png"
  ),
  "14.15": (
    caption: [The infection process during nodule organogenesis in legume roots. Panel (A) shows rhizobia binding to an emerging root hair in response to flavonoid attractants secreted by the plant. Panel (B) depicts abnormal curling growth of the root hair in response to bacterial Nod factors, with rhizobia proliferating within the curled structure. Panel (C) illustrates formation of the infection thread - a tunnel-like structure created by invagination of the root hair cell wall and plasma membrane, filled with multiplying rhizobia. Panel (D) shows the infection thread growing through root cortical tissue toward developing nodule primordia, which arise from dedifferentiated cortical cells. This process involves coordinated plant and bacterial gene expression, cell wall remodeling, and directional growth, ultimately delivering rhizobia to nodule cells where they differentiate into nitrogen-fixing bacteroids.],
    path: "../fig/image_place_holder.png"
  ),
  "14.16": (
    caption: [The reaction mechanism catalyzed by the nitrogenase enzyme complex for biological nitrogen fixation. The diagram shows the two-component system: the Fe protein (iron protein, dinitrogenase reductase) and the MoFe protein (molybdenum-iron protein, dinitrogenase). Reduced ferredoxin donates electrons to the Fe protein. ATP binding and hydrolysis (16 ATP molecules per #ce("N_2") reduced) induce conformational changes in the Fe protein that facilitate electron transfer to the MoFe protein. The MoFe protein contains the active site (FeMo-cofactor) where #ce("N_2") is reduced to ammonia (#ce("NH_3")) through a series of intermediate steps. The reaction also produces hydrogen gas (#ce("H_2")) as an obligatory byproduct. This ATP-dependent process requires 8 electrons and 16 ATP molecules per #ce("N_2") molecule, representing one of the most energy-intensive biochemical reactions in nature. The strict oxygen sensitivity of nitrogenase necessitates anaerobic or microanaerobic conditions.],
    path: "../fig/image_place_holder.png"
  ),
  "14.17": (
    caption: [Chemical structures of the major ureide compounds (allantoin and allantoic acid) used for long-distance nitrogen transport in tropical legumes. These compounds are synthesized from purines in nodules and transported via xylem from nitrogen fixation sites in root nodules to shoots and other nitrogen-demanding tissues. At destination sites, ureides are catabolized through deamination reactions that release ammonium for incorporation into amino acids and nucleotides. Ureides have a high nitrogen-to-carbon ratio (N:C), making them efficient nitrogen transport compounds that minimize carbon loss during translocation. Their use is particularly prevalent in tropical legumes like soybean and common bean, distinguishing them from temperate legumes that primarily transport amides (asparagine and glutamine).],
    path: "../fig/image_place_holder.png"
  ),
  "14.18": (
    caption: [Structure and metabolic pathways of sulfur assimilation compounds in plants. The pathway begins with sulfate (#ce("SO_4^{2-}")), which is activated by ATP sulfurylase through reaction with ATP to form adenosine 5'-phosphosulfate (APS), releasing pyrophosphate. APS can be either phosphorylated to 3'-phosphoadenosine 5'-phosphosulfate (PAPS) for sulfation reactions, or reduced to sulfite (#ce("SO_3^{2-}")) by APS reductase. Sulfite is further reduced by sulfite reductase to sulfide (#ce("S^{2-}")), which is then incorporated into the amino acid cysteine through reaction with O-acetylserine. Cysteine serves as the sulfur donor for synthesis of methionine and other sulfur-containing compounds including glutathione, coenzyme A, and various secondary metabolites. This pathway requires substantial reducing power and ATP, consuming approximately 14 ATP equivalents per sulfate assimilated.],
    path: "../fig/image_place_holder.png"
  ),
  "14.19": (
    caption: [Overview of sulfur assimilation in plant cells showing the subcellular compartmentation of the pathway. Sulfate (#ce("SO_4^{2-}")) is taken up across the plasma membrane by proton-coupled sulfate transporters (SULTRs) and can be stored in vacuoles. The assimilation pathway spans three compartments: sulfate activation to APS occurs in plastids (chloroplasts) using ATP sulfurylase; reduction of APS to sulfide involves APS reductase in plastids and sulfite reductase also in plastids, requiring reducing power from photosynthetic electron transport (ferredoxin) in leaves or from oxidative metabolism in roots; finally, cysteine synthesis occurs in plastids through O-acetylserine sulfhydrylase, which combines sulfide with O-acetylserine. Mitochondria may also participate in cysteine synthesis. The compartmentation allows coordinate regulation with photosynthesis in leaves and ensures efficient sulfide incorporation to prevent toxicity. Cysteine then serves as precursor for all other organic sulfur compounds in the cell.],
    path: "../fig/image_place_holder.png"
  ),
  "14.20": (
    caption: [Summary diagram integrating processes involved in mineral nitrogen assimilation in leaf mesophyll cells with photosynthetic electron transport. Nitrate translocated from roots via xylem enters mesophyll cells through nitrate transporters (NRT). In the cytosol, nitrate reductase (NR) reduces nitrate to nitrite using NAD(P)H as electron donor. Nitrite is transported into chloroplasts where nitrite reductase reduces it to ammonium using reduced ferredoxin from photosystem I. Ammonium is immediately assimilated via glutamine synthetase (GS) in chloroplast stroma, forming glutamine from glutamate with ATP. Glutamate synthase (GOGAT) uses reduced ferredoxin to transfer the amide group to 2-oxoglutarate, regenerating two glutamates. This photorespiratory nitrogen assimilation is tightly coupled to photosynthetic electron transport and competes with carbon fixation for ATP and reducing equivalents, explaining why nitrogen assimilation is maximal during active photosynthesis and why it affects plant carbon-nitrogen balance.],
    path: "../fig/image_place_holder.png"
  ),
  "14.21": (
    caption: [Relationship between shoot nitrate assimilation rate and internal #ce("CO_2") concentration (Ci) in C3 and C4 plants. Panel (A) shows data for nine C3 species, demonstrating that shoot nitrate assimilation (assessed by ΔAQ, the decrease in the ratio of shoot #ce("CO_2") uptake to #ce("O_2") evolution when plants shift from ammonium to nitrate nutrition) declines sharply as internal #ce("CO_2") increases above current atmospheric levels. This occurs because elevated #ce("CO_2") stimulates carbon fixation and carbohydrate production, which reduces availability of reductant and ATP for nitrate reduction in mesophyll cells. Panel (B) shows three C4 species maintain constant nitrate assimilation rates regardless of Ci, because their bundle sheath cells have ample malate and NADH for nitrate reduction, and they assimilate nitrate exclusively in mesophyll cells where #ce("CO_2") concentration is low. These findings have important implications for crop nutrition and food quality under rising atmospheric #ce("CO_2") levels, suggesting that C3 crops may show decreased protein content while C4 crops remain unaffected.],
    path: "../fig/image_place_holder.png"
  ),
  "table-14.1": (
    caption: [The major processes of the biogeochemical nitrogen cycle, showing process definitions and rates in megatons per year (Mt y⁻¹). The table lists key processes: industrial fixation (110-120 Mt y⁻¹) converts molecular nitrogen to ammonia chemically; atmospheric fixation (2-10 Mt y⁻¹) occurs through lightning and photochemical reactions; biological fixation (150-380 Mt y⁻¹) is prokaryotic conversion of #ce("N_2") to ammonia, representing the largest natural nitrogen input; plant acquisition (1000-1200 Mt y⁻¹) involves plant uptake and assimilation of ammonium or nitrate; immobilization is microbial assimilation of inorganic nitrogen; ammonification is bacterial and fungal breakdown of organic matter to ammonium; anammox is anaerobic ammonium oxidation; nitrification converts ammonium to nitrate; and denitrification returns nitrogen to the atmosphere as #ce("N_2"). This table quantifies the global nitrogen cycle and highlights the critical importance of biological nitrogen fixation in maintaining nitrogen availability for ecosystems and agriculture.],
    path: "../fig/image_place_holder.png"
  ),
  "table-14.2": (
    caption: [Examples of organisms that can carry out nitrogen fixation, divided into symbiotic and free-living categories. Symbiotic nitrogen fixation includes: legume hosts (legumes and Parasponia) with Azorhizobium, Bradyrhizobium, Mesorhizobium, Rhizobium, and Sinorhizobium; actinorhizal plants (alder trees, Ceanothus, Casuarina, Datisca) with Frankia bacteria; Gunnera with Nostoc cyanobacteria; Azolla water fern with Anabaena cyanobacteria; and grasses like sugarcane and Miscanthus with Acetobacter and Azospirillum. Free-living nitrogen fixation includes cyanobacteria (Anabaena, Calothrix, Nostoc) and other bacteria categorized by oxygen requirements: aerobic (Azospirillum, Azotobacter, Beijerinckia, Derxia, Gloeothece), facultative (Bacillus, Klebsiella), and anaerobic types including non-photosynthetic (Clostridium, Methanococcus) and photosynthetic (Chromatium, Rhodospirillum). This comprehensive list demonstrates the diversity of nitrogen-fixing organisms and their ecological niches.],
    path: "../fig/image_place_holder.png"
  ),
  "table-14.3": (
    caption: [Associations between specific legume host plants and their compatible rhizobial symbionts, illustrating host-specificity in legume-rhizobia symbioses. Examples include: Parasponia (a rare non-legume) with Bradyrhizobium spp.; soybean (Glycine max) with Bradyrhizobium japonicum (slow-growing) and Sinorhizobium fredii; common bean (Phaseolus vulgaris) with Rhizobium leguminosarum and R. tropici; pea (Pisum sativum) with Rhizobium leguminosarum; clover (Trifolium) species with various Rhizobium strains; alfalfa (Medicago sativa) with Sinorhizobium meliloti; and other legume-rhizobia pairs. Host specificity is determined primarily by Nod factor structures produced by rhizobia in response to specific flavonoids secreted by host plant roots, ensuring that only compatible partners form effective nitrogen-fixing nodules.],
    path: "../fig/image_place_holder.png"
  ),
  "table-14.4": (
    caption: [Substrates reduced by the nitrogenase enzyme complex, demonstrating the enzyme's broad but natural specificity for nitrogen-containing compounds. While nitrogenase can reduce numerous substrates in vitro including acetylene (used to measure nitrogenase activity via acetylene reduction assay, converting acetylene to ethylene), azide, cyanide, and various other nitrogen-containing molecules, under natural physiological conditions nitrogenase primarily reduces only molecular nitrogen (#ce("N_2")) to ammonia and protons (#ce("H^+")) to hydrogen gas (#ce("H_2")). The production of #ce("H_2") is an obligatory side reaction that consumes approximately 25% of electron flow, representing a significant energy cost. Some nitrogenase variants can use alternative substrates, but the reduction of #ce("N_2") remains the primary biological function. This table illustrates both the catalytic versatility and the natural substrate specificity of this ancient and highly conserved enzyme.],
    path: "../fig/image_place_holder.png"
  )
)
