#let images = (
  "figure-6-1": (
    caption: [Main driving forces for water flow from the soil through the plant to the atmosphere. Differences in water vapor concentration (Δ#sub[cwv]) between leaf and air are responsible for the diffusion of water vapor from the leaf to the air; differences in pressure potential (ΔΨ#sub[p]) drive the bulk flow of water through xylem conduits; and differences in water potential (ΔΨ) are responsible for the movement of water across the living cells in the root. This diagram illustrates the three different transport mechanisms that work together to move water through the soil-plant-atmosphere continuum.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-2": (
    caption: [Root hairs make intimate contact with soil particles and greatly amplify the surface area used for water absorption by the plant. The soil is a mixture of particles (sand, clay, silt, and organic material), water, dissolved solutes, and air. When the soil is wet, the curvature of air–water interfaces is small. As water is absorbed by the plant, the soil solution recedes into smaller pockets, channels, and crevices between the soil particles. This recession causes the curvature of air–water interfaces in the soil to increase, resulting in a decrease in Ψ#sub[p] (pressure potential).],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-3": (
    caption: [Water uptake by roots. (A) Rate of water uptake by short segments (3–5 mm) at various positions along an intact pumpkin (*Cucurbita pepo*) root, showing that water uptake occurs primarily near the root tip in less suberized regions. (B and C) Diagrams comparing water uptake patterns when the entire root surface is equally permeable versus when older regions are impermeable due to suberin deposition. When root surfaces are equally permeable, most water enters near the top of the root system, with more distal regions being hydraulically isolated. Decreasing the permeability of older regions allows xylem tensions to extend farther into the root system, enabling water uptake from distal regions.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-4": (
    caption: [Pathways for water uptake by the root. Through the cortex, water may travel via three distinct pathways: the apoplast pathway (water flows through cell walls and extracellular spaces without crossing membranes), the transmembrane pathway (water crosses plasma membranes, entering and exiting cells sequentially), and the symplasm pathway (water flows between cells through plasmodesmata without crossing the plasma membrane). At the endodermis, the apoplast pathway is blocked by the Casparian strip, a band of hydrophobic lignin in the radial cell walls. Many roots also develop a Casparian strip in the outer cell layer of the cortex, forming an exodermis where flow through the apoplast pathway is blocked. This structure forces selective membrane transport and allows the plant to control which solutes enter the xylem.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-5": (
    caption: [Guttation in a leaf from lady's mantle (*Alchemilla vulgaris*). In the early morning, leaves secrete water droplets through hydathodes, specialized pores located at the margins of the leaves. This phenomenon occurs when root pressure (positive hydrostatic pressure in the xylem resulting from solute accumulation) causes exudation of xylem sap. Guttation is most noticeable when transpiration is suppressed and relative humidity is high, such as at night. The positive pressures within the xylem at night can help dissolve gas bubbles and reverse the effects of cavitation.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-6": (
    caption: [Xylem conduits and their interconnections. (A) Structural comparison of tracheids and vessel elements. Tracheids are elongated, hollow, dead cells with highly lignified walls containing numerous pits (regions where secondary wall is absent but primary wall remains). Vessels consist of stacks of vessel elements connected by perforation plates (regions with pores or holes). (B) Scanning electron micrograph showing vessels with pits on side walls and scalariform (ladderlike) perforation plates between vessel elements. (C) Diagram of coniferous bordered pit pair with torus (thickened central region) and margo (porous outer region). When pressure difference is small, the torus is centered allowing water flow through the margo; when pressure difference is large (e.g., one tracheid cavitated), the torus lodges against the walls, preventing embolism propagation. (D) Angiosperm pit membranes are homogeneous with very small pores that prevent embolism spread but impart significant hydraulic resistance. (E and F) Scanning electron microscope images showing torus–margo membrane structure in conifers versus homogenous pit membrane in angiosperms.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-7": (
    caption: [Vessels and tracheids form a series of parallel, interconnected pathways for water movement. Cavitation blocks water movement by forming gas-filled (embolized) conduits. Because xylem conduits are interconnected through bordered pits in their thick secondary walls, water can detour around blocked vessels by moving through adjacent conduits. Pit membranes help prevent embolisms from spreading between xylem conduits. In vessels, gas can fill the entire cavitated vessel (shown as three vessel elements separated by scalariform perforation plates; in nature, vessels can be several meters long). In tracheids, gas is typically contained within a single cavitated tracheid due to pit membrane function.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-8": (
    caption: [The driving force for water movement through plants originates in leaves. As water evaporates from the surfaces of mesophyll cells, water withdraws farther into the interstices of the cell wall. Because cellulose is hydrophilic (contact angle = 0°), the force resulting from surface tension causes a negative pressure in the liquid phase. As the radius of curvature of the air–water interfaces decreases (from 0.5 μm to 0.05 μm to 0.01 μm), the hydrostatic pressure becomes more negative (from –0.3 MPa to –3 MPa to –15 MPa), as calculated from the Young–Laplace equation (Ψ#sub[p] = –2T/r). This negative pressure creates the tension that pulls water up through the xylem.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-9": (
    caption: [Xylem vulnerability curves represent the percentage loss of hydraulic conductance in stem xylem versus xylem water pressure in three species of contrasting drought tolerance: cottonwood (moisture-adapted), Wyoming sagebrush (intermediate), and hoaryleaf ceanothus (drought-adapted). Data were obtained from excised branches subjected experimentally to increasing levels of xylem tension using a centrifugal force technique. Arrows on the upper axis indicate the minimum xylem pressure measured in the field for each species. Species from moist habitats like cottonwood show decreased hydraulic conductivity at much lower tensions than species from arid regions like sagebrush, reflecting adaptations to their respective environments. The curves quantify species' susceptibility to cavitation and the impact of cavitation on xylem flow.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-10": (
    caption: [Water pathway through the leaf. Water is pulled from the xylem into the cell walls of the mesophyll, where it evaporates into the air spaces within the leaf. Water vapor then diffuses through the leaf air space, through the stomatal pore, and across the boundary layer of still air found next to the leaf surface. #ce("CO_2") diffuses in the opposite direction along its concentration gradient (low inside, higher outside). The diagram shows key components including the cuticle, upper epidermis, palisade parenchyma, mesophyll cells, lower epidermis, guard cells, stomatal pore, substomatal cavity, and the two main resistances: leaf stomatal resistance (r#sub[s]) and boundary layer resistance (r#sub[b]). Water vapor concentration is high in the leaf and low in the surrounding air, while #ce("CO_2") concentration is low in the leaf and high outside.],
    path: "../fig/image_place_holder.png"
  ),
  "table-6-1": (
    caption: [Representative values for relative humidity, absolute water vapor concentration, and water potential for four points in the pathway of water loss from a leaf at 25°C (inner air spaces and just inside stomatal pore) and 20°C (just outside stomatal pore and bulk air). The table shows how water vapor concentration (c#sub[wv]) decreases at each step of the pathway from the cell wall surface (1.27 mol m#super[–3], 99% RH, –1.38 MPa) to the bulk air outside the leaf (0.50 mol m#super[–3], 50% RH, –93.6 MPa). The driving force for water loss is the absolute concentration difference (difference in c#sub[wv]), and this difference is markedly influenced by leaf temperature. This demonstrates the steep gradient driving transpiration.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-11": (
    caption: [Dependence of transpiration on the stomatal aperture of zebra plant (*Zebrina pendula*) in still air and in moving air. The boundary layer is thicker and more rate-limiting in still air than in moving air. As a result, the stomatal aperture has less control over transpiration in still air (transpiration rate plateaus around 5 μm stomatal aperture), while in moving air, transpiration increases more steeply with stomatal aperture. When the air surrounding the leaf is very still, the thick boundary layer may be the primary deterrent to water vapor loss. When wind velocity is high, the moving air reduces boundary layer thickness and stomatal resistance largely controls water loss. This demonstrates the interaction between stomatal and boundary layer resistances in controlling transpiration.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-12": (
    caption: [Stomata and guard cell structure. (A) Most plants have kidney-shaped guard cells, as seen in this open stoma of *Tradescantia zebrina*, with the stomatal pore at their center. (B) Stomata of maize (*Zea mays*) showing dumbbell-shaped guard cells typical of grasses, with bulbous ends and a long slit pore between the two "handles." These guard cells are flanked by subsidiary cells that help control the stomatal pore. (C) Radial alignment of cellulose microfibrils in guard cells and epidermal cells. In kidney-shaped stomata, microfibrils fan out radially from the pore, making the wall facing the pore stronger than the wall contacting epidermal cells. As guard cells increase in volume, the side facing the epidermis expands more, causing the pore to open. In grass stomata, microfibrils are oriented such that as the bulbous ends increase in volume, the beams move apart and the slit widens. The guard cells, subsidiary cells, and pore are collectively called the stomatal complex.],
    path: "../fig/image_place_holder.png"
  ),
  "figure-6-13": (
    caption: [Guard cell wall structure. (A) Electron micrograph of a stoma from grass (*Phleum pretense*) showing the bulbous ends of each guard cell with their cytosolic content, joined by heavily thickened walls. The stomatal pore separates the two midportions of the guard cells. (B) Electron micrograph showing a pair of guard cells from tobacco (*Nicotiana tabacum*) in cross-section perpendicular to the main leaf surface. In both images, the stomatal pore is very small, indicating the stomata are essentially closed. The uneven thickening pattern of the walls (with very thick inner and outer walls, thin walls contacting surrounding epidermal cells, and somewhat thickened walls facing the pore) determines the asymmetric deformation of guard cells when their volume increases during stomatal opening. Portions of outer walls often extend into well-developed ledges. These wall thickenings can be up to 5 μm thick, compared to 1–2 μm in typical epidermal cells.],
    path: "../fig/image_place_holder.png"
  )
)
