#let images = (
  "8.1": (
    caption: [Relationship between chemical potential and the transport of molecules across a semipermeable membrane. The net movement of molecular species between compartments A and B depends on the relative magnitude of the chemical potential in each compartment. Movement down a chemical gradient occurs spontaneously and is called passive transport; movement against a gradient requires energy input and is called active transport.],
    path: "../fig/image_place_holder.png"
  ),
  "8.2": (
    caption: [Development of a diffusion potential and a charge separation between two compartments separated by a membrane that is preferentially permeable to potassium ions. If the concentration of potassium chloride is higher in compartment A, potassium and chloride ions will diffuse into compartment B. If the membrane is more permeable to potassium than to chloride, more potassium ions will cross the membrane, creating an electrical potential difference (diffusion potential) across the membrane.],
    path: "../fig/image_place_holder.png"
  ),
  "8.3": (
    caption: [Diagram of a pair of microelectrodes used to measure membrane potentials across plasma membranes. One of the glass micropipette electrodes is inserted into the cell compartment under study (usually the vacuole or the cytoplasm), while the other is kept in an electrically conducting solution that serves as a reference. The microelectrodes are connected to a sensitive voltmeter that measures the electrical potential difference between the two compartments.],
    path: "../fig/image_place_holder.png"
  ),
  "8.4": (
    caption: [The plasma membrane potential of a pea cell collapses when cyanide is added to the bathing solution. Cyanide blocks ATP production in the cell by poisoning the mitochondria. The collapse of the membrane potential upon addition of cyanide indicates that an ATP supply is necessary for maintenance of the potential. Washing out the cyanide allows the cell to recover its membrane potential.],
    path: "../fig/image_place_holder.png"
  ),
  "8.5": (
    caption: [Typical values for the permeability of a biological membrane to various substances compared with those for an artificial phospholipid bilayer. For nonpolar molecules such as oxygen and carbon dioxide, and for some small uncharged molecules such as glycerol, permeability values are similar in both systems. For ions and selected polar molecules, including water, the biological membrane has much higher permeability than the artificial bilayer, indicating the presence of membrane transport proteins.],
    path: "../fig/image_place_holder.png"
  ),
  "8.6": (
    caption: [Three classes of membrane transport proteins: channels, carriers, and pumps. Channels and carriers can mediate the passive transport of a solute across a membrane down the electrochemical potential gradient of the solute. Channel proteins act as membrane pores, and their specificity is determined primarily by the biophysical properties of the pore. Carrier proteins bind solutes and undergo conformational changes to transport them across membranes. Pumps use metabolic energy (usually from ATP hydrolysis) to drive the active transport of solutes against their electrochemical potential gradients.],
    path: "../fig/image_place_holder.png"
  ),
  "8.7": (
    caption: [Models of potassium channels in plants. (A) Top view of a channel, looking through the pore of the protein. Membrane-spanning helices of four subunits come together in an inverted teepee with the pore at the center. The pore-forming regions of the four subunits dip into the membrane, forming a potassium selectivity filter region at the outer part of the pore. (B) Side view showing the structure of a single subunit with its transmembrane domains and pore-forming region.],
    path: "../fig/image_place_holder.png"
  ),
  "8.8": (
    caption: [Current-voltage relationships. (A) Diagram showing the current that would result from potassium flux through a set of hypothetical plasma membrane potassium channels that were not voltage-regulated, given a potassium concentration in the cytosol of 100 mM and an extracellular potassium concentration of 1 mM. (B) Actual current-voltage relationships for inward-rectifying and outward-rectifying potassium channels. Inward-rectifying channels conduct potassium more readily into the cell than out of the cell, while outward-rectifying channels show the opposite behavior.],
    path: "../fig/image_place_holder.png"
  ),
  "8.9": (
    caption: [Hypothetical model of secondary active transport. In secondary active transport, the energetically uphill transport of one solute is driven by the energetically downhill transport of another solute. In the illustrated example, energy that was stored as proton motive force is being used to drive the accumulation of a solute against its concentration gradient. The proton gradient was generated by a primary active transport pump.],
    path: "../fig/image_place_holder.png"
  ),
  "8.10": (
    caption: [Two examples of secondary active transport coupled to a primary proton gradient. (A) In symport, the energy dissipated by a proton moving back into the cell is coupled to the uptake of one molecule of a solute (e.g., a sugar) into the cell. (B) In antiport, the energy dissipated by a proton moving back into the cell is coupled to the active transport of a substrate (e.g., a sodium ion) out of the cell. In both cases, the substrate under study moves against its concentration gradient.],
    path: "../fig/image_place_holder.png"
  ),
  "8.11": (
    caption: [Carrier transport often shows enzyme kinetics, including saturation (Vmax). In contrast, simple diffusion through open channels is ideally directly proportional to the concentration of the transported solute or, for an ion, to the difference in electrochemical potential across the membrane. The saturation kinetics of carriers reflect the fact that they have a limited number of binding sites that can become saturated at high substrate concentrations.],
    path: "../fig/image_place_holder.png"
  ),
  "8.12": (
    caption: [The transport properties of a solute can change with solute concentrations. For example, at low concentrations (1-10 mM), the rate of uptake of sucrose by soybean cells shows saturation kinetics typical of carriers. A curve fitted to these data is predicted to approach a maximum rate (Vmax) of 57 nmol per million cells per hour. Instead, at higher sucrose concentrations, the uptake rate continues to increase, suggesting that additional transport systems or different transport mechanisms become active at higher substrate concentrations.],
    path: "../fig/image_place_holder.png"
  ),
  "8.13": (
    caption: [Overview of the various transport proteins in the plasma membrane and tonoplast of plant cells. The diagram shows the diversity of channels, carriers, and pumps that regulate the movement of ions, nutrients, and other solutes across cellular membranes. These include potassium channels, proton pumps, calcium pumps, various ion transporters, and aquaporins for water transport.],
    path: "../fig/image_place_holder.png"
  ),
  "8.14": (
    caption: [Five families of Arabidopsis cation channels. Some channels have been identified from sequence homology with channels of animals, while others have been experimentally verified. (A) Two families of potassium-selective channels: voltage-gated potassium channels and two-pore domain potassium channels. (B) Weakly selective cation channels with activity regulated by cyclic nucleotides. (C) Glutamate receptor-like channels. (D) Mechanosensitive channels. (E) Calcium-permeable channels.],
    path: "../fig/image_place_holder.png"
  ),
  "8.15": (
    caption: [Examples of coordination complexes. Coordination complexes form when oxygen or nitrogen atoms of a carbon compound donate shared electron pairs to form a bond with a cation. (A) Copper ions share electrons with the hydroxyl oxygens of tartaric acid. (B) Magnesium ions share electrons with nitrogen atoms in chlorophyll, forming the active center of this important photosynthetic pigment.],
    path: "../fig/image_place_holder.png"
  ),
  "8.16": (
    caption: [Examples of electrostatic (ionic) complexes. (A) The monovalent cation potassium and malate form the complex potassium malate. (B) The divalent cation calcium and pectate form the complex calcium pectate. Divalent cations can form cross-links between parallel strands that contain negatively charged carboxylic acid groups. Calcium ion cross-links play a structural role in the cell walls.],
    path: "../fig/image_place_holder.png"
  ),
  "8.17": (
    caption: [Two mechanisms for iron uptake by plants. (A) A process used by eudicots such as pea, tomato, and soybean. The chelators include organic compounds such as malic acid, citric acid, phenolics, and piscidic acid. A ferric reductase reduces iron(III) to iron(II), which is then transported into the root cell by an iron transporter. (B) A process used by grasses such as barley, maize, and oat. After the grass excretes a siderophore that removes iron from soil particles, the iron-siderophore complex is transported into the root cell.],
    path: "../fig/image_place_holder.png"
  ),
  "8.18": (
    caption: [The ferrochelatase reaction. The enzyme ferrochelatase catalyzes the insertion of iron into the porphyrin ring to form a coordination complex. This reaction is crucial for the synthesis of heme groups used in cytochromes and other iron-containing proteins.],
    path: "../fig/image_place_holder.png"
  ),
  "8.19": (
    caption: [Hypothetical steps in the transport of a proton against its chemical gradient by proton-ATPase. The pump, embedded in the membrane, (A) binds the proton on the inside of the cell and (B) is phosphorylated by ATP. (C) This phosphorylation leads to a conformational change that exposes the proton-binding site to the outside of the cell, where the proton is released. (D) The pump returns to its original conformation after dephosphorylation.],
    path: "../fig/image_place_holder.png"
  ),
  "8.20": (
    caption: [Three-dimensional representation of the plasma membrane proton-ATPase AtAHA2 from Arabidopsis thaliana. The nucleotide (N) binding domain, phosphorylation (P) domain, actuator (A) domain, and transmembrane domain contain ten transmembrane spans. The solvent cavity within the transmembrane domain contains eight to ten water molecules that facilitate proton transport.],
    path: "../fig/image_place_holder.png"
  ),
  "8.21": (
    caption: [Model of the V-ATPase rotary motor. Many polypeptide subunits come together to make up this complex enzyme. The V1 catalytic complex, which is easily dissociated from the membrane, contains the nucleotide-binding and catalytic sites. Components of V1 are designated by uppercase letters. The integral membrane complex mediating proton transport is designated V0 and consists of subunits labeled with lowercase letters. ATP hydrolysis drives rotation of the central stalk, which causes conformational changes that pump protons across the membrane.],
    path: "../fig/image_place_holder.png"
  ),
  "8.22": (
    caption: [Micrograph of a light-stimulated stomatal opening in detached epidermis of Vicia faba. An open, light-treated stoma is shown in (A), and a closed, dark-treated stoma is shown in (B). Stomatal aperture is quantified by measuring the width of the stomatal pore. The changes in aperture result from changes in the volume of the guard cells driven by ion and water fluxes.],
    path: "../fig/image_place_holder.png"
  ),
  "8.23": (
    caption: [Transport activities in guard cells during stomatal opening and closing. (A) Stomatal opening: Blue light is detected by phototropins, which activate proton-ATPases in the plasma membrane. The resulting hyperpolarization activates inward-rectifying potassium channels, leading to potassium uptake. Chloride and malate also accumulate in the guard cells. Water follows osmotically, causing the guard cells to swell and the stomatal pore to open. (B) Stomatal closing: Abscisic acid (ABA) triggers calcium release, which activates outward-rectifying potassium channels and anion channels. The resulting loss of ions and water causes guard cells to shrink and the stomatal pore to close.],
    path: "../fig/image_place_holder.png"
  ),
  "8.24": (
    caption: [Plasmodesmata connect the cytoplasm of neighboring cells, thereby facilitating cell-to-cell communication. These cytoplasmic channels traverse the cell wall and provide a symplastic pathway for the movement of ions, small molecules, and even proteins and RNA between adjacent cells.],
    path: "../fig/image_place_holder.png"
  ),
  "8.25": (
    caption: [Tissue organization in roots. (A) Cross section through a root of carrion flower (genus Smilax), a monocot, showing the epidermis, cortex parenchyma, endodermis, xylem, and phloem. (B) Schematic diagram of a root cross section, illustrating the cell layers through which solutes pass from the soil solution to the xylem tracheary elements. The endodermis, with its Casparian strip, serves as a barrier that forces solutes to pass through the symplast before entering the xylem.],
    path: "../fig/image_place_holder.png"
  ),
  "table-8.1": (
    caption: [Comparison of observed and predicted ion concentrations in pea root tissue. The table shows experimental measurements of ion concentrations at steady state in pea root cells compared with predicted values calculated from the Nernst equation. The data illustrate that only potassium is at or near equilibrium, while other ions are maintained far from equilibrium by active transport processes.],
    path: "../fig/image_place_holder.png"
  )
)
