#let images = (
  "2.1": (
    caption: [The Weddell seal (Leptonychotes weddellii), though clumsy on land, can dive to over 500 meters depth and remain submerged for up to an hour and 20 minutes. The Adélie penguin (Pygoscelis adeliae) must overcome the buoyancy of its plumage to descend, but that buoyancy also allows it to ascend rapidly.],
    path: "../fig/fig-2025-10-16-09-45-41.png"
  ),
  "2.2": (
    caption: [Water expands and becomes less dense as it freezes. Because the density of ice is 0.92 g per cm³ (just slightly less than that of liquid water, which is 1 g per cm³), this antarctic iceberg floats, but more than 90% of its bulk lies below the sea surface.],
    path: "../fig/fig-2025-10-16-09-45-58.png"
  ),
  "2.3": (
    caption: [The droplets of oil in these algal cells provide buoyancy.],
    path: "../fig/fig-2025-10-16-09-46-21.png"
  ),
  "2.4": (
    caption: [Streamlined shapes reduce the drag of water. The sleek bodies of barracudas (Sphyraena) allow them to swim rapidly through water with a relatively low expenditure of energy.],
    path: "../fig/fig-2025-10-16-09-47-34.png"
  ),
  "2.5": (
    caption: [Appendages prevent small aquatic animals from sinking. These long, filamentous and feathery projections from the body of a tropical marine planktonic crustacean retard sinking.],
    path: "../fig/fig-2025-10-16-09-46-34.png"
  ),
  "2.6": (
    caption: [Diatoms use silicates to build their shells. The glassy outer shells of these photosynthetic protists take diverse forms, as shown by these scanning electron micrographs of (a) Entogonia and (b) Cyclotella.],
    path: "../fig/fig-2025-10-16-09-49-48.png"
  ),
  "2.7": (
    caption: [Limestone is made of calcium carbonate. The limestone sediments that form many mountains represent calcium carbonate precipitated out of solution in shallow seas.],
    path: "../fig/fig-2025-10-16-09-50-52.png"
  ),
  "2.8": (
    caption: [The pH scale of hydrogen ion concentration extends from 0 (highly acidic) to 14 (highly alkaline).],
    path: "../fig/fig-2025-10-16-09-51-31.png"
  ),
  "2.9": (
    caption: [Soils with smaller particles hold more water. Soils with large particles have large spaces between them that are not completely filled with water at field capacity. Soils with very small particles hold more water, but they hold it so tightly that its availability to plants is reduced.],
    path: "../fig/fig-2025-10-16-09-52-23.png"
  ),
  "2.10": (
    caption: [Solutes enclosed within a membrane that is permeable to water create an osmotic potential. Plant roots use this principle to draw water from the soil and to develop sufficient osmotic pressure to push water up into the stem.],
    path: "../fig/fig-2025-10-16-09-53-09.png"
  ),
  "2.11": (
    caption: [The cohesion–tension theory explains the movement of water from the roots to the leaves of a plant. The water potential that draws water upward is generated by transpiration.],
    path: "../fig/fig-2025-10-16-09-53-39.png"
  ),
  "2.12": (
    caption: [Plants control water loss by opening and closing stomates on the leaf surface.],
    path: "../fig/fig-2025-10-16-09-54-01.png"
  ),
  "2.13": (
    caption: [Mangroves have adaptations for coping with a high salt load. (a) The roots of mangroves are immersed in salt water at high tide. (b) Specialized glands in the leaves of the button mangrove (Conocarpus erecta) excrete salt, which precipitates on their outer surfaces.],
    path: "../fig/fig-2025-10-16-09-54-44.png"
  ),
  "2.14": (
    caption: [Exchanges of water and solutes differ between freshwater and marine fish. The body fluids of freshwater fish are hyperosmotic (have a higher salt concentration than the surrounding water), whereas those of marine fish are hypo-osmotic. The gills and kidneys of fish actively exclude or retain solutes to maintain salt balance. Marine fish must drink to acquire water.],
    path: "../fig/fig-2025-10-16-09-55-54.png"
  ),
  "2.15": (
    caption: [Sharks match their total solute concentration to that of seawater. Sodium, potassium, urea, and other solutes (mostly chloride ions) contribute differently to the osmotic potential of seawater and of the body fluids of marine fish and sharks.],
    path: "../fig/fig-2025-10-16-09-59-44.png"
  ),
  "2.16": (
    caption: [The tiny copepod Tigriopus, shown here with an attached egg mass, lives in splash pools high in the rocky intertidal zone in California.],
    path: "../fig/fig-2025-10-16-10-00-51.png"
  )
)
