#let images = (
  "23-1": (
    caption: [Parasitism at many levels. (A) Most animals harbor parasites, an example being the blacklegged tick, or deer tick (Ixodes scapularis), shown here on a human finger. Although ticks of this species thrive on white-tailed deer and other wild mammals, they can also live on humans. (B) Ticks themselves harbor their own parasites including the bacterium Borrelia burgdorferi, stained here with a vital dye that labels living bacteria green and dead bacteria red. These long spiral- shaped bacteria live in deer ticks and can be transmitted to humans during a tick’s blood meal. B. burgdorferi causes Lyme disease, which is characterized by a bull’s-eye–shaped skin rash and fever; if the infection is left untreated, various complications can result, including arthritis and neurological abnormalities. The idea that parasites have their own parasites was noted by Jonathan Swift in 1733: “So, naturalists observe, a flea Has smaller fleas that on him prey; And these have smaller still to bite ’em; And so proceed ad infinitum.” (A, National Geographic Image Collection/Alamy Stock Photo; B, courtesy of M. Embers.) 1314 Chapter 23: Pathogens and Infection (A) (B) 20 µm],
    path: "../fig/image_place_holder.png"
  ),
  "23-2": (
    caption: [Pathogens in many forms. (A) The structure of the protein coat, or capsid, of poliovirus. This virus was once a common cause of paralysis, but the disease (poliomyelitis) has been greatly reduced by widespread vaccination. (B) The bacterium Vibrio cholerae, the causative agent of the epidemic diarrheal disease cholera, shown here with its attached flagellum. (C) The protozoan parasite Trypanosoma brucei (purple) in a field of erythrocytes (red blood cells; pink). This parasite causes African sleeping sickness, a potentially fatal disease of the central nervous system. (D) Powdery mildew spores germinating on an Arabidopsis leaf. (E) This clump of Ascaris nematodes was passed rectally by a child in Africa. (A, courtesy of Robert Grant, Stephan Crainic, and James M. Hogle; B, photograph kindly provided by John Mekalanos; C, CDC, Department of Health and Human Services; D, courtesy of Kim Findlay and John Innes Centre; E, CDC/James Gathany.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-3": (
    caption: [Bacterial shapes and cell-surface structures. (A) Bacteria are traditionally classified by shape. For example, the bacterium Borrelia burgdorferi, shown in Figure 23–1B, is spiral shaped and is thus classified as a spirochete. (B and C) Bacteria are also classified as Gram positive or Gram negative on the basis of a staining procedure first described in 1884. (B) Gram-positive bacteria such as Streptococcus and Staphylococcus have a single membrane and a thick cell wall made of cross-linked peptidoglycan. They are called Gram positive because they retain the violet dye used in the Gram-staining procedure. (C) Gram-negative bacteria such as Escherichia coli (E. coli) and Salmonella enterica have two membranes, separated by the periplasm (see Figure 11–17). The peptidoglycan cell wall of these organisms is located in the periplasm and is thinner than in Gram-positive bacteria; they therefore fail to retain the dye in the Gram-staining procedure. The inner membrane of both Gram-positive and Gram-negative bacteria is a phospholipid bilayer. The inner leaflet of the outer membrane of Gram-negative bacteria is also made primarily of phospholipids, whereas the outer leaflet of the outer membrane is composed of the unique glycosylated lipid LPS. (D) Cell-surface appendages are important for bacterial behavior. Both Gram-positive and Gram-negative bacteria swim using the rotation of helical flagella. An example is V. cholerae, depicted in panel A and shown in Figure 23–2B. Although the bacterium illustrated has only a single flagellum at one pole, many have multiple flagella. Pili (also called fimbriae) are used to adhere to various surfaces in the host and to facilitate genetic exchange between bacteria. Some kinds of pili can retract to generate force and thereby help bacteria move along surfaces.],
    path: "../fig/image_place_holder.png"
  ),
  "23-4": (
    caption: [Genetic differences between pathogenic and nonpathogenic bacteria. (A) Genetic differences between nonpathogenic E. coli and two closely related food-borne pathogens—Shigella flexneri, which causes dysentery, and Salmonella enterica serovar Typhimurium, a common cause of food poisoning. Nonpathogenic E. coli has a single circular chromosome. The chromosome of S. flexneri differs from that of E. coli in a limited number of locations; most of the genes required for pathogenesis (virulence genes) are carried on an extrachromosomal virulence plasmid. The chromosome of S. enterica serovar Typhimurium carries two large inserts (pathogenicity islands) not found in the E. coli chromosome; these inserts each contain many virulence genes. (B) Bacterial pathogens evolve by horizontal gene transfer. This can occur by three mechanisms: natural transformation, in which naked DNA is taken in by competent bacteria; transduction, in which bacterial viruses (bacteriophages) transfer DNA from one bacterium (in the example shown, a pathogen) into another; and conjugation (see Movie 23.1), during which plasmid DNA, and even chromosomal DNA, is transferred from a donor to a recipient bacterium.],
    path: "../fig/image_place_holder.png"
  ),
  "23-5": (
    caption: [Model for the evolution of pathogenic V. cholerae strains. Progenitor strains in the wild first acquired the biosynthetic pathway necessary to make the O1 antigen type of carbohydrate chain (blue outline) on the outer-membrane LPS (see Figure 23–3C), a feature that is associated with the ability to cause epidemic cholera disease. Incorporation of the CTX bacteriophage created the classical pathogenic strains responsible for the first six worldwide epidemics of cholera between 1817 and 1923. Sometime in the twentieth century, an O1 strain in the environment picked up the CTX bacteriophage again, along with an associated bacteriophage RS1 and two pathogenicity islands (VSP-1 and VSP-2), creating the El Tor (wave 1) strain that emerged as the seventh worldwide pandemic in 1961. In the 1990s, an El Tor strain was isolated that had picked up a new DNA cassette, enabling it to produce the O139 antigen type of carbohydrate chain (purple outline) rather than the O1 type. This altered the bacterium’s interaction with the human immune system without diminishing its virulence; this bacterium also picked up a new pathogenicity island (SXT). Separately, wave 2 strains emerged, in which CTX-1 was replaced with CTX-2–6 bacteriophages. In 2006, wave 3 strains emerged with variant CTX-3 and CTX- 6 bacteriophages. The history of the V. cholerae strains shown in this diagram was deduced by comparing the DNA sequences of the genome of each strain to one another and noting the key differences. An electron micrograph of V. cholerae is shown in Figure 23–2B. 1318 Chapter 23: Pathogens and Infection V. cholerae progenitor O1 surface antigen V. cholerae O1 serogroup 1961–2000 WAVE 1],
    path: "../fig/image_place_holder.png"
  ),
  "23-6": (
    caption: [Toxins released by bacteria bind to and enter into host cells, disrupting host-cell processes. Bacterial toxins are often composed of A and B protein subunits. The B (binding) subunit of the toxin, which interacts with host- cell toxin receptors, can assemble after binding to toxin receptors (as with anthrax toxin) or prior to receptor binding (as with cholera and pertussis toxins). Binding to toxin receptors enables endocytosis and intracellular trafficking of the B subunits and the associated and enzymatically active A subunit(s). In the case of Bacillus anthracis, the B subunit changes conformation in the low-pH environment of the endosome to form a pore through which two different A subunits, lethal factor and edema factor, are transported across the membrane of the endosome in an unfolded conformation. In the cases of V. cholerae toxin and Bordetella pertussis toxin, the B and A subunits are transported to the Golgi apparatus and then to the endoplasmic reticulum (ER), where the A subunits are then translocated into the cytosol in an unfolded conformation through a protein-translocation channel (see Movie 23.2).],
    path: "../fig/image_place_holder.png"
  ),
  "23-7": (
    caption: [Contact-dependent type III secretion systems can deliver effector proteins from the cytosol of a bacterium directly into the host cell. (A) Electron micrograph of type III secretion systems on the surface of a bacterial cell, each of which consists of more than two dozen proteins. (B) The large lower ring is embedded in the bacterial inner membrane, and the smaller upper ring is embedded in the bacterial outer membrane. During infection, docking of the tip of the hollow needle at a host-cell plasma membrane results in the secretion of bacterial translocator proteins (dark green), which form a pore in the host membrane. Bacterial effector proteins (blue) are initially bound to chaperone proteins in the bacterial cytosol (light green), which keep them in an unfolded conformation. Unfolded effector proteins then pass through the injectisome and are secreted into the host cell, where they fold into their active conformation. (A, Hu et al., Cell 168:1065–1074, 2017. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-8": (
    caption: [Dimorphism in the pathogenic fungus Histoplasma capsulatum. (A) At low temperature in the soil, H. capsulatum grows as a multicellular filamentous mold consisting of many individual cells connected together. (B) After it is inhaled into the lung of a mammal, the increase in temperature to 37°C causes a switch to a yeast form consisting of small clumps of round cells. (C) A stained histologic section of a mouse lung infected with H. capsulatum, showing a macrophage containing yeast forms of the pathogen. (A and B, courtesy of Sinem Beyhan and Anita Sil; C, courtesy of Davina Hocking Murray and Anita Sil.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-9": (
    caption: [The complex life cycle of malaria parasites. (A) The sexual cycle of Plasmodium falciparum requires passage between a human host and an insect host (see Movie 23.3). (B–D) Blood smears from people with malaria, showing three different forms of the parasite that appear in red blood cells: B, ring stage; C, schizont; and D, gametocyte. (B–D, courtesy of the Centers for Disease Control, Division of Parasitic Diseases, DPDx.) 1322 Chapter 23: Pathogens and Infection],
    path: "../fig/image_place_holder.png"
  ),
  "23-1": (
    caption: [Viruses That Cause Human Disease],
    path: "../fig/image_place_holder.png"
  ),
  "23-10": (
    caption: [A simple viral life cycle. The hypothetical simple virus shown here consists of a small double-stranded DNA molecule that codes for only a single viral capsid protein. To reproduce, the viral genome must (1) enter a host cell, where it (2) disassembles and releases its genetic material. The genome is (3) replicated to produce multiple copies, and (4) transcribed and translated to produce the viral coat protein. The viral genomes can then (5) assemble spontaneously with the coat protein to form a new virus particle, which (6) escapes from the host cell. No known virus is this simple.],
    path: "../fig/image_place_holder.png"
  ),
  "23-11": (
    caption: [Examples of viral morphology. As shown, both DNA and RNA viruses vary greatly in both size and shape. Although there is a general correlation between virus physical size and genome size, there are likely to be outliers such as Ebola virus, which has a large physical size but a smaller genome size suggesting a lower degree of genome compaction.],
    path: "../fig/image_place_holder.png"
  ),
  "23-12": (
    caption: [Acquisition of a viral envelope. (A) Electron micrograph of an animal cell from which several copies of an enveloped virus (Semliki Forest virus) are budding. (B) Schematic drawing of the envelope assembly and budding processes. The lipid bilayer that surrounds the viral capsid is derived directly from the plasma membrane of the host cell. In contrast, the proteins in this lipid bilayer (shown in green) are encoded by the viral genome. (A, from A. Loewy et al., J. Virol. 69:469–475, 1995. Reproduced with permission from the American Society for Microbiology.) (A) (B) 100 nm],
    path: "../fig/image_place_holder.png"
  ),
  "23-13": (
    caption: [Effective control of a viral disease through vaccination. The graph shows the number of cases of poliomyelitis reported per year worldwide (blue line) and the global immunization coverage as a percentage of the human population (red line). As immunization coverage increased, disease incidence decreased. (Figure based on information found at https:// polioeradication.org.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-14": (
    caption: [Plague bacteria within a flea. This light micrograph shows the digestive tract dissected from a flea that had dined about 2 weeks previously on the blood of an animal infected with the plague bacterium, Yersinia pestis. The bacteria multiplied in the flea gut to produce large cohesive aggregates (red arrows); the bacterial mass on the left is occluding the passage between the esophagus and the midgut. This type of blockage prevents MBoC7 m23.14/23.14 a flea from digesting its blood meals, so that hunger causes it to bite repeatedly, disseminating the infection. (From B.J. Hinnebusch, E.R. Fischer, and T.G. Schwan, J. Infect. Dis. 178:1406–1415, 1998.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-15": (
    caption: [Pathogenic E. coli in the infected bladder of a mouse. (A) Scanning electron micrograph of uropathogenic E. coli, a common cause of bladder and kidney infections. The bacteria are attached to the surface of epithelial cells lining the infected bladder. (B) A close- up view of one of the bacteria showing the pili on its surface. (C) An E. coli pilus spans the mucus layer and has adaptor proteins on its tip that bind to glycolipids on the surface of kidney cells. (A, from G.E. Soto and S.J. Hultgren, J. Bacteriol. 181:1059– 1071, 1999. With permission from the American Society for Microbiology; B, from D.G. Thanassi and S.J. Hultgren, Methods 20:111–126, 2000. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-16": (
    caption: [H. pylori interaction with epithelial cells in the stomach lining. These bacteria colonize the gastric epithelium by using their flagella to swim through the mucus layer lining the stomach and attach to the surface of epithelial cells. H. pylori produces the enzyme urease, which converts urea obtained from the environment into ammonia that is released and neutralizes acid surrounding the bacterium, raising the pH in its local environment. H. pylori also uses its type IV secretion system to secrete the effector protein CagA, which assists in colonization but also causes chronic disruption of host- cell pathways and prolonged inflammation, which predisposes infected individuals to gastric ulcers and cancer.],
    path: "../fig/image_place_holder.png"
  ),
  "23-17": (
    caption: [and Movie 23.4). The extracellular domain of Tir binds to the bacterial surface protein intimin, trigger- ing actin polymerization in the host cell that results in the formation of a unique cell-surface protrusion called a pedestal; this pushes the tightly adherent bacte- ria up about 1–5 µm from the host-cell membrane, thereby promoting bacterial],
    path: "../fig/image_place_holder.png"
  ),
  "23-17": (
    caption: [Interaction of enteropathogenic E. coli (EPEC) with host intestinal epithelial cells. (A) When EPEC contacts an epithelial cell in the lining of the human gut, it delivers a bacterial protein called Tir into the host cell through a type III secretion system. Tir then inserts into the plasma membrane of the host cell, where it functions as a receptor for the bacterial adhesin protein intimin. Next, a host-cell protein tyrosine kinase phosphorylates the intracellular domain of Tir on tyrosines. Phosphorylated Tir recruits host-cell proteins \[including an adaptor protein, a nucleation-promoting factor (NPF), and the Arp2/3 complex\] that trigger actin polymerization (see Figure 16–12). Consequently, a branched network of actin filaments assembles underneath the bacterium, forming an actin pedestal (see Movie 23.4). (B) EPEC on a pedestal. In this fluorescence micrograph, the DNA of the EPEC and host cell is labeled in blue, Tir protein is labeled in green, and host-cell actin filaments are labeled in red. The inset shows a close-up view of the two upper bacteria on pedestals. (B, from D. Goosney et al., Annu. Rev. Cell Dev. Biol. 16:173–189, 2000. With permission from Annual Reviews.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-18": (
    caption: [Receptor and co-receptors for HIV. All strains of HIV require the CD4 protein as a primary receptor. Early in an infection, most of the viruses use CCR5 as a co-receptor, allowing them to infect macrophages and their precursors, monocytes. As the infection progresses, mutant variants of the virus arise that now use CXCR4 as a co-receptor, enabling them to infect helper T cells efficiently. The natural ligand for the chemokine receptors (Sdf1 for CXCR4; RANTES, MIP-1α, or MIP-1β for CCR5) blocks co-receptor function and prevents viral invasion. 1330 Chapter 23: Pathogens and Infection],
    path: "../fig/image_place_holder.png"
  ),
  "23-19": (
    caption: [Four virus entry strategies that follow virus binding to virus receptors. (A) Some enveloped viruses, such as HIV, fuse directly with the host-cell plasma membrane to release their RNA genome (blue) and capsid proteins (brown) into the cytosol. (B) Other enveloped viruses, such as influenza virus, first bind to cell-surface receptors, triggering receptor-mediated endocytosis; when the endosome acidifies, the virus envelope fuses with the endosomal membrane, releasing the viral RNA genome (blue) and capsid proteins (tan) into the cytosol. (C) Poliovirus, a nonenveloped virus, induces receptor-mediated endocytosis, and then forms a pore in the endosomal membrane to extrude its RNA genome (blue) into the cytosol. (D) Adenovirus, another nonenveloped virus, uses a more complicated strategy: it induces receptor- mediated endocytosis and then disrupts the endosomal membrane, releasing the capsid including its DNA genome into the cytosol. The trimmed-down virus eventually docks onto a nuclear pore and releases its DNA (red) directly into the nucleus where it is transcribed and replicated (see Movie 23.5).],
    path: "../fig/image_place_holder.png"
  ),
  "23-20": (
    caption: [Mechanisms used by bacteria to induce phagocytosis by host cells that are normally nonphagocytic. (A) In the zipper mechanism, bacteria express an invasion protein that binds with high affinity to a host-cell receptor, which is often a cell–cell or cell–matrix adhesion protein. (B) In the trigger mechanism, bacteria inject a set of effector molecules into the host-cell cytosol through a type III secretion system called SPI1 (Salmonella pathogenicity island 1), inducing membrane ruffling. Both the zipper and trigger mechanisms cause the polymerization of actin at the site of bacterial attachment by activating Rho family small GTPases and the Arp2/3 complex. (C) A scanning electron micrograph showing Salmonella enterica invasion by the trigger mechanism. Bacteria (pseudocolored yellow) are shown surrounded by a small membrane ruffle. (D) Fluorescence micrograph showing that the large ruffles that engulf the Salmonella bacteria are actin rich. The bacteria are labeled in green and actin filaments in red; because of the color overlap, the bacteria appear yellow. (C, from Rocky Mountain Laboratories, NIAID, NIH; D, from J.E. Galán, Annu. Rev. Cell Dev. Biol. 17:53–86, 2001. With permission from Annual Reviews.) (C) 4 µm (D) 20 µm],
    path: "../fig/image_place_holder.png"
  ),
  "23-21": (
    caption: [The life cycle of the intracellular parasite Toxoplasma gondii. (A) After attachment to a host cell, T. gondii uses its conoid to inject effector proteins that facilitate invasion. These effector proteins include a receptor that binds a parasite surface protein, as well as components of the moving junction (shown in blue) through which the parasite squeezes as it enters the host cell. As the host cell’s plasma membrane invaginates, the parasite somehow removes the normal host-cell membrane proteins, so that the compartment (shown in red) does not fuse with lysosomes. After several rounds of replication, the parasite causes the compartment to break down and the host cell to lyse, releasing the progeny parasites to infect other host cells (see Movie 23.6). (B) Light micrograph of T. gondii replicating within a membrane- enclosed compartment (a parasitophorous vacuole) in a cultured cell. (B, courtesy of Manuel Camps and John Boothroyd.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-21": (
    caption: [and Movie 23.6). When this protozoan contacts a host cell, it pro- trudes an unusual microtubule-based structure called a conoid, which facilitates host-cell entry. At the point of contact, the parasite discharges effector proteins into the host cell from specialized secretory organelles. One of these effector pro- teins is a receptor that inserts into the host-cell plasma membrane and binds to a parasite surface protein. Other effector proteins form a ring-like moving junction through which the parasite squeezes using forces generated by its own unusual actin and myosin cytoskeleton. Remarkably, as the parasite invades it removes host transmembrane proteins from the surrounding membrane, so that it is eventually protected in a membrane-enclosed compartment, or parasitophorous vacuole, that does not fuse with lysosomes and does not participate in host-cell membrane trafficking processes. The specialized membrane is selectively porous: it allows the parasite to take up small metabolic intermediates and nutrients from],
    path: "../fig/image_place_holder.png"
  ),
  "23-22": (
    caption: [The two alternative strategies that Trypanosoma cruzi uses to invade host cells. In the lysosome-dependent pathway (left), T. cruzi recruits host-cell lysosomes to its site of attachment to the host cell. The lysosomes fuse with the invaginating plasma membrane to create an intracellular compartment constructed almost entirely of lysosomal membrane. After a brief stay in the compartment, the parasite secretes a pore-forming protein that disrupts the surrounding membrane, thereby allowing the parasite to escape into the host-cell cytosol and proliferate. In the lysosome- independent pathway (right), the parasite induces the host plasma membrane to invaginate and pinch off without recruiting lysosomes; then, lysosomes fuse with the endosome prior to the parasite’s escape into the cytosol.],
    path: "../fig/image_place_holder.png"
  ),
  "23-23": (
    caption: [Choices that an intracellular pathogen faces. After entry into a host cell, generally through phagocytosis into a membrane-enclosed compartment, intracellular pathogens can use one of three strategies to survive and replicate. Pathogens that escape into the cytosol (1) include all viruses, Trypanosoma cruzi, Listeria monocytogenes, and Shigella flexneri. Those that prevent fusion with lysosomes (2) include Mycobacterium tuberculosis, Legionella pneumophila, and Toxoplasma gondii. Those that survive in the lysosome (3) include Salmonella enterica, Coxiella burnetii, and Leishmania.],
    path: "../fig/image_place_holder.png"
  ),
  "23-24": (
    caption: [Escape of Listeria monocytogenes by selective destruction of the phagosomal membrane. The bacterium attaches to E-cadherin or other receptors on the surface of host epithelial cells and induces its own uptake by the zipper mechanism (see Figure 23–20A). Within the phagosome, the bacterium secretes the protein listeriolysin O, which is activated at pH <6 and forms oligomers in the phagosome membrane, thereby creating large pores and eventually disrupting the membrane. Once in the host-cell cytosol, the bacteria begin to replicate and continue to secrete listeriolysin O; because the pH in the cytosol is >6, however, the listeriolysin O there is less active and is also rapidly degraded by proteasomes. Thus, the host cell’s plasma membrane remains intact.],
    path: "../fig/image_place_holder.png"
  ),
  "23-25": (
    caption: [Modifications of membrane traffic in host cells by bacterial pathogens to slow or prevent normal fusing of endosomes with lysosomes. Intracellular bacterial pathogens, including Mycobacterium tuberculosis, Salmonella enterica, and Legionella pneumophila, all replicate in membrane-enclosed compartments, but the compartments differ. M. tuberculosis remains in a compartment that has early endosomal markers and continues to communicate with the plasma membrane via transport vesicles. S. enterica replicates in a compartment that has late endosomal markers. L. pneumophila replicates in an unusual compartment that is wrapped in rough endoplasmic reticulum (ER) membrane and communicates with the ER via transport vesicles. TGN = trans Golgi network.],
    path: "../fig/image_place_holder.png"
  ),
  "23-26": (
    caption: [Salmonella enterica residing in a modified phagosomal compartment called the Salmonella-containing vacuole. These bacteria invade the host cell using one of two type III secretion systems to inject effector proteins that induce the trigger mechanism of microbe entry illustrated in Figure 23–20B. (A) After its engulfment into a phagosome, the bacterium inactivates the first type III secretion system and activates the second type III secretion system to inject different effector proteins, which remodel the phagosome into the specialized Salmonella-containing vacuole. One of the injected effector proteins activates host kinesin motor proteins to pull membrane tubules outward toward the plus ends of the microtubules (see Figure 16–53), forming a structure with an unusual tubulated shape that is of unknown functional significance. (B) Fluorescence micrograph showing S. enterica in a Salmonella-containing vacuole. The bacteria are stained green, the microtubules red, and the nucleus blue. (B, courtesy of Stephane Meresse.)],
    path: "../fig/image_place_holder.png"
  ),
  "23-27": (
    caption: [Legionella pneumophila residing in a compartment with characteristics similar to those of the rough endoplasmic reticulum (ER). (A) Electron micrograph showing the unusual coiled structure that the Legionella pneumophila bacterium induces on the surface of a phagocyte during the invasion process. Some other pathogens, including the bacterium Borrelia burgdorferi (which causes Lyme disease), the eukaryotic pathogen Leishmania, and the yeast Candida albicans, can also invade cells using this type of coiling phagocytosis. (B) After invasion, L. pneumophila uses its type IV secretion system to secrete effector proteins that block phagosome– endosome fusion and phagosome maturation. It also secretes effector proteins that promote phosphoinositide conversion from PI(3)P to PI(4)P and the fusion of the phagosome with ER-derived vesicles, thereby converting the characteristics of the Legionella-containing vacuole from those of an endosome to those of the rough ER. See Figures 13–10 and 13–11 for a discussion of phosphoinositides and membrane targeting. (A, from M.A. Horwitz, Cell 36:27–33, 1984. With permission from Elsevier.) 1336 Chapter 23: Pathogens and Infection],
    path: "../fig/image_place_holder.png"
  ),
  "23-28": (
    caption: [Complex strategies for viral envelope acquisition. (A) The coronavirus SARS-CoV-2 replicates its positive sense RNA genome in double membrane vesicles associated with the endoplasmic reticulum (ER). Viral genomes are released into the cytoplasm by a poorly understood mechanism that may involve passage through pores in the double membrane. Transcription of sub- genomic RNAs encoding viral structural proteins occurs in the surrounding cytosol. Translation of transmembrane viral proteins, including the spike protein, occurs on the ER. These proteins are then trafficked from the ER to the ER Golgi intermediate compartment (ERGIC), where the single- stranded viral RNA genome associates with viral proteins to drive formation of virus particles in the lumen of exocytic vesicles. When these vesicles fuse with the plasma membrane, viruses are released from the cell surface. (B) Vaccinia virus assembles in “replication factories” in the cytosol, far away from the plasma membrane. The immature virion, surrounded by a single membrane, then acquires two additional membranes from the Golgi apparatus by a poorly understood wrapping mechanism, to form the intracellular enveloped virion. After fusion of the outermost membrane with the host-cell plasma membrane, the extracellular enveloped virion is released from the host cell. (C) Herpesvirus nucleocapsids assemble in the nucleus and then bud through the inner nuclear membrane into the space between the inner and outer nuclear membranes, acquiring a membrane coat. The virus particles then apparently lose this coat when they fuse with the endoplasmic reticulum membrane to escape into the cytosol. Subsequently, the nucleocapsids travel through the Golgi apparatus, acquiring two new membrane coats in the process. The virus then buds from the cell surface with a single membrane when its outer membrane fuses with the plasma membrane.],
    path: "../fig/image_place_holder.png"
  ),
  "23-29": (
    caption: [The actin-based movement of bacterial pathogens within and between host cells. After invasion, bacterial pathogens such as L. monocytogenes, S. flexneri, R. rickettsii, and B. pseudomallei induce the assembly of actin-rich tails in the host-cell cytoplasm, which drives rapid bacterial movement. For most of these pathogens, the moving bacteria collide with the host-cell plasma membrane to form membrane-covered protrusions, which are engulfed by neighboring cells—spreading the infection from cell to cell. In contrast, for B. pseudomallei, collision with the plasma membrane promotes cell–cell fusion, creating a conduit through which bacteria can invade neighboring cells (Movie 23.7).],
    path: "../fig/image_place_holder.png"
  ),
  "23-30": (
    caption: [Molecular mechanisms for actin nucleation by various bacterial pathogens. L. monocytogenes and S. flexneri induce actin nucleation by recruiting and activating the host Arp2/3 complex (see Figure 16–12), although each uses a different recruitment strategy: L. monocytogenes expresses a surface protein, ActA, that directly binds to and activates the Arp2/3 complex; S. flexneri expresses a surface protein, IcsA (unrelated to ActA), that recruits the host NPF N-WASp, which in turn recruits the Arp2/3 complex, along with other host proteins, including WIP (WASp-interacting protein). R. rickettsii uses an entirely different strategy: it expresses a surface protein, Sca2, that directly nucleates actin polymerization by mimicking the activity of host formin proteins.],
    path: "../fig/image_place_holder.png"
  ),
  "23-31": (
    caption: [Microtubule-based movement of viruses. Neurotropic alphaherpesviruses infect peripheral nerve cells from neighboring epithelial cells in the skin. Virus particles are then transported along microtubules in the nerve-cell axon toward the microtubule minus ends in the cell body (retrograde transport), a process that is driven by dynein motor proteins. Upon reaching the cell body, viruses can establish a latent reservoir in the nucleus. After reactivation (for example, following stress or immune suppression) or upon replication, virus particles are again transported along microtubules in the axon, this time toward the microtubule plus ends at the nerve terminal (anterograde transport), where they are released to enable local reinfection and spread. In rare instances, viruses can instead spread to the central nervous system (CNS), which can cause encephalitis.],
    path: "../fig/image_place_holder.png"
  ),
  "23-32": (
    caption: [Microbial manipulation of autophagy. Microbial pathogens have various mechanisms for avoiding antimicrobial autophagy (red lines), which include modifying their surface to avoid autophagy initiation or secreting factors and initiating actin-based motility to avoid enclosure in autophagosomes. Microbes can also exploit autophagy (green arrows), for example by recruiting and fusing with autophagosomes to gain nutrients and lipids or by growing near autolysosomes for nutrient acquisition. 1340 Chapter 23: Pathogens and Infection],
    path: "../fig/image_place_holder.png"
  ),
  "23-33": (
    caption: [Antigenic variation in trypanosomes. (A) There are about 1000 distinct Vsg genes in Trypanosoma brucei, and they are expressed one at a time from approximately 20 expression sites in the genome. To be expressed, an inactive gene is copied and the copy is moved into an expression site through DNA recombination. Each Vsg gene encodes a different surface protein (antigen). These switching events allow the trypanosome to repeatedly change the surface antigen it expresses. (B) A person infected with trypanosomes expressing VSGa mounts an antibody response against this particular antigen, which clears most of the VSGa- expressing parasites. However, a few of the trypanosomes will have spontaneously switched to expression of VSGb, which can now proliferate until anti-VSGb antibodies are made. By that time, however, some parasites will have switched to VSGc, and so the cycle continues. ×1000],
    path: "../fig/image_place_holder.png"
  ),
  "23-34": (
    caption: [Diversification of HIV-1, HIV-2, and related strains of SIV. (A) HIV comprises different viral families, all descended from SIV (simian immunodeficiency virus). On three separate occasions, SIV was passed from a chimpanzee to a human, resulting in three HIV-1 groups: major (M), outlier (O), and non-M non-O (N). HIV-1 M is the most common and is primarily responsible for the global AIDS epidemic. On two separate occasions, SIV was passed from a sooty mangabey monkey to a human, resulting in the two pandemic HIV-2 groups A and B. In 2009, a new strain of HIV was discovered that appears to have resulted from SIV passage from a gorilla to a human. (B) Geography and timing of HIV-1 spread from Africa to other parts of the world.],
    path: "../fig/image_place_holder.png"
  ),
  "23-35": (
    caption: [Model for the evolution of pandemic strains of influenza virus by recombination. Influenza A virus is a natural pathogen of birds, particularly waterfowl, and it is always present in wild bird populations. In 1918, a particularly virulent form of the virus crossed the species barrier from birds to humans and caused a devastating worldwide epidemic. This strain was designated H1N1, referring to the specific forms of its main antigens, hemagglutinin (H) and neuraminidase (N). Changes in the virus, rendering it less virulent, and the rise of adaptive immunity in the human population prevented the pandemic from continuing in subsequent seasons, although H1N1 influenza strains continued to cause serious disease every year in very young and very old people. In 1957, a new pandemic arose when three genes were replaced by equivalent genes from a different avian virus (green bars); the new strain (designated H2N2) was not effectively cleared by antibodies in people who had previously contracted only H1N1 forms of influenza. In 1968, another pandemic was triggered when two genes were replaced from yet another avian virus; the new virus was designated H3N2. In 1977, there was a resurgence of H1N1 influenza, which had previously been almost completely replaced by the N2 strains. Molecular sequence information suggests that this minor pandemic may have been caused by an accidental release of an influenza strain that had been held in a laboratory since about 1950 or by the use of this strain in a vaccine study. In 2009, a new H1N1 swine virus emerged that had derived five genes from pig influenza viruses, two from avian influenza viruses, and one from a human influenza virus. As indicated, most human influenza today is caused by H1N1 and H3N2 strains.],
    path: "../fig/image_place_holder.png"
  ),
  "23-36": (
    caption: [Antibiotic targets. Although there are many antibiotics in clinical use, they have a narrow range of targets, which are highlighted in blue. A few representative antibiotics in each class are listed. Nearly all antibiotics used to treat human infections fall into one of these categories. The vast majority inhibit either bacterial protein synthesis or bacterial cell-wall synthesis. The illustration example is a Gram-positive bacterium.],
    path: "../fig/image_place_holder.png"
  ),
  "23-37": (
    caption: [Three general mechanisms of antibiotic resistance. (A) A nonresistant wild-type bacterial cell bathed in a drug (red triangles) that binds to and inhibits an essential enzyme (light green) will be killed because of enzyme inhibition. (B) A bacterium that has altered the drug’s target enzyme so that the drug no longer binds to the enzyme will survive and proliferate. In many cases, a single point mutation in the gene encoding the target protein can generate resistance. (C) A bacterium that expresses an enzyme (dark green) that either degrades or covalently modifies the drug will survive and proliferate. Some resistant bacteria, for example, make β-lactamase enzymes, which cleave penicillin and similar molecules. (D) A bacterium that expresses or up-regulates an efflux pump that ejects the drug from the bacterial cytoplasm (using energy derived from either ATP hydrolysis or the electrochemical gradient across the bacterial plasma membrane) will survive and proliferate. Some efflux pumps, such as the TetR efflux pump, are specific for a single drug (in this case, tetracycline), whereas others, called multidrug resistance (MDR) efflux pumps, are capable of exporting a wide variety of structurally dissimilar drugs. Up-regulation of an MDR pump can render a bacterium resistant to a very large number of different antibiotics in a single step.],
    path: "../fig/image_place_holder.png"
  ),
  "23-38": (
    caption: [Sites in the human body that harbor the microbiota include the skin, mouth, and digestive tract. An estimate of the total number of microbes in each location is indicated.],
    path: "../fig/image_place_holder.png"
  ),
  "23-39": (
    caption: [Influences of the microbiota on metabolism and development. The microbiota (not drawn exactly to scale) produces nutrients as well as signaling molecules that affect host-cell biology and physiology and also influences the development of the intestinal epithelium and the mucosal immune system.],
    path: "../fig/image_place_holder.png"
  ),
)