#let images = (
  "7-1": (
    caption: [A neuron and a liver cell share the same genome. The long branches of this neuron from the retina enable it to receive electrical signals from many other neurons and convey them to neighboring neurons. The liver cell, which is drawn to the same scale, is involved in many metabolic processes, including digestion and the detoxification of alcohol and other drugs. Both of these mammalian cells contain the same genome, but they express different sets of RNAs and proteins. (Neuron adapted from S. Ramón y Cajal, Histologie du Système Nerveux de l’Homme et de Vertébrés, 1909–1911. Paris: A. Maloine Éditeur; reprinted, Madrid: C.S.I.C., 1972.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-2": (
    caption: [Differentiated cells contain all the genetic instructions necessary to direct the formation of a complete organism. (A) The nucleus of a skin cell from an adult frog transplanted into an enucleated egg can give rise to an entire tadpole. The broken arrow indicates that, to give the transplanted genome time to adjust to an embryonic environment, a further transfer step is required in which one of the nuclei is taken from an early embryo that begins to develop and is put back into a second enucleated egg. (B) In many types of plants, differentiated cells retain the ability to “de-differentiate,” so that a single cell can form a clone of progeny cells that later give rise to an entire plant. (C) A nucleus removed from a differentiated cell from an adult cow and introduced into an enucleated egg from a different cow can give rise to a calf. Different calves produced from the same differentiated cell donor are all clones of the donor and are therefore genetically identical. (A, modified from J.B. Gurdon, Sci. Am. 219:24–35, 1968.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-3": (
    caption: [Differences in RNA levels for two human genes in seven different tissues. To obtain RNA data by the technique known as RNA-seq (see pp. 514–516), RNA was collected from seven different human cell lines grown in culture, each derived from a different tissue. Millions of “sequence reads” were obtained for each RNA sample and mapped by matching RNA sequences to the DNA sequence of the human genome. At each position along the genome, the height of the colored trace is proportional to the number of sequence reads that match the genome sequence at that point. As seen in the figure, the exon sequences in transcribed genes are present at high levels, reflecting their presence in mature mRNAs. Intron sequences are present at much lower levels and reflect pre-mRNA molecules that have not yet been spliced, plus intron sequences that have been spliced out but not yet degraded. (A) The data for one of the genes coding for actin, a major component of the cytoskeleton in all cells. Note that the left-hand end of the mature β-actin mRNA is not translated into protein. As explained later in this chapter, many mRNAs have 5′ untranslated regions that regulate their translation into protein. (B) The same type of data displayed for the enzyme tyrosine aminotransferase, which is highly expressed in liver cells but not in the other cell types tested. \[Information for both panels from the University of California, Santa Cruz, Genome Browser (https:// genome.ucsc.edu), which provides this type of information for every human gene. See also S. Djebali et al., Nature 489:101– 108, 2012.\]],
    path: "../fig/image_place_holder.png"
  ),
  "7-4": (
    caption: [Differences in the proteins expressed by two human tissues, (A) brain and (B) liver. The proteins have been separated by size (top to bottom) and isoelectric point, the pH at which the protein has no net charge (right to left). The protein spots artificially colored red are common to both samples; those in blue are specific to that tissue. The differences between the two tissue samples vastly outweigh their similarities: even for proteins that are shared between the two tissues, their relative abundances are usually different. Note that this technique separates proteins by both size and charge; therefore, a protein that has several different phosphorylation states will appear as a series of horizontal spots (see upper right-hand portion of right panel). Only a small portion of the complete protein spectrum is shown for each sample.],
    path: "../fig/image_place_holder.png"
  ),
  "7-5": (
    caption: [Classification of a group of neurons in the mouse brain into seven different subtypes by single-cell mRNA sequencing. For this experiment, approximately 4000 individual neurons (which were activated in response to a particular stimulus) were dissected from the brain and separated from each other. The mRNAs produced by each cell were isolated and their sequences determined by the methods described in Chapter 8. On the basis of the spectrum of the mRNAs produced by each cell, the 4000 different cells could be grouped into seven distinctive subtypes. Within each subtype, the mRNAs were similar from cell to cell, but between subtypes they differed significantly. (A) Here, the level of the mRNAs detected for approximately 200 different genes is plotted for each cell as a tiny rectangle, whose color intensity is proportional to the amount of that mRNA in that cell, with red indicating increased expression and green decreased expression, relative to all the samples. These data are plotted for each of the 4000 cells along the X axis. The cells have been arranged so that similar cells are located next to each other. In this way it is possible, using mRNA sequence data alone, to recognize seven distinctive types of neurons, as indicated. To highlight similarities, the data for the 25 mRNAs specifically enriched in each of the seven subtypes is indicated by red blocks. (B) By analyzing the mRNA data using a mathematical method known as unsupervised clustering (see Figure 8–66), the seven different subtypes can readily be distinguished on a two-dimensional “cluster diagram,” with each dot representing a single cell. In addition, information regarding the extent of differences among the subgroups can also be ascertained. For example, subtypes 1 and 4 are more closely related to each other in the mRNAs they make than are subtypes 1 and 7. This type of analysis helps us to understand how the brain processes sensory information and indicates that, even though neurons may look the same under the microscope, they can differ significantly in gene expression patterns and therefore in their functions. (A and B, from M.B. Chen et al., Nature 587:437–442, 2020, doi 10.1038/s41586-020-2905-5. With permission from Springer Nature.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-6": (
    caption: [Seven steps at which eukaryotic gene expression can be controlled. Controls that operate at steps 1 through 5 are discussed in this chapter. Step 7, the regulation of protein activity, occurs largely through covalent post-translational modifications including phosphorylation, acetylation, and ubiquitylation (see Table 3–4, p. 175). Steps 6 and 7 were introduced in Chapters 3 and 6 and will be subsequently discussed in other chapters throughout the book.],
    path: "../fig/image_place_holder.png"
  ),
  "7-7": (
    caption: [Double-helical structure of DNA. A space-filling model of DNA showing the major and minor grooves on the outside of the double helix (see Movie 4.1). The atoms are colored conventionally as follows: carbon, black; nitrogen, blue; hydrogen, white; oxygen, red; phosphorus, yellow.],
    path: "../fig/image_place_holder.png"
  ),
  "7-8": (
    caption: [How the different base pairs in DNA can be recognized from their edges without the need to open the double helix. The four possible configurations of base pairs are shown, with potential hydrogen-bond donors indicated in blue, potential hydrogen-bond acceptors in red, and hydrogen bonds of the base pairs themselves as a series of short, parallel red lines. Methyl groups, which form hydrophobic protuberances, are shown in yellow, and hydrogen atoms that are attached to carbons, and are therefore unavailable for hydrogen-bonding, are white. From the major groove, each of the four base-pair configurations projects a unique pattern of features. (From C. Branden and J. Tooze, Introduction to Protein Structure, 2nd ed. New York: Garland Publishing, 1999. With permission from Taylor & Francis.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-9": (
    caption: [The binding of a transcription regulator to a specific DNA sequence. On the left, a single contact is shown between a transcription regulator and DNA; such contacts allow the protein to “read” the DNA sequence from the outside of the DNA double helix. On the right, the complete set of contacts between a transcription regulator (a member of the homeodomain family—see Panel 7–1) and its cis-regulatory sequence is shown. The DNA-binding portion of the protein is 60 amino acids long, and the amino acids that directly contact DNA are numbered beginning with the amino terminus. Although the interactions in the major groove are the most important, the protein also contacts both the minor groove and phosphates in the sugar–phosphate DNA backbone, as shown. (See C. Wolberger et al., Cell 67:517–528, 1991.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-10": (
    caption: [Transcription regulators and cis-regulatory sequences. (A) Depiction of the cis-regulatory sequence for Nanog, a homeodomain family member that is a key transcription regulator in embryonic stem cells. This “logo” form (see Figure 6–12) shows that the protein can recognize a collection of closely related DNA sequences and gives the preferred nucleotide pair at each position. Cis-regulatory sequences are almost always “read” as double- stranded DNA, but only one strand typically is shown in a logo. (B) Representation of the cis-regulatory sequence as a green box embedded in a longer DNA molecule (gray). (C) Many transcription regulators form dimers (homodimers and heterodimers). In the example shown, three different DNA- binding specificities are formed from two transcription regulators.],
    path: "../fig/image_place_holder.png"
  ),
  "7-11": (
    caption: [Occupancy of a cis- regulatory sequence by a transcription regulator. (A) Noncooperative binding by a stable heterodimer. (B) Cooperative binding by components of a heterodimer that are predominantly monomers in solution. The shape of the curve differs from that of panel A because the fraction of protein in a form competent to bind DNA (the heterodimer) increases with increasing protein concentration.],
    path: "../fig/image_place_holder.png"
  ),
  "7-12": (
    caption: [How nucleosomes affect the binding of transcription regulators.],
    path: "../fig/image_place_holder.png"
  ),
  "7-13": (
    caption: [Two cooperating transcription regulators, Oct4 (green) and Sox2 (blue), bound to a MBoC7 n7.650/7.13 nucleosome. These two transcription regulators work together and play key roles in maintaining embryonic stem cells (see Figures 7–36 and 7–37). Only the DNA- binding portion of each regulator protein is shown. (Courtesy of Nicolas H. Thomä and Alicia K. Michael. PDB code: 6T90.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-14": (
    caption: [Tracking single molecules of a transcription regulator in the nucleus of a living cell. By conjugating a fluorescent tag to the glucocorticoid receptor (see pp. 573–575), the behavior of this transcription regulator can be followed in living cells, using a microscope that follows its fluorescence. Computational methods then allow the observed behavior of such molecules to be classified into sets of distinct mobility groups, two of which are shown here. (A) Sample tracks observed for individual molecules of the glucocorticoid receptor in the freely diffusing mobility group. The positions illustrated were determined for a total of 10 seconds. (B) Tracks of individual molecules bound to DNA, with positions determined over a 120-second interval. (A and B, courtesy of D.A. Garcia and G.L. Hager.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-15": (
    caption: [A cluster of bacterial genes can be transcribed from a single promoter. Each of these five genes encodes a different enzyme, and all of these enzymes are needed to synthesize the amino acid tryptophan from simpler molecules. The genes are transcribed as a single mRNA molecule, a feature that allows their expression to be coordinated. Clusters of genes transcribed as a single mRNA molecule are common in bacteria. Each of these clusters is called an operon because its expression is controlled by a cis-regulatory sequence called the operator (green), situated within the promoter. (In this and subsequent figures, the yellow blocks in the promoter represent DNA sequences that bind RNA polymerase; see Figure 6–12).],
    path: "../fig/image_place_holder.png"
  ),
  "7-16": (
    caption: [Genes can be switched off by repressor proteins. If the concentration of tryptophan inside a bacterium is low (left), RNA polymerase (blue) binds to the promoter and transcribes the five genes of the tryptophan operon. However, if the concentration of tryptophan is high (right), the tryptophan repressor protein (dark green) becomes active and binds to the operator (light green), where it blocks the binding of RNA polymerase to the promoter. Whenever the concentration of intracellular tryptophan drops, this transcription regulator falls off the DNA, allowing the polymerase to again transcribe the operon. Although not shown in the figure, the tryptophan repressor exists as a stable protein dimer.],
    path: "../fig/image_place_holder.png"
  ),
  "7-17": (
    caption: [Genes can be switched on by activator proteins. An activator protein binds to its cis-regulatory sequence on the DNA and interacts with the RNA polymerase to help it initiate transcription. Without the activator, the promoter fails to initiate transcription efficiently. In bacteria, the binding of the activator to DNA is often controlled by the interaction of a metabolite or other small molecule (red circle) with the activator protein. 412],
    path: "../fig/image_place_holder.png"
  ),
  "7-18": (
    caption: [How the Lac operon is controlled by two transcription regulators, causing it to be expressed only when needed. LacZ, the first gene of the operon, encodes the enzyme β-galactosidase, which breaks down lactose to galactose and glucose. When lactose is absent, the Lac repressor binds to a cis-regulatory sequence, called the Lac operator, and shuts off expression of the operon (Movie 7.4). Addition of lactose increases the intracellular concentration of a related compound, allolactose; allolactose binds to the Lac repressor, causing it to undergo a conformational change that releases its grip on the operator DNA (not shown). This removes a block to expression of the Lac operon, but the operon can turn on only if the sugar glucose, a preferred carbon source, is absent. This is because cyclic AMP (red triangle) is produced by the cell in the absence of glucose, and this small molecule is required for CAP to bind to DNA and activate transcription.],
    path: "../fig/image_place_holder.png"
  ),
  "7-19": (
    caption: [Transcriptional activation by DNA looping in bacteria. (A) The NtrC protein is a bacterial transcription regulator that activates transcription by directly contacting RNA polymerase. (B) The interaction of NtrC and RNA polymerase, with the intervening DNA looped out, can be seen in the electron microscope. (B, courtesy of Harrison Echols and Sydney Kustu.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-20": (
    caption: [Transcription is controlled by gene control regions. (A) The gene control region of a typical eukaryotic gene depicted with the DNA arranged in a straight line. The promoter is the DNA sequence where the general transcription factors and the polymerase assemble (see Figure 6–15). The cis-regulatory sequences are binding sites for transcription regulators, whose presence on the DNA ultimately affects the rate of transcription initiation. These sequences can be located adjacent to the promoter, far upstream of it, or even within introns or entirely downstream of the gene. The broken stretches of DNA signify that the length of DNA between the cis-regulatory sequences and the start of transcription varies, sometimes reaching tens of thousands of nucleotide pairs in length. The TATA box is a DNA recognition sequence for the general transcription factor TFIID (see Figures 6–15 and 6–17). (B) DNA looping allows transcription regulators bound at many positions to “communicate” with the proteins that assemble at the promoter. As shown in this schematic diagram, many transcription regulators act through Mediator (described in Chapter 6), while some interact with the general transcription factors and RNA polymerase directly. Transcription regulators also act by recruiting proteins that alter the chromatin structure of the promoter (not shown here but discussed later in the chapter). Whereas Mediator and the general transcription factors are the same for all RNA polymerase II–transcribed genes, the transcription regulators and the locations of their binding sites relative to the promoter differ for each gene. At especially complex gene control regions, the many proteins that assemble can, by virtue of large numbers of low-specificity interactions, undergo phase transitions that further coalesce the protein and DNA components needed to initiate transcription—presumably accelerating the process.],
    path: "../fig/image_place_holder.png"
  ),
  "7-21": (
    caption: [Eukaryotic transcription regulators assemble into complexes on DNA. (A) Seven different proteins and an RNA molecule are shown. The nature and function of the complex they form depend on the specific cis-regulatory sequences that seed their assembly. (B) Some assembled complexes activate gene transcription, while another represses transcription. Note that the light green and dark green proteins are shared by both activating and repressing complexes. Proteins that do not themselves bind DNA but assemble on other DNA-bound transcription regulators are termed coactivators or co-repressors. In some cases (lower right), long, noncoding RNA molecules are also found in these assemblies. As described later in this chapter, these RNAs often act as scaffolds to hold groups of proteins together. 416],
    path: "../fig/image_place_holder.png"
  ),
  "7-22": (
    caption: [Eukaryotic transcription activator proteins direct local alterations in chromatin structure. Nucleosome remodeling, nucleosome removal, histone replacement, and certain types of histone modifications favor transcription initiation (see Table 4–2, p. 210). As illustrated, some of these changes are driven by different types of ATP-dependent chromatin remodeling complexes (see Figures 4–26 and 4–27); most also involve histone chaperones (not shown). Such alterations increase the accessibility of DNA and facilitate the binding of RNA polymerase and the general transcription factors.],
    path: "../fig/image_place_holder.png"
  ),
  "7-23": (
    caption: [Successive histone modifications during transcription initiation. In this example, taken from the human interferon-β gene promoter, a transcription activator binds to DNA packaged into chromatin and attracts a histone acetyl transferase that acetylates lysine 9 of histone H3 and lysine 8 of histone H4 (see Figure 4–35). Next, a histone kinase, part of a different coactivator attracted by the same transcription activator, phosphorylates serine 10 of histone H3, but it can only do so after lysine 9 has been acetylated. This serine modification signals the original histone acetyl transferase to acetylate position K14 of histone H3. Next, the general transcription factor TFIID and a chromatin remodeling complex come into play to promote the subsequent steps of transcription initiation. TFIID and the remodeling complex both recognize acetylated histone tails through a bromodomain, a protein domain specialized to read this particular mark on histones; a bromodomain is carried in a subunit of each protein complex. Binding of TFIID causes a sharp bend in the DNA (not shown but see Figure 6–17), which facilitates sliding of the nucleosome to a new position, thereby freeing the start site of transcription for binding by RNA polymerase II.],
    path: "../fig/image_place_holder.png"
  ),
  "7-24": (
    caption: [Different transcription regulators can act at different steps. (A) As described earlier in this chapter (see Figure 7–12), a DNA-bound transcription activator can promote DNA binding by additional transcription regulators. (B) As shown in more detail in Figures 7–20 and 7–22, most transcription activators direct assembly of RNA polymerase at promoters; this can occur by a variety of mechanisms. (C) Some other transcription activators, once bound to DNA, release RNA polymerase molecules that are paused after transcribing about 50 nucleotides of RNA. For simplicity, many of the additional proteins required for transcription initiation are not shown. (C) RELEASES RNA POLYMERASE FROM PAUSE],
    path: "../fig/image_place_holder.png"
  ),
  "7-25": (
    caption: [Transcriptional synergy. This experiment compares the rate of transcription produced by three experimentally constructed regulatory regions in a eukaryotic cell and reveals transcriptional synergy, a greater than additive effect of multiple activators working together. Such transcriptional synergy is not only observed between different transcription activators from the same organism; it is also seen between activator proteins from different eukaryotic species when they are experimentally introduced into the same cell. This last observation reflects the high degree of conservation of the machinery responsible for eukaryotic transcription initiation.],
    path: "../fig/image_place_holder.png"
  ),
  "7-26": (
    caption: [Condensate formation at the transcription control region of the Nanog gene in a mouse embryonic stem cell. The cell was fixed, and in (A) the Nanog gene was identified by hybridizing a complementary nucleotide sequence attached to a red fluorophore, according to a procedure known as FISH (see Figure 8–32). Nanog is a key transcription regulator in embryonic stem cells (see Figure 7–10), and its own regulatory region is one of the most com- plex in the mouse genome. The nucleus is indicated by the blue oval. (B) A subunit of Mediator fused to a green fluorescent protein (see Figure 9–16) was visualized. (C) The two preceding images have been merged, and in (D) the portion of the image in the white square is magnified tenfold. The size and diffuse nature of the “blob” suggest a condensate containing a large number of proteins. Note that additional condensates of Mediator are visible throughout the nucleus and may represent condensates at other enhancers. These condensates are much smaller than those of the nuclear “organelles,” such as the nucleolus, discussed in Chapter 6. (From B.R. Sabari et al., Science 361:eaar3958, 2018. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-27": (
    caption: [have different consequences for the ease with which a repressed gene can be reactivated. For most of the strategies, the repressed state is relatively easy to rapidly reverse, for],
    path: "../fig/image_place_holder.png"
  ),
  "7-27": (
    caption: [Six of the ways in which eukaryotic repressor proteins can operate. (A) A repressor protein outcompetes activator proteins for binding to the same regulatory DNA sequence. (B) Both activator and repressor proteins bind close to each other on DNA, and the repressor “quenches” the activator, preventing it from functioning (for example, by blocking the recruitment of its coactivators). (C) The repressor “poisons” assembly of the general transcription factors by binding to and stabilizing an intermediate. (D) The repressor recruits a chromatin remodeling complex that restores the nucleosomal state of the promoter region to its pre-transcriptional, default form. (E) The repressor attracts a histone deacetylase to the promoter, removing the histone acetylation needed for transcription initiation (see Figure 7–23). (F) Heterochromatin formation is triggered when a repressor attracts a specific histone methyl transferase that trimethylates either lysine 9 or lysine 27 on histone H3, thereby creating either H3K9me3- or H3K27me3-marked nucleosomes. “Read–write” mechanisms then spread each type of methylated nucleosome for thousands of nucleotide pairs along the DNA; they also help the methylation pattern to be inherited across cell divisions (see Figures 4–40 and 4–44). The final step in heterochromatin formation occurs when each type of modified nucleosome attracts additional proteins that condense the DNA and maintain it in a transcriptionally silent form.],
    path: "../fig/image_place_holder.png"
  ),
  "7-28": (
    caption: [Schematic diagram summarizing the properties of insulators and barrier sequences. (A) Insulators directionally block the action of enhancers, whereas barrier sequences prevent the spread of heterochromatin. How barrier sequences likely function is depicted in Figure 4–41. (B) Insulator-binding proteins (purple) hold chromatin in loops that favor “correct” enhancer–promoter associations. Thus, gene B is properly regulated, and gene B’s cis-regulatory sequences can be prevented from influencing the transcription of gene A. The major insulator-binding protein in mammals is denoted CTCF.],
    path: "../fig/image_place_holder.png"
  ),
  "7-29": (
    caption: [The nonuniform distribution of transcription regulators in an early Drosophila embryo. At this stage, the embryo is a syncytium; that is, multiple nuclei are contained in a common cytoplasm. Although the nuclei are shown in only a slice of the embryo, in reality, they are arranged in three dimensions around the inner surface of the giant cell.],
    path: "../fig/image_place_holder.png"
  ),
  "7-30": (
    caption: [Experiment demonstrating the modular construction of the Eve gene regulatory region. (A) A 480- nucleotide-pair section of the Eve regulatory region was removed and (B) inserted upstream of a test promoter that directs the synthesis of the enzyme β-galactosidase (the product of the E. coli LacZ gene—see Figure 7–18). (C, D) When this artificial construct was reintroduced into the genome of Drosophila embryos, the embryos (D) expressed β-galactosidase (detectable by histochemical staining) precisely in the position of the second of the seven Eve stripes. (C) The complete set of Eve stripes was detected using antibodies directed against the Eve protein. β-Galactosidase is simple to detect and thus provides a convenient way to monitor the expression specified by a gene control region. As used here, β-galactosidase is said to serve as a reporter, because it “reports” the activity of a gene control region. (C and D, courtesy of Stephen Small and Michael Levine.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-31": (
    caption: [The Eve stripe 2 unit. The segment of the Eve gene control region identified in Figure 7–30 contains cis- regulatory sequences for four transcription regulators. It is known from genetic experiments that these four regulatory proteins are responsible for the proper expression of Eve in stripe 2. Flies that are deficient in the two gene activators Bicoid and Hunchback, for example, fail to efficiently express Eve in stripe 2. In flies deficient in either of the two gene repressors, Giant and Krüppel, stripe 2 expands and covers an abnormally broad region of the embryo. As indicated, in some cases the binding sites for the transcription regulators overlap, and the proteins can compete for binding to the DNA. For example, binding of Krüppel and binding of Bicoid to the site at the far right is mutually exclusive.],
    path: "../fig/image_place_holder.png"
  ),
  "7-32": (
    caption: [shows the distributions of the four transcription regulators across the region of a Drosophila embryo where stripe 2 forms. It is thought that either of the two repressor proteins, when bound to the DNA, will turn off the stripe 2 module, whereas both Bicoid and Hunchback must bind for this module’s maximal activa- tion. This simple regulatory scheme suffices to turn on the stripe 2 module (and therefore the expression of the Eve gene) only in those nuclei located where the levels of both Bicoid and Hunchback are high and both Krüppel and Giant are absent—a combination that occurs in only one region of the early embryo. It is not known exactly how these four transcription regulators interact with coactivators and co-repressors to specify the final level of transcription across the stripe, but the outcome very likely relies on competition between activators and repressors that act by the mechanisms outlined in Figures 7–21, 7–22, and 7–27.],
    path: "../fig/image_place_holder.png"
  ),
  "7-32": (
    caption: [Distribution of the transcription regulators responsible for ensuring that Eve is expressed in stripe 2. The distributions of these proteins were visualized by staining a developing Drosophila embryo with antibodies directed against each of the four proteins, and a graph of the staining intensities is shown. The expression of Eve in stripe 2 occurs only at the position where the two activators (Bicoid and Hunchback) are present and the two repressors (Giant and Krüppel) are absent. In fly embryos that lack Krüppel, for example, stripe 2 expands posteriorly. Likewise, stripe 2 expands posteriorly if the DNA- binding sites for Krüppel in the stripe 2 module are inactivated by mutation (see also Figure 7–31).],
    path: "../fig/image_place_holder.png"
  ),
  "7-33": (
    caption: [The integration of multiple inputs at a promoter. Multiple sets of transcription regulators, coactivators, and co-repressors can work together to influence transcription initiation at a promoter, as they do in the Eve stripe 2 module illustrated in Figure 7–31. It is not yet understood in detail how the cell achieves integration of multiple inputs, but it is likely that the final transcriptional activity of the gene results from competitions between activators and repressors that act by the mechanisms summarized in Figures 7–21, 7–22, and 7–27. As we saw earlier, for especially complex gene control regions, it has been proposed that these competitions take place and are “summed up” in localized biomolecular condensates formed by networks of weak interactions.],
    path: "../fig/image_place_holder.png"
  ),
  "7-34": (
    caption: [Some ways in which the activity of transcription regulators is controlled inside eukaryotic cells. (A) The protein is synthesized only when needed. (B) Activation by ligand binding. (C) Activation by covalent modification; phosphorylation is shown here, but many other modifications are possible (see Table 3–4, p. 175). (D) Formation of a complex between a DNA-binding protein and a separate protein with a transcription- activating domain. (E) Unmasking of an activation domain by the phosphorylation of an inhibitor protein. (F) Stimulation of nuclear entry by removal of an inhibitory protein that otherwise keeps the regulatory protein from entering the nucleus. (G) Release of a transcription regulator from a membrane bilayer by regulated proteolysis.],
    path: "../fig/image_place_holder.png"
  ),
  "7-35": (
    caption: [Modular structure of the control region for the mouse a-globin gene. Each of the five modules (R1–R5) can independently act as an enhancer, that is, they can each activate transcription of a reporter construct (see Figure 7–30B). However, the patterns of expression in a developing embryo are somewhat different for different modules. As indicated by the percentage designations, each module differs in the quantitative contributions it makes to the overall transcription rate in erythroid cells, with the total amount of mRNA being roughly equal to that of the sum of that produced by the individual modules. The additive properties of this control region suggest that the modules all affect the same step in transcription. The combination of transcription],
    path: "../fig/image_place_holder.png"
  ),
  "7-36": (
    caption: [The importance of combinatorial gene control for development. Combinations of a few transcription regulators can generate many cell types during development. In this simple, idealized scheme, a “decision” to make one of a pair of different transcription regulators (shown as numbered circles) is made after each cell division. Sensing its relative position in the embryo, the daughter cell toward the left side of the embryo is always induced to synthesize the even-numbered protein of each pair, while the daughter cell toward the right side of the embryo is induced to synthesize the odd-numbered protein. The production of each transcription regulator is assumed to be self-perpetuating once it has become initiated (see Figure 7–42). In this way, through cell memory, the final combinatorial specification is built up step by step. In this purely hypothetical example, five different transcription regulators have created eight final cell types (G–N).],
    path: "../fig/image_place_holder.png"
  ),
  "7-37": (
    caption: [A small set of transcription regulators can convert one differentiated cell type into another. In this experiment, liver cells grown in culture (A) were converted into neuronal cells (B) by the artificial expression of three neuron-specific transcription regulators. (Both types of cells express a red fluorescent protein, which helps to visualize them.) This conversion involves the activation of many neuron- specific genes as well as the repression of many liver-specific genes. (From S. Marro et al., Cell Stem Cell 9:374–382, 2011. With permission from Elsevier.) 428],
    path: "../fig/image_place_holder.png"
  ),
  "7-38": (
    caption: [Expression of the Drosophila Eyeless gene in precursor cells of the fly leg triggers the development of an eye on the leg. (A) Simplified diagrams showing the result when a fruit fly larva contains either the normally expressed Eyeless gene (left) or an Eyeless gene that is additionally expressed artificially in cells that normally give rise to leg tissue (right). (B) Photograph of an abnormal leg that contains a misplaced eye (see also Figure 21–2). The transcription regulator was named Eyeless because its inactivation in otherwise normal flies causes the loss of eyes (see Figure 21–32). (B, courtesy of Walter Gehring.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-39": (
    caption: [A combination of transcription regulators can induce a differentiated cell to de-differentiate into a pluripotent cell. The artificially induced expression of a set of three genes, each of which encodes a transcription regulator, can reprogram a fibroblast into a pluripotent cell with embryonic stem (ES) cell–like properties. Like ES cells, such induced pluripotent stem (iPS) cells can proliferate indefinitely in culture and can be stimulated by appropriate extracellular signal molecules to differentiate into almost any cell type found in the body. Transcription regulators such as Oct4, Sox2, and Klf4 are often called master transcription regulators because their expression is sufficient to trigger a change in cell identity. How two of these transcription regulators interact with DNA in a nucleosome is shown in Figure 7–13.],
    path: "../fig/image_place_holder.png"
  ),
  "7-40": (
    caption: [A portion of the transcription network specifying embryonic stem cells. (A) The three master transcription regulators in Figure 7–39 are shown as large circles. Genes whose cis-regulatory sequences are bound by each regulator in embryonic stem cells are indicated by a small green dot (representing the gene) connected by a thin line (representing the binding interaction). Note that many of the target genes are bound by more than one of the regulators. (B) The master regulators control their own expression. As shown here, the three transcription regulators bind to their own control regions (indicated by feedback loops), as well as those of the other master regulators (indicated by straight arrows). (Courtesy of Trevor Sorrells, based on data from J. Kim et al., Cell 132:1049–1061, 2008.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-41": (
    caption: [A single transcription regulator can coordinate the expression of many different genes. The action of the glucocorticoid receptor is illustrated schematically. On the left is a series of genes, each of which has various transcription regulators bound to its regulatory region. However, these bound proteins are not sufficient on their own to fully activate transcription. On the right is shown the effect of adding an additional transcription regulator—the glucocorticoid receptor in a complex with glucocorticoid hormone—that has a cis- regulatory sequence in the control region of each gene. The glucocorticoid receptor completes the combination of transcription regulators required for maximal initiation of transcription, and the genes are now maximally switched on as a set. When the hormone is no longer present, the glucocorticoid receptor dissociates from DNA, and the genes return to their prestimulated levels.],
    path: "../fig/image_place_holder.png"
  ),
  "7-42": (
    caption: [A positive feedback loop can create cell memory. Protein A is a master transcription regulator that activates the transcription of its own gene—as well as other cell-type- specific genes (not shown). All of the descendants of the original cell will therefore “remember” that the progenitor cell had experienced a transient signal that initiated the production of protein A.],
    path: "../fig/image_place_holder.png"
  ),
  "7-43": (
    caption: [Common types of network motifs in transcription circuits. A and B represent transcription regulators, green arrows indicate positive transcription control, while red lines with bars depict negative transcription control. In the feed-forward loop, A and B represent transcription regulators that both activate the transcription of target gene Z (see also Figure 8–88).],
    path: "../fig/image_place_holder.png"
  ),
  "7-44": (
    caption: [How a feed-forward loop can measure the duration of a signal. (A) In this theoretical example, transcription regulators A and B must both be present on the DNA for transcription of gene Z, and gene A becomes active only when an input signal is present. (B) If the input signal to gene A is brief, it does not stay active long enough for transcription regulator B to accumulate, and gene Z is not transcribed. (C) If the signal to gene A persists, transcription regulators A and B both accumulate, and gene Z is transcribed. This arrangement allows the cell to ignore rapid fluctuations of the input signal and respond only to persistent levels. This strategy could be used, for example, to distinguish between random noise and a true signal.],
    path: "../fig/image_place_holder.png"
  ),
  "7-45": (
    caption: [The exceedingly complex gene circuit that specifies a portion of the developing sea urchin embryo. Each colored small box represents a different gene. Those in yellow code for transcription regulators, and those in green and blue code for proteins that give cells of the mesoderm and endoderm, respectively, their specialized characteristics. Genes depicted in gray are largely active in the mother and provide the egg with cues needed for proper development. As in Figure 7–43, arrows depict instances in which a transcription regulator activates the transcription of another gene, and lines ending in bars indicate examples of gene repression. (From I.S. Peter and E.H. Davidson, Nature 474:635–639, 2011. With permission from Springer Nature.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-46": (
    caption: [Formation of 5-methylcytosine occurs by methylation of a cytosine base in the DNA double helix. In vertebrates, this event is largely confined to selected cytosine (C) nucleotides located in the sequence CG. CG sequences are sometimes denoted as CpG sequences, where the p indicates a phosphate linkage to distinguish it from a CG base pair. In this chapter, we will continue to use the simpler nomenclature CG to indicate this dinucleotide.],
    path: "../fig/image_place_holder.png"
  ),
  "7-47": (
    caption: [How DNA methylation patterns are faithfully inherited. In vertebrate DNA, a large fraction of the cytosine nucleotides in the sequence CG is methylated (see Figure 7–46). Because of the existence of a methyl- directed methylating enzyme (the maintenance methyl transferase), once a pattern of DNA methylation is established, that pattern of methylation is inherited in the progeny DNA, as shown.],
    path: "../fig/image_place_holder.png"
  ),
  "7-48": (
    caption: [Multiple mechanisms can produce especially stable gene repression. In this schematic example, histone reader and writer proteins (discussed in Chapter 4), triggered by transcription regulators, establish a repressive form of chromatin whose nucleosomes are marked by the trimethylation of specific lysine amino acids in histones (see Figure 4–35, as well as Figure 7–27F). An additional layer of repression can occur when a de novo DNA methylase is attracted by the modified histones and methylates nearby cytosines in DNA; and these are, in turn, bound by DNA methyl-binding proteins. During DNA replication, some of the modified (blue dot) histones will be inherited by one daughter chromosome, some by the other, and in each daughter they can induce reconstruction of the same pattern of chromatin modifications (see Figure 4–44). At the same time, the mechanism shown in Figure 7–47 will cause both daughter chromosomes to inherit the same methylation pattern. This makes the two mechanisms for inheriting a repressed gene mutually reinforcing, accounting for the inheritance by daughter cells of both the histone and the DNA modifications. It can also explain the tendency of some chromatin modifications to spread along a chromosome (see Figure 4–39). This type of heterochromatin is assembled and disassembled on different genes as mammalian development proceeds, depending on whether the gene product is needed. For example, when endoderm precursor cells differentiate into the hepatocytes of the liver, an estimated 6000 genes are unpackaged from this repressive form of chromatin and become actively transcribed. At roughly the same time, about 1600 genes active in endoderm cells become packaged into this type of chromatin and are thereby tightly repressed in hepatocytes.],
    path: "../fig/image_place_holder.png"
  ),
  "7-49": (
    caption: [The CG islands surrounding the promoter in three mammalian housekeeping genes. The yellow boxes show the extent of each island. As for most genes in mammals, the exons (dark red) are very short relative to the introns (light red). (Adapted from A.P. Bird, Trends Genet. 3:342–347, 1987.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-50": (
    caption: [A mechanism to explain both the marked overall deficiency of CG sequences and their clustering into CG islands in vertebrate genomes. The vertical white lines mark the location of CG dinucleotides in the DNA sequences, while red circles indicate the presence of a methyl group on the CG dinucleotide. CG sequences that lie in regulatory sequences of genes that are transcribed in germ cells are unmethylated and therefore tend to be retained in evolution. Methylated CG sequences, on the other hand, tend to be lost through deamination of 5-methyl C to T, unless the CG sequence is critical for survival.],
    path: "../fig/image_place_holder.png"
  ),
  "7-51": (
    caption: [How imprinting can cause a non-Mendelian pattern of inheritance. The top portion of the figure shows a pair of homologous chromosomes in the somatic cells of two adult mice, one male and one female. In this example, both mice have inherited the top homolog from their father and the bottom homolog from their mother, and the paternal copy of a gene subject to imprinting (indicated in orange) is methylated, preventing its expression. The maternally derived copy of the same gene (yellow) is expressed. The remainder of the figure shows the outcome of a cross between these two mice. During germ-cell formation, but before meiosis, the imprints are erased and then, much later in germ-cell development, they are reimposed in a sex-specific pattern (middle portion of figure). In eggs produced from the female, neither allele of the A gene is methylated. In sperm from the male, both alleles of gene A are methylated. Shown at the bottom of the figure are two of the possible imprinting patterns inherited by the progeny mice; the mouse on the left has the same imprinting pattern as each of the parents, whereas the mouse on the right has the opposite pattern. If the two alleles of gene A are distinct (for example, if one codes for a mutant protein), the different imprinting patterns can cause phenotypic differences in the progeny mice, even though they carry exactly the same DNA sequences of the two A gene alleles.],
    path: "../fig/image_place_holder.png"
  ),
  "7-52": (
    caption: [Some mechanisms of imprinting. (A) On chromosomes inherited from the female, the CTCF protein binds to an insulator (see Figure 7–28), blocking communication between cis-regulatory sequences (green) and the Igf2 gene (orange). Igf2 is therefore not expressed from the maternally inherited chromosome. Because of imprinting, the insulator on the male-derived chromosome is methylated (red circles); this inactivates the insulator by blocking the binding of the CTCF protein and allows the cis-regulatory sequences to activate transcription of the Igf2 gene. In other examples of imprinting, methylation simply blocks gene expression by interfering with the binding of proteins required for a gene’s transcription. (B) Imprinting of the mouse Kcnq1 gene. On the maternally derived chromosome, synthesis of the lncRNA is blocked by methylation of the DNA (red circles), and the Kcnq1 gene is expressed. On the paternally derived chromosome, the lncRNA is synthesized, remains in place, and by directing alterations in chromatin structure blocks expression of the Kcnq1 gene. Although shown as directly binding to lncRNA, the histone-modifying enzymes are likely to be recruited indirectly, through additional proteins.],
    path: "../fig/image_place_holder.png"
  ),
  "7-53": (
    caption: [X-inactivation. (A) The clonal inheritance in female mammals of a condensed, inactive X chromosome. (B) A calico cat, whose patches of color reflect the random nature of the X-inactivation process. (B, bluecaterpillar/ Deposit photos.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-54": (
    caption: [Photoreceptor cells in the retina of a female mouse showing patterns of X-inactivation. Using genetic engineering techniques (described in Chapter 8), the germ line of a mouse was modified so that one copy of the X chromosome (if active) makes a green fluorescent protein and the other (if active) a red fluorescent protein. Both proteins concentrate in the nucleus, and, in the field of cells shown here, it is clear that only one of the two X chromosomes is active in each cell. If both chromosomes were active, the nuclei would fluoresce both red and green, and therefore appear yellow. (From H. Wu et al., Neuron 81:103–119, 2014. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-55": (
    caption: [Mammalian X-inactivation. The two X chromosomes in a female mammal (A) before and (B) after X-inactivation. (C) At an early stage of X-chromosome inactivation, mouse chromosomes have been hybridized with a fluorescent probe that is complementary to the Xist RNA, which coats only the inactive X chromosome; the remaining DNA has been stained blue with a dye. (D) A schematic illustration of how the continuing synthesis of Xist RNA at the Xist locus moves Xist molecules outward, across the chromosome. As Xist molecules coat the chromosome, they begin to associate with a variety of structural proteins and enzymes that modify histones and DNA. \[Although some of these proteins are bound to the chromosome prior to Xist spreading (not shown), most are brought in by direct association with Xist.\] The two major chromosome domains that are created at the completion of the inactivation process have been proposed to be biomolecular condensates. Genes that escape the inactivation process are shown as loops, extending from the compact domains. (B and D, based on a figure supplied by Agnese Loda and Edith Heard; C, from L. Giorgetti et al., Nature 535:575–579, 2016. Reproduced with permission from SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-56": (
    caption: [Four distinct mechanisms that can produce an epigenetic form of inheritance in an organism. (A) Two epigenetic mechanisms that act in cis. As discussed in this chapter, a maintenance methylase can propagate specific patterns of cytosine methylation (see Figure 7–47). Alternatively, as discussed in Chapter 4, a histone-modifying enzyme that replicates the same covalent modification that attracts it to chromatin can result in a chromatin structure being self-propagating (see Figure 4–44). Note that the term epigenetic is sometimes misused to refer to all covalent modifications of histones, whether or not they are self-propagating. But many histone modifications are erased each time a cell divides, and they therefore do not fit our definition. (B) Two epigenetic mechanisms that act in trans. Positive feedback loops formed by transcription regulators are found in all species and are probably the most common form of cell memory. As discussed in Chapter 3, some proteins can form self-propagating prions (see Figure 3–33). When these proteins are involved in gene expression, prions can transmit a particular pattern of gene expression to daughter cells.],
    path: "../fig/image_place_holder.png"
  ),
  "7-57": (
    caption: [Post-transcriptional controls of gene expression. The final synthesis rate of a protein can, in principle, be controlled at any of the steps listed in capital letters, although only a few of the steps depicted here are likely to be critical for the regulation of any one particular protein. As we shall discuss, the 3′ end cleavage, splicing, editing, and translation recoding steps also make it possible for the cell to produce more than one protein MBoC7 m7.54/7.57 variant from the same gene.],
    path: "../fig/image_place_holder.png"
  ),
  "7-58": (
    caption: [A riboswitch that responds to guanine. In this example from bacteria, the riboswitch controls expression of the purine biosynthetic genes. (A) When guanine levels in cells are low, an elongating RNA polymerase transcribes the purine biosynthetic genes, and the enzymes needed for guanine synthesis are therefore expressed. (B) When guanine is abundant, it binds the riboswitch, causing it to undergo a conformational change that forces the RNA polymerase to terminate transcription (see Figure 6–11). (C) Guanine (red) bound to the riboswitch. Only those nucleotides that form the guanine-binding pocket are shown. Many other riboswitches exist, including those that recognize S-adenosylmethionine, coenzyme B12, flavin mononucleotide, adenine, lysine, and glycine. (A and B, adapted from M. Mandal and R.R. Breaker, Nat. Rev. Mol. Cell Biol. 5:451–463, 2004; and C.K. Vanderpool and S. Gottesman, Mol. Microbiol. 54:1076–1089, 2004; C, adapted from A. Serganov et al., Chem. Biol. 11:1729–1741, 2004. PDB code: 1Y27.) (C) G],
    path: "../fig/image_place_holder.png"
  ),
  "7-59": (
    caption: [Patterns of alternative RNA splicing. Dark blue boxes mark exon sequences that are retained in spliced mRNAs. Light blue boxes mark possible exon sequences that are included only in the indicated mRNAs. The boxes are joined by red lines to indicate where intron sequences (yellow) are removed. In back splicing (discussed later in the chapter), a single exon is removed as a circular RNA molecule. (Adapted from H. Keren et al., Nat. Rev. Genet. 11:345–355, 2010.) 5′],
    path: "../fig/image_place_holder.png"
  ),
  "7-60": (
    caption: [Alternative splicing of RNA transcripts of the Drosophila Dscam gene. Dscam proteins have several different functions. In cells of the fly immune system, they mediate the phagocytosis of bacterial pathogens. In cells of the nervous system, they are needed for proper wiring of neurons. Each mature mRNA contains 24 exons, four of which (denoted A, B, C, and D) are present in the Dscam gene as arrays of alternative exons. Each RNA contains 1 of 12 alternatives for exon A (red), 1 of 48 alternatives for exon B (green), 1 of 33 alternatives for exon C (blue), and 1 of 2 alternatives for exon D (yellow). This figure shows only one of the many possible splicing patterns (indicated by the red line and by the mature mRNA below it). Each variant Dscam protein folds into roughly the same structure (predominantly a series of extracellular immunoglobulin-like domains linked to a membrane-spanning region; see Figure 24–48), but the amino acid sequences of the domains vary according to the splicing pattern. The diversity of Dscam variants contributes to the plasticity of the immune system, as well as to the formation of complex neural circuits. (Adapted from D.L. Black, Cell 103:367–370, 2000. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-61": (
    caption: [Negative and positive control of alternative RNA splicing. (A) In negative control, a repressor protein binds to a specific sequence in the pre- mRNA transcript and blocks access of the splicing machinery to a splice junction. This often results in the use of a secondary splice site, thereby producing an altered pattern of splicing (see Figure 7–59). (B) In positive control, the splicing machinery is unable to remove a particular intron sequence efficiently without assistance from an activator protein. Because an RNA molecule is flexible, the nucleotide sequences that bind these activators can be located many nucleotide pairs from the splice junctions they control, and they are often called splicing enhancers, by analogy with the transcription enhancers mentioned earlier in this chapter. 448],
    path: "../fig/image_place_holder.png"
  ),
  "5-59": (
    caption: [and Table 5–4, p. 308). This difference in transposon activity has been traced to the presence of an intron sequence in the transposase RNA that is removed only in germ cells.],
    path: "../fig/image_place_holder.png"
  ),
  "7-62": (
    caption: [Regulation of the site of RNA cleavage and poly-A addition determines whether an antibody molecule is secreted or remains membrane-bound. (A) In unstimulated B lymphocytes, a long RNA transcript is produced, and the intron sequence (yellow) near its 3′ end is removed by RNA splicing to provide an mRNA molecule that codes for a membrane-bound antibody molecule. Only a portion of the antibody gene is shown in the figure; the actual gene and its mRNA would extend further to the left of the diagram. (B) After antigen stimulation, the RNA transcript is cleaved and polyadenylated upstream from the intron’s 3′ splice site. As a result, some of the intron sequence remains as a coding sequence in the short transcript, specifying the hydrophilic C-terminal portion of the secreted antibody molecule (brown). (Adapted from D. Di Giammartino et al., Mol. Cell 43:853–866, 2011.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-63": (
    caption: [Four of the most prominent of the many types of covalent base modifications found in mRNA. Differences from the normal nucleosides are indicated in red. Each base is joined to a ribose sugar (not shown) by the indicated bond to form the nucleoside.],
    path: "../fig/image_place_holder.png"
  ),
  "7-64": (
    caption: [Mechanism of A-to-I RNA editing in mammals. (A) Typically, a sequence complementary to the position of the edit is present in an intron, and the resulting double-strand RNA structure attracts an A-to-I editing enzyme (ADAR). In the case illustrated, the edit is made in an exon; in most cases, however, it occurs in noncoding portions of the mRNA. Editing by ADAR takes place in the nucleus, before the pre-mRNA has been fully processed. Mice and humans have two ADAR genes: ADR1 is expressed in many tissues and is required in the liver for proper red blood cell development; ADR2 is expressed only in the brain, where it is required for proper brain development. (B) The human ADR2 enzyme bound to double-stranded RNA. The adenine to be edited is seen to be flipped out of the RNA double helix and buried deep in the catalytic pocket of the enzyme. Base flipping, which allows the enzyme access to the entire base, is also observed in enzymes that repair DNA (see Figure 5–42). (PDB code: 5ED1.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-65": (
    caption: [C-to-U RNA editing produces a truncated form of apolipoprotein B. As indicated, a tissue-specific edit in the middle of a coding sequence creates a truncated version of this protein in the intestine.],
    path: "../fig/image_place_holder.png"
  ),
  "7-66": (
    caption: [The compact genome of HIV, the human AIDS virus. The positions of the nine HIV genes are shown in green. The red double line indicates a DNA copy of the viral genome that has become integrated into the host DNA (gray). Note that the coding regions of many HIV genes overlap, and that those for Tat and Rev are split by introns. The blue line in the middle of the figure represents the pre-mRNA transcript of the viral DNA and shows the locations of all the possible splice sites (arrows). There are many alternative ways of splicing the viral transcript; for example, the Env mRNAs retain the intron that has been spliced out of the Tat and Rev mRNAs. The Rev response element (RRE) is indicated by a blue ball and stick. It is a 234-nucleotide-long stretch of RNA that folds into a defined structure; Rev recognizes a particular hairpin within this larger structure.],
    path: "../fig/image_place_holder.png"
  ),
  "7-67": (
    caption: [Regulation of nuclear export by the HIV Rev protein. (A) Early in HIV infection, only the fully spliced RNAs (which contain the coding sequences for Rev, Tat, and Nef) are exported from the nucleus and translated. (B) Once sufficient Rev protein has accumulated and been transported into the nucleus, unspliced viral RNAs can be exported from the nucleus. Many of these RNAs are translated into protein, and the full-length transcripts are packaged into new viral particles.],
    path: "../fig/image_place_holder.png"
  ),
  "7-69": (
    caption: [An experiment demonstrating the importance of the 3′ UTR in localizing mRNAs to specific regions of the cytoplasm. For this experiment, two different fluorescently labeled RNAs were prepared by transcribing DNA in vitro in the presence of fluorescently labeled derivatives of ribonucleoside triphosphates. One RNA (labeled with a red fluorochrome) contains the coding region for the Drosophila Hairy protein and includes the adjacent 3′ UTR. The other RNA (labeled green) contains the Hairy coding region with the 3′ UTR deleted. The two RNAs were mixed and injected into a Drosophila embryo at a stage of development when multiple nuclei reside in a common cytoplasm (see Figure 7–29). When the fluorescent RNAs were visualized 10 minutes later, the full-length hairy RNA (red) was localized to the apical side of nuclei (blue), whereas the transcript missing the 3′ UTR (green) failed to localize and is seen as a diffuse cloud. Hairy is one of many transcription regulators that specify positional information in the developing Drosophila embryo, and the localization of its mRNA (shown in this experiment to depend on its 3′ UTR) is critical for proper fly development. (Courtesy of Simon Bullock and David Ish-Horowicz.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-68": (
    caption: [Mechanisms for the localization of mRNAs. The mRNA to be localized leaves the nucleus through nuclear pores (top). Some localized mRNAs (left diagram) travel to their destination by associating with cytoskeletal motors, which use the energy of ATP hydrolysis to move the mRNAs unidirectionally along filaments in the cytoskeleton (red) (see Chapter 16). At their destination, the mRNAs are held in place by anchor proteins (black). Other mRNAs randomly diffuse through the cytosol and are simply trapped by anchor proteins at their sites of localization (center diagram). As an additional feature, many mRNAs (right diagram) are degraded in the cytosol unless they have bound, through random diffusion, a localized anchor protein complex that protects the mRNA from degradation (black). These mechanisms require specific signals on the mRNA, which are typically located in the 3′ UTR. In all cases, other RNA-bound components block the translation of the mRNA until it is properly localized. Even then, additional signals are often needed to begin translation. (Adapted from H.D. Lipshitz and C.A. Smibert, Curr. Opin. Genet. Dev. 10:476–488, 2000.) 20 µm],
    path: "../fig/image_place_holder.png"
  ),
  "7-70": (
    caption: [Mechanisms of translational control. Although these examples are from bacteria, many of the same principles operate in eukaryotes. (A) Sequence-specific RNA-binding proteins repress translation of specific mRNAs by blocking access of the ribosome to the Shine–Dalgarno sequence (orange). For example, some ribosomal proteins repress translation of their own mRNA. This negative feedback mechanism allows the cell to maintain balanced quantities of the various components needed to form ribosomes. (B) An RNA “thermosensor” permits efficient translation initiation only at elevated temperatures at which the stem–loop structure has been melted. An example occurs in the human pathogen Listeria monocytogenes, in which the translation of its virulence genes increases at 37°C, the temperature of the host. (C) Binding of a small molecule to a riboswitch causes a major rearrangement of RNA structure, creating a different set of stem–loop structures. In the bound structure, the Shine–Dalgarno sequence (orange) is sequestered, and translation initiation is thereby blocked. In many bacteria, S-adenosylmethionine acts in this manner to block production of the enzymes that synthesize it. (D) An “antisense” RNA produced from elsewhere in the genome base-pairs with a specific mRNA and blocks its translation. Many bacteria regulate expression of iron-storage proteins in this way.],
    path: "../fig/image_place_holder.png"
  ),
  "7-71": (
    caption: [The eIF2 cycle. (A) The recycling of used eIF2 by a guanine nucleotide exchange factor (eIF2B). (B) How eIF2 phosphorylation controls protein synthesis rates by sequestering eIF2B.],
    path: "../fig/image_place_holder.png"
  ),
  "7-72": (
    caption: [Internal ribosome entry sites (IRESs) can promote translation initiation by a variety of mechanisms. (A) The normal cap-dependent mechanism requires eIF4G binding to the cap to begin assembly of the other translation components (see Figure 6–74). (B) The cap and eIF4E are bypassed by direct binding of eIF4G to a specific RNA structure formed by the IRES. (C) The small ribosome subunit binds directly to the IRES through base-pairing between sequences in the IRES and the l8S rRNA, positioning it to begin translation. (D) Specialized proteins bind to an IRES and then attract the small ribosome subunit.],
    path: "../fig/image_place_holder.png"
  ),
  "7-73": (
    caption: [Two mechanisms of eukaryotic mRNA decay. Once a mature mRNA is exported to the cytosol, enzymes known as deadenylases gradually shorten its poly-A tail. When a critical threshold of poly-A tail length occurs, the two degradation mechanisms shown are triggered, probably by loss of the poly-A–binding proteins. Although 5′-to-3′ and 3′-to-5′ degradation are shown here on separate RNA molecules, these two processes can occur together on the same molecule. (Adapted from C.A. Beelman and R. Parker, Cell 81:179–183, 1995.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-74": (
    caption: [Two post-translational controls mediated by iron. (A) During iron starvation, the binding of aconitase to the 5′ UTR of the ferritin mRNA blocks translation initiation; its binding to the 3′ UTR of the transferrin receptor mRNA blocks an endonuclease cleavage site and thereby stabilizes the mRNA. (B) In response to an increase in iron concentration in the cytosol, a cell increases its synthesis of ferritin in order to bind the extra iron and decreases its synthesis of transferrin receptors in order to import less iron across the plasma membrane. Both responses are mediated by the same iron-responsive regulatory protein, aconitase, which recognizes common features in a stem–loop structure in the mRNAs encoding ferritin and the transferrin receptor. Aconitase dissociates from the mRNA when it binds iron. But because the transferrin receptor and ferritin are regulated by different types of mechanisms, their levels respond oppositely to iron concentrations even though they are regulated by the same iron-responsive regulatory protein. (Adapted from M.W. Hentze et al., Science 238:1570–1573, 1987; and J.L. Casey et al., Science 240:924–928, 1988.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-75": (
    caption: [Visualization of P-bodies. Human cells were stained with antibodies to a component of the mRNA decapping enzyme Dcp1a (left panels) and to the Argonaute protein (middle panels). As described later in this chapter, Argonaute is a key component of RNA interference pathways and both it and the decapping enzyme destabilize mRNAs. The merged images (right panels) show that the two proteins co-localize to P-bodies in the cytoplasm. (Adapted from J. Liu et al., Nat. Cell Biol. 7:719–723, 2005. Reproduced with permission from SNCSC.) 20 µm],
    path: "../fig/image_place_holder.png"
  ),
  "7-76": (
    caption: [Possible fates of an intact mRNA molecule. An mRNA molecule released from the nucleus can be actively translated (center), stored in P-bodies (left), or, if the cell is stressed, moved into stress granules (right). As the needs of the cell change, stored mRNAs can be reactivated and returned to the cytosol to be translated into protein. Although not shown, all mRNA molecules are eventually degraded, and some of the final steps take place in P-bodies.],
    path: "../fig/image_place_holder.png"
  ),
  "7-77": (
    caption: [RNA interference in eukaryotes. Single-strand interfering RNAs locate target RNAs through complementary base-pairing, and, at this point, several fates are possible, as shown. As described in the text, there are several types of RNA interference; the way that interfering RNA is produced and the ultimate fate of the target RNA depend on the particular system.],
    path: "../fig/image_place_holder.png"
  ),
  "7-78": (
    caption: [miRNA processing and mechanism of action. The precursor miRNA, through complementary base- pairing between one part of its sequence and another, forms a double-strand structure. This RNA is “cropped” while still in the nucleus and then exported to the cytosol, where it is further cleaved (“diced”) by the Dicer enzyme to form the miRNA proper. Argonaute, in conjunction with other components of RISC, initially associates with both strands of the miRNA and then cleaves and discards one of them. The other strand guides RISC to specific mRNAs through base-pairing. If the RNA–RNA match is extensive, as is commonly seen in plants, Argonaute cleaves the target mRNA (“slicing”), causing its rapid degradation. In mammals, the miRNA–mRNA match often does not extend beyond a short seven-nucleotide “seed” region near the 5′ end of the miRNA. This less extensive base-pairing leads to a rapid inhibition of translation and, in most cases, eventual destruction of the mRNA.],
    path: "../fig/image_place_holder.png"
  ),
  "7-79": (
    caption: [Human Argonaute protein carrying an miRNA. The protein is folded into four structural domains, each indicated by a different color. The miRNA is held in an extended form that is optimal for forming RNA–RNA base pairs. The active site of Argonaute that slices a target RNA, when it is extensively base-paired with the miRNA, is indicated in red. Many Argonaute proteins (three out of the four human proteins, for example) lack the catalytic site and therefore bind target RNAs without slicing them. (Adapted from C.D. Kuhn and L. Joshua-Tor, Trends Biochem. Sci. 38:263–271, 2013.)],
    path: "../fig/image_place_holder.png"
  ),
  "7-80": (
    caption: [RNA interference directed by siRNAs. In many organisms, double- stranded RNA can trigger both the destruction of complementary mRNAs (left) and transcriptional silencing (right). The change in chromatin structure induced by the bound RITS (RNA-induced transcriptional silencing) complex resembles that of Figure 7–48.],
    path: "../fig/image_place_holder.png"
  ),
  "7-78": (
    caption: [RNA polymerase],
    path: "../fig/image_place_holder.png"
  ),
  "7-81": (
    caption: [CRISPR-mediated immunity in bacteria and archaea. After infection by a virus (left panel), a small bit of DNA from the viral genome is inserted into the CRISPR locus. For this to happen, a small fraction of infected cells must survive the initial viral infection. The surviving cells, or more generally their descendants, transcribe the CRISPR locus and process the transcript into crRNAs (middle panel). Upon reinfection with a virus that the population has already been “vaccinated” against, the incoming viral DNA is destroyed by a complementary crRNA (right panel).],
    path: "../fig/image_place_holder.png"
  ),
  "7-82": (
    caption: [Roles of long noncoding RNA (lncRNA). (A) As described in Chapter 6, RNAs can fold into short, specific three-dimensional structures whose specific features can be recognized by proteins. Thus, lncRNAs can serve as scaffolds, bringing together proteins that function together in the same process and thereby facilitating their interactions and speeding the reactions that they catalyze. (B) lncRNAs can also, through formation of complementary base pairs, localize the proteins that they bind near specific nucleotide sequences on RNA or DNA molecules. (C) In some cases, lncRNAs act only in cis at their sites of synthesis—as, for example, when the RNA is held in place by the RNA polymerase that produced them (top). But as shown, other lncRNAs diffuse from their sites of synthesis and are said to act in trans.],
    path: "../fig/image_place_holder.png"
  ),
)