#let images = (
  "15-1": (
    caption: [A simple intracellular signaling pathway activated by an extracellular signal molecule. The signal molecule usually binds to a receptor protein that is embedded in the plasma membrane of the target cell. The receptor activates one or more intracellular signaling pathways, involving a series of signaling proteins and small chemical messengers. Finally, one or more of the intracellular signaling molecules alters the activity of effector proteins and thereby the behavior of the cell.],
    path: "../fig/image_place_holder.png"
  ),
  "15-2": (
    caption: [Four forms of intercellular signaling. (A) Contact-dependent signaling requires cells to be in direct membrane– membrane contact. (B) Paracrine signaling depends on local mediators that are released into the extracellular space and act on neighboring cells. (C) Synaptic signaling is performed by neurons that transmit signals electrically along their axons and release neurotransmitters at chemical synapses, which are often located far away from the neuronal cell body. (D) Endocrine signaling depends on endocrine cells, which secrete hormones into the bloodstream for distribution throughout the body. Many of the same types of signaling molecules are used in paracrine, synaptic, and endocrine signaling; the crucial differences lie in the speed and selectivity with which the signals are delivered to their targets. (A)],
    path: "../fig/image_place_holder.png"
  ),
  "15-3": (
    caption: [The binding of extracellular signal molecules to either cell-surface or intracellular receptors. (A) Most signal molecules are hydrophilic and are therefore unable to cross the target cell’s plasma membrane directly; instead, they bind to cell-surface receptors, which in turn generate signals inside the target cell (see Figure 15–1). (B) Some small signal molecules, by contrast, diffuse across the plasma membrane and bind to receptor proteins inside the target cell—either in the cytosol or in the nucleus (as shown here). Many of these small signal molecules are hydrophobic and poorly soluble in aqueous solutions; they are therefore transported in the bloodstream and other extracellular fluids bound to carrier proteins, from which they dissociate before entering the target cell.],
    path: "../fig/image_place_holder.png"
  ),
  "15-4": (
    caption: [An animal cell’s dependence on multiple extracellular signal molecules. Each cell type displays a set of receptors that enables it to respond to a corresponding set of signal molecules produced by other cells. These signal molecules work in various combinations to regulate the behavior of the cell. As shown here, an individual cell often requires multiple signals to survive (blue arrows) and additional signals to grow and divide (red arrows) or differentiate (green arrows). If deprived of appropriate survival signals, a cell will undergo a form of cell suicide known as apoptosis. The actual situation is even more complex. Although not shown, some extracellular signal molecules act to inhibit these and other cell behaviors or even to induce apoptosis.],
    path: "../fig/image_place_holder.png"
  ),
  "15-5": (
    caption: [Various responses induced by the neurotransmitter acetylcholine. (A) The chemical structure of acetylcholine. (B–D) Different cell types are specialized to respond to acetylcholine in different ways. In some cases (B and C), acetylcholine binds to the same type of acetylcholine receptor (a G-protein-coupled receptor; see Figure 15–6), but the intracellular signals produced are interpreted differently in cells specialized for different functions. In other cases (D), the acetylcholine receptor protein is different (an ion-channel-coupled receptor; see Figure 15–6).],
    path: "../fig/image_place_holder.png"
  ),
  "15-6": (
    caption: [Three classes of cell- surface receptors. (A) Ion-channel- coupled receptors (also called transmitter- gated ion channels), (B) G-protein-coupled receptors, and (C) enzyme-coupled receptors. Although many enzyme-coupled receptors have intrinsic enzymatic activity, as shown on the left in C, many others rely on associated enzymes, as shown on the right in C. Ligands activate many enzyme- coupled receptors by promoting their dimerization, which results in the interaction and activation of the cytoplasmic domains.],
    path: "../fig/image_place_holder.png"
  ),
  "15-8": (
    caption: [illustrates the regu- lation of monomeric GTPases.],
    path: "../fig/image_place_holder.png"
  ),
  "15-7": (
    caption: [Two types of intracellular signaling proteins that act as molecular switches. (A) A protein kinase covalently adds a phosphate from ATP to the signaling protein, and a protein phosphatase removes the phosphate. Although not shown, many signaling proteins are activated by dephosphorylation rather than by phosphorylation. (B) A GTP- binding protein is induced to exchange its bound GDP for GTP, which activates the protein; the protein then inactivates itself by hydrolyzing its bound GTP to GDP.],
    path: "../fig/image_place_holder.png"
  ),
  "15-8": (
    caption: [The regulation of a monomeric GTPase. GTPase-activating proteins (GAPs) inactivate the protein by stimulating it to hydrolyze its bound GTP to GDP, which remains tightly bound to the inactivated GTPase. Guanine nucleotide exchange factors (GEFs) activate the inactive protein by stimulating it to release MBoC7 e16.12/15.08 its GDP; because the concentration of GTP in the cytosol is 10 times greater than the concentration of GDP, the protein rapidly binds GTP and is thereby activated.],
    path: "../fig/image_place_holder.png"
  ),
  "15-9": (
    caption: [A sequence of two inhibitory signals produces a positive signal. (A) In this simple signaling system, a transcription regulator is kept in an inactive state by a bound inhibitor protein. In response to some upstream signal, a protein kinase is activated and phosphorylates the inhibitor, causing its dissociation from the transcription regulator, which can now activate gene expression. (B) The signaling pathway consists of a sequence of four steps, including two sequential inhibitory steps that are equivalent to a single activating step.],
    path: "../fig/image_place_holder.png"
  ),
  "15-10": (
    caption: [Three types of intracellular signaling complexes. (A) A receptor and some of the intracellular signaling proteins it activates in sequence are preassembled into a signaling complex on the inactive receptor by a large scaffold protein. (B) A signaling complex assembles transiently on a receptor only after the binding of an extracellular signal molecule has activated the receptor; here, the activated receptor phosphorylates itself at multiple sites, which then act as docking sites for intracellular signaling proteins. (C) Activation of a receptor leads to the increased phosphorylation of specific phospholipids (phosphoinositides) in the adjacent plasma membrane; these then serve as docking sites for specific intracellular signaling proteins, which can now interact with each other.],
    path: "../fig/image_place_holder.png"
  ),
  "15-11": (
    caption: [illustrates how some interaction domains mediate the formation of a large signaling complex around the receptor for the hormone insulin.],
    path: "../fig/image_place_holder.png"
  ),
  "15-11": (
    caption: [A specific signaling complex formed using modular interaction domains. This example is based on the insulin receptor, which is a dimeric enzyme-coupled receptor (a receptor tyrosine kinase, discussed later). First, the activated receptor phosphorylates itself on tyrosines, and one of the phosphotyrosines then recruits an adaptor protein called insulin receptor substrate-1 (IRS1) via a PTB domain of IRS1; the PH domain of IRS1 also binds to specific phosphoinositides on the inner surface of the plasma membrane. Then, the activated receptor phosphorylates IRS1 on tyrosines, and one of these phosphotyrosines binds the SH2 domain of the adaptor protein Grb2. Next, Grb2 uses one of its two SH3 domains to bind to a proline-rich region of a protein called Sos, which is thereby brought to the membrane to relay the signal downstream by acting as a GEF (see Figure 15–8) to activate a monomeric GTPase called Ras (not shown). Sos also binds to phosphoinositides in the plasma membrane via its PH domain. Grb2 uses its other SH3 domain to bind to a proline-rich sequence in a scaffold protein, which binds several other signaling proteins (not shown). The other phosphorylated tyrosines on IRS1 recruit additional signaling proteins that have SH2 domains (not shown).],
    path: "../fig/image_place_holder.png"
  ),
  "15-12": (
    caption: [Formation of large receptor clusters by multivalent interactions among signaling proteins. The system pictured here contains activated receptor tyrosine kinases that are extensively phosphorylated on disordered regions in the receptor tails. The system also includes two adaptor proteins. One adaptor protein (pink) contains one SH2 domain, which binds phosphorylated tyrosines on the receptors, and two SH3 domains. The other adaptor protein (blue) contains three proline-rich regions that can bind to SH3 domains, plus a protein kinase domain. Numerous multivalent binding interactions can occur among the three components in this system, generating a cross-linked protein matrix or condensate in which the protein kinases of the receptor and adaptor protein are concentrated, potentially providing a more effective signal output. The cross-linking of the matrix can be enhanced further by including adaptor proteins with domains that interact with modified phospholipids in the membrane (see Figure 15–11).],
    path: "../fig/image_place_holder.png"
  ),
  "15-13": (
    caption: [An example of signal integration. Extracellular signals A and B activate different intracellular signaling pathways, each of which leads to the phosphorylation of protein Y but at different sites on the protein. Protein Y is activated only when both of these sites are phosphorylated, and therefore it becomes MBoC7 m15.12/15.13 active only when signals A and B are simultaneously present.],
    path: "../fig/image_place_holder.png"
  ),
  "15-14": (
    caption: [Slow and rapid responses to an extracellular signal. Certain types of signal-induced cellular responses, such as increased cell growth and division, involve changes in gene expression and the synthesis of new proteins; they therefore occur slowly, often starting an hour or more after the signal is received. Other responses—such as changes in cell movement, secretion, or metabolism— need not involve changes in gene transcription and therefore occur much more quickly, often starting in seconds or minutes; they may involve the rapid phosphorylation of effector proteins in the cytoplasm, for example. Synaptic responses mediated by changes in membrane potential are even quicker and can occur in milliseconds (not shown). Some signaling systems generate both rapid and slow responses as shown here, allowing the cell to respond quickly to a signal while simultaneously initiating a more long-term, persistent response.],
    path: "../fig/image_place_holder.png"
  ),
  "15-15": (
    caption: [The importance of rapid turnover. The graphs show the predicted relative rates of change in the intracellular concentrations of molecules with differing turnover times when their synthesis rates are either (A) decreased or (B) increased suddenly by a factor of 10. In both cases, the concentrations of those molecules that are normally degraded rapidly in the cell (red lines) change quickly, whereas the concentrations of those that are normally degraded slowly (green lines) change proportionally more slowly. The numbers (in blue) on the right are the half-lives assumed for each of the different molecules.],
    path: "../fig/image_place_holder.png"
  ),
  "15-16": (
    caption: [Signal processing can produce smoothly graded or switchlike responses. Some cell responses increase gradually as the concentration of extracellular signal molecule increases, eventually reaching a plateau as the signaling pathway is saturated, resulting in a hyperbolic response curve (blue line). In other cases, the signaling system reduces the response at low signal concentrations and then produces a steeper response at some intermediate signal concentration— resulting in a sigmoidal response curve (red line). In still other cases, the response is more abrupt and switchlike; the cell switches completely between a low and high response, without any stable intermediate response (green line).],
    path: "../fig/image_place_holder.png"
  ),
  "15-17": (
    caption: [Activation curves for an allosteric protein as a function of effector molecule concentration. The curves show how the sharpness of the activation response increases with an increase in the number of effector molecules that must be bound simultaneously to activate the target protein. The curves shown are those expected, under certain conditions, if the activation requires the simultaneous binding of 1, 2, 8, or 16 effector molecules. MBoC7 m15.16/15.17],
    path: "../fig/image_place_holder.png"
  ),
  "15-18": (
    caption: [Positive and negative feedback. In these simple examples, a stimulus activates protein A, which, in turn, activates protein B. Protein B then acts back to either increase or decrease the activity of A.],
    path: "../fig/image_place_holder.png"
  ),
  "15-19": (
    caption: [Some effects of simple feedback. The graphs show the computed effects of simple positive and negative feedback loops (discussed in Chapter 8). In each case, the input signal is an activated protein kinase (S) that phosphorylates and thereby activates another protein kinase (E); a protein phosphatase (I) dephosphorylates and inactivates the activated E kinase. In the graphs, the red line indicates the activity of the E kinase over time; the underlying black bracket indicates the time during which the input signal (activated S kinase) is present. (A) Diagram of a positive feedback loop, in which the activated E kinase acts back to promote its own phosphorylation and activation; the basal activity of the I phosphatase dephosphorylates activated E at a steady, low rate. (B) The top graph shows that, without feedback, the activity of the E kinase is simply proportional to the level of stimulation by the S kinase. The bottom graph shows that, with the positive feedback loop, the transient stimulation by S kinase switches the system from an “off” state to an “on” state, which then persists after the stimulus has been removed. (C) Diagram of a negative feedback loop, in which the activated E kinase phosphorylates and activates the I phosphatase, thereby increasing the rate at which the phosphatase dephosphorylates and inactivates the phosphorylated E kinase. (D) The top graph shows, again, the response in E kinase activity without feedback. The other graphs show the effects on E kinase activity of negative feedback operating after a short or long delay. With a short delay, the system shows a response when the signal is first increased, but the feedback quickly dampens the response—which then declines to some intermediate level at which the input signal and feedback are balanced. With a long delay, the response rises unopposed at first, allowing kinase activity to reach maximum levels before it feeds back to shut itself off. Then the sudden drop in activity removes the negative feedback, unleashing another pulse of kinase activity. If conditions are right, the result is sustained oscillations for as long as the stimulus is present.],
    path: "../fig/image_place_holder.png"
  ),
  "15-20": (
    caption: [The importance of examining individual cells to detect all-or-none responses to increasing concentrations of an extracellular signal. In these experiments, immature frog eggs (oocytes) were stimulated with increasing concentrations of the hormone progesterone. The response was assessed by analyzing the activation of MAP kinase (discussed later), which is one of the protein kinases activated by phosphorylation in the response. The amount of phosphorylated (activated) MAP kinase in extracts of the oocytes was assessed biochemically. In (A), extracts of populations of stimulated oocytes were analyzed, and the activation of MAP kinase appeared to increase progressively with increasing progesterone concentration. There are two possible ways of explaining this result: (B) MAP kinase could have increased gradually in each individual cell with increasing progesterone concentration; or (C) individual cells could have responded in an all-or- none way, with the gradual increase in total MAP kinase activation reflecting the increasing number of cells responding with increasing progesterone concentration. When extracts of individual oocytes were analyzed, it was found that cells had either very low amounts or very high amounts, but not intermediate amounts, of the activated kinase, indicating that the response was essentially all-or- MBoC7 m15.19/15.20 none at the level of individual cells, as diagrammed in C. Subsequent studies revealed that this all-or-none response is due in part to strong positive feedback in the progesterone signaling system. (Adapted from J.E. Ferrell and E.M. Machleder, Science 280:895–898, 1998. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-21": (
    caption: [Some ways in which target cells can become adapted (desensitized) to an extracellular signal molecule. (A) Negative feedback with a short delay can dampen the initial response to receptor activation. (B) In some cases, the activated receptor rapidly activates a stimulatory pathway while also initiating a slower inhibitory pathway—resulting in a transient output response. This is called a delayed feed-forward loop. (C, D, E) Various mechanisms can inactivate a cell-surface receptor after a signal molecule binds, including mechanisms that depend on internalization of the receptor into endosomes, from which the receptor can be returned to the cell surface or destroyed in lysosomes.],
    path: "../fig/image_place_holder.png"
  ),
  "15-22": (
    caption: [A G-protein-coupled receptor (GPCR). (A) GPCRs that bind small ligands such as epinephrine have small extracellular domains, and the ligand usually binds deep within the plane of the plasma membrane to a site that is formed by amino acids from several transmembrane segments. GPCRs that bind protein ligands have a large extracellular domain (not shown here) that contributes to ligand binding. (B) The structure of the β2-adrenergic receptor, a receptor for the neurotransmitter epinephrine, illustrates the typical cylindrical arrangement of the seven transmembrane helices in a GPCR. The ligand (orange) binds in a pocket between the helices, resulting in conformational changes on the cytoplasmic surface of the receptor that promote G-protein activation (not shown). (PDB code: 3P0G.) N],
    path: "../fig/image_place_holder.png"
  ),
  "15-23": (
    caption: [The structure of an inactive G protein. (A) Note that both the α and γ subunits have covalently attached lipid molecules (red tails) that help them bind to the plasma membrane, and the α subunit has GDP bound. (B) The three-dimensional structure of the inactive, GDP-bound form of a G protein called Gi, which interacts with numerous GPCRs, including the β2-adrenergic receptor shown in Figure 15–22. The α subunit contains the GTPase domain and binds to one side of the β subunit. The γ subunit binds to the opposite side of the β subunit, and the β and γ subunits together form a single functional unit. The GTPase domain of the α subunit contains two major subdomains: the Ras domain, which is related to other GTPases and provides one face of the GTP-binding pocket; and the α-helical or AH domain, which clamps the GTP in place (see Figure 15–24). (PDB code: 1GG2.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-24": (
    caption: [Activation of a G protein by an activated GPCR. Binding of an extracellular signal molecule to a GPCR changes the conformation of the receptor, which allows the receptor to bind and alter the conformation of a heterotrimeric G protein. The AH domain of the G protein α subunit moves outward to open the GTP-binding site, thereby promoting dissociation of GDP. GTP binding then promotes closure of the binding site, triggering conformational changes that cause dissociation of the α subunit from the receptor and from the βγ complex. The GTP-bound α subunit and the βγ complex each regulate the activities of downstream signaling molecules (not shown). The receptor stays active while the extracellular signal molecule is bound to it, and it can therefore catalyze the activation of many G-protein molecules (Movie 15.1).],
    path: "../fig/image_place_holder.png"
  ),
  "15-26": (
    caption: [The synthesis and degradation of cyclic AMP. In a reaction catalyzed by the enzyme adenylyl cyclase, cyclic AMP (cAMP) is synthesized from ATP through a cyclization reaction that removes two phosphate groups as pyrophosphate (PP); a pyrophosphatase drives this synthesis by hydrolyzing the released pyrophosphate to phosphate. Cyclic AMP is short-lived (unstable) in the cell because it is hydrolyzed by specific phosphodiesterases to form 5′-AMP, as indicated.],
    path: "../fig/image_place_holder.png"
  ),
  "15-25": (
    caption: [An increase in cyclic AMP in response to an extracellular signal. This Aplysia sensory nerve cell in culture is responding to the neurotransmitter serotonin, which acts through a GPCR to cause a rapid rise in the intracellular concentration of cAMP. To monitor the cAMP level, the cell has been loaded with a fluorescent protein that changes its fluorescence when it binds cAMP. Blue indicates a low level of cAMP, yellow an intermediate level, and red a high level. (A) In the resting cell, the cAMP level is about 5 × 10–8 M. (B) Twenty seconds after the addition of serotonin to the culture medium, the intracellular level of cAMP has increased to more than 10–6 M in the relevant parts of the cell, an increase of more than twentyfold. (From B.J. Bacskai et al., Science 260:222–226, 1993. With permission from AAAS.) N N O O O _ O],
    path: "../fig/image_place_holder.png"
  ),
  "15-1": (
    caption: [Some Hormone-induced Cell Responses Mediated by Cyclic AMP],
    path: "../fig/image_place_holder.png"
  ),
  "15-27": (
    caption: [The activation of cyclic- AMP-dependent protein kinase (PKA). The binding of cAMP to the regulatory subunits of the PKA tetramer induces a conformational change, causing these subunits to dissociate from the catalytic subunits, thereby activating the kinase activity of the catalytic subunits. The release of the catalytic subunits requires the binding of more than two cAMP molecules to the regulatory subunits in the tetramer. This requirement greatly sharpens the response of the kinase to changes in cAMP concentration, as discussed earlier (see Figure 15–17).],
    path: "../fig/image_place_holder.png"
  ),
  "15-28": (
    caption: [How a rise in intracellular cyclic AMP concentration can alter gene transcription. The binding of an extracellular signal molecule to its GPCR activates adenylyl cyclase via Gs and thereby increases cAMP concentration in the cytosol. This rise activates PKA, and the released catalytic subunits of PKA can then enter the nucleus, where they phosphorylate the transcription regulatory protein CREB. Once phosphorylated, CREB recruits the coactivator CBP, which stimulates gene transcription. In some cases, the inactive CREB protein is bound to the cyclic AMP response element (CRE) in DNA before it is phosphorylated (not shown). See Movie 15.2.],
    path: "../fig/image_place_holder.png"
  ),
  "15-2": (
    caption: [Some Cell Responses in Which GPCRs Activate PLCβ],
    path: "../fig/image_place_holder.png"
  ),
  "15-2": (
    caption: [lists some examples of responses activated in this way. The phospholipase acts on a phosphorylated inositol phospholipid (a phosphoinositide) called phos- phatidylinositol 4,5-bisphosphate \[PI(4,5)P2\], which is present in small amounts in the inner half of the plasma membrane lipid bilayer (Figure 15–29). Receptors that activate this inositol phospholipid signaling pathway do so primarily through a G protein called Gq, which activates phospholipase C-β in much the same way that Gs activates adenylyl cyclase. The activated phospholipase then cleaves the PI(4,5)P2 to generate two products: inositol 1,4,5-trisphosphate (IP3) and diacylglycerol. At this step, the signaling path- way splits into two branches.],
    path: "../fig/image_place_holder.png"
  ),
  "15-29": (
    caption: [The hydrolysis of PI(4,5)P2 by phospholipase C-b. Two second messengers are produced directly from the hydrolysis of PI(4,5)P2: inositol 1,4,5-trisphosphate (IP3), which diffuses through the cytosol and releases Ca2+ from the endoplasmic reticulum, and diacylglycerol, which remains in the membrane and helps to activate protein kinase C (PKC; see Figure 15–30). There are several classes of phospholipase C: these include the β class, which is activated by GPCRs; as we see later, the γ class is activated by a class of enzyme- coupled receptors called receptor tyrosine kinases (RTKs).],
    path: "../fig/image_place_holder.png"
  ),
  "15-30": (
    caption: [How GPCRs increase cytosolic Ca2+ and activate protein kinase C. The activated GPCR stimulates the plasma-membrane-bound phospholipase C-β (PLCβ) via a G protein called Gq. The α subunit and βγ complex of Gq are both involved in this activation. Two second messengers are produced when PI(4,5)P2 is hydrolyzed by activated PLC. Inositol 1,4,5-trisphosphate (IP3) diffuses through the cytosol and releases Ca2+ from the ER by binding to and opening IP3-gated Ca2+-release channels (IP3 receptors) in the ER membrane (opening of these channels also requires binding of Ca2+, not shown). The large electrochemical gradient for Ca2+ across this membrane causes Ca2+ to escape into the cytosol when the release channels are opened. Diacylglycerol remains in the plasma membrane and, together with phosphatidylserine (not shown) and Ca2+, helps to activate protein kinase C (PKC), which is recruited from the cytosol to the cytosolic face of the plasma membrane. Of the 10 or more distinct isoforms of PKC in humans, at least 4 are activated by diacylglycerol (Movie 15.3).],
    path: "../fig/image_place_holder.png"
  ),
  "15-31": (
    caption: [and Movie 15.4).],
    path: "../fig/image_place_holder.png"
  ),
  "15-31": (
    caption: [The fertilization of an egg by a sperm triggers a wave of cytosolic Ca2+. This sea star egg was injected with a Ca2+-sensitive fluorescent dye before it was fertilized. A wave of cytosolic Ca2+ (red and yellow), caused by Ca2+ release from the ER, sweeps across the egg from the site of sperm entry (arrow). This Ca2+ wave changes the egg cell surface, preventing the entry of other sperm, and it also initiates embryonic development (Movie 15.5). The initial increase in Ca2+ is thought to be caused by a sperm-specific form of PLC (PLCζ) that the sperm brings into the egg cytoplasm when it fuses with the egg; the PLCζ cleaves PI(4,5)P2 to produce IP3, which releases Ca2+ from the egg ER. The released Ca2+ stimulates further Ca2+ release from the ER, producing the spreading wave, as we explain in Figure 15–32. (Courtesy of Stephen Stricker.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-32": (
    caption: [Positive and negative feedback produce cytosolic Ca2+ waves and oscillations. This diagram shows IP3 receptors on a portion of the ER membrane: active receptors are shown in green, inactive receptors in red, Ca2+ in orange, and IP3 in blue. When cytosolic IP3 rises to high levels in response to a strong extracellular signal, it occupies most IP3 receptors on the ER membrane. A few IP3-bound receptors are then activated by the low amount of cytosolic Ca2+ that is present in the unstimulated cell. The local release of Ca2+ by an activated receptor cluster (top) promotes the opening of nearby IP3 receptors (and ryanodine receptors, not shown), resulting in more Ca2+ release. This positive feedback (indicated by positive signs) produces a regenerative wave of Ca2+ release that spreads across the cell (see Figure 15–31). These waves of Ca2+ release move more quickly across the cell than would be possible by simple diffusion. Also, unlike a diffusing burst of Ca2+ ions, which will become more dilute as it spreads, the regenerative wave produces a high Ca2+ concentration across the entire cell. When it reaches high concentrations, Ca2+ inactivates IP3 receptors and ryanodine receptors (middle; indicated by red negative signs), shutting down the Ca2+ release. Ca2+-pumps reduce the local cytosolic Ca2+ concentration to its low resting levels. The result is a cytosolic Ca2+ pulse: positive feedback drives a rapid rise in cytosolic Ca2+, and negative feedback sends it back down again. The Ca2+ channels remain refractory to further stimulation for some period of time, delaying the generation of another Ca2+ spike (bottom). Eventually, however, the negative feedback wears off, allowing IP3 to trigger another Ca2+ wave. The end result is repeated Ca2+ oscillations (see Figure 15–33). Under some conditions, these oscillations can be seen as repeating narrow waves of Ca2+ moving across the cell.],
    path: "../fig/image_place_holder.png"
  ),
  "15-33": (
    caption: [Vasopressin-induced cytosolic Ca2+ oscillations in a liver cell. The cell was loaded with the Ca2+- sensitive protein aequorin and then exposed to increasing concentrations of the peptide signal molecule vasopressin, which activates a GPCR and thereby PLCβ (see Table 15–2). Note that the frequency of the Ca2+ spikes increases with an increasing concentration of vasopressin but that the amplitude of the spikes is not affected. Each spike lasts about 7 seconds. (Adapted from N.M. Woods et al., Nature 319:600–602, published 1986 by Nature Publishing Group. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-34": (
    caption: [The structure of Ca2+/ calmodulin. (A) The molecule has a dumbbell shape, with two globular ends, which can bind to many different target proteins. The globular ends are connected by a long, exposed α helix, which allows the protein to adopt a number of different conformations, depending on the target protein it interacts with. Each globular head has two Ca2+-binding sites (Movie 15.6). (B) Shown is the major structural change that occurs in Ca2+/calmodulin when it binds to a target protein (in this example, a peptide that consists of the Ca2+/ calmodulin-binding domain of a Ca2+/ calmodulin-dependent protein kinase). Note that the Ca2+/calmodulin has folded to surround the peptide. When it binds to other targets, it can adopt different conformations. (A, PDB code: 1CLL; B, PDB codes: 1CDL and 2BBM.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-35": (
    caption: [The stepwise activation of CaM-kinase II. (A) Each CaM-kinase II protein has two major domains: an amino-terminal kinase domain (green) and a carboxyl-terminal hub domain (blue), linked by a regulatory segment. Six CaM-kinase II proteins are assembled into a giant ring in which the hub domains interact tightly to produce a central structure that is surrounded by kinase domains. The complete enzyme contains two stacked rings, for a total of 12 kinase proteins, but only one ring is shown here for clarity. When the enzyme is inactive, the ring exists in a dynamic equilibrium between two states. The first (upper left) is a compact state, in which the kinase domains interact with the hub domains, so that the regulatory segments are buried in the kinase active sites and thereby block catalytic activity. In the second inactive state (upper middle), a kinase domain has popped out and is linked to its hub domain by its regulatory segment, which continues to inhibit the kinase domain but is now accessible to Ca2+/calmodulin. If present, Ca2+/calmodulin will bind the regulatory segment and prevent it from inhibiting the kinase, thereby locking the kinase in an active state (upper right). If the adjacent kinase domain also pops out from the hub, it will also be activated by Ca2+/calmodulin, and the two kinase domains will then phosphorylate each other on their regulatory segments (lower right). This autophosphorylation further activates the enzyme. It also prolongs the activity of the enzyme in two ways. First, it traps the bound Ca2+/calmodulin so that it does not dissociate from the enzyme until cytosolic Ca2+ levels return to basal values for at least 10 seconds (not shown). Second, it converts the enzyme to a Ca2+-independent form, so that the kinase remains active even after the Ca2+/calmodulin dissociates from it (lower left). This activity continues until the action of a protein phosphatase overrides the autophosphorylation activity of CaM-kinase II. (B) This model of the enzyme is based on x-ray crystallography analysis of the CaM-kinase II dodecamer.],
    path: "../fig/image_place_holder.png"
  ),
  "15-36": (
    caption: [CaM-kinase II as a frequency decoder of Ca2+ oscillations. (A) At low frequencies of Ca2+ spikes, the enzyme becomes inactive after each spike, as the autophosphorylation induced by Ca2+/calmodulin binding does not maintain the enzyme’s activity long enough for the enzyme to remain active until the next Ca2+ spike arrives. (B) At higher spike frequencies, however, the enzyme fails to inactivate completely between Ca2+ spikes, so its activity ratchets up with each spike. If the spike frequency is high enough, this progressive increase in enzyme activity will continue until the enzyme is autophosphorylated on all subunits and is therefore maximally activated. Although not shown, once enough of its subunits are autophosphorylated, the enzyme can be maintained in a highly active state even with a relatively low frequency of Ca2+ spikes—a form of cell memory. The binding of Ca2+/calmodulin to the enzyme is enhanced by the CaM-kinase II autophosphorylation (an additional form of positive feedback), helping to generate a more switchlike response to repeated Ca2+ spikes. (From P.I. Hanson et al., Neuron 12:943–956, 1994. With permission from Elsevier.) 904],
    path: "../fig/image_place_holder.png"
  ),
  "15-37": (
    caption: [Olfactory receptor neurons. (A) A simplified drawing of a section of olfactory epithelium in the nose. Olfactory receptor neurons possess modified cilia, which project from the surface of the epithelium and contain the olfactory receptors, as well as the signal transduction machinery. The axon, which extends from the opposite end of the receptor neuron, conveys electrical signals to the brain when an odorant activates the cell to produce an action potential. In rodents, at least, the basal cells act as stem cells, producing new receptor neurons throughout life, to replace the neurons that die. (B) A scanning electron micrograph of the cilia on the surface of a human olfactory neuron. (B, from E.E. Morrison and R.M. Costanzo, J. Comp. Neurol. 297:1–13, 1990. With permission from Wiley-Liss.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-38": (
    caption: [Cyclic GMP.],
    path: "../fig/image_place_holder.png"
  ),
  "15-39": (
    caption: [A rod photoreceptor cell. There are about 1000 discs in the outer segment. The disc membranes are not connected to the plasma membrane. The inner and outer segments are specialized parts of a primary cilium (discussed in Chapter 16). A primary cilium extends from the surface of most vertebrate cells, where it serves as a signaling compartment.],
    path: "../fig/image_place_holder.png"
  ),
  "15-40": (
    caption: [The response of a rod photoreceptor cell to light. Rhodopsin molecules in the outer-segment discs absorb photons. Photon absorption closes cation channels in the plasma membrane, which hyperpolarizes the membrane and reduces the rate of neurotransmitter release from the synaptic region. Because the neurotransmitter inhibits many of the postsynaptic retinal neurons in the absence of light, illumination serves to free the neurons from inhibition and thus, in effect, excites them. The neural connections of the retina lie between the light source and the outer segment, and so light must pass through the synapses and rod cell nucleus to reach the light sensors.],
    path: "../fig/image_place_holder.png"
  ),
  "15-3": (
    caption: [Four Major Families of Heterotrimeric G Proteins*],
    path: "../fig/image_place_holder.png"
  ),
  "15-41": (
    caption: [The role of nitric oxide (NO) in smooth muscle relaxation in a blood vessel wall. (A) Drawing of a cross section of a small blood vessel, showing the endothelial cells lining the lumen, the smooth muscle cells around them, and the basal lamina separating the two. (B) The neurotransmitter acetylcholine stimulates blood vessel dilation by activating a GPCR—the muscarinic acetylcholine receptor—on the surface of endothelial cells. This receptor activates a G protein, Gq, thereby stimulating IP3 synthesis and Ca2+ release from the ER by the mechanisms illustrated in Figure 15–30. Increased Ca2+ activates nitric oxide synthase, causing the endothelial cells to produce NO from arginine. The NO diffuses out of the endothelial cells and into the neighboring smooth muscle cells, where it activates guanylyl cyclase to produce cyclic GMP. The cyclic GMP triggers a response that causes the smooth muscle cells to relax, increasing blood flow through the vessel.],
    path: "../fig/image_place_holder.png"
  ),
  "15-42": (
    caption: [Amplification in the light- induced catalytic cascade in vertebrate rods. The red arrows indicate the steps where amplification occurs, with the thickness of the arrow roughly indicating the magnitude of the amplification.],
    path: "../fig/image_place_holder.png"
  ),
  "15-43": (
    caption: [The roles of GPCR kinases (GRKs) and arrestins in GPCR desensitization. A GRK phosphorylates only activated receptors because it is the activated GPCR that turns on the GRK. The binding of an arrestin to the phosphorylated receptor prevents the receptor from binding to its G protein and also directs its endocytosis (not shown). Mice deficient in one form of arrestin fail to desensitize in response to morphine, for example, attesting to the importance of arrestins for desensitization. (internalized) so that they no longer have access to their ligand. (3) In receptor destruction, they are destroyed in lysosomes after internalization. In each case, the desensitization of the GPCRs depends on their phosphorylation by PKA, PKC, or a member of the family of GPCR kinases (GRKs), which includes the rhodop- sin kinase involved in rod photoreceptor desensitization discussed earlier. The GRKs phosphorylate multiple serines and threonines on a GPCR, but they do so only after ligand binding has activated the receptor, because it is the activated receptor that allosterically activates the GRK. As with rhodopsin, once a receptor has been phosphorylated by a GRK, it binds with high affinity to a member of the arrestin family of proteins (Figure 15–43).],
    path: "../fig/image_place_holder.png"
  ),
  "15-44": (
    caption: [shows the basic structural features of a number of the families that operate in mammals. In all cases, the binding of the signal protein to the ligand- binding domain on the extracellular side of the receptor activates the tyrosine kinase domain on the cytosolic side. This leads to phosphorylation of tyrosine],
    path: "../fig/image_place_holder.png"
  ),
  "15-4": (
    caption: [Some Extracellular Signal Proteins That Act Via RTKs],
    path: "../fig/image_place_holder.png"
  ),
  "15-44": (
    caption: [Some subfamilies of RTKs. Only one or two members of each subfamily are indicated. Note that in some cases, the tyrosine kinase domain is interrupted by a kinase insert region that is an extra segment emerging from the folded kinase domain. The functions of most of the cysteine-rich, immunoglobulin-like, and fibronectin-type-III-like domains are not known. Some of the ligands for the receptors shown are listed in Table 15–4, along with some representative responses that they mediate. ﬁbronectin-type-III- like domain],
    path: "../fig/image_place_holder.png"
  ),
  "15-45": (
    caption: [Activation of RTKs by dimerization. In the absence of extracellular signals, many RTKs exist as monomers in which the internal kinase domain is inactive. Binding of ligand brings two monomers together to form a dimer. The close proximity in the dimer leads the two kinase domains to phosphorylate each other, which has two effects. First, phosphorylation at some tyrosines in the kinase domains promotes the complete activation of the domains. Second, phosphorylation at tyrosines in other parts of the receptors generates docking sites for intracellular signaling proteins, resulting in the formation of large signaling complexes that can then broadcast signals along multiple signaling pathways.],
    path: "../fig/image_place_holder.png"
  ),
  "15-46": (
    caption: [Activation of the EGF receptor kinase. In the absence of ligand, the EGF receptor exists primarily as an inactive monomer. EGF binding results in a conformational change that promotes dimerization of the external domains. The receptor kinase domain, unlike that of many RTKs, is not activated by transautophosphorylation. Instead, dimerization orients the internal kinase domains into an asymmetrical dimer, in which one kinase domain (the activator) pushes against the other kinase domain (the receiver), thereby causing an activating conformational change in the receiver. The active receiver domain then phosphorylates multiple tyrosines in the C-terminal tails of both receptors, generating docking sites for intracellular signaling proteins (see Figure 15–45). Note that protein kinase activity is generated only in the receiver kinase domain; the activator kinase domain remains in an inactive conformation. In fact, some members of the EGF receptor family contain kinase domains that are missing key residues in their active site and are therefore inactive. These pseudokinase receptors can still dimerize with and activate EGF receptors containing an active kinase receiver domain.],
    path: "../fig/image_place_holder.png"
  ),
  "15-47": (
    caption: [The binding of SH2- containing intracellular signaling proteins to an activated RTK. (A) Drawing based on an activated receptor for platelet-derived growth factor (PDGF); for simplicity, only one monomer of the dimer is shown, and the PDGF ligand is omitted. Five phosphotyrosines are shown, three in the kinase insert region and two on the C-terminal tail; these form three docking sites, each of which binds a different signaling protein as indicated. The numbers on the right indicate the positions of the tyrosines in the polypeptide chain. The functions of these phosphotyrosines were determined by mutation of specific tyrosines. Mutation of tyrosines 1009 and 1021, for example, prevents the binding and activation of PLCγ, so that receptor activation no longer stimulates the inositol phospholipid signaling pathway. The locations of the SH2 (red) and SH3 (blue) domains in the primary structures of the three signaling proteins are indicated. Additional phosphotyrosine docking sites on this receptor are not shown, including those that bind the cytoplasmic tyrosine kinase Src and two adaptor proteins. It is unclear how many signaling proteins can bind simultaneously to a single RTK. (B) The three-dimensional structure of an SH2 domain, as determined by x-ray crystallography. The binding pocket for phosphotyrosine is shaded in yellow on the right, and a pocket for binding a specific amino acid side chain (valine, in this case) is shaded in green on the left. The RTK polypeptide segment that binds the SH2 domain is shown in green. (C) The SH2 domain is a compact, “plug-in” module, which can be inserted in disordered regions of a protein without disturbing the protein’s folding or function (discussed in Chapter 3). Because each domain has distinct sites for recognizing phosphotyrosine and for recognizing a particular amino acid side chain, different SH2 domains recognize phosphotyrosine in the context of different flanking amino acid sequences. (B, PDB code: 2SRC.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-5": (
    caption: [The Ras Superfamily of Monomeric GTPases],
    path: "../fig/image_place_holder.png"
  ),
  "15-48": (
    caption: [How an RTK activates Ras. The Grb2 adaptor protein recognizes a specific phosphorylated tyrosine on the activated receptor by means of an SH2 domain and recruits the Ras GEF Sos by means of an interaction between its SH3 domains and proline-rich regions in Sos. Sos also contains a PH domain that recognizes specific phospholipids but is not used here (see Figure 15–11). The Ras GEF domain of Sos stimulates the inactive Ras protein to replace its bound GDP by GTP, which activates Ras to relay the signal downstream. P P P P P P P P],
    path: "../fig/image_place_holder.png"
  ),
  "15-49": (
    caption: [Transient activation of Ras revealed by single-molecule fluorescence resonance energy transfer (FRET). (A) Schematic drawing of the experimental strategy. Cells of a human cancer cell line were genetically engineered to express a Ras protein that was covalently linked to yellow fluorescent protein (YFP). GTP that was labeled with a red fluorescent dye was microinjected into some of the cells. The cells were then stimulated with the extracellular signal protein EGF, and single fluorescent molecules of Ras-YFP at the inner surface of the plasma membrane were measured by video fluorescence microscopy in individual cells. When a fluorescent Ras- YFP molecule becomes activated, it exchanges unlabeled GDP for fluorescently labeled GTP; the energy emitted by the YFP now activates the fluorescent GTP to emit red light (called fluorescence resonance energy transfer, or FRET; see Figure 9–22). Thus, the activation of single Ras molecules can be followed by the emission of red fluorescence from a previously yellow-green fluorescent spot at the plasma membrane. As shown in (B), activated Ras molecules could be detected after about 30 seconds of EGF stimulation. The red signal peaked at about 3 minutes and then decreased to baseline by 6 minutes. As Ras GAP was found to be recruited to the same spots at the plasma membrane as Ras, it presumably plays a major part in rapidly shutting off the Ras signal. (Modified from H. Murakoshi et al., Proc. Natl. Acad. Sci. USA 101:7317–7322, 2004. Copyright 2004 National Academy of Sciences, USA. With permission from National Academy of Sciences.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-50": (
    caption: [The MAP kinase module activated by Ras. The three-component module begins with a MAP kinase kinase kinase called Raf. Ras recruits Raf to the plasma membrane and helps activate it. Raf then activates the MAP kinase kinase Mek, which then activates the MAP kinase Erk. Erk in turn phosphorylates a variety of downstream proteins, including other protein kinases, as well as transcription regulators in the nucleus. The resulting changes in protein activities and gene expression cause complex changes in cell behavior (Movie 15.8).],
    path: "../fig/image_place_holder.png"
  ),
  "15-51": (
    caption: [The organization of two MAP kinase modules by scaffold proteins in budding yeast. Budding yeast have at least six three-component MAP kinase modules involved in a variety of biological processes, including the two responses illustrated here—a mating response and the response to high osmolarity. (A) The mating response is triggered when a mating factor secreted by a yeast of opposite mating type binds to a GPCR. This activates a G protein, the βγ complex of which indirectly activates the MAPKKK (kinase A), which then relays the response onward. Once activated, the MAP kinase (kinase C) phosphorylates and thereby activates several downstream proteins that mediate the mating response, in which the yeast cell stops dividing and prepares for fusion. The three kinases in this module are bound to scaffold protein 1. (B) In a second response, a yeast cell exposed to a high-osmolarity environment is induced to synthesize glycerol to increase its internal osmolarity. This response is mediated by an osmolarity-sensing receptor protein and a different MAP kinase module bound to a second scaffold protein. (Note that the kinase domain of scaffold 2 provides the MAPKK activity of this module.) Although both pathways use the same MAPKKK (kinase A, green), there is no cross-talk between them because the kinases in each module are bound to different scaffold proteins, and the osmolarity-sensing receptor is bound to the same scaffold protein as the particular kinase it activates.],
    path: "../fig/image_place_holder.png"
  ),
  "15-52": (
    caption: [Growth cone collapse mediated by the Rho family GTPase RhoA. The binding of ephrin A1 proteins on an adjacent cell activates EphA4 RTKs on the growth cone. The resulting phosphotyrosines on the activated Eph receptors recruit and activate a cytoplasmic tyrosine kinase to phosphorylate the receptor-associated Rho GEF ephexin on a tyrosine. This enhances the ability of the ephexin to activate membrane- bound RhoA, which stimulates the myosin-dependent contraction of the actin cytoskeleton, thereby causing the growth cone to collapse.],
    path: "../fig/image_place_holder.png"
  ),
  "15-53": (
    caption: [The generation of phosphoinositide docking sites by PI 3-kinase. PI 3-kinase phosphorylates the inositol ring on carbon atom 3 to generate the phosphoinositides shown at the bottom of the figure (diverting them away from the pathway leading to IP3 and diacylglycerol; see Figure 15–29). The most important phosphorylation (indicated by the red arrow) is of PI(4,5)P2 to PI(3,4,5)P3, which can serve as a docking site for signaling proteins with PI(3,4,5)P3-binding PH domains. Other inositol phospholipid kinases (not shown) catalyze the phosphorylations indicated by the green arrows.],
    path: "../fig/image_place_holder.png"
  ),
  "15-54": (
    caption: [One way in which signaling through PI 3-kinase can promote cell survival. An extracellular survival signal activates an RTK, which recruits and activates PI 3-kinase. The PI 3-kinase produces PI(3,4,5)P3, which serves as a docking site for two serine/threonine kinases with PH domains—Akt and the phosphoinositide-dependent kinase PDK1—and brings them into proximity at the plasma membrane. The Akt is phosphorylated on a serine by a third membrane-associated kinase (mTOR in complex 2, or mTORC2), which alters the conformation of the Akt so that it can be phosphorylated on a threonine by PDK1, which activates the Akt. The activated Akt now dissociates from the plasma membrane and phosphorylates various target proteins, including the Bad protein. When unphosphorylated, Bad holds the apoptosis-inhibitory Bcl2 in an inactive state (Bad and Bcl2 are both members of a family of proteins that regulates apoptosis, as discussed in Chapter 18). Once phosphorylated, Bad releases Bcl2, which now can block apoptosis and thereby promote cell survival. The phosphorylated Bad binds to a ubiquitous cytosolic protein called 14-3-3, which keeps the protein out of action, as shown.],
    path: "../fig/image_place_holder.png"
  ),
  "15-55": (
    caption: [Activation of mTOR complex 1 (mTORC1) by growth factors and amino acids. mTORC1 activity depends on binding to the GTP-bound forms of two Ras-related GTPases, Rag and Rheb. In the presence of abundant cytosolic amino acids, Rag-GTP recruits mTORC1 to the surface of lysosomes. Full activation of mTORC1 then requires interaction with Rheb-GTP, which is activated in response to growth factor signaling. In both cases, enhanced GTP binding is driven primarily by inhibition of specific GTPase-activating proteins (GAPs). In the case of Rag, the GAP is a protein complex called Gator1, which is anchored on the lysosome and is regulated by a series of inhibitory interactions: cytosolic amino acids bind receptor proteins, thereby removing their inhibitory effect on Gator2, which is then free to inhibit the GAP activity of Gator1—resulting in Rag activation and binding to mTORC1. The interaction of Rag with the lysosome depends on a large protein complex, the Ragulator, that serves as an activating GEF for Rag; this GEF activity is stimulated by amino acids in the lysosome, further promoting mTORC1 activation. On the left side of the diagram are the mechanisms leading to activation of the Rheb GTPase by growth factors. As described earlier in the chapter, activation of RTKs by growth factor binding initiates various signaling pathways, including activation of PI 3-kinase (see Figure 15–54) and the GTPase Ras (see Figure 15–48), resulting in activation of the protein kinases Akt and Erk, respectively. One target of these kinases is a trimeric protein complex called TSC, which is a GAP for Rheb. Its phosphorylation inhibits TSC, allowing Rheb-GTP to accumulate and stimulate mTORC1.],
    path: "../fig/image_place_holder.png"
  ),
  "15-56": (
    caption: [Five parallel intracellular signaling pathways activated by GPCRs, RTKs, or both. In this simplified example, the five kinases (shaded gray) at the end of each signaling pathway phosphorylate target proteins (shaded red), many of which are phosphorylated by more than one of the kinases. The phospholipase C activated by the two types of receptors is different: GPCRs activate PLCβ, whereas RTKs activate PLCγ (not shown). Although not shown, some GPCRs can also activate Ras, but they do so independently of Grb2, via a Ras GEF that is activated by Ca2+ and diacylglycerol.],
    path: "../fig/image_place_holder.png"
  ),
  "15-56": (
    caption: [illustrates both of these types of signaling overlaps: it summarizes five parallel intracellular signaling pathways that we have discussed so far—one triggered by GPCRs, two triggered by RTKs, and two triggered by both kinds of receptors. Interactions among these pathways allow different extracellular signal molecules to modulate and coordinate each other’s effects.],
    path: "../fig/image_place_holder.png"
  ),
  "15-57": (
    caption: [The JAK–STAT signaling pathway activated by cytokines. The binding of the cytokine either causes two separate receptor polypeptide chains to dimerize (as shown) or re-orients the receptor chains in a preformed dimer. In either case, the associated JAKs are brought together so that they can phosphorylate each other on tyrosines to become fully activated, after which they phosphorylate the receptors to generate binding sites for the SH2 domains of STAT proteins. The JAKs also phosphorylate the STAT proteins, which dissociate from the receptor to form dimers that enter the nucleus to control gene expression. P P P P],
    path: "../fig/image_place_holder.png"
  ),
  "15-6": (
    caption: [lists some of the more than 30 cytokines and hormones that activate the JAK–STAT pathway by binding to cytokine receptors.],
    path: "../fig/image_place_holder.png"
  ),
  "15-6": (
    caption: [Some Extracellular Signal Proteins That Act Through Cytokine Receptors and the JAK–STAT Signaling Pathway],
    path: "../fig/image_place_holder.png"
  ),
  "15-58": (
    caption: [The Smad-dependent signaling pathway activated by TGFb. The TGFβ dimer promotes the assembly of a tetrameric receptor complex containing two copies each of the type-I and type-II receptors. The type-II receptors phosphorylate specific sites on the type-I receptors, thereby activating their kinase domains and leading to phosphorylation of R-Smads such as Smad2 and Smad3. Smads open up to expose a binding surface when they are phosphorylated, leading to the formation of a trimeric Smad complex containing two R-Smads and the co-Smad, Smad4. The phosphorylated Smad complex enters the nucleus and collaborates with other transcription regulators to control the transcription of specific target genes.],
    path: "../fig/image_place_holder.png"
  ),
  "15-59": (
    caption: [Lateral inhibition mediated by Notch and Delta during neural cell development in Drosophila. When individual cells in the epithelium begin to develop as neural cells, they signal to their neighbors not to do the same. This inhibitory, contact-dependent signaling is mediated by the ligand Delta, which appears on the surface of the future neural cell and binds to Notch protein on the neighboring cells. In many tissues, all the cells in a cluster initially express both Delta and Notch, and a competition occurs, with one cell emerging as winner, expressing Delta strongly and inhibiting its neighbors from doing likewise. In other cases, additional factors interact with Delta or Notch to make some cells susceptible to the lateral inhibition signal and others unresponsive to it.],
    path: "../fig/image_place_holder.png"
  ),
  "15-60": (
    caption: [The processing and activation of Notch by proteolytic cleavage. The numbered red arrowheads indicate the sites of proteolytic cleavage. The first proteolytic processing step occurs within the trans Golgi network to generate mature heterodimeric Notch, which is then displayed on the cell surface. The binding to Delta on a neighboring cell triggers the next two proteolytic steps: the complex of Delta and the Notch fragment to which it is bound is endocytosed by the Delta-expressing cell, exposing the extracellular cleavage site in the transmembrane Notch subunit. Note that Notch and Delta interact through their repeated EGF-like domains. The released Notch tail migrates into the nucleus, where it binds to the Rbpsuh protein, which it converts from a transcription repressor to a transcription activator.],
    path: "../fig/image_place_holder.png"
  ),
  "15-61": (
    caption: [The Wnt/b-catenin signaling pathway. (A) In the absence of a Wnt signal, β-catenin that is not bound to cell–cell adherens junctions (not shown— discussed in Chapter 19) interacts with a degradation complex containing APC, axin, GSK3, and CK1. In this complex, β-catenin is phosphorylated by CK1 and then by GSK3, triggering its ubiquitylation and degradation in proteasomes. Wnt- responsive genes are kept inactive by the Groucho co-repressor protein bound to the transcription regulator LEF1/TCF. (B) Wnt binding to Frizzled and LRP brings the two co-receptors together, and the cytosolic tail of LRP is phosphorylated by CK1 and GSK3. The scaffold protein Dishevelled is recruited to the activated Frizzled protein. Axin binds to Dishevelled and the phosphorylated LRP and is inactivated, resulting in disassembly of the degradation complex. The phosphorylation of β-catenin is thereby prevented, and unphosphorylated β-catenin accumulates and translocates to the nucleus, where it binds to LEF1/TCF, displaces the co-repressor Groucho, and acts as a coactivator to stimulate the transcription of Wnt target genes. The scaffold protein Dishevelled is required for the signaling pathway to operate; it binds to Frizzled and becomes phosphorylated (not shown), but its precise role is unknown. (A)],
    path: "../fig/image_place_holder.png"
  ),
  "15-61": (
    caption: [is supplemented with additional regulatory inputs that fine-tune the strength of the Wnt signal. Some Wnt-stimulated genes, for example, suppress the Wnt signal, resulting in negative feedback. One of these genes encodes a secreted enzyme called Notum, which removes the fatty acid modification from Wnt, thereby inactivating it. Another Wnt-stimulated gene encodes a cell-surface transmembrane protein, Rnf43, which is a ubiquitin ligase that targets the Frizzled protein for degradation. This negative feedback mechanism can be suppressed by extracellular signaling mol- ecules from other cells: a signaling protein called R-spondin, for example, binds to a GPCR called Lgr, which inactivates Rnf43, thereby enhancing the Wnt signal. Through these and a variety of other mechanisms, the localization and strength of the Wnt signal can be fine-tuned in different tissues.],
    path: "../fig/image_place_holder.png"
  ),
  "15-62": (
    caption: [Vertebrate Hedgehog signaling in the primary cilium. (A) In the absence of Hedgehog, its receptor, Patched, is active in the cilium membrane and inhibits Smoothened, which is in the membrane adjacent to the cilium. Gli transcription regulators (primarily Gli2 and Gli3) are held in an inactive state by SuFu. In addition, an active GPCR (Gpr161) stimulates adenylyl cyclase, generating cyclic AMP that leads to PKA-dependent phosphorylation of the Gli3 protein. Phosphorylated Gli3 is processed to a transcription repressor, which accumulates in the nucleus to help keep Hedgehog target genes inactive. (B) Hedgehog binding to Patched removes the inhibition of Smoothened. Smoothened translocates to the cilium, where it triggers the dissociation of SuFu–Gli2 complexes and the conversion of Gli2 to an active transcription regulator; activated Gli2 is then transported to the cytoplasm, from where it moves to the nucleus to stimulate expression of Hedgehog- responsive genes. Hedgehog also promotes removal of Gpr161 from the cilium (not shown), thereby reducing the processing of Gli3 to a transcription repressor.],
    path: "../fig/image_place_holder.png"
  ),
  "15-63": (
    caption: [The activation of the NFkB pathway by TNFa. Both TNFα and its receptors are trimers. The binding of TNFα causes a rearrangement of the clustered cytosolic tails of the receptors, which now recruit various signaling proteins, resulting in the activation of a protein kinase that phosphorylates and activates IκB kinase kinase (IKK). IKK is a heterotrimer composed of two kinase subunits (IKKα and IKKβ) and a regulatory subunit called NEMO. IKKβ then phosphorylates IκB on two serines, which marks the protein for ubiquitylation and degradation in proteasomes. The released NFκB translocates into the nucleus, where, in collaboration with a coactivator protein, it stimulates the transcription of its target genes.],
    path: "../fig/image_place_holder.png"
  ),
  "15-64": (
    caption: [Negative feedback in the NFkB signaling pathway induces oscillations in NFkB activation. (A) Diagram showing how activated NFκB stimulates the transcription of the IkBa gene, the protein product of which acts back in the cytoplasm to sequester and inhibit NFκB there. If the stimulus is persistent, the newly made IκBα protein will then be ubiquitylated and degraded, liberating active NFκB again so that it can return to the nucleus and activate transcription (see Figure 15–63). (B) A short exposure to TNFα produces a single, short pulse of NFκB activation, beginning within minutes and ending by 1 hour. This response turns on the transcription of gene A but not gene B. (C) A sustained exposure to TNFα for the entire 6 hours of the experiment produces oscillations in NFκB activation that damp down over time. This response turns on the transcription of both genes A and B; gene B turns on only after several hours, indicating that gene B transcription requires prolonged activation of NFκB, for reasons that are not understood. (D) These time-lapse confocal fluorescence micrographs from a different study of TNFα stimulation show the oscillations of NFκB in a cultured cell, as indicated by the periodic movement into the nucleus (N) of a fusion protein composed of NFκB fused to a red fluorescent protein. In the cell at the center of the micrographs, NFκB is active and in the nucleus at 6, 60, 210, 380, and 480 minutes, but it is exclusively in the cytoplasm at 0, 120, 300, 410, and 510 minutes. (A–C, based on data from A. Hoffmann et al., Science 298:1241–1245, 2002, and adapted from A.Y. Ting and D. Endy, Science 298:1189–1190, 2002; D, from D.E. Nelson et al., Science 306: 704–708, 2004. All with permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-65": (
    caption: [Some extracellular signal molecules that bind to intracellular receptors. Note that all of them are small and hydrophobic. The active, hydroxylated form of vitamin D3 is shown. Estradiol and testosterone are steroid sex hormones.],
    path: "../fig/image_place_holder.png"
  ),
  "15-66": (
    caption: [The activation of nuclear receptors. All nuclear receptors bind to DNA as either homodimers or heterodimers, but for simplicity we show them as monomers. (A) The receptors all have a related structure, which includes three major domains. An inactive receptor is bound to inhibitory proteins. (B) Typically, the binding of ligand to the receptor causes the ligand-binding domain of the receptor to clamp shut around the ligand, the inhibitory proteins to dissociate, and coactivator proteins to bind to the receptor’s transcription-activating domain, thereby increasing gene transcription. In other cases, ligand binding has the opposite effect, causing co-repressor proteins to bind to the receptor, thereby decreasing transcription (not shown). (C) The structure of the ligand-binding domain of the retinoic acid receptor is shown in the absence (left) and presence (middle) of ligand (shown in red). When ligand binds, the blue α helix acts as a lid that snaps shut, trapping the ligand in place. The shift in the conformation of the receptor upon ligand binding also creates a binding site for a small α helix (orange) on the surface of coactivator proteins. (PDB codes: 6HN6, 2ZY0, and 2ZXZ.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-67": (
    caption: [Simplified outline of the mechanism of the circadian clock in Drosophila cells. A central feature of the clock is the periodic accumulation and decay of two transcription regulatory proteins, Tim (short for timeless, based on the phenotype when its gene is inactivated) and Per (short for period). The levels of mRNAs encoding these proteins increase gradually during the day and are translated in the cytoplasm, where the two proteins slowly associate to form a Tim–Per heterodimer. The heterodimer is transported into the nucleus, where it represses the Tim and Per genes, resulting in negative feedback that causes the levels of Tim and Per proteins to fall during the night. Decreased Per and Tim levels remove the negative feedback, allowing renewed expression of Tim and Per genes the following day. In addition to this transcriptional feedback, the clock depends on numerous other proteins that influence the period of the circadian oscillator through post-translational modifications. For example, a protein kinase called Doubletime (DBT) promotes the degradation of Per in the cytoplasm, thereby delaying the formation of the Tim–Per dimer. Once formed, the nuclear import of the dimer depends on phosphorylation and glycosylation of one or both proteins, introducing additional delays that further influence the timing of the clock.],
    path: "../fig/image_place_holder.png"
  ),
  "15-68": (
    caption: [The core circadian oscillator of cyanobacteria. (A) KaiC protein (C, blue) is a combined kinase and phosphatase that phosphorylates and dephosphorylates itself on two adjacent sites. In the absence of other proteins, the phosphatase activity is dominant, and the protein is mostly unphosphorylated. During the day, the binding of KaiA (A, green) to KaiC suppresses the phosphatase activity and promotes the kinase activity, leading to KaiC phosphorylation, first at site 1 and then, slowly, at site 2, resulting in diphosphorylated KaiC. This form of KaiC interacts with KaiB (B, orange), which blocks the stimulatory effects of KaiA, thereby reducing the rate of KaiC phosphorylation and allowing dephosphorylation at both sites to occur by the end of the night. KaiB then dissociates, allowing KaiA to promote KaiC phosphorylation again. Diphosphorylated KaiC increases in abundance during the day and peaks around dusk. It activates other proteins that phosphorylate a transcription regulator called RpaA (dark green), which then stimulates expression of certain genes that peak in early evening (the dusk genes) and inhibits expression of other genes that peak in the morning (the dawn genes). When KaiC dephosphorylation gradually occurs during the night, these effects are reversed: dusk genes are turned off and dawn genes are turned on. (B) In this experiment, the three Kai proteins were purified and mixed in a test tube with ATP (which is required for KaiC kinase activity). Every 2 hours over the next 3 days, the KaiC protein was analyzed by polyacrylamide-gel electrophoresis, in which the phosphorylated form of KaiC migrates more slowly (upper band, P-KaiC) than the nonphosphorylated form (lower band, NP-KaiC). The three different phosphorylated forms of KaiC are not distinguished by this method. The phosphorylation of KaiC oscillates with a roughly 24-hour period. (C) The amount of phosphorylated and unphosphorylated KaiC in the experiment in B is plotted on this graph, along with the amount of total protein. (B and C, from M. Nakajima et al., Science 308:414–415, 2005. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-69": (
    caption: [The proposed divergence of plant and animal lineages from a common unicellular eukaryotic ancestor. The plant lineage acquired chloroplasts after the two lineages diverged. Both lineages independently gave rise to multicellular organisms—plants and animals. (Paintings courtesy of John Innes Foundation.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-70": (
    caption: [The ethylene-mediated triple response that occurs when the growing shoot of a germinating seedling encounters an obstacle underground. (A) The structure of ethylene. (B) In the absence of obstacles, the shoot grows upward and is long and thin. (C) If the shoot encounters an obstacle, such as a piece of gravel in the soil, the seedling responds to the encounter in three ways. First, it thickens its stem, which can then exert more force on the obstacle. Second, MBoC7 m15.69/15.70 it shields the tip of the shoot (at top) by increasing the curvature of a specialized hook structure. Third, it reduces the shoot’s tendency to grow away from the direction of gravity, so as to avoid the obstacle. (Courtesy of Melanie Webb.) 942],
    path: "../fig/image_place_holder.png"
  ),
  "15-71": (
    caption: [The ethylene signaling pathway. (A) In the absence of ethylene, the receptors and CTR1 are active, causing the ubiquitylation and destruction of EIN3, the transcription regulatory protein in the nucleus that is responsible for the transcription of ethylene-responsive genes. (B) The binding of ethylene inactivates the receptors and disrupts the activation of CTR1. The EIN3 protein is not degraded and can therefore activate the transcription of ethylene-responsive genes.],
    path: "../fig/image_place_holder.png"
  ),
  "15-72": (
    caption: [The auxin signaling pathway. (A) The structure of auxin (indole-3-acetic acid). (B) In the absence of auxin, a transcription repressor protein (called Aux/IAA) binds and suppresses a transcription regulator (called auxin- response factor; ARF), which is required for the transcription of auxin-responsive genes. (C) The auxin receptor proteins are located mainly in the nucleus. When activated by auxin binding, the receptor– auxin complex recruits a ubiquitin ligase, which ubiquitylates the Aux/IAA protein, marking it for degradation in proteasomes. ARF is now free to activate the transcription of auxin-responsive genes. There are many ARFs, Aux/IAA proteins, and auxin receptors that work as illustrated.],
    path: "../fig/image_place_holder.png"
  ),
  "15-73": (
    caption: [Auxin transport and root gravitropism. (A–C) Roots respond to a 90° change in the gravity vector and adjust their direction of growth so that they grow downward again. The cells that respond to gravity are in the center of the root cap, while it is the epidermal cells further back (on the lower side) that decrease their rate of elongation to restore downward growth. (D) The gravity-responsive cells in the root cap redistribute their auxin efflux transporters in response to the displacement of the root. This redirects the auxin flux mainly to the lower part of the displaced root, where it inhibits the elongation of the epidermal cells. The resulting asymmetrical distribution of auxin in the Arabidopsis root tip shown here is assessed indirectly, using an auxin-responsive reporter gene that encodes a protein fused to green fluorescent protein (GFP); the epidermal cells on the downward side of the root are green, whereas those on the upper side are not, reflecting the asymmetrical distribution of auxin. The distribution of auxin efflux transporters in the plasma membrane of cells in different regions of the root (shown as gray rectangles) is indicated in red, and the direction of auxin efflux is indicated by a green arrow. (D, photograph from T. Paciorek MBoC7 m15.72/15.73 et al., Nature 435:1251–1256, published 2005 by Nature Publishing Group. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "15-74": (
    caption: [One way in which phytochromes mediate a light response in plant cells. When activated by red light, the phytochrome, which is a dimeric protein kinase, phosphorylates itself and then moves into the nucleus, where it activates transcription regulatory proteins to stimulate the transcription of red-light- responsive genes.],
    path: "../fig/image_place_holder.png"
  ),
)