#let images = (
  "9-1": (
    caption: [A sense of scale between living cells and atoms. (A) Each diagram shows an image magnified by a factor of 10 in an imaginary progression from a thumb, through skin cells, to a ribosome, to a cluster of atoms forming part of one of the many protein molecules in the ribosome. Atomic details of biological macromolecules, as shown in the last two panels, are just within the power of the electron microscope. While color has been used here in all the panels, it is not a feature of objects much smaller than the wavelength of light, so the last five panels should really be in black and white. (B) Sizes of cells and their components are shown on a logarithmic scale, indicating the range of objects that can readily be resolved by the naked eye and in the light and electron microscopes. Note that new superresolution microscopy techniques, discussed in detail later, allow an improvement in resolution by an order of magnitude compared with conventional light microscopy.],
    path: "../fig/image_place_holder.png"
  ),
  "9-2": (
    caption: [A light microscope. (A) Diagram showing the light path in an upright compound microscope. Light is focused on the specimen by lenses in the condenser. A combination of objective lenses, tube lenses, and eyepiece lenses is arranged to focus an image of the illuminated specimen in the eye. (B) A modern upright research light microscope. (C) A modern inverted microscope, particularly useful for looking at cells in culture. Both microscopes are equipped for fluorescence imaging (B and C, courtesy of Carl Zeiss Microscopy, GmbH.) (A)],
    path: "../fig/image_place_holder.png"
  ),
  "9-3": (
    caption: [Interference between light waves. When two light waves combine in phase, the amplitude of the resultant wave is larger, and the brightness is increased. Two light waves that are out of phase cancel each other partly and produce a wave whose amplitude, and therefore brightness, is decreased.],
    path: "../fig/image_place_holder.png"
  ),
  "9-4": (
    caption: [Images of an edge and of a point of light. (A) The interference effects, or fringes, seen at high magnification when light of a specific wavelength passes the edge of a solid object placed between the light source and the observer. (B) The image of a point source of light. Diffraction spreads this out into a complex, circular pattern, whose width depends on the numerical aperture of the optical system: the smaller the aperture, the bigger (more blurred) the diffracted image. Two point sources can be just resolved when the center of the image of one lies within the first dark ring in the image of the other: this is used to define the limit of resolution.],
    path: "../fig/image_place_holder.png"
  ),
  "9-5": (
    caption: [Basic principles of light microscopy. The path of light rays passing through a transparent specimen in a microscope illustrates the concept of numerical aperture and its relation to the limit of resolution. The higher the numerical aperture of a lens, the brighter the image it forms and the higher its resolution.],
    path: "../fig/image_place_holder.png"
  ),
  "9-6": (
    caption: [Contrast in light microscopy. (A) The stained portion of the cell will absorb light of some wavelengths, which depends on the stain, but will allow other wavelengths to pass through it. A colored image of the cell is thereby obtained that is visible in the normal bright-field light microscope. (B) In the dark-field microscope, oblique rays of light focused on the specimen do not enter the objective lens, but light that is scattered by components in the living cell can be collected to produce a bright image on a dark background. (C) Light passing through the unstained living cell experiences very little change in amplitude, and the structural details cannot be seen even if the image is highly magnified. The phase of the light, however, is altered by its passage through either thicker or denser parts of the cell, and small phase differences can be made visible by exploiting interference effects using a phase-contrast or a differential- interference-contrast microscope.],
    path: "../fig/image_place_holder.png"
  ),
  "9-7": (
    caption: [compares images of the same cell obtained by four kinds of light microscopy.],
    path: "../fig/image_place_holder.png"
  ),
  "9-7": (
    caption: [Four types of light microscopy. Four images are shown of the same fibroblast cell in culture. All images can be obtained with most modern microscopes by interchanging optical components. (A) Bright-field microscopy, in which light is transmitted straight through the specimen. (B) Phase-contrast microscopy, in which phase alterations of light transmitted through the specimen are translated into brightness changes. (C) Differential-interference-contrast microscopy, which highlights edges where there is a steep change of refractive index. (D) Dark-field microscopy, in which the specimen is lit from the side and only the scattered light is seen.],
    path: "../fig/image_place_holder.png"
  ),
  "9-8": (
    caption: [Making tissue sections. This illustration shows how an embedded tissue is sectioned with a microtome in preparation for examination in the light microscope. Very rapidly frozen samples can also be sectioned, and these better preserve the structure of cells in their native state.],
    path: "../fig/image_place_holder.png"
  ),
  "9-9": (
    caption: [Staining of cell components. (A) This section of cells in a salivary gland was stained with hematoxylin and eosin, two dyes commonly used in histology. The central duct is made of closely packed cells with nuclei stained purple and cytoplasm stained red. The duct is surrounded by groups of saliva-secreting cells. (B) This section of a young plant root is stained with two dyes, safranin and fast green. Fast green stains the cellulosic cell walls, while the safranin stains the lignified xylem cell walls red. (A, from R.L. Sorenson and T.C. Brelje, Atlas of Human Histology: A Guide to Microscopic Structure of Cells, Tissues and Organs, 3rd ed., 2014. With permission from the authors; B, courtesy of University of Wisconsin Plant Teaching Collection.) (A) 50 µm (B) 100 µm],
    path: "../fig/image_place_holder.png"
  ),
  "9-10": (
    caption: [Fluorescence and the fluorescence microscope. (A) An orbital electron of a fluorochrome molecule can be raised to an excited state after the absorption of a photon. Fluorescence occurs when the electron returns to its ground state and emits a photon of light at a longer wavelength. Too much exposure to light or too bright a light can destroy the fluorochrome molecule in a process called photobleaching. (B) The excitation and emission spectra for the common fluorescent dye fluorescein isothiocyanate (FITC). (C) In the fluorescence microscope, a filter set consists of two barrier filters (1 and 3) and a dichroic (beam-splitting) mirror (2). This example shows the filter set for detection of the fluorescent molecule fluorescein. High-numerical-aperture objective lenses are especially important in this type of microscopy because, for a given magnification, the brightness of the fluorescent image is proportional to the fourth power of the numerical aperture (see also Figure 9–5).],
    path: "../fig/image_place_holder.png"
  ),
  "9-11": (
    caption: [RNA in situ hybridization. (A) As described in Chapter 8 (see Figure 8–63), it is possible to visualize the distribution of different RNAs in tissues using in situ hybridization. Here, the transcription pattern of five different genes involved in patterning the early fruit fly embryo is revealed in a single embryo. Each RNA probe has been fluorescently labeled, and the resulting images are displayed each in a different color (“false-colored”) and then combined to give an image where different color combinations represent different sets of genes expressed. The genes whose expression pattern is revealed here are wingless (yellow), engrailed (blue), short gastrulation (red), intermediate neuroblasts defective (green), and muscle specific homeobox (purple). (B) Individual RNA transcripts can be detected in a single cell. Each of these six yeast cells is expressing less than 20 transcripts of a particular gene. Using multiple DNA oligonucleotide probes to that particular gene, each labeled with many fluorescent Cy5 molecules, each individual RNA transcript can be detected as a red spot. \[A, from D. Kosman et al., Science 305:846, 2004. With permission from AAAS; B, from G.M. Wadsworth, R.Y. Parikh, and H.D. Kim, Single-probe RNA FISH in yeast. Bio Protoc. 8(11):e2868, 2018, doi 10.21769/BioProtoc.2868.\]],
    path: "../fig/image_place_holder.png"
  ),
  "9-12": (
    caption: [Fluorescent probes. The maximum excitation and emission wavelengths of several commonly used fluorescent probes are shown in relation to the corresponding colors of the spectrum. The photon emitted by a fluorescent molecule is necessarily of lower energy (longer wavelength) than the absorbed photon, and this accounts for the difference between the excitation and emission peaks. CFP, GFP, YFP, and RFP are cyan, green, yellow, and red fluorescent proteins, respectively. DAPI is widely used as a general fluorescent DNA probe, which absorbs ultraviolet light and fluoresces bright blue. FITC is an abbreviation for fluorescein isothiocyanate—a widely used derivative of fluorescein—which fluoresces bright green. The other probes are all commonly used to fluorescently label antibodies and other proteins. Note that although the true fluorescence emission colors are shown here, the actual color seen in the microscope will depend on the second barrier filter used (see Figure 9–10), and these are usually optimized so as to allow as many different non-overlapping colored probes to be seen in the same specimen. Thus although YFP emits in the green spectrum, it actually appears as a yellow-green in the microscope because of the filter used. The use of fluorescent proteins will be discussed later in the chapter.],
    path: "../fig/image_place_holder.png"
  ),
  "9-13": (
    caption: [Different fluorescent probes can be visualized in the same cell. In this composite micrograph of an epithelial cell in culture, three different fluorescent probes have been used to label three different cellular components. The actin filaments of the cytoskeleton are revealed with a green fluorescent probe, the numerous mitochondria with a red fluorescent dye that accumulates inside the organelles, and the nucleus with a blue fluorescent dye that binds to DNA. (Courtesy of Carl Zeiss Microscopy, GmbH.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-14": (
    caption: [Immunofluorescence. (A) A transmission electron micrograph of the periphery of a cultured epithelial cell showing the distribution of microtubules and other filaments. (B) The same area stained with fluorescent antibodies against tubulin, the protein that assembles to form microtubules, using the technique of indirect immunocytochemistry (see Figure 9–15). Red arrows indicate individual microtubules that are readily recognizable in both images. Note that, because of diffraction effects, the microtubules in the light microscope appear 0.2 μm wide rather than their true width of 0.025 μm. (© 1978 M. Osborn et al. Originally published in J. Cell Biol. doi 10.1083/jcb.77.3.R27. With permission from Rockefeller University Press.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-15": (
    caption: [Indirect immunocytochemistry. This detection method is very sensitive because many molecules of the secondary antibody recognize each primary antibody. The secondary antibody is covalently coupled to a marker molecule that makes it readily detectable. Commonly used marker molecules include fluorescent dyes (for fluorescence microscopy) and colloidal gold spheres (for electron microscopy).],
    path: "../fig/image_place_holder.png"
  ),
  "9-16": (
    caption: [Green fluorescent protein (GFP). (A) The structure of GFP, shown here schematically, highlights the eleven β strands that form the staves of a barrel, buried within which is the active chromophore (dark green). (B) The chromophore is formed post-translationally from the protruding side chains of two amino acid residues in a series of autocatalytic steps. (A, PDB code: 1EMA, from M. Ormö et al., Science 273:1392– 1395, 1996. With permission from AAAS.) (A) N (B) O],
    path: "../fig/image_place_holder.png"
  ),
  "9-17": (
    caption: [Fluorescent proteins as reporter molecules. (A) For this experiment, carried out in the fruit fly, the GFP gene was joined (using recombinant DNA techniques) to a fly promoter that is active only in a specialized set of neurons. This image of a live fly embryo was captured by a fluorescence microscope and shows approximately 20 neurons, each with long projections (axons and dendrites) that communicate with other (nonfluorescent) cells. These neurons are located just under the surface of the animal and allow it to sense its immediate environment. (B) In a variation of this method, three different fluorescent proteins, red, yellow, and cyan, can be expressed at random in neurons of the live fly embryo. The genetic constructs have been arranged such that a strong pulse of blue light will activate the expression of one or other of the three fluorescent proteins at random in neuronal cells, where they are then targeted to the plasma membrane. This noninvasive control of the timing of cell labeling allows the behavior of individual MBoC7 m9.23/9.17 cells to be followed subsequently over time. The fine detail of all the dendrites of individual sensory neurons can be clearly seen. The lines of pale dots arise from the autofluorescence of the bands of denticles in the cuticle that define the segments of the embryo (see Figure 21–24). (A, from W.B. Grueber et al., Curr. Biol. 13:618–626, 2003. With permission from Elsevier; B, from M. Boulina et al., Development 140:1605–1613, 2013, doi 10.1242/dev.088930. © 2013. Published by the Company of Biologists Ltd.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-18": (
    caption: [GFP-tagged proteins. This cultured mammalian cell is expressing EB3, a plus-end tracking protein that is fused to a GFP-derived blue fluorescent protein (BFP). These proteins associate with MBoC7 n9.123/9.18 the plus ends of growing microtubules (see Figure 16–49), and their dynamics can be followed as they appear to zoom brightly around the cell. (Courtesy of Carl Zeiss Microscopy, GmbH.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-19": (
    caption: [Fluorescence resonance energy transfer (FRET). To determine whether (and when) two proteins interact inside a cell, the proteins are first produced as fusion proteins attached to different color variants of green fluorescent protein (GFP). (A) In this example, protein X is coupled to a blue fluorescent protein, which is excited by violet light and emits blue light; protein Y is coupled to a green fluorescent protein, which is excited by blue light and emits green light. (B) If protein X and Y do not interact, illuminating the sample with violet light yields fluorescence only from the blue fluorescent protein. (C) When protein X and protein Y interact, the resonance transfer of energy, FRET, can now occur. Illuminating the sample with violet light excites the blue fluorescent protein, which transfers its energy to the green fluorescent protein, resulting in an emission of green light. The fluorochromes must be quite close together—within about 1–5 nm of one another—for FRET to occur. Because not every molecule of protein X and protein Y is bound at all times, some blue light may still be detected. But as the two proteins begin to interact, emission from the donor blue fluorescent protein falls as the emission from the acceptor GFP rises.],
    path: "../fig/image_place_holder.png"
  ),
  "9-20": (
    caption: [Fluorescence recovery after photobleaching (FRAP). A strong focused pulse of laser light will extinguish, or bleach, fluorescent proteins. By selectively photobleaching a set of fluorescently tagged protein molecules within a defined region of a cell, the microscopist can monitor recovery over time, as the remaining fluorescent molecules move into the bleached region (see Movie 10.6). (A) This cultured mammalian cell is expressing an integral membrane protein called CD86, which is fused with a fluorescent protein. CD86 is a co-stimulatory protein present in the plasma membrane of antigen-presenting cells and is required for the activation of T cells (see Figure 24–34). After a small region of the plasma membrane is selectively photobleached, the remaining fluorescent molecules diffuse rapidly within the plane of the membrane and populate MBoC7 n9.121/9.20 the bleached region. This recovery can be followed as a function of time. (B) Schematic diagram of the experiment shown in A. (C) Measurements of the fluorescence intensity in the bleached area as a function of time can be plotted as a fluorescence recovery curve. From such graphs quantitative data can be derived about the rate of recovery and the fraction of fluorescent protein molecules that are either mobile or immobile. (A, from S. Dorsch et al., Nat. Methods 6:225–230, 2009.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-21": (
    caption: [Visualizing intracellular Ca21 concentrations by using a fluorescent indicator. The branching tree of dendrites of a Purkinje cell in the cerebellum receives more than 100,000 synapses from other neurons. The output from the cell is conveyed along the single axon seen leaving the cell body at the bottom of the picture. This image of the intracellular Ca2+ concentration in a single Purkinje cell (from the brain of a guinea pig) was taken with a low-light camera and the Ca2+-sensitive fluorescent indicator fura-2. The concentration of free Ca2+ is represented by different colors, red being the highest and blue the lowest. The highest Ca2+ levels are present in the thousands of dendritic branches. (Courtesy of D.W. Tank, J.A. Connor, M. Sugimori, and R.R. Llinas.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-22": (
    caption: [Genetically encoded fluorescent biosensors. (A) Here we show one strategy for constructing a fluorescent biosensor for calcium ions. A sensor, in this case calmodulin (see Figure 15–34), undergoes a large conformational change on binding Ca2+. This change brings together the blue and yellow fluorescent proteins to which each end of the sensor is attached, close enough to undergo Förster resonance energy transfer (FRET) and to change the wavelength of the fluorescence emission to yellow in response to a violet excitation light. By measuring the ratio of fluorescence intensity at two wavelengths, blue and yellow, we can determine the concentration ratio of the Ca2+-bound indicator to the Ca2+-free indicator, thereby providing an accurate measurement of the free Ca2+ concentration. (B) This panel illustrates a similar strategy used to construct a biosensor for cAMP. In this case the sensor is a cAMP-regulated guanine nucleotide exchange factor, which again undergoes a large conformational change, enough to move the two attached fluorescent proteins farther apart, thus abolishing their FRET. Hence the emitted light is switched from yellow to blue. (C) A calcium biosensor, similar to that shown in A, is genetically encoded and expressed in an Arabidopsis seedling. When a cell in the epidermis, on the side of the shoot apical meristem, is pricked with a small glass needle, calcium enters the cell from the extracellular environment, and this response is rapidly propagated as a wave of calcium entering cells across the entire surface of the meristem. Mechanical signals help pattern plant morphogenesis, and transient calcium responses affect cell polarity. (C, from T. Li et al., Nat. Commun. 10:726–735, 2019. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-23": (
    caption: [Image deconvolution. (A) A light micrograph of a Caenorhabditis elegans embryo, fluorescently labeled for microtubules (green), mitochondria (red), and DNA (blue). Detail at any one level of focus is blurred by light from out-of-focus levels of the specimen. (B) After deconvolution of the three-dimensional stack of images, an optical section at the same level of focus shows a much crisper image with more contrast and much reduced blurring. (A and B, from D. Sage et al., Methods 115:28–41, 2017, doi 10.1016/j.ymeth.2016.12.015. With permission from Elsevier.) MBoC7 n9.122/9.23],
    path: "../fig/image_place_holder.png"
  ),
  "9-24": (
    caption: [The confocal fluorescence microscope. (A) This simplified diagram shows that the basic arrangement of optical components is similar to that of the standard fluorescence microscope shown in Figure 9–10C, except that a laser is used to illuminate a small pinhole whose image is focused at a single point in the three- dimensional (3D) specimen. (B) Emitted fluorescence from this focal point in the specimen is focused at a second (confocal) pinhole. (C) Emitted light from elsewhere in the specimen is not focused at the pinhole and therefore does not contribute to the final image. By scanning the beam of light across the specimen, a very sharp two-dimensional image of the exact plane of focus is built up that is not significantly degraded by light from other regions of the specimen. (D) Commercial versions of laser scanning confocal microscopes can be configured for both upright and inverted microscopes. Shown here is a standard upright confocal microscope. (D, courtesy of Andrew Davis.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-25": (
    caption: [Confocal fluorescence microscopy produces clear optical sections and three-dimensional data sets. (A) The elaborate cup-shaped trap of the carnivorous water plant, Utricularia gibba. A stack of 452 separate confocal images using a fluorescent label for the cell walls was assembled to produce the image. (B) A reconstruction of an object can be assembled from a stack of optical sections. In this case, and at a vastly different scale, the complex branching structure of the mitochondrial compartment in a single live yeast cell is shown. (A, courtesy of Karen Lee, Claire Bushell, and Enrico Coen; B, courtesy of Stefan Hell.) (A) (B) 50 µm 2 µm],
    path: "../fig/image_place_holder.png"
  ),
  "9-26": (
    caption: [Multiphoton imaging. Infrared laser light causes less damage to living cells than does visible light and can also penetrate farther, allowing microscopists to peer deeper into living tissues. The two-photon effect, in which a fluorochrome can be excited by two coincident infrared photons instead of a single high-energy photon, allows us to see nearly 0.5 mm inside the cortex of a live mouse brain. A dye, whose fluorescence changes with the calcium concentration, reveals active synapses (yellow) on the dendritic spines (red) that change as a function of time; in this case, there is a day between each image. (Courtesy of Thomas Oertner and Karel Svoboda.) 580],
    path: "../fig/image_place_holder.png"
  ),
  "9-27": (
    caption: [Structured illumination microscopy. The principle, illustrated here, is to illuminate a sample with patterned light and measure the moiré pattern. Shown are (A) the pattern from an unknown structure and (B) a defined grid pattern. (C) When these are combined, the resulting moiré pattern contains more information than is easily seen in A, the original pattern. If the known pattern (B) has higher spatial frequencies, then better resolution will result. However, because the spatial patterns that can be created optically are also diffraction-limited, SIM can only improve the resolution by about a factor of 2. (From B.O. Leung and K.C. Chou, Appl. Spectrosc. 65:967–980, 2011. With permission from SAGE.) (A) (B) (C)],
    path: "../fig/image_place_holder.png"
  ),
  "9-28": (
    caption: [Structured illumination microscopy can be used to create three-dimensional data. These three- dimensional projections of the meiotic chromosomes at pachytene in a maize cell show the paired lateral elements of the synaptonemal complexes. (A) The chromosome set has been stained with a fluorescent antibody to cohesin and is viewed here by conventional fluorescence microscopy. Because the distance between the two lateral elements is about 200 nm, the diffraction limit, the two lateral elements that make up each complex are not resolved. (B) In the three-dimensional SIM image, the improved resolution enables each lateral element, about 100 nm across, to be clearly resolved, and the two chromosomes of each separate pair can be seen to coil around each other. (C) Because the complete three-dimensional data set for the whole nucleus is available, the path of each separate pair of chromosomes can be traced and artificially assigned a different color. (Courtesy of C.J. Rachel Wang, Peter Carlton, and Zacheus Cande.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-29": (
    caption: [The point spread function of a lens determines resolution. (A) When a point source of light is brought to a focus by a lens system, diffraction effects mean that, instead of being imaged as a point, it is blurred in all dimensions. As shown, the point spread function is elongated, meaning that the resolution is better in the XY axes than along the Z axis. (B) In the plane of the image, the distribution of light approximates a Gaussian distribution, whose width at half-maximum height under ideal conditions is about 200 nm. (C) Two separate point sources that are about 200 nm apart can still just be distinguished as separate objects in the image, but if they are any nearer than that, their images will overlap and not be resolvable.],
    path: "../fig/image_place_holder.png"
  ),
  "9-30": (
    caption: [Superresolution microscopy can be achieved by reducing the size of the point spread function. (A) The size of a normal focused beam of excitatory light. (B) An extremely strong superimposed laser beam, at a different wavelength and in the shape of a torus, or doughnut, depletes emitted fluorescence everywhere in the specimen except right in the center of the beam, reducing the effective width of the point spread function (C). As the specimen is scanned, this small point spread function can then build up a crisp image in a process called STED (stimulated emission depletion) microscopy. (D) Here, STED microscopy is used to examine the structure of the nuclear pore. Fixed samples of the nuclear envelope have been stained by indirect immunofluorescence, using antibodies to different nuclear pore components. Membrane ring proteins (see Figure 12–55) have been stained red while the FC repeat proteins that form fibrils in the center of the pore are stained green. (E) An enlargement of the boxed region shows the clear eightfold symmetry of the membrane ring proteins and the central fibrillar region with a resolution of about 20 nm. \[A, B, and C, from G. Donnert et al., Proc. Natl. Acad. Sci. USA 103: 11440–11445, 2006. Copyright 2006 National Academy of Sciences. With permission from National Academy of Sciences; D and E, from F. Gottfert et al., Biophysical Journal 105(1):PL01–L03, 2013. With permission from Elsevier.\] 500 nm 150 nm],
    path: "../fig/image_place_holder.png"
  ),
  "9-31": (
    caption: [Single fluorescent molecules can be located with great accuracy. Determination of the exact mathematical center of the blurred image of a single fluorescent molecule becomes more accurate as more photons contribute to the final image. The point spread function described in the text dictates that the size of the molecular image is about 200 nm across, but in very bright specimens, the position of its center can be pinpointed to within a nanometer or so. (From A.L. McEvoy et al., BMC Biol. 8:106, 2010. With permission of the authors.) 200 nm],
    path: "../fig/image_place_holder.png"
  ),
  "9-32": (
    caption: [Single-molecule localization microscopy (SMLM). (A) In this imaginary specimen, sparse subsets of fluorescent molecules are individually switched on briefly and then bleached. The exact positions of all these well-spaced molecules can be gradually added together and built up into an image at superresolution. (B) In this portion of a cell, the microtubules have been fluorescently labeled and imaged (left) in a TIRF microscope (see Figure 9–38) and (right) at superresolution in a PALM microscope. The diameter of each microtubule on the right now resembles its true size, about 25 nm, rather than the 250 nm for each microtubule in the blurred diffraction-limited image on the left. (B, courtesy of Shinsuke Niwa.) (A) (B) 1 µm],
    path: "../fig/image_place_holder.png"
  ),
  "9-33": (
    caption: [Multiple structures that are below the diffraction-limited resolution can be imaged by single-molecule localization microscopy. (A) Two recently divided Escherichia coli cells imaged in a STORM microscope with a resolution of about 20 nm. The cells are stained with three separate switchable fluorescent labels: the membrane is labeled green, the recently segregated DNA molecules are blue, and the ends of the two replicated chromosomes are seen as two bright white dots. (B) In this nerve cell, evenly spaced ring-like structures of actin (red) are wrapped around the circumference of the axon with a periodicity of about 190 nm, just smaller than the diffraction limit to resolution. In between are similarly spaced structures of spectrin (blue). This periodic actin–spectrin cytoskeletal framework helps support the long thin axons of nerve cells. Such images depend heavily on the development of new, very fast-switching, and extremely bright fluorescent probes. (A, from C.K. Spahn et al., Sci. Rep. 8:14768, 2018, doi.org/10.1038/s41598- 018-33052-3; B, from K. Xu et al., Science 339:452–456, 2013, doi 10.1126/science.1232251.) (A) (B) 1 µm 1 µm],
    path: "../fig/image_place_holder.png"
  ),
  "9-34": (
    caption: [Expansion microscopy. (A) Although the technique has numerous variations, the essential features are that the fluorescently labeled sample is embedded in a polymer gel to which the fluorescent labels are covalently attached. After a proteinase digestion step, the gel is immersed in water and everything in the sample expands equally in every direction, usually by between 4 and 10 times, thus allowing details to be seen far more easily. (B) A peroxisome, whose membrane has been labeled with a fluorescent probe, appears in a confocal microscope as a blurred, diffraction-limited disc. (C) After expansion by a factor of 10, the image is captured with a standard epifluorescence microscope and, after deconvolution, shows the peroxisomal membrane well resolved and with a resolution of 25 nm. (From S. Truckenbrodt et al., EMBO Rep. 19:e45836, 2018, doi 10.15252/embr.201845836.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-35": (
    caption: [Expansion microscopy. (A and B) Two orthogonal views of the same cultured human nasal epithelial cells that have been stained with a fluorescent dye, expanded by ten times, and then imaged by conventional confocal microscopy. The hollow centers of ciliary basal bodies, which are not resolvable by conventional microscopy, are clearly visible in both top view (A) and side view (B) (red arrows) (see Movie 9.1). (C and D) A segment of mouse brain lateral hypothalamus, 800 × 800 × 300 μm, that has been expanded by a factor of 2, probed by sequential rounds of in situ RNA hybridization, and imaged by light- sheet microscopy. The cellular expression patterns of six different genes are shown: Gad1 (red), Slc17a6 (green), Hcrt (blue), Trh (yellow), Calb2 (magenta), and Meis2 (cyan). (A and B, courtesy of Hugo Damstra, Lukas Kapitein, and Paul Tillberg; C and D, courtesy of Yuhan Wang, Mark Eddison, Scott Sternson, and Paul Tillberg.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-36": (
    caption: [Light-sheet microscopy. A simple diagram showing how a very thin sheet of light that is projected (usually from a special cylindrical microscope objective lens) through a large specimen excites only those fluorescent labels in the thin plane that is illuminated. The resulting fluorescence is observed by an objective lens that is placed perpendicular to the light sheet. This means that, by progressively moving the specimen stage, multiple, sequential, and very sharp optical sections can be obtained rapidly and then digitally combined into a three-dimensional image.],
    path: "../fig/image_place_holder.png"
  ),
  "9-37": (
    caption: [Light-sheet microscopy in the brain. A 1-mm-thick portion of a mouse brain has been prepared for expansion microscopy and then imaged with a light-sheet microscope. Reconstructions of thousands of optical sections allow the tracing of individual neurons and all their connections, such as this pyramidal neuron (left) from the visual cortex. On the right is shown the complex cellular context (green) for a short region of one of the neuron’s basal dendrites (orange dendrite with its spines shown in yellow). (From R. Gao et al., Science 363:245–261, 2019, doi 10.1126/science.aau8302. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-38": (
    caption: [TIRF microscopy allows the detection of single fluorescent molecules near the cell surface. (A) TIRF microscopy uses excitatory laser light to illuminate the cover-slip surface at the critical angle at which all the light is reflected by the glass–water interface. Some electromagnetic energy extends a short distance across the interface as an evanescent wave that excites just those molecules that are attached to the cover slip or are very close to its surface. (B) TIRF microscopy is used to follow the formation of an individual clathrin-coated pit and its subsequent endocytosis. In this image of the surface of the plasma membrane of an Arabidopsis root cell, a clathrin adaptor protein is tagged with GFP. Individual pits can be followed over time. (C) The pit ringed in B is shown at 1-second intervals, demonstrating that its appearance and its removal at the plasma membrane by endocytosis takes place in about 10 seconds. (B and C, from A. Johnson and G. Vert, Front. Plant Sci. 8:612, 2017, doi 10.3389 /fpls.2017.00612.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-37": (
    caption: [and Movie 9.1). Light-sheet microscopy can also be combined with other techniques. Coupled with STED imaging, for example, superresolution is attainable, and higher-resolution images can also be obtained by preparing the sample for expansion microscopy.],
    path: "../fig/image_place_holder.png"
  ),
  "9-39": (
    caption: [The resolution of the electron microscope. This transmission electron micrograph of a monolayer of graphene resolves the individual carbon atoms as bright spots in a hexagonal lattice. Graphene is a single isolated atomic plane of graphite and forms the basis of carbon nanotubes. The distance between adjacent bonded carbon atoms MBoC7 m9.40/9.39 is 0.14 nm (1.4 Å). Such resolution can only be obtained in a specially built transmission electron microscope in which all lens aberrations are carefully corrected, and with optimal specimens; it is rarely achieved with most conventional biological specimens. (From A. Dato et al., Chem. Commun. 40:6095–6097, 2009. With permission from the Royal Society of Chemistry.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-40": (
    caption: [The principal features of an inverted light microscope and a transmission electron microscope. These drawings emphasize the similarities of overall design. Whereas the lenses in the light microscope are made of glass, those in the electron microscope are magnetic coils. The electron microscope requires that the specimen be placed in a vacuum. The inset shows a routine transmission electron microscope in use. (Photograph courtesy of Andrew Davis.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-41": (
    caption: [Specimen support. The metal grid that supports the thin sections of a specimen in a transmission electron microscope.],
    path: "../fig/image_place_holder.png"
  ),
  "9-42": (
    caption: [Thin section of a cell. This thin section is of a yeast cell that has been very rapidly frozen and the vitreous ice replaced by organic solvents and then by plastic resin (freeze substitution). The nucleus, mitochondria, cell wall, Golgi stacks, and ribosomes can all be readily seen in a state that is presumed to be as lifelike as possible. (Courtesy of Andrew Staehelin.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-43": (
    caption: [Localizing proteins in electron microscopy. Immunogold electron microscopy is used here to find the specific location of a protein that is targeted to the Golgi apparatus. The protein has been tagged with a genetically encoded fluorescent protein and is localized to the trans-Golgi network. The protein is seen in this thin section using an antibody to the fluorescent protein coupled to 10-nm colloidal gold particles, seen in the electron microscope as black dots. The cell has been frozen under high pressure and freeze substituted before embedding and sectioning. (Courtesy of Charlotta Funaya and M. Teresa Alonso.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-44": (
    caption: [Heavy metals provide contrast in the electron microscope. (A) This transmission electron micrograph shows RecA protein together with E. coli DNA adsorbed to flakes of mica, frozen, carefully dried, and then shadowed with evaporated platinum atoms. The RecA protein clearly forms tight, right-handed helices around the bacterial DNA molecules, some of which can be seen free at the top of the image (see also Figure 5–48). (B) In this transmission electron micrograph of actin filaments, negatively stained with uranyl acetate, each filament is about 8 nm in diameter and is seen, on close inspection, to be composed of a helical chain of globular actin molecules (see also Figure 16–8). (A, from J. Heuser, J. Electron Microsc. Tech. 13:244–263, 1989; B, courtesy of Roger Craig.)],
    path: "../fig/image_place_holder.png"
  ),
  "12-2": (
    caption: [or Figure 12–15).],
    path: "../fig/image_place_holder.png"
  ),
  "9-45": (
    caption: [The scanning electron microscope. In an SEM, the specimen is scanned by a beam of electrons brought to a focus on the specimen by the electromagnetic coils that act as lenses. The detector measures the quantity of electrons scattered or emitted as the beam bombards each successive point on the surface of the specimen and records the intensity of successive points in an image built up on a screen. The SEM creates striking images of three-dimensional objects with great depth of focus and a resolution between 0.5 nm and 10 nm depending on the kind of instrument. (Photograph courtesy of Andy Davis.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-46": (
    caption: [The scanning electron microscope produces surface images with great depth of field. SEM micrographs taken at a wide range of magnifications. (A) A developing wheat flower, or spike. This delicate flower spike was rapidly frozen, coated with a thin metal film, and examined in the frozen state with an SEM. This low-magnification micrograph demonstrates the large depth of focus of an SEM, even with a large specimen like this. (B) These pollen grains from a hellebore flower reveal their sculpted cell walls in the SEM. The shapes and patterns are specific for each species of pollen grain. (C) Chains of bacteria living in the blue veins of a Stilton cheese. (A, B, and C, courtesy of Kim Findlay.) (A) (B) 1 mm (C) 50 µm 1 µm],
    path: "../fig/image_place_holder.png"
  ),
  "9-47": (
    caption: [Higher-resolution SEM. Macromolecular assemblies, shadowed with a very thin coating of tungsten and imaged in an SEM equipped with a field-emission electron gun. (A) An actin filament showing the helical arrangement of actin monomers. (B) Clathrin-coated vesicles. \[A and B, from R. Wepf et al., in Biological Field Emission Scanning Electron Microscopy (R. Fleck and B. Humbel, eds.), pp. 269–298. Hoboken, NJ: Wiley, 2019.\]],
    path: "../fig/image_place_holder.png"
  ),
  "9-48": (
    caption: [EM tomography. The COP1 coat mediates vesicle traffic within the Golgi apparatus and retrograde traffic to the endoplasmic reticulum (ER) (see Figures 13–4 and 13–5). EM tomography has helped visualize the details of COP1 coats in situ on buds and vesicles in rapidly frozen Chlamydomonas cells. (A) One slice through a three-dimensional tomogram of a complete Golgi apparatus. (The tomogram can be seen in Movie 9.2.) (B) Using the information from several such tomograms, a portion of the Golgi is shown here, color coded to show ER dark yellow, the cis vesicles yellow, the four cis cisternae green, the four medial cisternae red, the trans cisterna blue, medial vesicles pink, trans vesicles light blue, and the trans Golgi network purple. Ribosomes can also be seen as small gray blobs. (C) Individual slices through COP1 vesicles in the tomogram; the bottom one is partially uncoated. (D) By identifying and averaging more than 10,000 COP1 subunits on vesicles in the tomograms, a molecular structure was obtained by subtomogram averaging at a resolution of 2 nm. Structures of the various proteins in the COP1 coat have been solved, and they can be fitted neatly into the electron-density envelope of the EM structure. A surface view of a triad of COP1 subunits on the surface of a vesicle is shown here together with the molecular structures (in color) of the individual components that have been fitted into the EM structure. (Adapted from Y.S. Bykov et al., eLife 6:e32493, 2017, doi 10.7554/eLife.32493.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-49": (
    caption: [CryoEM structure of microtubules. This cryoEM reconstruction of the structure of a microtubule was helped by the intrinsic symmetry of the microtubule itself (see Figure 16–37). This detailed model of the whole microtubule has allowed an examination of the way in which the protofilaments interact and the way in which the whole lattice and associated proteins are assembled. (A) CryoEM image of two intact microtubules embedded in vitreous ice. (B) A reconstruction of the surface lattice of a single microtubule at a resolution of 0.35 nm (3.5 Å). (C) The detailed electron-density map of the tubulin dimer extracted from the structure of the intact microtubule. α-Tubulin is darker green, and β-tubulin is lighter green. (From E. Nogales, Mol. Biol. Cell 27:3202–3204, 2016, doi 10.1091/mbc.E16-06-0372. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-50": (
    caption: [The spike protein on the SARS-CoV-2 virus. The SARS-CoV-2 virus was responsible for the COVID-19 pandemic. Protruding from the viral membrane are many trimeric spike proteins that mediate binding of the virus to a receptor on cells in our respiratory tract and its subsequent entry into the cell. The trimeric spike protein is a target both of our immune system and of vaccine developers. The closed conformation of the trimeric spike protein shown here, both from the top (A) and from the side (B), was obtained from rapidly frozen intact virus particles. Spike proteins were identified by computer from multiple tilted images of the viruses and subtomogram averaging applied to them. The final electron-density map was determined to a resolution of 0.35 nm, good enough for the molecular model (shown here) to be accurately fitted within its envelope, although the details of the membrane-spanning portion of the trimeric spike protein are not revealed. The proteins are heavily N-glycosylated, and these surface glycans are shown in green, while the three spike proteins are shown in dark green, light blue, and light brown. (PDB code: 6ZWV.) (A)],
    path: "../fig/image_place_holder.png"
  ),
  "9-51": (
    caption: [Atomic resolution by cryoEM. Apoferritin is a cytosolic protein, present in almost all living organisms, that reversibly stores iron in a nontoxic form. It is a large (474 kilodaltons) and particularly stable molecule. Its hollow globular cage has 24 symmetrical subunits, which means that a structure can be determined with relatively few particles. (A) Cryo-electron micrograph of cage-like apoferritin particles. (B) By use of every possible new technical advance in single-particle reconstruction, the complete cryoEM structure shown here is at the remarkable resolution of 0.12 nm (1.2 Å). (C) When the known amino acid sequence is modeled into the electron- density map, clear electron densities can be seen associated with hydrogen atoms in the three amino acid side chains. The molecular model is fitted into the final electron-density envelope that is shown as a gray cage. (A, from T. Nakane et al., Nature 587:152– 156, 2020, doi 10.1038/s41586-020-2829-0; B, EMD-11668; C, adapted from K.M. Yip et al., Nature 587:157–161, 2020. With permission from Nature.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-52": (
    caption: [PRC2, a large macromolecular machine. Polycomb repressive complex 2 (PRC2) is a large protein complex involved in establishing heterochromatin and the epigenetic regulation of gene expression (see Figure 4–40). PRC2 interacts with a nucleosome through the binding of the nucleosomal DNA by one of its subunits, EZH2, which also engages the extended tail of histone H3 to direct its lysine 27 (K27) to the active site for methylation. The density map of PRC2 and two essential cofactors bound to a single nucleosome was produced by single-particle cryo- electron microscopy reconstruction at a resolution of 0.35 nm. The long arm of histone H3 is shown in more detail with the protein backbone modeled into the density map. (Courtesy of Vignesh Kasinath and Eva Nogales and based on EMDB- 21707. From V. Kasinath et al., Science 371:eabc3393, 2021. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "9-53": (
    caption: [Correlated light and electron microscopy (CLEM). The correct folding of proteins in the endoplasmic reticulum (ER) is sensed by a major transmembrane protein called IRE1 (see Figures 12–36 and 12–37). If IRE1 is activated, it forms oligomers that are visible in fluorescence microscopy as bright foci. Here, stressed cells, expressing fluorescent IRE1 and growing on an EM grid, are rapidly frozen and subsequently imaged by EM tomography. The resulting tomograms can be directly correlated with the light micrographs. (A) A fluorescent spot of labeled IRE1 is shown here precisely superimposed on a slice through its corresponding EM tomogram that contains a network of ER. (B) Another slice through the tomogram at a different level shows IRE1 is localized as aggregates in a complex network of specialized, narrow ER tubules. (C) The outlines of the ER membranes in each slice of the tomogram are manually defined (in a process called segmentation), and the drawing here shows that the oligomers of IRE1 are concentrated in this convoluted network of specialized ER tubules. (A, B, and C, adapted from S.D. Carter et al., 2021, doi 10.1101/2021.02.24.432779.) (A) 200 nm (B) (C)],
    path: "../fig/image_place_holder.png"
  ),
  "9-54": (
    caption: [Focused ion beam–scanning electron microscopy (FIB–SEM). Superresolution light microscopy is combined here with three-dimensional electron microscopy of rapidly frozen cells to enable the high-resolution localization of target molecules throughout the entire volume of a cell. Sequential slices through the frozen cell are obtained by steadily milling the surface of the frozen block face with a focused ion beam, while images of the surface are collected at each step in an SEM. This particular cell has been labeled with fluorescent markers for the lumen of the endoplasmic reticulum (green) and for the outer membrane of mitochondria (magenta). (A) Three orthogonal slices through the cell show the combined electron microscope and fluorescence light microscope images. (B) A small region of the same cell imaged with a structured illumination microscope (SIM) is used to define mitochondrion and ER. (C) The corresponding block face image in the SEM. (D) The correlated electron microscope and light microscope images identify the position of the fluorescent labels in the electron micrograph. (E, F, and G) Because the three-dimensional SEM data set is of the entire cell, different views of the same area can be readily obtained. Here, the three corresponding vertical sections along the yellow dotted lines on the images above are shown. (From D.P. Hoffman et al., Science 367:265–277, 2020. With permission from AAAS.) (C) (F) (D) (G) 200 nm (A) (B) (E)],
    path: "../fig/image_place_holder.png"
  ),
)