#let images = (
  "22-1": (
    caption: [Tissue homeostasis compared to a river. In a self-renewing adult tissue, a constant flow of new cells produced by cell division “upstream” and a constant loss of differentiated cells “downstream” maintain the tissue in a dynamic equilibrium.],
    path: "../fig/image_place_holder.png"
  ),
  "22-2": (
    caption: [The defining characteristics of a stem cell. Each daughter cell produced when a stem cell divides can either remain a stem cell, in the process of self-renewal, or commit to differentiation, usually after a number of cell divisions. The self-renewal process maintains the pool of stem cells in the tissue.],
    path: "../fig/image_place_holder.png"
  ),
  "22-3": (
    caption: [A hierarchy of stem cells, progenitor cells, and differentiated cells. In addition to self-renewal, tissue-specific stem cells generally produce progenitor (transit-amplifying) cells that divide a limited number of times before they terminally differentiate. Stem cells and progenitor cells can be unipotent or multipotent, depending on whether they produce only one type or multiple types of differentiated cells.],
    path: "../fig/image_place_holder.png"
  ),
  "22-4": (
    caption: [Renewal of the gut epithelial lining. (A) The pattern of cell turnover and proliferation in the epithelium that forms the lining of the small intestine. Stem cells (red) lie at the crypt base, interspersed among nondividing differentiated cells (Paneth cells). Progeny of the stem cells move mainly upward from the crypts onto the villi; after a few quick divisions, they cease dividing and differentiate—some of them while still in the crypt, most of them as they emerge from the crypt. The Paneth cells, like the other nondividing differentiated cells, are continually replaced by the progeny of the stem cells, but they migrate downward to the crypt base and survive there for many weeks. (B) Micrograph of a section of part of the lining of the small intestine, showing the crypts and villi. Note the mixture of differentiated cell types, all generated from the stem cells; these are primarily absorptive cells, with mucus-secreting goblet cells (stained red) interspersed among them.],
    path: "../fig/image_place_holder.png"
  ),
  "22-5": (
    caption: [The four main differentiated cell types found in the epithelial lining of the small intestine. All cells are oriented with the gut lumen at top. Broad orange arrows indicate direction of secretion or uptake of materials for each type of cell. All of these cells are generated from undifferentiated multipotent stem cells living near the bottoms of the crypts (see Figure 22–4). Absorptive (brush-border) cells outnumber the other cell types in the epithelium by about 10:1 or more. The microvilli on their apical surface provide a 30-fold increase in surface area, not only for the import of nutrients but also for the anchorage of enzymes that perform the final stages of extracellular digestion, breaking down small peptides and disaccharides into monomers that can be transported across the cell membrane. Goblet cells secrete mucus; these are the most common of the secretory cell types. Paneth cells secrete (along with some growth factors) cryptdins—proteins of the defensin family that kill bacteria. Different subtypes of enteroendocrine cells secrete serotonin and peptide hormones into the gut wall (and thence the blood). Cholecystokinin is a hormone released from enteroendocrine cells in response to the presence of nutrients in the gut. It binds to receptors on nearby sensory nerve endings and causes the release of digestive enzymes from the pancreas and bile from the gall bladder; it also signals to the brain to stop the feeling of hunger once one has eaten enough. (Absorptive and goblet cells, Don W. Fawcett/Science Source; Paneth and enteroendocrine cells, from R.V. Krstic´, Illustrated Encyclopedia of Human Histology. Berlin: Springer-Verlag, 1964. With permission from Springer Nature.) 5 µm absorptive cell goblet cell Paneth cell enteroendocrine cell],
    path: "../fig/image_place_holder.png"
  ),
  "22-6": (
    caption: [The multilayered structure of the epidermis. The epidermis forms the outer covering of the skin, creating a waterproof barrier that is self-repairing and continually renewed. Beneath this lies a relatively thick layer of connective tissue, which includes the tough, collagen-rich dermis (from which leather is made). The cells of the epidermis are called keratinocytes, because their characteristic differentiated activity is the synthesis of keratin intermediate filament proteins, which give the epidermis its toughness. These cells change their appearance and properties from one layer to the next, progressing through a regular program of terminal differentiation. Those in the innermost layer, attached to an underlying basal lamina, are termed basal cells, and it is normally only these that divide: the basal-cell population includes relatively small numbers of stem cells along with larger numbers of transit-amplifying progenitor cells derived from them. Above the basal cells are several layers of larger prickle cells. Beyond the prickle cells lies the thin, darkly staining granular-cell layer, where the cells are sealed together to form a waterproof barrier; this marks the boundary between the inner, metabolically active strata and the outermost layer of the epidermis, consisting of dead cells whose intracellular organelles have disappeared. These outermost cells are reduced to flattened scales, or squames, filled with densely packed keratin, which are eventually shed from the surface of the skin. The time from exit of a cell from the basal layer to its loss by shedding at the surface is a week or two, depending on body region and species.],
    path: "../fig/image_place_holder.png"
  ),
  "22-7": (
    caption: [and Figure 22–8. This approach does not require prior knowledge as to whether a tissue contains stem cells or not. If they exist, the stem cells will be marked randomly and will lead to a persistent clonal lineage that contains stem cells as well as differenti- ated cells (see Figure 22–7B); dividing progenitor cells will also be randomly marked and produce labeled clones, but all of these will eventually disappear (see Figure 22–7C). The analysis of the clones not only indicates whether stem cells are],
    path: "../fig/image_place_holder.png"
  ),
  "22-7": (
    caption: [Clonal analysis using a genetic marker. (A) Transgenic animals containing two transgenes can be used to drive expression of a readily detected and heritable marker in a small set of cells. The first transgene encodes a marker gene, such as one that encodes green fluorescent protein (GFP). However, the expression of the GFP transgene, shown here in green, is prevented by a blocking sequence (red) that is flanked by LoxP sites ( pink; see Figure 5–66). The second transgene, CreERT2 (brown), encodes a chimeric form of the Cre recombinase called CreERT, which consists of the Cre recombinase linked to the estrogen receptor protein; this enzyme becomes active as a recombinase only when it binds the artificial estrogen analog tamoxifen (red spheres). Addition of tamoxifen leads to a recombination event that removes the blocking DNA sequence. As a result, the GFP marker is expressed. Because the blocking DNA has been permanently removed from the genome, the marker continues to be expressed in all the descendants of a cell in which the recombination event has occurred. With a low dose of the inducer molecule tamoxifen, it is possible to activate the marker at random in just a few widely spaced cells, giving rise to distinguishable clones. (B) If the recombination event occurs in a stem cell, a clonal lineage will be marked, and the labeling will persist over time as the marked stem cell self-renews and produces differentiated cells. (C) If the recombination event occurs in a cell that is not a stem cell, the label will disappear over time as the marked cell differentiates and is eventually lost.],
    path: "../fig/image_place_holder.png"
  ),
  "22-8": (
    caption: [Lgr5-expressing stem cells and their progeny in the small intestine. The basic method shown in Figure 22–7 was modified here to mark single intestinal stem cells and trace the fates of their progeny. The Lgr5 gene encodes a member of the family of G-protein-linked transmembrane receptors, and it is expressed specifically in stem cells near the crypt base. In this case, the Lgr5 promoter was used to drive expression of CreERT2, and treatment with a low dose of tamoxifen resulted in occasional stem cells expressing the marker protein LacZ (rather than GFP). These cells and all of their progeny could subsequently be detected with a blue histochemical stain. All of the blue cells in these images derive from a single Lgr5-expressing stem cell. After 60 days, the blue progeny of this cell are seen to extend almost all the way up a villus. These progeny can be shown to include all types of differentiated cells, as well as persistent Lgr5-expressing cells at the crypt base. This proves that Lgr5- expressing cells are multipotent stem cells. (From N. Barker et al., Nature 449:1003– 1007, published 2007 by Nature Publishing Group. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-9": (
    caption: [The repair of skeletal muscle fibers by satellite cells. (A) The specimen is stained with an antibody (red) against a muscle cadherin, M-cadherin, which is present on both the satellite cell and the muscle fiber and is concentrated at the site where their membranes are in contact. The nuclei of the muscle fiber are stained green, and the nucleus of the satellite cell is stained blue. (B) Schematic drawing of the repair of a damaged muscle fiber by the proliferation and fusion of satellite cells. (A, courtesy of Terence Partridge.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-1": (
    caption: [Blood Cells],
    path: "../fig/image_place_holder.png"
  ),
  "22-10": (
    caption: [Rescue of an irradiated mouse by a transfusion of bone marrow cells. An essentially similar procedure is used in the treatment of leukemia in humans by bone marrow transplantation after irradiation or chemotherapy. x-irradiation halts blood cell production; mouse would die if no further treatment were given],
    path: "../fig/image_place_holder.png"
  ),
  "22-11": (
    caption: [Human blood cells. (A) A light micrograph of a blood smear stained with the Romanowsky stain, which faintly colors the red blood cells red and strongly colors the white blood cells blue. (B–E) Electron micrographs of (B) a neutrophil, (C) a basophil, (D) an eosinophil, and (E) a monocyte. (Electron micrographs of lymphocytes are shown in Figure 24–14.) Each of the cell types shown here has a different function (see Table 22–1), which is reflected in the distinctive types of secretory granules and lysosomes each cell type contains. There is only one nucleus per cell, but it has an irregular lobed shape, and in panels B, C, and D the connections between the lobes are out of the plane of section. (A–D, courtesy of Dorothy Bainton; E, courtesy of David Mason.) (B)],
    path: "../fig/image_place_holder.png"
  ),
  "22-12": (
    caption: [A simplified scheme of mouse and human hematopoiesis. A multipotent hematopoietic stem cell normally divides infrequently to generate either more multipotent stem cells, which are self-renewing, or multipotent progenitor cells, which give rise to all the cells of the blood and immune system. The progenitor cells divide a limited number of times and go through multiple stepwise intermediates before they develop into fully differentiated cells. As they go through their divisions, the progenitors become progressively more specialized in the range of cell types that they can give rise to, as indicated by the branching of this cell lineage diagram. In adult mammals, all of the cells shown develop mainly in the bone marrow—except for T lymphocytes, which as indicated develop in the thymus, and macrophages and some dendritic cells, which develop from monocytes that are circulating in the blood. Note that not all stem cells generate the identical patterns of progeny via precisely the same sequence.],
    path: "../fig/image_place_holder.png"
  ),
  "22-13": (
    caption: [The stem-cell niche. Stem cells undergo self-renewal only in a specialized microenvironment where they are exposed to the necessary signal molecules. These signal molecules can be provided by niche-supporting cells or by a specialized extracellular matrix that serves to concentrate them. The niche environment can be very small. In some cases, a stem cell directly adjacent to the niche is capable of self-renewal, while a cell just one cell-diameter away from the niche is not.],
    path: "../fig/image_place_holder.png"
  ),
  "22-14": (
    caption: [Genesis of a minigut from a single Lgr5-expressing cell cultured in a cell-free matrix. (A) Schematic drawing and (B) phase-contrast micrographs of the developing organoid. The founder cell first divides to form a small sack or vesicle. At random, one or more of the cells in this vesicle differentiates as a Paneth cell (blue). The Paneth cells secrete Wnt proteins that stimulate stem-cell self-renewal and maintain Lgr5 expression (yellow) in their immediate MBoC7 m22.08/22.14 neighbors; besides generating more stem cells, the stem cells produce progenitor cells that differentiate into the full range of intestinal epithelial-cell types. (C) Schematic diagram showing how Paneth cell–derived Wnt signals help organize the developing crypt: besides keeping neighboring cells in the crypt proliferating in a stem-cell state, these signals activate repulsive interactions mediated by membrane-bound ephrin and Eph proteins on contacting cells (discussed in Chapter 15). These interactions cause dividing crypt cell types (which express EphB, induced by Wnt) to segregate from the nondividing, terminally differentiated villus cell types (which express ephrinB). In many tissues, cells that interact via ephrin–Eph binding repel each other when they touch (see Figure 15–52 or Figure 21–47). (Adapted from T. Sato and H. Clevers, Science 340:1190–1194, 2013. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-14": (
    caption: [shows this process and outlines the key signaling events that establish the crypt stem-cell niche, where different cell types are produced that arrange themselves into miniature villi to form the three-dimensional organ- oid structure.],
    path: "../fig/image_place_holder.png"
  ),
  "22-15": (
    caption: [Stem-cell niche of the C. elegans gonad. (A) Fluorescence micrograph showing the nuclei (blue) in a portion of the C. elegans gonad. The nucleus of the distal tip cell is shown in red. (B) The same tissue is stained to show the cytoplasm and processes of the distal tip cell in red and the differentiated germ cells in green. The distal tip cell processes extend across multiple stem-cell diameters, maintaining stem-cell identity through MBoC7 n22.104/22.15 Notch signaling. Those cells moved out of reach of the distal tip cell processes initiate meiosis and begin the differentiation program that will produce either eggs or sperm. (Courtesy of Judith Kimble and Sarah Crittenden.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-16": (
    caption: [Asymmetric and symmetric stem-cell divisions. (A) In the asymmetric stem-cell division schematized here, a cell-fate determinant (red) that maintains stem-cell identity is localized to the cell cortex at one side of the cell. When the cell divides, only one daughter cell inherits the determinant and remains a stem cell, while the other daughter commits to differentiation, differentiating after a number of progenitor-cell divisions (not shown). (B) In the symmetric stem-cell division shown, both daughter cells inherit such determinants and remain stem cells.],
    path: "../fig/image_place_holder.png"
  ),
  "22-17": (
    caption: [How the plane of division in a dividing, germ-line stem cell in the Drosophila testis determines which daughter cell maintains contact with the niche. (A) The niche consists of a hub of somatic cells, and the germ-line stem cells are arranged in a ring around the hub. When a stem cell divides, its mitotic spindle is oriented perpendicular to the niche, so that only one daughter cell maintains contact with the niche and remains a stem cell; the other daughter loses contact with the niche cells and is therefore deprived of self-renewal signals and commits to differentiation. (B) The light micrograph shows germ-line stem cells surrounding the niche and a dividing stem cell with its mitotic spindle oriented perpendicular to the niche. The stem cells have been genetically engineered to express fluorescently labeled tubulin. (B, from Y.M. Yamashita et al., Science 301: 1547–1550, 2003. With permission from AAAS.) 1294 Chapter 22: Stem Cells in Tissue Homeostasis and Regeneration],
    path: "../fig/image_place_holder.png"
  ),
  "22-18": (
    caption: [The independent-choice mechanism for how the two daughters of a stem-cell division choose their fates. The outcomes of this mechanism are more variable than that of symmetric stem-cell divisions. The choice might be determined by the local environment a daughter finds itself in (left side of the drawing) or it might be entirely stochastic (right side of drawing). With a choice made stochastically by each daughter and with a 50% probability for each one to remain a stem cell or commit to differentiation, there is, for example, a 25% chance at the first division that both daughters will commit to differentiation, so that the clone will eventually disappear. Or, at this division or later, a preponderance of daughters might choose to remain stem cells, creating a clone that persists and increases in size. With the help of some mathematics, the probability distribution of clone sizes generated from a single stem cell at any given time can be predicted on this stochastic assumption. The observations in the gut and often elsewhere fit this stochastic independent-choice strategy.],
    path: "../fig/image_place_holder.png"
  ),
  "22-19": (
    caption: [Methods to distinguish the contribution of cell-autonomous versus environmental factors to declines in hematopoietic stem-cell function during aging. (A) Hematopoietic stem cells are transplanted from young or old donor to young or old host, so that the function of stem cells can be assessed. A four-way comparison will reveal the contribution of the autonomous aging of stem cells versus the aging of the environment or niche in the decline of stem-cell function. (B) In parabiosis, animals are joined to develop a shared circulatory system. Cells in one animal will be exposed to the systemic environment of the other animal. The cellular functions in young or old partners in the heterochronic pairs (young-to-old) are compared with those in isochronic pairs (young-to-young and old- to-old). Such comparisons reveal the role of autonomous stem-cell aging compared to the role of circulating factors or the stem-cell niche in the decline of stem-cell function. \[Based on M.A. Goodell and T.A. Rando, Science 350(6265):1199–1204, 2015, doi 10.1126/science.aab3388.\]],
    path: "../fig/image_place_holder.png"
  ),
  "22-20": (
    caption: [The planarian worm, Schmidtea mediterranea. (A) External view. (B) Immunostaining with three different antibodies, revealing the internal anatomy. (A, courtesy of A. Sánchez Alvarado; B, from A. Sánchez Alvarado, BMC Biol. 10:88, 2012. With permission from the author.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-21": (
    caption: [Regeneration of a planarian from a single somatic cell. (A) The distribution of dividing cells (neoblasts; blue) in the adult body. Irradiation blocks all cell division and prevents regeneration. (B) A single unirradiated neoblast cell injected into the irradiated animal is able to proliferate and reconstitute all tissues. This eventually produces a complete animal that consists entirely of the progeny of this one cell and can regenerate normally. A gradient of information concerning head- to-tail identity is continually expressed in muscle cells along the body and instructs the neuroblasts. (Adapted from E.M. Tanaka and P.W. Reddien, Dev. Cell 21:172–185, 2011.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-22": (
    caption: [Newt limb regeneration. (A) The time-lapse sequence shows the stages of regeneration after amputation at the mid-humerus level. The sequence spans the events of wound healing, activation and proliferation of stump stem cells and progenitor cells in the process of blastema formation, and differentiation of various limb-cell types. (B) Schematic diagram of the early blastema. (A, courtesy of Susan Bryant and David Gardiner.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-23": (
    caption: [for stem cells that give rise to neurons in the mouse olfactory bulb. In both the adult mouse and human brain, there is also a continual turnover of neurons in the hippocampus, a region specifically concerned with learning and memory. Here, plasticity of adult brain function is associated with turnover of a particular subset of neurons: about 1400 new neurons in this class are generated every day, which is a turnover rate of 1.75% of the cells per year. A more dramatic neuronal turnover is observed in the brains of certain song- birds. In these birds, large numbers of neurons die each year and are replaced by new neurons, as part of a process by which the birds refine their song for each new breeding season.],
    path: "../fig/image_place_holder.png"
  ),
  "22-23": (
    caption: [The continuing production of neurons in an adult mouse brain. The brain is viewed from above, in a cutaway section, to show the region lining the ventricles of the forebrain where neural stem cells are found. These cells continually produce progeny that migrate to the olfactory bulb, where they terminally differentiate into neurons. The constant turnover of neurons in the olfactory bulb is presumably linked in some way to the turnover of the olfactory receptor neurons that project to it from the olfactory epithelium in the nose. In adult mice and humans, there is also a continuing turnover of neurons in the hippocampus (not shown), a region specially concerned with learning and memory. (Adapted from B. Barres, Cell 97:667–670, 1999.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-24": (
    caption: [Neural stem cells. Shown are the steps leading from fetal brain tissue or embryonic stem cells, via neurospheres (A), to a pure culture of neural stem cells (B). These stem cells can be kept proliferating as such indefinitely or, through a change of medium, can be caused to differentiate (C) into neurons (red) and glial cells (green). Neural stem cells with the same properties can also be derived, via a similar series of steps, from embryonic stem (ES) or induced pluripotent stem (iPS) cells (discussed later in this chapter). (Micrographs from L. Conti et al., PLoS Biol. 3:e283, 2005. With permission from the authors.) (A) (B) (C)],
    path: "../fig/image_place_holder.png"
  ),
  "22-25": (
    caption: [Production and pluripotency of ES cells. ES cells are derived from the inner cell mass (ICM) of the early embryo. The ICM cells are transferred to a culture dish containing an appropriate medium, where they become converted to ES cells and can be kept proliferating indefinitely without differentiating. The ES cells can be taken at any time—after genetic manipulation, if desired—and injected back into a developing blastocyst. There they incorporate into the inner cell mass and take part in formation of a well-formed chimeric animal that is a mixture of ordinary and ES-derived cells. The ES-derived cells can differentiate into any of the cell types in the body, including germ cells from which a new generation of mice can be produced, which are no longer chimeric, but consist of cells that all inherit half their genes from the cultured ES cell line.],
    path: "../fig/image_place_holder.png"
  ),
  "22-26": (
    caption: [Reprogramming fibroblasts to iPS cells with the OSKM factors. As indicated, the transcription regulatory proteins Oct4, Sox2, and Klf4 (OSK factors) MBoC7 m22.41/22.26 induce both their own and each other’s synthesis (gray shading). This generates a self-sustaining feedback loop that helps to maintain cells in an ES cell–like state, even after all of the experimentally added OSKM initiators have been removed. Myc overexpression speeds up early stages of the reprogramming process through the mechanisms shown (see Figure 17–59). Stable reprogramming also involves the permanently induced expression of the Nanog gene, which encodes an additional transcription regulator (see Figure 7–10). (Adapted from J. Kim et al., Cell 132: 1049–1061, 2008.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-27": (
    caption: [A strategy used to select cells that have converted into iPS cells. The experiment makes use of a gene (Fbx15) that is present in all cells but is normally expressed only in ES and early embryonic cells (although not required for their survival). G418 is an aminoglycoside antibiotic that blocks protein synthesis in both bacteria and eukaryotic cells. A fibroblast cell line is genetically engineered to contain a gene that produces an enzyme that degrades G418 under the control of the Fbx15 regulatory sequence. When the OSKM factors are artificially expressed in this cell line, a small proportion of the cells undergo a change of state and activate the Fbx15 regulatory sequence, driving expression of the G418-resistance gene. When G418 is added to the culture medium, these are the only cells that survive and proliferate. When tested, they turn out to have iPS-cell characteristics.],
    path: "../fig/image_place_holder.png"
  ),
  "22-28": (
    caption: [A summary of some of the major events that accompany the reprogramming of fibroblasts to iPS cells. Expression of the OSKM factors induces a series of events over a period of days to weeks. Reprogramming begins with down-regulation of somatic- cell markers. Morphological changes characteristic of a mesenchymal-to- epithelial transition ensue (see p. 1197), driven in part by changes in the expression of cell adhesion and signal proteins. Induction of early pluripotency markers is followed by the expression of pluripotency genes such as Nanog and Oct4. With similar timing, cells become immortalized as telomerase is induced and cell-cycle genes are regulated to enable stem-cell self-renewal. Stable reprogramming occurs in the time window when cells activate endogenous pluripotency genes and become independent of the OSKM factors. Notably, the vast majority of fibroblasts expressing the OSKM factors fail to down- regulate somatic markers and activate pluripotency genes and do not convert to iPS cells. (Adapted from M. Stadtfeld et al., Cell Stem Cell 2:230–240, 2008. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-29": (
    caption: [categorizes some of the factors that when manipulated can enhance the trans- formation of fibroblasts to iPS cells; those in the top three rows—chromatin remodelers, histone modifiers, and histone variants—are especially well known to have profound effects on the organization of nucleosomes in chromatin (dis- cussed in Chapter 4).],
    path: "../fig/image_place_holder.png"
  ),
  "22-29": (
    caption: [Factors that have been observed to enhance reprogramming efficiency. Emphasized here are those factors that can alter chromatin states, with those in the top three rows having the most direct effects. An up arrow indicates that reprogramming is increased when the activity of the indicated factor is increased; a down arrow indicates that reprogramming is increased when the activity of the indicated factor is decreased. Thus, for example, increased activity of histone acetyl transferases and increased activity of histone deacetylases have opposite effects, as expected from their biochemical activities (see p. 206). Note that histone chaperones also contribute to programming efficiency and may do so either positively or negatively depending on the histone variants assembled into chromatin. 1306 Chapter 22: Stem Cells in Tissue Homeostasis and Regeneration],
    path: "../fig/image_place_holder.png"
  ),
  "22-31": (
    caption: [and Movie 22.2). Success requires trial and error but has now been achieved for many differentiated mouse and human cell types, including human dopaminergic neurons and human insulin-producing β cells, the cells lost in Parkinson’s disease and type 1 diabetes, respectively.],
    path: "../fig/image_place_holder.png"
  ),
  "22-30": (
    caption: [A teratoma. These tumors contain tissues derived from each of the embryonic germ layers: endoderm, mesoderm, and ectoderm (including hair and teeth, as seen here). The tumors are usually benign and can develop when ES or iPS cells are injected into an immunocompatible adult animal, demonstrating the pluripotency of these MBoC7 n22.108/22.30 stem cells. (Courtesy of Cao Xuan Cu.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-31": (
    caption: [Production of differentiated cells from mouse or human ES or iPS cells in culture. ES and iPS cells can be cultured indefinitely as pluripotent cells when attached as a monolayer to a dish. Alternatively they can be detached and allowed to form aggregates called embryoid bodies, which causes the cells to begin to specialize. Cells from embryoid bodies, cultured in media with different factors added, can then be driven to differentiate in various ways. Notably, it takes very much longer to generate the differentiated cells from human compared to mouse pluripotent stem cells, reflecting the much slower rate of human development compared to a mouse. (Based on E. Fuchs and J.A. Segre, Cell 100:143–155, 2000.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-32": (
    caption: [Cultured human ES cells can give rise to a three-dimensional organoid. (A) Schematic drawing shows how, under appropriate conditions, mouse or human pluripotent stem cells and their progeny in culture can proliferate, differentiate, and self-assemble into a three-dimensional eye-like structure (an optic cup), which includes a multilayered retina similar in organization to the one that forms during normal eye development in vivo. (B) Fluorescence micrograph of an optic cup formed by human ES cells in culture. The structure includes a developing retina containing multiple layers of neural cells (stained green) and an underlying layer of pigmented epithelium, the apical surface of which is stained red. All nuclei are stained blue. (A, adapted from M. Eiraku and Y. Sasai, Curr. Opin. Neurobiol. 22:768–777, 2012; B, from T. Nakano et al., Cell Stem Cell 10:771–785, 2012. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "22-33": (
    caption: [Use of iPS cells for drug discovery and for analysis and treatment of genetic disease. The left side of the diagram shows how differentiated cells that are generated from iPS cells derived from an individual with a genetic disease can be used for analysis of the disease mechanism and for discovery of therapeutic drugs. The right side of the diagram shows how the genetic defect might be repaired in the iPS cells, which could then be induced to differentiate in an appropriate way and grafted back into the individual without danger of immune rejection. (Adapted from D.A. Robinton and G.Q. Daley, Nature 481:295–305. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
)