#let images = (
  "16-1": (
    caption: [The cytoskeleton. (A) A cell in culture has been fixed and labeled to show its cytoplasmic arrays of microtubules (green) and actin filaments (red). (B) This dividing cell has been labeled to show its spindle microtubules (green) and surrounding cage of intermediate filaments (red). The DNA in both cells is labeled in blue. (A, courtesy of Albert Tousson, High Resolution Imaging Facility, University of Alabama at Birmingham; B, courtesy of Conly Rieder.) 949 C H A P T E R 16 I N T H I S C H A P T E R],
    path: "../fig/image_place_holder.png"
  ),
  "16-2": (
    caption: [for a fibroblast growing in a tissue-culture dish. After the chromosomes have replicated, the interphase microtubule array that spreads throughout the cytoplasm is recon- figured into the bipolar mitotic spindle, which transfers the two copies of each chromosome into separate daughter nuclei. At the same time, the special- ized actin structures that enable the fibroblast to crawl across the surface of the dish rearrange so that the cell stops moving and assumes a more spherical shape. Actin and its associated motor protein myosin then form a belt around the middle of the cell, the contractile ring, which constricts like a tiny muscle to pinch the cell in two. When division is complete, the cytoskeletons of the two daughter fibroblasts recreate their interphase structures, thereby convert- ing the two rounded-up daughter cells into smaller versions of the flattened, crawling mother cell.],
    path: "../fig/image_place_holder.png"
  ),
  "16-2": (
    caption: [Diagram of changes in cytoskeletal organization associated with cell division. The crawling fibroblast drawn here has a polarized, dynamic actin cytoskeleton (shown in red) that assembles lamellipodia and filopodia to push its leading edge toward the right. The polarization of the actin cytoskeleton is assisted by the microtubule cytoskeleton (green), consisting of long microtubules that emanate from a microtubule-organizing center located in front of the nucleus. When the cell divides, actin filaments are reorganized and the cell assumes a spherical shape. The polarized microtubule array rearranges to form a bipolar mitotic spindle, which is responsible for aligning and then segregating the duplicated chromosomes (brown). After chromosome segregation, the actin filaments form a contractile ring at the center of the cell that pinches the cell in two. Then the two daughter cells reorganize their microtubule and actin cytoskeletons into smaller versions of those that were present in the mother cell, enabling them to crawl their separate ways.],
    path: "../fig/image_place_holder.png"
  ),
  "16-3": (
    caption: [A neutrophil in pursuit of bacteria. In this preparation of human blood, a small clump of bacteria (white arrow) is about to be captured by a neutrophil. As the bacteria move, the neutrophil quickly reassembles the dense actin network within a pseudopod (“false foot”) at its leading edge (highlighted in red) to push toward the location of the bacteria (Movie 16.1). Rapid disassembly and reassembly of the actin cytoskeleton in this cell enable it to change its orientation and direction of movement within a few minutes. (From a video recorded by David Rogers.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-4": (
    caption: [Organization of the cytoskeleton in polarized epithelial cells. All the components of the cytoskeleton cooperate to produce the characteristic shapes of specialized cells, including the epithelial cells that line the small intestine, diagrammed here. At the apical (upper) surface, facing the intestinal lumen, bundled actin filaments (red) form microvilli that increase the cell-surface area available for absorbing nutrients from food. Below the microvilli, a circumferential band of actin filaments is connected to cell–cell adherens junctions that anchor the cells to each other. Intermediate filaments (blue) are anchored to other kinds of adhesive structures, including desmosomes and hemidesmosomes, that connect the epithelial cells into a sturdy sheet and attach them to the underlying extracellular matrix; these structures are discussed in Chapter 19. Microtubules (green) run vertically from the top of the cell to the bottom and provide a global coordinate system that enables the cell to direct newly synthesized components to their proper locations. – – – – – – – – + +],
    path: "../fig/image_place_holder.png"
  ),
  "16-5": (
    caption: [The thermal stability of cytoskeletal filaments with dynamic ends. A protofilament consisting of a single strand of subunits is thermally unstable, because breakage of a single bond between subunits is sufficient to break the filament. In contrast, formation of a cytoskeletal filament from more than one protofilament allows the ends to be dynamic, while enabling the filaments themselves to resist thermal breakage. In a microtubule, for example, removing a single subunit dimer from the end of the filament requires breaking noncovalent bonds with a maximum of three other subunits, whereas fracturing the filament in the middle requires breaking noncovalent bonds in all 13 protofilaments.],
    path: "../fig/image_place_holder.png"
  ),
  "16-6": (
    caption: [Flexibility and stretch in an intermediate filament. Intermediate filaments are formed from elongated fibrous subunits with strong lateral contacts, resulting in resistance to stretching forces. In this experiment, a tiny mechanical probe was used to rapidly scan across a surface to which intermediate filaments were adhered, providing a measurement of the height and contour of the filaments as shown in shades of gray to white. Along a single scan line (arrow) the applied force of the probe was increased from less than 1 nN to 30–40 nN. At this position one of the filaments stretched to more than three times its length before breaking, as illustrated in the micrographs. This technique is called atomic force microscopy. (Adapted from L. Kreplak et al., J. Mol. Biol. 354:569–577, 2005. With permission from Elsevier.) 200 nm],
    path: "../fig/image_place_holder.png"
  ),
  "16-7": (
    caption: [Cellular life occurs at a low Reynolds number. (A) The inertia of a swimming organism is counteracted by the viscous drag of water, and the ratio of these two forces is the Reynolds number, which is dimensionless. As illustrated in the graph, the Reynolds number is in the range of 106 for a blue whale traveling at about 10 meters per second. For a tiny swimming bacterium moving at 10–5 meters per second, the viscosity of the water dominates and the MBoC7 n1.111/1.07 Reynolds number decreases to about 10–4. (B) The Reynolds number indicates the extent to which an object will continue to coast or glide through a fluid after the motive force has stopped. The stopping distance in water for a sphere that has an initial velocity equal to its diameter per second is plotted. Thus, a one micron–diameter organelle would come to a halt within just a few angstroms once its forward motion ceases.],
    path: "../fig/image_place_holder.png"
  ),
  "16-8": (
    caption: [The structures of an actin monomer and actin filament. (A) The actin monomer has either ATP or ADP bound in a deep cleft in the center of the molecule. (B) Arrangement of monomers in a filament consisting of two protofilaments, held together by lateral contacts, which wind around each other as two parallel strands of a helix, with a twist repeating every 37 nm. All the subunits within the filament have the same orientation. (C) Electron micrograph of negatively stained actin filament. (C, courtesy of Roger Craig.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-9": (
    caption: [Structural polarity of the actin filament. (A) This electron micrograph shows an actin filament polymerized from a short actin filament seed that was decorated with myosin motor domains, resulting in an arrowhead pattern. The filament has grown much faster at the barbed (plus) end than at the pointed (minus) end. (B) Enlarged image and model showing the arrowhead pattern. (A, courtesy of Tom Pollard; B, adapted from M. Whittaker et al., Ultramicroscopy 58:245–259, 1995. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-10": (
    caption: [The time course of actin polymerization. Purified actin subunits were induced to polymerize in a test tube. (A) Polymerization of actin subunits into filaments occurs after a lag phase. (B) Polymerization occurs more rapidly in the presence of preformed fragments of actin filaments, which act as nuclei for filament growth. The percent (%) free subunits after polymerization reflects the critical concentration (Cc), at which there is no net change in polymer. The Cc has a constant value of ∼0.1 μM, but the percent of actin subunits in filaments varies depending on how much actin is present in the reaction. Actin polymerization is often studied by observing the change in the light emission from a fluorescent probe, called pyrene, that has been covalently attached to the actin. Pyrene-actin fluoresces more brightly when it is incorporated into actin filaments.],
    path: "../fig/image_place_holder.png"
  ),
  "16-11": (
    caption: [Treadmilling of an actin filament, made possible by the ATP hydrolysis that follows subunit addition. (A) Explanation for the different critical concentrations (Cc) at the plus and minus ends. Subunits with bound ATP (T-form subunits) polymerize at both ends of a growing filament and then undergo ATP hydrolysis within the filament. As the filament grows, elongation is faster than hydrolysis at the plus end in this example, and the terminal subunits at this end are therefore always in the T form. However, hydrolysis is faster than elongation at the minus end, and so terminal subunits at this end are in the D form. (B) Treadmilling occurs at intermediate concentrations of free subunits. The critical concentration for polymerization on a filament end in the T form, Cc(T), is lower than that for a filament end in the D form, Cc(D). If the actual subunit concentration is somewhere between these two values, the plus end grows while the minus end shrinks, resulting in treadmilling.],
    path: "../fig/image_place_holder.png"
  ),
  "16-1": (
    caption: [Chemical Inhibitors of Actin and Microtubules],
    path: "../fig/image_place_holder.png"
  ),
  "16-12": (
    caption: [Nucleation and branching of actin filaments by the Arp2/3 complex. (A) The structures of Arp2 and Arp3 compared to the structure of actin. Although the face of the molecule equivalent to the plus end (top) in both Arp2 and Arp3 is very similar to the plus end of actin itself, differences on the sides and minus end prevent these actin-related proteins from forming filaments on their own or coassembling into filaments with actin. (B) A model for actin filament nucleation by the Arp2/3 complex. In the absence of an activating factor, Arp2 and Arp3 are held by their accessory proteins in an orientation that prevents them from nucleating a new actin filament. When a nucleation-promoting factor (NPF; brown) binds the complex, Arp2 and Arp3 are brought together into a new configuration that resembles the plus end of an actin filament. Actin subunits can then assemble onto this structure, bypassing the rate-limiting step of filament nucleation. In cells, NPF activation required to induce Arp2/3-dependent nucleation occurs at membrane surfaces. (C) The Arp2/3 complex nucleates filaments most efficiently when it is bound to the side of a preexisting actin filament. The result is a filament branch that grows at a 70° angle relative to the original filament. Repeated rounds of branching nucleation result in a treelike web of actin filaments. (D) Electron micrograph of a branched actin filament formed by mixing purified actin subunits with purified Arp2/3 complexes. (E) Diagram showing the position of the Arp2/3 complex at the branch between the preexisting mother filament and the daughter filament. (D, from I. Rouiller et al., J. Cell Biol. 180:887–895, 2008. © 2008A. Rouiller et al. Originally published in J. Cell Biol. 180:887–895. https://doi.org/10.1083/jcb.200709092. With permission from Rockefeller University Press.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-13": (
    caption: [Actin filament elongation mediated by formins. Formin proteins (green) form a dimeric complex that can nucleate the formation of a new actin filament (red) and remain associated with the rapidly growing plus end as it elongates. The formin protein maintains its binding to one of the two actin subunits exposed at the plus end as it allows each new subunit to assemble. Only part of the large dimeric formin molecule is shown here. Other regions regulate its activity and link it to particular structures in the cell. Many formins are indirectly connected to the cell plasma membrane and aid the insertional polymerization of the actin filament directly beneath the membrane surface.],
    path: "../fig/image_place_holder.png"
  ),
  "16-14": (
    caption: [Profilin stimulates actin filament elongation. (A) Many nucleation-promoting factors (NPFs; brown) contain binding sites for profilin (blue), which is bound to actin monomers. As a result, NPF activation leads not only to nucleation of branched actin filaments by Arp2/3 (green; see Figure 16–12), but also to rapid elongation of the new filaments. (B) Some members of the formin protein family possess whisker-like unstructured domains that contain several binding sites for profilin–actin complexes. This serves to recruit actin monomers to the growing plus end of the actin filament when formin is bound. Under some conditions, profilin can enhance the rate of actin filament elongation so that filament growth is faster than that expected for a diffusion-controlled reaction (see also Figure 3–76). Like NPFs, formin proteins inside the cell are activated to promote actin filament polymerization at membrane surfaces.],
    path: "../fig/image_place_holder.png"
  ),
  "16-15": (
    caption: [Filament capping and its effects on filament dynamics. A population of uncapped filaments adds and loses subunits at both the plus and minus ends, resulting in rapid growth or shrinkage, depending on the concentration of available free monomers (green line). In the presence of a protein that caps the plus end (red line), only the minus end is able to add or lose subunits; consequently, filament growth will be slower at all monomer concentrations above the critical concentration, and filament shrinkage will be slower at all monomer concentrations below the critical concentration. In addition, the critical concentration for the population shifts to that of the filament minus end.],
    path: "../fig/image_place_holder.png"
  ),
  "16-16": (
    caption: [Twisting of an actin filament induced by cofilin. (A) Three-dimensional reconstruction from cryo-electron micrographs of filaments made of pure actin. The bracket shows the span of two twists of the actin helix. (B) Reconstruction of an actin filament coated with cofilin, which binds in a 1:1 stoichiometry to actin subunits all along the filament. Cofilin is a small protein (14 kilodaltons) compared to actin (43 kilodaltons), and so the filament appears only slightly thicker. The energy of cofilin binding serves to deform the actin filament, twisting it more tightly and reducing the distance spanned by each twist of the helix. (© 1997 A. McGough et al. Originally MBoC7 m16.20/16.16 published in J. Cell Biol. https://doi.org.10.1083/jcb.138.4.771. With permission from Rockefeller University Press.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-17": (
    caption: [The actin-based movement of Listeria monocytogenes. (A) Fluorescence micrograph of an infected cell that has been stained to reveal bacteria in blue and actin filaments in red. Note the cometlike tail of actin filaments behind each moving bacterium. (B) Listeria motility can be reconstituted in a test tube with ATP and just four purified proteins: actin, Arp2/3 complex, capping protein, and cofilin. This micrograph shows the dense actin tails behind bacteria (black). (C) The ActA protein on the bacterial surface activates the Arp2/3 complex to nucleate new filament assembly along the sides of existing filaments. Filaments grow at their plus end until capped by capping protein. Actin is recycled through the action of cofilin, which enhances depolymerization at the minus ends of the filaments. By this mechanism, polymerization is focused at the rear surface of the bacterium, propelling it forward (see Movie 23.7). (A, courtesy of Julie Theriot and Tim Mitchison; B, from T.P. Loisel et al., Nature 401:613–616, published 1999 by Nature Publishing Group. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-18": (
    caption: [Actin arrays in a cell moving along a flat surface. (A) A schematic of a fibroblast migrating in a tissue-culture dish is shown with four areas enlarged to show the arrangement of actin filaments. The actin filaments are shown in red, with arrowheads pointing toward the minus end. Stress fibers are contractile and exert tension. The actin cortex underlies the plasma membrane and consists of actin networks that enable membrane protrusion at lamellipodia. Filopodia are spike- like projections of the plasma membrane that sense extracellular signals and allow a cell to explore its environment. (B) A migrating cell that was fixed, dried, and shadowed with platinum reveals a dense network of actin filaments at the leading edge (right side of image). The fast-growing plus ends are oriented toward the cell edge. Accessory proteins organize the filaments. Pseudo-colored in red are actin filaments in the process of becoming a filopodium. (B, courtesy of Tatyana Svitkina.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-19": (
    caption: [illustrates distinct modes of cell migration on the basis of how the actin is organized. All migration is characterized by protrusion, in which the plasma membrane is pushed out at the front of the cell. In mesenchymal cell migration, characteristic of fibroblasts or epithe- lial cells grown on glass surfaces, the Arp2/3 complex mediates actin filament (A)],
    path: "../fig/image_place_holder.png"
  ),
  "16-19": (
    caption: [Modes of cell migration. (A) In the mesenchymal mode of cell migration, focal adhesions form behind protruding lamellipodia that connect to contractile stress fibers, bracing the cell against the surface (substratum) across which it is migrating. (B) In amoeboid cell migration, a three-dimensional pseudopod is formed by explosive actin polymerization at the leading edge. Cells maintain traction even though adhesion to the substratum is reduced, enabling much more rapid cell movement. (C) Leading edge protrusion can also occur through the formation of a bleb if the plasma membrane detaches from the underlying cortex and is pushed out by hydrostatic pressure. In all three modes of migration, contraction of cortical actin and myosin II at the rear of the cell drives locomotion of the cell body.],
    path: "../fig/image_place_holder.png"
  ),
  "16-20": (
    caption: [A dendritic cell migrating in three dimensions. (A) Schematic of a cell introduced into a collagen gel matrix. Images at right show that a chemotactic signal gradient induces polarized extension of pseudopodia that explore the environment, seeking out a path through gaps in the gel matrix that are typically smaller than the cell diameter. The nucleus is stained with a blue dye. (B) Three-dimensional image of a dendritic cell and its many pseudopodia (outlined in red) that is based on fluorescence microscopy. A portion of the collagen matrix surrounding the cell is shown in gray. (C) In this experiment, a dendritic cell was introduced into a microchannel that contains a decision point with four different pore sizes. Using the nucleus as a gauge, the cell ultimately chooses a path through the largest pore (Movie 16.3). (Courtesy of Michael Sixt.) (B) (C)],
    path: "../fig/image_place_holder.png"
  ),
  "16-21": (
    caption: [Myosin II. (A) The two globular heads and long tail of a myosin II molecule shadowed with platinum can be seen in this electron micrograph. (B) A myosin II molecule is composed of two heavy chains (each about 2000 amino acids long; green) and four light chains (blue). The light chains are of two distinct types, and one copy of each type is present on each myosin head. Dimerization occurs when the two α helices of the heavy chains wrap around each other to form a coiled- coil, driven by the association of regularly spaced hydrophobic amino acids (see Figure 3–8). The coiled-coil arrangement makes an extended rod in solution, and this part of the molecule forms the tail. (A, courtesy of David Shotton.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-22": (
    caption: [The myosin II bipolar thick filament in muscle. (A) Electron micrograph of a myosin II thick filament isolated from frog muscle. Note the central bare zone, which is free of head domains. (B) Schematic diagram, not drawn to scale. The myosin II molecules aggregate by means of their tail regions, with their heads projecting to the outside of the filament. The bare zone in the center of the filament consists entirely of myosin II tails. (C) A small section of a myosin II filament as reconstructed from electron micrographs. In the relaxed (noncontracting) state, the two heads of a myosin molecule are bent backward and sterically interfere with each other to switch off their activity. An individual myosin molecule in the inactive state is highlighted in green. The cytoplasmic myosin II filaments in non-muscle cells are much smaller, although similarly organized (see Figure 16–34). (A, from M. Stewart and R.W. Kensler, J. Mol. Biol. 192:831–851, 1986. With permission from Elsevier; C, based on R.A. Crowther et al., J. Mol. Biol. 184:429–439, 1985.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-23": (
    caption: [Direct evidence for the motor activity of the myosin head. In this experiment, purified myosin heads were attached to a glass slide, and then actin filaments labeled with fluorescent phalloidin were added and allowed to bind to the myosin heads. (A) When ATP was added, the actin filaments began to glide along the surface, owing to the many individual steps taken by each of the dozens of myosin heads bound to each filament. The video frames shown in this sequence were recorded about 0.6 second apart; the two actin filaments shown (red) were moving in opposite directions at a rate of about 4 μm/sec. (B) Diagram of the experiment. The large red arrows indicate the direction of actin filament movement (Movie 16.4). (A, courtesy of James Spudich.) (A) (B)],
    path: "../fig/image_place_holder.png"
  ),
  "16-24": (
    caption: [The cycle of structural changes used by myosin II to walk along an actin filament. In the myosin II cycle, the head remains bound to the actin filament for only about 5% of the entire cycle time, allowing many myosins to work together to move a single actin filament (Movie 16.5). (Based on I. Rayment et al., Science 261:58–65, 1993.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-25": (
    caption: [The force of a single myosin molecule moving along an actin filament measured using an optical trap. (A) Schematic of the experiment, showing an actin filament with beads attached at both ends and held in place by focused beams of light called optical tweezers (Movie 16.6). The tweezers trap and move the bead and can also be used to measure the force exerted on the bead through the filament. In this experiment, the filament was positioned over another bead to which myosin II motors were attached, and the optical tweezers were used to determine the effects of myosin binding on movement of the actin filament. (B) These traces show filament movement in two separate experiments. Initially, when the actin filament is unattached to myosin, thermal motion of the filament produces noisy fluctuations in filament position. When a single myosin binds to the actin filament, thermal motion decreases abruptly, and a roughly 10-nm displacement results from movement of the filament by the motor. The motor then releases the filament. Because the ATP concentration is very low in this experiment, the myosin remains attached to the actin filament for much longer than it would in a muscle cell. (Adapted from C. Rüegg et al., News Physiol. Sci. 17:213–218, 2002. With permission from the American Physiological Society.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-26": (
    caption: [Skeletal muscle cells (also called muscle fibers). (A) These huge multinucleated cells form by the fusion of many muscle cell precursors, called myoblasts. Here, a single muscle cell is depicted. In an adult human, a muscle cell is typically 50 μm in diameter and can be up to several centimeters long. (B) Fluorescence micrograph of rat muscle, showing the peripherally located nuclei (blue) in these giant cells. Myofibrils are stained red. (B, courtesy of Nancy L. Kedersha.) (A)],
    path: "../fig/image_place_holder.png"
  ),
  "16-27": (
    caption: [Skeletal muscle myofibrils. (A) Low-magnification electron micrograph of a longitudinal section through a skeletal muscle cell of a rabbit, showing the regular pattern of cross- striations. The cell contains many myofibrils aligned in parallel (see Figure 16–26). (B) Detail of the skeletal muscle shown in A, showing portions of two adjacent myofibrils and the definition of a sarcomere (black arrow). (C) Schematic diagram of a single sarcomere, showing the origin of the dark and light bands seen in the electron micrographs. The Z discs, at each end of the sarcomere, are attachment sites for the plus ends of actin filaments (thin filaments); the M line, or midline, is the location of proteins that link adjacent myosin II filaments (thick filaments) to one another. (D) When the sarcomere contracts, the actin and myosin filaments slide past one another without shortening. (A and B, courtesy of Roger Craig.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-28": (
    caption: [Electron micrographs of an insect flight muscle viewed in cross section. The myosin and actin filaments are packed together with almost crystalline regularity. Unlike their vertebrate counterparts, these myosin filaments have a hollow center, as seen in the enlargement on the right. The geometry of the hexagonal lattice is slightly different in vertebrate muscle. (From J. Auber and R. Couteaux, J. Microsc. 2:309–324, 1963. With permission from Société Française de Microscopie Électronique.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-29": (
    caption: [Organization of accessory proteins in a sarcomere. Each giant titin molecule extends from the Z disc to the M line—a distance of more than 1 μm. Part of each titin molecule is closely associated with a myosin thick filament (which switches polarity at the M line); the rest of the titin molecule is elastic and changes length as the sarcomere contracts and relaxes. Each nebulin molecule is exactly the length of a thin filament. The actin filaments are also coated with tropomyosin and bound intermittently by troponin (not shown; see Figure 16–31) and are capped at both ends. Tropomodulin caps the minus end of the actin filaments, and CapZ anchors the plus end at the Z disc, which also contains α-actinin (not shown).],
    path: "../fig/image_place_holder.png"
  ),
  "16-30": (
    caption: [T tubules and the sarcoplasmic reticulum. (A) Drawing of the two membrane systems that relay the signal to contract from the muscle cell plasma membrane to all of the myofibrils in the cell. (B) Electron micrograph showing a cross section of a T tubule. Note the position of the large Ca2+-release channels in the sarcoplasmic reticulum membrane that connect to the adjacent T-tubule membrane. (C) Schematic diagram showing how a Ca2+-release channel in the sarcoplasmic reticulum membrane is thought to be opened by the activation of a voltage-gated Ca2+ channel in the membrane of the T tubule (Movie 16.7). (B, courtesy of Clara Franzini-Armstrong.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-31": (
    caption: [The control of skeletal muscle contraction by troponin. (A) A thin filament of a skeletal muscle cell, showing the positions of tropomyosin and troponin along the actin filament. Each tropomyosin molecule has seven evenly spaced regions with similar amino acid sequences, each of which is thought to bind to an actin subunit in the filament. (B) Reconstructed cryo-electron microscopy image of an actin filament showing the relative position of a superimposed tropomyosin strand in the presence (dark purple) or absence (light purple) of calcium. (A, adapted from G.N. Phillips et al., J. Mol. Biol. 192:111–131, 1986; B, adapted from C. Xu et al., Biophys. J. 77:985–992, 1999. With permission from the Biophysical Society.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-32": (
    caption: [Smooth muscle contraction. (A) Upon muscle stimulation by activation of cell-surface receptors, Ca2+ released into the cytoplasm from the sarcoplasmic reticulum (SR) binds to calmodulin (see Figure 15–34). Ca2+-bound calmodulin then binds myosin light-chain kinase (MLCK), which phosphorylates myosin light chain, stimulating myosin activity. Non- muscle myosin is regulated by the same mechanism (see Figure 16–34). (B) Smooth muscle cells in a cross section of cat intestinal wall. The outer layer of smooth muscle is oriented with the long axis of its cells extending parallel along the length of the intestine, and upon contraction will shorten the intestine. The inner layer is oriented circularly around the intestine and when contracted will cause the intestine to become narrower. Contraction of both layers squeezes material through the intestine, much like squeezing toothpaste out of a tube. (C) A model for the contractile apparatus in a smooth muscle cell, with bundles of contractile filaments containing actin and myosin (red) oriented obliquely to the long axis of the cell. Their contraction greatly shortens the cell. In this diagram, the bundle angles are exaggerated to schematically illustrate the effect of contraction. In addition, only a few of the many bundles are shown. (B, courtesy of Gwen V. Childs.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-33": (
    caption: [Effect on the heart of a subtle mutation in cardiac myosin. Left, normal heart from a 6-day-old mouse pup. Right, heart from a pup with a point mutation in both copies of its cardiac myosin gene, changing Arg403 to Gln. The arrows indicate the atria. In the heart from the pup with the cardiac myosin mutation, both atria are greatly enlarged (hypertrophic), and the mice die within a few weeks of birth. (From D. Fatkin et al., J. Clin. Invest. 103:147–153, 1999. With permission from the American Society for Clinical Investigation.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-34": (
    caption: [Light-chain phosphorylation and the regulation of the assembly of myosin II into thick filaments. (A) Phosphorylation by myosin light-chain kinase (MLCK) of one of the two light chains (the so-called regulatory light chain, shown in light blue) on non-muscle myosin II in a test tube has at least two effects: it causes a change in the conformation of the myosin heads, relieving steric inhibition to permit actin binding, and it releases the myosin tail from a “sticky patch” on the myosin head, thereby allowing the myosin molecules to assemble into short, bipolar, thick filaments. Smooth muscle is regulated by the same mechanism (see Figure 16–32). (B) Fluorescence micrograph showing the distribution of myosin light chain (yellow) and the actin filament cross-linker α-actinin (blue) in the contractile fibers of a rat embryo fibroblast. (C) A parallel stack of myosin filaments at higher magnification. These myosin II filaments are much smaller than those found in skeletal muscle cells (see Figure 16–22), but nevertheless form sarcomere-like units. (B and C, courtesy of Shiqiong Hu and Alexander Bershadsky.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-35": (
    caption: [Myosin superfamily members. Comparison of the domain structure of the heavy chains of some myosin types. All myosins share similar motor domains (shown in dark green), but their C-terminal tails (light green) and N-terminal extensions (light blue) are very diverse. On the right are depictions of the molecular structures for these family members. Many myosins form dimers, with two motor domains per molecule, but a few (such as I, III, and XIV) seem to function as monomers, with just one motor domain. Myosin VI, despite its overall structural similarity to other family members, is unique in moving toward the minus end (instead of the plus end) of an actin filament. The small insertion within its motor head domain, not found in other myosins, is probably responsible for this change in direction.],
    path: "../fig/image_place_holder.png"
  ),
  "16-36": (
    caption: [Myosin V walks along actin filaments. (A) The lever arm of myosin V is long, allowing it to take a bigger step along an actin filament than can myosin II (see Figure 16–24). (B) Atomic force microscopy images showing myosin V (green) walking along an actin filament. Myosin V functions to carry cargo in cells. (B, adapted from N. Kodera and T. Ando, Biophys. Rev. 6:237–260, 2014. Reproduced with permission of SNCSC.) 30 nm],
    path: "../fig/image_place_holder.png"
  ),
  "16-37": (
    caption: [The structure of a microtubule and its subunit. (A) The subunit of each protofilament is a tubulin heterodimer, formed from a tightly linked pair of α- and β-tubulin monomers. The GTP molecule in the α-tubulin monomer is so tightly bound that it can be considered an integral part of the protein. The GTP molecule in the β-tubulin monomer, however, is less tightly bound and has an important role in filament dynamics. GTP is shown in red. (B) One tubulin subunit (αβ-heterodimer) and one protofilament are shown schematically. Each protofilament consists of many adjacent subunits with the same orientation. (C) The microtubule is a stiff hollow tube formed from 13 protofilaments aligned in parallel. (D) A short segment of a microtubule viewed in an electron microscope. (E) Electron micrograph of a cross section of a microtubule showing a ring of 13 protofilaments. (A, PDB code: 1JFF; D, courtesy of Richard Wade; E, courtesy of Richard Linck.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-38": (
    caption: [The preferential growth of microtubules at the plus end. Microtubules grow faster at one end than at the other. A stable bundle of microtubules obtained from the core of a cilium (called an axoneme) was incubated for a short time with tubulin subunits under polymerizing conditions. Microtubules grew fastest from the plus end of the microtubule bundle, the end on the right in this micrograph. (Courtesy of Gary Borisy.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-39": (
    caption: [and Figure 16–40A; see Panel 16–2). The change from growth to shrinkage is called a catastrophe, while the change from shrinkage to growth is called a rescue.],
    path: "../fig/image_place_holder.png"
  ),
  "16-39": (
    caption: [Direct observation of the dynamic instability of microtubules in a living cell. Microtubules in a newt lung epithelial cell were observed after the cell was injected with a small amount of fluorescently labeled tubulin. Notice the dynamic instability of microtubules at the edge of the cell. Four individual microtubules are highlighted for clarity; each of these shows alternating shrinkage and growth (Movie 16.9). (Courtesy of Wendy C. Salmon and Clare Waterman.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-40": (
    caption: [Dynamic instability due to the structural differences between a growing and a shrinking microtubule end. (A) If the free tubulin concentration in solution is near the critical concentration, a single microtubule end may undergo transitions between a growing state and a shrinking state. A growing microtubule has GTP-containing subunits at its end, forming a GTP cap. If GTP hydrolysis proceeds more rapidly than subunit addition, the cap is lost and the microtubule begins to shrink, an event called a catastrophe. But GTP-containing subunits may still add to the shrinking end, and if enough add to form a new cap, then microtubule growth resumes, an event called a rescue. (B) Model for the structural consequences of GTP hydrolysis in the microtubule lattice. The addition of GTP-containing tubulin subunits to the end of a protofilament causes the end to grow in a linear conformation that can readily pack into the cylindrical wall of the microtubule. Hydrolysis of GTP after assembly changes the conformation of the subunits and tends to force the protofilament into a curved shape that is less able to pack into the microtubule wall. (C) In an intact microtubule with a stable cap of GTP-tubulin, protofilaments made from GDP-containing subunits are forced into a linear conformation by the many lateral bonds within the microtubule wall. Loss of the GTP cap, however, allows the GDP-containing protofilaments to relax into their more curved conformation. This leads to a progressive disruption of the microtubule. Above the drawings of a growing and a shrinking microtubule, electron micrographs show actual microtubules in each of these two states. Note particularly the curling, disintegrating GDP-containing protofilaments at the end of the shrinking microtubule. (C, © 1991 E.M. Mandelkow, E. Mandelkow, and R.A. Milligan. Originally published in J. Cell Biol. https://doi.org/10.1083/jcb.114.5.977. With permission from Rockefeller University Press.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-41": (
    caption: [Microtubule nucleation by the g-tubulin ring complex. (A) Two copies of γ-tubulin associate with a pair of accessory proteins to form the γ-tubulin small complex (γ-TuSC). This image was generated by high-resolution electron microscopy of individual purified complexes. (B) Seven copies of the γ-TuSC associate to form a spiral structure in which the last γ-tubulin lies beneath the first, resulting in 13 exposed γ-tubulin subunits in a circular orientation that matches the orientation of the 13 protofilaments in a microtubule. (C) In many cell types, the γ-TuSC spiral associates with additional accessory proteins to form the γ-tubulin ring complex (γ-TuRC), which is likely to nucleate the minus end of a microtubule as shown here. Note the longitudinal discontinuity between two protofilaments, which results from the spiral orientation of the γ-tubulin subunits. Microtubules often have one such “seam” breaking the otherwise uniform helical packing of the protofilaments. (A and B, from J.M. Kollman et al., Nature 466:879–883, published 2010 by Macmillan Publishers Ltd. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-42": (
    caption: [The centrosome. (A) The centrosome is a major MTOC in animal cells. Located in the cytoplasm next to the nucleus, it consists of a pair of centrioles surrounded by an amorphous matrix of fibrous proteins, the pericentriolar material, in which the γ-tubulin ring complexes that nucleate microtubule growth are embedded. (B) A centrosome with attached microtubules. The minus end of each microtubule is embedded in the centrosome, having grown from a γ-tubulin ring complex, whereas the plus end of each microtubule is free in the cytoplasm. (C) In a reconstructed image of the MTOC from a C. elegans cell, a dense thicket of microtubules can be seen emanating from the centrosome. (C, from E.T. O’Toole et al., J. Cell Biol. 163:451–456, 2003. With permission from the authors.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-43": (
    caption: [A pair of centrioles in the centrosome. (A) An electron micrograph of a thin section of an isolated centrosome from an interphase cell showing the mother centriole with its distal appendages and the adjacent daughter centriole, which formed through a duplication event during S phase (see Figure 17–29). In the centrosome, the centriole pair is surrounded by a dense matrix of pericentriolar material from which microtubules nucleate. Centrioles also function as basal bodies to nucleate the formation of ciliary axonemes (see Figure 16–58). (B) Electron micrograph of a cross section through a centriole in the cortex of a protozoan. Each centriole is composed of nine sets of microtubule triplets arranged to form a cylinder. (C) Each triplet contains one complete microtubule (the A microtubule) fused to two incomplete microtubules (the B and C microtubules). (D) The centriolar protein SAS-6 forms a coiled-coil dimer. Nine SAS-6 dimers can self-associate to form a ring. Located at the hub of the centriole cartwheel-like structure, the SAS-6 ring is thought to generate the ninefold symmetry of the centriole. (A, from M. Paintrand et al., J. Struct. Biol. 108:107, 1992. With permission from Elsevier; B, courtesy of Richard Linck; D, courtesy of Michel Steinmetz.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-44": (
    caption: [Microtubule organization in different cell types. Microtubules (green) are organized by MTOCs (red), which nucleate, anchor, or stabilize the microtubule minus ends. A single focal MTOC in a fibroblast or yeast cell is the primary nucleation site and leads to microtubules organized with their plus ends extending out toward the cell periphery. A more complex distribution of microtubule plus and minus ends is observed in other cell types.],
    path: "../fig/image_place_holder.png"
  ),
  "16-45": (
    caption: [Localization of MAPs in the axon and dendrites of a neuron. This immunofluorescence micrograph shows the distribution of the proteins tau (green) and MAP2 (orange) in a hippocampal neuron in culture. Whereas tau staining is confined to the axon (long and branched in this neuron), MAP2 staining is confined to the cell body and its dendrites. The antibody used here to detect tau binds only to unphosphorylated tau; phosphorylated tau is also present in dendrites. (Courtesy of James W. Mandell and Gary A. Banker.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-46": (
    caption: [Organization of microtubule bundles by MAPs. (A) One end of MAP2 binds along the microtubule lattice and extends a long projecting arm. (B) Tau possesses a shorter projection arm. (C) Electron micrograph showing a cross section through a microtubule bundle in a cell overexpressing MAP2. The regular spacing of the microtubules (MTs) in this bundle results from the constant length of the projecting arms of MAP2. (D) Similar cross section through a microtubule bundle in a cell overexpressing tau. Here the microtubules are spaced more closely together than they are in C because of tau’s relatively short projecting arm. (C and D, from J. Chen et al., Nature 360:674–677, published 1992 by Nature Publishing Group. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-47": (
    caption: [Microtubule branching by augmin. (A) Augmin binds along the side of an existing microtubule and recruits a γ-tubulin ring complex that nucleates a new microtubule with a low branching angle. (B) Fluorescence micrographs showing augmin (orange) nucleating a microtubule branch in the cortex of an epidermal cell in the plant Arabidopsis thaliana. (C) Depletion of augmin severely stunts plant growth. (B, from W. Liu et al., J. Integr. Plant Biol. 61:388–393, 2019; C, from T. Liu et al., Curr. Biol. 24:2708–2713, 2014. With permission from Elsevier.) γ-tubulin ring complex],
    path: "../fig/image_place_holder.png"
  ),
  "16-48": (
    caption: [The effects of proteins that bind to microtubule ends. The transition between microtubule growth and shrinkage is controlled in cells by a variety of proteins. Catastrophe factors such as kinesin-13, a member of the kinesin motor protein superfamily, bind to microtubule ends and pry them apart, thereby promoting depolymerization. On the other hand, a MAP such as XMAP215 promotes rapid microtubule polymerization (XMAP stands for Xenopus microtubule- associated protein, and the number refers to its molecular mass in kilodaltons). XMAP215 binds tubulin dimers and delivers them to the microtubule plus end, thereby increasing the microtubule growth rate.],
    path: "../fig/image_place_holder.png"
  ),
  "16-49": (
    caption: [1TIP proteins found at the growing plus ends of microtubules. (A) Frames from a fluorescence time-lapse movie of the edge of a cell expressing fluorescently labeled tubulin that incorporates into microtubules (green) as well as the +TIP protein EB1 tagged with a different color (red). The same microtubule is marked (asterisk) in successive movie frames. When the microtubule is growing (frames 1, 2), EB1 is associated with the tip. When the microtubule undergoes a catastrophe and begins shrinking, EB1 is lost (frames 3, 4). The labeled EB1 is regained when growth of the microtubule is rescued (frame 5). See Movie 16.11. (B) In the fission yeast Schizosaccharomyces pombe, microtubules (green) are bound at their plus ends by the homolog of EB1 (red) as they grow toward the two poles of the rod-shaped cells. (A, courtesy of Anna Akhmanova and Ilya Grigoriev; B, courtesy of Takeshi Toda.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-50": (
    caption: [Sequestration of tubulin by stathmin. Structural studies with electron microscopy and crystallography suggest that the elongated stathmin protein binds along the side of two tubulin heterodimers. (Adapted from M.O. Steinmetz et al., EMBO J. 19:572–580, 2000.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-51": (
    caption: [Microtubule severing by katanin can destabilize or amplify microtubules. (A) Taxol-stabilized, fluorescently labeled microtubules were adsorbed on the surface of a glass slide, to which purified katanin was added along with ATP. There are a few breaks in the microtubules 30 seconds after the addition of katanin. (B) Three minutes after the addition of katanin, the filaments have been severed in many places, leaving a series of small fragments at the previous locations of the long microtubules. (C) Incorporation of GTP-tubulin subunits from the soluble pool into sites of katanin-induced damage in the microtubule lattice stabilizes the severed end or generates an island of GTP- tubulin that promotes rescue. (A and B, from J.J. Hartman et al., Cell 93:277–287, 1998. With permission from Elsevier. C, adapted from A. Vemu et al., Science 361: eaau1504, 2018. With permission from AAAS.) (A) (B) 20 µm],
    path: "../fig/image_place_holder.png"
  ),
  "16-52": (
    caption: [Kinesins. Structures of four kinesin superfamily members. As in the myosin superfamily, only the motor domains are conserved. Kinesin-1 has the motor domain at the N-terminus of the heavy chain and moves toward the microtubule plus end. The middle domain forms a long coiled-coil, mediating dimerization. The C-terminal domain forms a tail that attaches to cargo, such as a membrane-enclosed organelle. Kinesin-5 forms tetramers in which two dimers associate by their tails. The bipolar kinesin-5 tetramer is able to slide two microtubules past each other, analogous to the activity of the bipolar thick filaments formed by myosin II. Kinesin-13 has its motor domain located in the middle of the heavy chain. It is a member of a family of kinesins that have lost typical motor activity and instead bind to microtubule ends to promote depolymerization (see Figure 16–48). Kinesin-14 is a C-terminal kinesin. Unlike most kinesins, members of the kinesin-14 family travel toward the microtubule minus end. 1000 Chapter 16: The Cytoskeleton N N kinesin-1 N N kinesin-5 N C C N N N],
    path: "../fig/image_place_holder.png"
  ),
  "16-53": (
    caption: [The mechanochemical cycle of kinesin. Kinesin-1 is a dimer of two ATP-binding motor domains (heads) that are connected through a long coiled-coil tail (see Figure 16–52). The two kinesin motor domains work in a coordinated manner; during a kinesin “step,” the rear head detaches from its tubulin binding site on the microtubule, passes the partner motor domain, and then rebinds to the next available binding site. Using this “hand-over-hand” motion, the kinesin dimer can move for long distances on the microtubule without completely letting go of its track.],
    path: "../fig/image_place_holder.png"
  ),
  "16-54": (
    caption: [Cytoplasmic dynein. (A) Cryo-electron microscopy (cryoEM) reconstruction of a molecule of cytoplasmic dynein. Like myosin II and kinesin-1, cytoplasmic dynein is a two-headed molecule. The dynein head is very large compared with the head of either myosin or kinesin. (B) Schematic depiction of cytoplasmic dynein showing the two heavy chains that contain a motor head with domains for microtubule binding and ATP hydrolysis, connected by a long stalk. The tail domain consists of a linker that connects the motor heads to a dimerization domain. Bound to the linker domain are multiple intermediate chains and light chains (blue) that help to mediate many of dynein’s functions. (C) The organization of domains in a dynein heavy chain. This is a huge polypeptide, containing more than 4000 amino acids. The conserved dynein motor head domain contains six AAA domains, four of which retain ATP-binding sequences, but only one of which has the major ATPase activity (brown). The tail domain is not as highly conserved as the head domain and varies among different dynein subtypes. (A, courtesy of Andrew Carter.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-55": (
    caption: [The power stroke of dynein. Illustration of the movement of a monomeric axonemal dynein found in the flagellum of the unicellular green alga Chlamydomonas reinhardtii. As in cytoplasmic dynein, the motor-containing head domain of axonemal dynein connects to a long, coiled-coil stalk with the microtubule-binding site at the tip. The tail attaches to an adjacent microtubule in the axoneme. Movement is thought to occur through a “linker-swing, dynein- winch” mechanism. ATP binding and hydrolysis cause the linker to throw the head domain toward the microtubule minus end like a fishing hook. The microtubule-binding domain reattaches 8 nm along the microtubule. Release of ATP and phosphate then leads to a large conformational power stroke in the linker domain, pulling the tail and its attached microtubule toward the minus end. Each cycle generates a step of about 8 nm, thereby contributing to flagellar beating (see Figure 16–60). In the case of cytoplasmic dynein, the tail is attached to a cargo such as a vesicle, and a single power stroke transports the cargo about 8 nm along the microtubule toward its minus end (see Figure 16–56).],
    path: "../fig/image_place_holder.png"
  ),
  "16-56": (
    caption: [Dynactin and an adaptor protein mediate the attachment of dynein to a membrane-enclosed organelle. Dynein requires the presence of a large number of accessory proteins to associate with membrane-enclosed organelles. Dynactin is a large complex that includes components that bind weakly to microtubules, components that bind to dynein itself, and components that form a small, actin-like filament made of the actin- related protein Arp1. Dynactin associates with two molecules of cytoplasmic dynein as well as with an adaptor protein that mediates the connection to a cargo.],
    path: "../fig/image_place_holder.png"
  ),
  "16-57": (
    caption: [Regulated melanosome movements in fish pigment cells. These giant cells, which are responsible for changes in skin coloration in several species of fish, contain large pigment granules called melanosomes. The melanosomes can change their location in the cell in response to a hormonal or neuronal stimulus. (A) Schematic view of a pigment cell, showing the dispersal and aggregation of melanosomes (brown) in response to an increase or decrease in intracellular cyclic AMP (cAMP), respectively. Both redistributions of melanosomes occur along microtubules. (B) Bright-field images of a single cell in a scale of an African cichlid fish, showing its melanosomes either dispersed throughout the cytoplasm (left) or aggregated in the center of the cell (right). (B, courtesy of Leah Haimo.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-58": (
    caption: [The arrangement of microtubules in a flagellum or cilium. (A) Electron micrograph of the flagellum of a green-alga cell (Chlamydomonas) shown in cross section, illustrating the distinctive “9 + 2” arrangement of microtubules. (B) Diagram of the parts of a flagellum or cilium. The various projections from the microtubules link the microtubules together and occur at regular intervals along the length of the axoneme. (C) High-resolution electron tomography image of an outer microtubule doublet showing structural details and features inside the microtubules called microtubule inner proteins (MIPs). (A, courtesy of Lewis Tilney; C, courtesy of Daniela Nicastro.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-59": (
    caption: [Axonemal dynein. CryoEM reconstruction of a sea urchin sperm flagellum showing dynein arms connecting the A microtubule of one doublet with the B microtubule of an adjacent doublet at regular intervals. Sperm axonemal dynein is dimeric. The tail of the molecule binds tightly to an A microtubule, while the two globular heads each have a stalk that connects to an ATP-dependent binding site on a B microtubule (see Figure 16–58). When the heads hydrolyze their bound ATP, they move toward the minus end of the B microtubule, thereby producing a sliding force between the adjacent microtubule doublets in a cilium or flagellum (see Figure 16–60). (Courtesy of Daniela Nicastro.) A microtubule B microtubule 50 nm],
    path: "../fig/image_place_holder.png"
  ),
  "16-60": (
    caption: [The bending of an axoneme. (A) When axonemes are exposed to the proteolytic enzyme trypsin, the flexible protein links holding adjacent microtubule doublets together are broken. In this case, the addition of ATP allows the motor action of the dynein heads to slide one microtubule doublet against the adjacent doublet. (B) In an intact axoneme (such as in a spermatozoon), the flexible protein links prevent the sliding of the doublet. The motor action therefore causes a bending motion, creating waves or beating motions.],
    path: "../fig/image_place_holder.png"
  ),
  "16-61": (
    caption: [Primary cilia. (A) Electron micrograph and diagram of the basal body of a mouse neuron primary cilium. The axoneme of the primary cilium (black arrow) is nucleated by the mother centriole at the basal body, which localizes at the plasma membrane near the cell surface. (B) Centrioles function alternately as basal bodies and as the core of centrosomes. Before a cell enters the cell-division cycle, the primary cilium is shed or resorbed. The centrioles recruit pericentriolar material and duplicate during S phase, generating two centrosomes, each of which contains a pair of centrioles. The centrosomes nucleate microtubules and localize to the poles of the mitotic spindle. Upon exit from mitosis, a primary cilium again grows from the mother centriole. (A, courtesy of Josef Spacek.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-2": (
    caption: [Major Types of Intermediate Filament Proteins in Vertebrate Cells],
    path: "../fig/image_place_holder.png"
  ),
  "16-62": (
    caption: [A model of intermediate filament construction. An electron micrograph of intermediate filaments is shown in (A). The monomer shown in (B) pairs with another monomer to form a dimer, in which the conserved central rod domains are aligned in parallel and wound together into a coiled-coil. (C) Two dimers then line up side by side to form an antiparallel tetramer of four polypeptide chains. Dimers and tetramers are the soluble subunits of intermediate filaments. (D) Within each tetramer, the two dimers are offset with respect to one another, thereby allowing it to associate with another tetramer. (E) In the final 10-nm-diameter filament, tetramers are packed together in a rope-like array, which has 16 dimers (32 coiled-coils) in cross section. Half of these dimers are pointing in each direction. An electron micrograph of intermediate filaments is shown on the upper left (Movie 16.16). (A, from L. Norlén et al., Exp. Cell Res. 313:2217–2227, 2007. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-63": (
    caption: [Keratin filaments in epithelial cells. Immunofluorescence micrograph of the network of keratin filaments (blue) in a sheet of epithelial cells in culture. The filaments in each cell are indirectly connected to those of its neighbors by desmosomes (discussed in Chapter 19). A second protein (red) has been stained to reveal the location of the cell boundaries. (From K.J. Green and C.A. Gaudry, Nat. Rev. Mol. Cell Biol. 1:208–216, published 2000 by Nature Publishing Group. Reproduced with permission of SNCSC.) 10 µm],
    path: "../fig/image_place_holder.png"
  ),
  "16-64": (
    caption: [Blistering of the skin caused by a mutant keratin gene. A mutant gene encoding a truncated keratin protein (lacking both the N- and C-terminal domains) was expressed in a transgenic mouse. The defective protein assembles with the normal keratins and thereby disrupts the keratin filament network in the basal cells of the skin. Light micrographs of cross sections of (A) normal and (B) mutant skin show that the blistering results from the rupturing of cells in the basal layer of the mutant epidermis (short red arrows). (C) A sketch of three cells in the basal layer of the mutant epidermis, as observed by electron microscopy. As indicated by the red arrow, the cells rupture between the nucleus and the hemidesmosomes (discussed in Chapter 19), which connect the keratin filaments to the underlying basal lamina. (A and B, © 1991 P.A. Coulombe et al. Originally published in J. Cell Biol. https://doi.org/10.1083/jcb.115.6.1661. With permission from Rockefeller University Press.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-65": (
    caption: [Two types of intermediate filaments in cells of the nervous system. (A) Freeze-etch electron microscopy image of neurofilaments in a nerve cell axon, showing the extensive cross-linking through protein cross-bridges—an arrangement believed to give this long cell process great tensile strength. The cross-bridges are formed by the long, nonhelical extensions at the C-terminus of the largest neurofilament protein (NF-H). (B) Freeze-etch image of glial filaments in glial cells, showing that these intermediate filaments are smooth and have few cross-bridges. (C) Conventional transmission electron micrograph of a cross section of an axon showing the regular side-to-side spacing of the neurofilaments, which greatly outnumber the microtubules. (A and B, courtesy of Nobutaka Hirokawa; C, courtesy of Anthony Brown.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-66": (
    caption: [Plectin cross-linking of diverse cytoskeletal elements. Plectin (green) is seen here making cross- links from intermediate filaments (blue) to microtubules (red). In this electron micrograph, the dots (yellow) are gold particles linked to anti-plectin antibodies. The entire actin filament network was removed to reveal these proteins. (© 1996 T.M. Svitkina et al. Originally published in J. Cell Biol. http://doi.org/10.1083/ jcb.135.4.991. With permission from Rockefeller University Press.) 0.5 µm],
    path: "../fig/image_place_holder.png"
  ),
  "16-67": (
    caption: [SUN–KASH protein complexes connect the nucleus and cytoplasm through the nuclear envelope. The cytoplasmic cytoskeleton is linked across the nuclear envelope to the nuclear lamina or chromosomes through SUN and KASH proteins (orange and purple, respectively). The SUN and KASH domains of these proteins bind within the lumen of the nuclear envelope. From the inner nuclear envelope, SUN proteins connect to the nuclear lamina or chromosomes. KASH proteins in the outer nuclear envelope connect to the cytoplasmic cytoskeleton by binding microtubule motor proteins, actin filaments, or plectin.],
    path: "../fig/image_place_holder.png"
  ),
  "16-68": (
    caption: [Cell compartmentalization by septins. (A) Septins form filaments in the neck region between a mother yeast cell and bud. (B) In this photomicrograph of human cultured cells, the DNA is stained blue and septins are labeled in green. The microtubules of primary cilia are labeled with an antibody that recognizes a modified (acetylated) form of tubulin (red) that is enriched in the axoneme. (C) A magnified image reveals a collar of septin at the base of the cilium. (A, © 1976 B. Byers and L. Goetsch. Originally published in J. Cell Biol. https://doi.org/10.1083 /jcb.69.3.717. With permission from Rockefeller University Press; B and C, from Q. Hu et al., Science 329:436–439, 2010. With permission from AAAS.) (A)],
    path: "../fig/image_place_holder.png"
  ),
  "16-69": (
    caption: [Septins polymerize to form paired filaments and sheets. (A) Electron micrograph of a septin rod assembled by combining two copies each of the four yeast septins illustrated at the right. The eight-subunit rod is nonpolar because the central pair of subunits (Cdc10) creates a symmetrical dimer. (B) Electron micrograph of paired septin filaments and sheets, assembled from purified septins in the presence of high salt concentrations. (C) Paired septin filaments may assemble by lateral association between filaments, mediated by coiled-coils formed between the paired C-terminal extensions of Cdc3 and Cdc12 that project from each filament. (From A. Bertin et al., Proc. Natl. Acad. Sci. USA 105:8274–8279, 2008. With permission from the National Academy of Sciences.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-70": (
    caption: [Actin homologs in bacteria determine cell shape. The common soil bacterium Bacillus subtilis normally forms cells with a regular rodlike shape when viewed by scanning electron microscopy (left). In contrast, B. subtilis cells lacking the actin homolog MreB or Mbl grow in distorted or twisted shapes and eventually die (center and right). WT = wild type. \[From A. Chastanet and R. Carballido-Lopez, Front. Biosci. (Schol. Ed.) 4:1582–1606, 2012. With permission from Frontiers in Bioscience.\]],
    path: "../fig/image_place_holder.png"
  ),
  "16-71": (
    caption: [The bacterial FtsZ protein, a tubulin homolog in prokaryotes. (A) A band of FtsZ protein forms a ring in a dividing bacterial cell. This ring has been labeled by fusing the FtsZ protein to green fluorescent protein (GFP), which allows it to be observed in living E. coli cells with a fluorescence microscope. (B) FtsZ filaments and circles, formed in vitro, as visualized using electron microscopy. (C) Dividing chloroplasts (red) from a red alga also cleave using a protein ring made from FtsZ (yellow). (A, from X. Ma et al., Proc. Natl. Acad. Sci. USA 93:12998–13003, 1996; B, from H.P. Erickson et al., Proc. Natl. Acad. Sci. USA 93:519–523, 1996. Both with permission from National Academy of Sciences; C, from S. Miyagishima et al., Plant Cell 13:2257–2268, 2001, with permission from American Society of Plant Biologists.) (A) (B) (C) 1 µm 100 nm 1 µm],
    path: "../fig/image_place_holder.png"
  ),
  "16-72": (
    caption: [Caulobacter and crescentin. The sickle-shaped bacterium Caulobacter crescentus expresses a protein, crescentin, with a series of coiled- coil domains similar in size and organization to the domains of eukaryotic intermediate filaments. (A) The crescentin protein forms a fiber (labeled in red) that runs down the inner side of the curving bacterial cell wall. (B) When the gene is disrupted, the bacteria grow as straight rods (bottom). (From N. Ausmees et al., Cell 115:705– 713, 2003. With permission from Elsevier.) (A) 2 µm (B) 2 µm],
    path: "../fig/image_place_holder.png"
  ),
  "16-73": (
    caption: [Role of the actin homolog ParM in plasmid segregation in bacteria. (A) Some bacterial drug-resistance plasmids (orange) encode an actin homolog, ParM, that will spontaneously nucleate to form small, dynamic filaments (green) throughout the bacterial cytoplasm. A second plasmid-encoded protein called ParR (blue) binds to specific DNA sequences in the plasmid and also stabilizes the dynamic ends of the ParM filaments. When the plasmid duplicates, both ends of the ParM filaments become stabilized, and the growing ParM filaments push the duplicated plasmids to opposite ends of the cell. (B) In these bacterial cells harboring a drug-resistance plasmid, the plasmids are labeled in red and the ParM protein in green. Left, a short ParM filament bundle connects the two daughter plasmids shortly after their duplication. Right, the fully assembled ParM filament has pushed the duplicated plasmids to the cell poles. (A, adapted from E.C. Garner et al., Science 306:1021–1025, 2004; B, from J. Møller-Jensen et al., Mol. Cell 12:1477–1487, 2003. With permission from Elsevier.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-74": (
    caption: [MamK organizes chains of magnetosomes. (A) Three- dimensional reconstruction of a wild-type Magnetospirillum magneticum cell showing the cell membrane (gray), magnetosomes (yellow), and magnetosome-associated MamK filaments (green). (B) Magnetosomes appear disordered in a mamk deletion mutant, and no filaments are observed. (C) Magnetosomes are formed from invaginations of the plasma membrane and form chains along MamK filaments. (A and B, adapted from A. Komeili et al., Science 311:242–245, 2006. With permission from AAAS.) 1016 Chapter 16: The Cytoskeleton],
    path: "../fig/image_place_holder.png"
  ),
  "16-75": (
    caption: [The dramatic effects of Cdc42, Rac, and Rho on actin organization in fibroblasts. In each case, the actin filaments have been labeled with fluorescent phalloidin. (A) Serum-starved fibroblasts have actin filaments primarily in the cortex and relatively few stress fibers. (B) Microinjection of a constitutively activated form of Cdc42 results in many long filopodia at the cell periphery. (C) Microinjection of a constitutively activated form of Rac causes the formation of an enormous lamellipodium that extends from the entire circumference of the cell. (D) Microinjection of a constitutively activated form of Rho causes the rapid assembly of many prominent stress fibers. (From A. Hall, Science 279:509–514, 1998. With permission from Catherine Nobes.) (C) Rac ACTIVATION (D)],
    path: "../fig/image_place_holder.png"
  ),
  "16-76": (
    caption: [Cdc42 establishes yeast-cell polarity. (A) A positive feedback loop by which Cdc42-GTP recruits its own GEF to the plasma membrane to generate a focal site of Cdc42 activity. (B) Local activation of a formin protein by Cdc42- GTP nucleates actin filament assembly. Transport of vesicles along these actin filaments toward their plus ends by myosin V delivers cargoes necessary for growth of the bud.],
    path: "../fig/image_place_holder.png"
  ),
  "16-77": (
    caption: [PAR proteins establish two distinct cortical domains in C. elegans. (A) Symmetry breaking and polarity establishment occur in the fertilized egg before the maternal and paternal nuclei meet. After sperm entry, its centrosome duplicates and nucleates microtubules that decrease Rho GEF activity at what will become the posterior end of the embryo. This leads to accumulation of the anterior PAR proteins (including Par-3), allowing posterior PAR proteins (including Par-2) to bind the cortex at the posterior end. (B) Prior to fertilization, bundles of fluorescently labeled myosin II (white) are distributed throughout the cortex of the unpolarized egg because of the uniform distribution of activated Rho all along the plasma membrane, resulting in uniform cortical acto-myosin contractility. (C) After fertilization, local depletion of the Rho GEF near the sperm entry site (at right in this image) reduces myosin levels and contractility in the posterior cortex of the cell. (D) Par complex localization after polarization with Par-3 (red) at the anterior and Par-2 (green) at the posterior of the zygote. Multiple mechanisms operate to maintain this asymmetry through mutual antagonism between anterior and posterior PAR proteins. (B and C, from L. Rose and P. Gönczy, The C. elegans Research Community, WormBook, 2014, doi 10.1895/wormbook.1.30.2; D, from J. Nance and J.A. Zallen, Development 138:799–809, 2011. With permission from the Company of Biologists.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-78": (
    caption: [Cell-polarity protein modules identified in Drosophila. (A) PAR and Crumbs proteins cooperate to assemble the apical domain and junctional complexes, whereas Scribble defines the basolateral domain. Scribble and PAR are mutually antagonistic, whereas PAR and Crumbs reinforce each other. Cdc42 helps to recruit PAR proteins. (B) Fluorescence micrograph of a wild-type Drosophila larval epithelial tissue called the imaginal disc stained for actin (red) shows the well- organized, folded monolayer epithelium. (C) In a Scribble mutant, the imaginal disc has lost its normal morphology and grown dramatically larger because of hyperproliferation. Actively dividing cells are labeled yellow. (D) Higher-magnification image of a wild-type disc shows the polarized localization of actin (red) to the apical domain. (E) Actin organization is disrupted in the absence of Scribble. Nuclei are stained blue. (B and C, courtesy of David Bilder; D and E, from D. Bilder et al., Science 289:113–116, 2000. With permission from AAAS.)],
    path: "../fig/image_place_holder.png"
  ),
  "16-79": (
    caption: [Regulation of nucleation- promoting factors and formins by Rho family GTPases. (A) Members of the WAVE family of nucleation-promoting factors are activated upon binding to Rac-GTP at the plasma membrane. A conformational change in WAVE opens up the protein, allowing domains that were previously inaccessible to interact with both the Arp2/3 complex and profilin- bound actin subunits. For clarity, the WAVE regulatory complex is not shown. (B) The activity of some formin proteins is inhibited by an autoinhibitory interaction in the absence of an active GTPase. Binding to Rho-GTP exposes a binding site for the plus end of an actin filament, as well as profilin–actin binding domains.],
    path: "../fig/image_place_holder.png"
  ),
  "16-80": (
    caption: [The contrasting effects of Rac and Rho activation on actin organization. (A) Activation of the small GTPase Rac leads to alterations in actin accessory proteins that promote the formation of protrusive actin networks in lamellipodia and pseudopodia. Several different pathways contribute independently. Rac-GTP activates members of the WAVE protein family, which in turn activate actin nucleation and branched network formation by the Arp2/3 complex. In a parallel pathway, Rac- GTP activates the protein kinase PAK, which has several targets including the myosin light-chain kinase (MLCK), which is inhibited by phosphorylation. Inhibition of MLCK results in decreased phosphorylation of the myosin regulatory light chain and leads to myosin II filament disassembly and a decrease in contractile activity. In some cells, PAK also directly inhibits myosin II activity by phosphorylation of the myosin heavy chain (MHC). (B) Activation of the related GTPase Rho leads to nucleation of actin filaments by formins and increases contraction by myosin II, promoting the formation of contractile actin bundles at the rear of the cell and assembly of stress fibers. Activation of myosin II by Rho requires a Rho-associated kinase called ROCK. This kinase inhibits the phosphatase that removes the activating phosphate groups from myosin II light chains (MLC); it may also directly phosphorylate the myosin light chains in some cell types. ROCK also activates other protein kinases, such as LIM kinase, which in turn contributes to the formation of stable contractile actin filament bundles by inhibiting the actin- depolymerizing factor cofilin. A similar signaling pathway is important for forming the contractile ring necessary for cytokinesis (see Figure 17–45). 1022 Chapter 16: The Cytoskeleton (A)],
    path: "../fig/image_place_holder.png"
  ),
  "16-81": (
    caption: [Neutrophil polarization and chemotaxis. (A) The pipette tip at the right is leaking a small amount of the bacterial peptide formyl-Met-Leu- Phe, which is recognized by the human neutrophil as the product of a foreign invader. The neutrophil quickly extends a new lamellipodium toward the source of the chemoattractant peptide (top). It then extends this lamellipodium and polarizes its cytoskeleton so that contractile myosin II is located primarily at the rear, opposite the position of the lamellipodium (middle). Finally, the cell crawls toward the source of the peptide (bottom). If a real bacterium were the source of the peptide, rather than an investigator’s pipette, the neutrophil would engulf the bacterium and destroy it (see also Figure 16–3 and Movie 16.17). (B) Binding of bacterial molecules to G-protein-coupled receptors on the neutrophil stimulates directed motility. These receptors are found all over the surface of the cell, but are more likely to be bound to the bacterial ligand at the front. Two distinct signaling pathways contribute to the cell’s polarization. At the front of the cell, stimulation of the Rac pathway leads, via the trimeric G protein Gi, to growth of protrusive actin networks. Second messengers within this pathway are short-lived, so protrusion is limited to the region of the cell closest to the stimulant. The same receptor also stimulates a second signaling pathway, via the trimeric G proteins G12 and G13, that triggers the activation of Rho. The two pathways are mutually antagonistic. Because Rac-based protrusion is active at the front of the cell, Rho is activated only at the rear of the cell, stimulating contraction of the cell rear and assisting directed movement. (A, from O.D. Weiner et al., Nat. Cell Biol. 1:75–81, published 1999 by Macmillan Magazines Ltd. Reproduced with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
)