#let images = (
  "18-1": (
    caption: [shows a normal rat cell (panel A) and rat cells of the same type undergoing two different forms of cell death (panels B–D). In apop- tosis, the cell shrinks and condenses, the cytoskeleton collapses, the nuclear envelope disassembles, and the nuclear chromatin condenses and fragments (Figure 18–1B). The apoptotic cell surface often forms multiple large protrusions called blebs (Movie 18.1), and, if the cell is large, it breaks up into membrane- enclosed fragments called apoptotic bodies. Importantly, the surface of the cell and its fragments become chemically altered, so that a neighboring cell, often a macrophage in vertebrates, rapidly engulfs the cell and fragments before they can spill their contents (Figure 18–1C). In this way, the cell dies neatly, and the cell and its fragments are rapidly cleared away, without causing a damaging inflam- matory response. Because apoptotic cells are eaten and digested so quickly, there are often few dead cells to be seen, even in a tissue where large numbers of cells have died by apoptosis.],
    path: "../fig/image_place_holder.png"
  ),
  "18-1": (
    caption: [Two distinct forms of cell death. These electron micrographs show developing rat oligodendrocyte precursor cells in different states: (A) a normal cell in culture; (B) a cell in culture that has died by apoptosis because it was deprived of extracellular survival signals (discussed later); (C) a cell in a normal developing optic nerve that has died by apoptosis and has been engulfed by a neighboring phagocytic cell; (D) a cell in culture that died by necrosis. Note that the apoptotic cells in B and C have an intact plasma membrane, but the chromatin has become condensed and distorted and concentrated at the margin of the nucleus, whereas the necrotic cell in D seems to have exploded. The large vacuoles visible in the cytoplasm of the cell in B are a variable feature of apoptosis. (Courtesy of Julia Burne and Martin Raff.)],
    path: "../fig/image_place_holder.png"
  ),
  "18-2": (
    caption: [Sculpting the digits in the developing mouse paw by apoptosis. (A) The paw in this mouse fetus has been stained with the dye acridine orange, which MBoC7 m18.02/18.02 enters apoptotic cells and thereby brightly labels them in the normal developing paw. The apoptotic cells appear as bright green dots concentrated between the developing digits. (B) The interdigital cell death has eliminated much of the tissue between the developing digits, as seen one day later, when there are very few apoptotic cells. (From W. Wood et al., Development 127:5245–5252, 2000. With permission from the Company of Biologists.)],
    path: "../fig/image_place_holder.png"
  ),
  "18-3": (
    caption: [Activation of an initiator caspase at the start of apoptosis. An initiator caspase contains a protease domain in its large carboxyl-terminal region and a smaller, adaptor-protein-binding prodomain in its amino-terminal region. The caspase is made as an inactive monomer, which is activated by dimerization. The dimerization and activation only occurs when apoptotic signals trigger the assembly of specific adaptor-protein complexes (shown here as a hypothetical simplest form—a homodimer). Each type of adaptor complex then recruits multiple copies of one type of initiator caspase monomer, allowing them to dimerize and thereby become active. In the case shown, once activated, each monomer in the activated caspase dimer cross-cleaves its partner at specific sites; the cleavage in the protease domain enables the large and small caspase subunits to rearrange, and cleavage between the large protease domain and the prodomain releases the mature, active caspase dimer from the prodomain–adaptor complex.],
    path: "../fig/image_place_holder.png"
  ),
  "18-4": (
    caption: [Executioner caspase activation during apoptosis. Executioner caspases have very short prodomains, which lack sites for interacting with other proteins. They are initially formed as inactive dimers, which are activated by cleavage at a site in each protease domain, almost always by an initiator caspase. The cleavages allow the large and small subunits to rearrange to form two active protease sites, each of which then cleaves off the prodomain of its partner monomer to produce the mature, active executioner caspase, as shown. The mature activated caspase then cleaves a variety of cell target proteins, leading to the controlled apoptotic death of the cell.],
    path: "../fig/image_place_holder.png"
  ),
  "18-5": (
    caption: [DNA fragmentation during apoptosis. (A) In healthy cells, a caspase- activated DNase (CAD) is held in an inactive state by an inhibitor protein, iCAD. Activation of an executioner caspase, caspase-3, during apoptosis leads to cleavage of iCAD, releasing the active DNase to cut the chromosomal DNA between nucleosomes. (B) Because the DNA cleavage occurs only at accessible sites in linker regions between nucleosomes, the DNA is cut into fragments of variable size, equivalent to the DNA associated with either one or multiple nucleosomes (as shown in A), producing a ladder pattern upon DNA gel electrophoresis. The pattern shown was obtained by inducing apoptosis in mouse thymus lymphocytes with dexamethasone, extracting DNA at the times indicated at the top of the gel, separating the fragments by size by electrophoresis in an agarose gel, and staining the DNA in the gel with ethidium bromide. (B, from D. McIlroy et al., Genes Dev. 14:549–558, 2000. With permission from Cold Spring Harbor Laboratory Press.)],
    path: "../fig/image_place_holder.png"
  ),
  "18-6": (
    caption: [The extrinsic pathway of apoptosis activated through Fas death receptors. Trimeric Fas ligands on the surface of a killer lymphocyte bind to trimeric Fas death receptors on the surface of a target cell, inducing the target cell to kill itself by undergoing apoptosis by the extrinsic pathway. Although not shown, at least two trimeric Fas ligands have to bind to and cluster at least two trimeric Fas receptors to activate the pathway; for clarity, only a single copy of the ligand and receptor is shown. The ligand-induced receptor clustering (not shown) exposes a death domain on the receptor tails, as indicated here by the change in the color of the domain from light red to dark red upon exposure. Each exposed death domain binds to a similar exposed death domain on the cytosolic adaptor protein FADD (for Fas-associated death domain). The bound FADD protein then exposes a death effector domain (DED; dark blue), enabling FADD to recruit an inactive, monomeric initiator caspase (mainly caspase-8) MBoC7 m18.05/18.06 by binding to an exposed DED (dark blue) on the prodomain of the caspase. Each caspase-8 monomer has two DEDs, and, when one binds to an exposed DED, the other becomes exposed (as indicated by the change in the DED color from light blue to dark blue) and can recruit another caspase-8 monomer; this results in a chain reaction in which the caspase-8 monomers oligomerize into a three-dimensional helical filament (not shown), with each FADD protein attached to up to eight caspase-8 molecules. The end result is the assembly of a large death-inducing signaling complex (DISC) composed of multiple copies of Fas, FADD, and caspase-8. Within the DISC, neighboring caspase-8 monomers interact to form activated dimers, which can now cross-cleave their partner monomers (not shown, but see Figure 18–3), cleaving off the prodomain and forming the mature activated dimers, which are released into the cytosol, where they can cleave and activate executioner caspases to induce apoptosis. In human cells, the caspase-10 initiator caspase can also be incorporated into the DISC, but, unlike caspase-8, it is not essential for Fas-induced apoptosis.],
    path: "../fig/image_place_holder.png"
  ),
  "18-7": (
    caption: [Release of cytochrome c from mitochondria into the cytosol during the intrinsic pathway of apoptosis. These fluorescence micrographs show human cancer cells in culture. The cells were transfected with a gene encoding a fusion protein consisting of cytochrome c linked to green fluorescent protein (cytochrome c–GFP), and they were also treated with a red dye that accumulates in mitochondria. (A) Unstimulated control cells: the overlapping distribution of the green and red confirms that the cytochrome c–GFP is located in mitochondria. (B) Cells MBoC7 m18.06/18.07 were irradiated with ultraviolet (UV) light to induce the intrinsic pathway of apoptosis and were photographed 5 hours later. The seven cells in the bottom right of this micrograph have released their cytochrome c from mitochondria into the cytosol, whereas the other cells in the micrograph have not yet done so. (From J.C. Goldstein et al., Nat. Cell Biol. 2:156–162, published 2000 by Nature Publishing Group. Reprinted with permission of SNCSC.)],
    path: "../fig/image_place_holder.png"
  ),
  "18-8": (
    caption: [The intrinsic pathway of apoptosis. Intracellular apoptotic stimuli cause mitochondria to release cytochrome c. The binding of cytochrome c to the cytosolic adaptor protein Apaf1 induces a conformational change in Apaf1, which activates it, exposing a binding site for deoxy-ATP (dATP), an oligomerization domain, and a caspase recruitment domain (CARD). The exposed oligomerization domain mediates the assembly of Apaf1 into a wheel-like heptamer. Each CARD in the heptamer then recruits an inactive caspase-9 monomer through its own CARD, forming a large apoptosome, with the interacting CARDs clustered above the central hub of the apoptosome. The dATP is hydrolyzed to dADP during the assembly process. Within the apoptosome, the caspase-9 monomers are activated by dimerization. Activated caspase-9 dimers then cleave and activate downstream executioner caspases, leading to apoptosis. Note that the CARD domain is related in structure and function to the death effector domain (DED) of caspase-8 (see Figure 18–6). (It remains an important mystery how, during evolution, mitochondria and cyto- chrome c came to acquire their surprising role in apoptosis.)],
    path: "../fig/image_place_holder.png"
  ),
  "18-9": (
    caption: [Schematic drawing of the BH domains in the three classes of Bcl2 family proteins. Note that the BH3 domain is the only one of the four BH domains shared by all Bcl2 family members; it mediates the direct interactions between pro-apoptotic and anti-apoptotic family members (see Figure 18–10C and D).],
    path: "../fig/image_place_holder.png"
  ),
  "18-10": (
    caption: [How pro-apoptotic Bcl2 family effectors induce MOMP and how anti-apoptotic Bcl2 family proteins block it. (A) Most of the pro-apoptotic effector Bak is already attached to the outer mitochondrial membrane before the protein is activated. When activated by an apoptotic stimulus, the protein undergoes a conformational change that both exposes a BH3 domain and creates a BH3-binding groove, allowing Bak–Bak oligomerization in the outer membrane. (B) The Bak oligomers induce MOMP by creating openings in the outer membrane that allow cytochrome c and other soluble proteins in the intermembrane space to diffuse into the cytosol; although the details of how Bak (and Bax) oligomers produce the openings are uncertain, it is thought that they form large ring structures that disrupt the integrity of the outer membrane. Once released into the cytosol, cytochrome c stimulates the assembly of apoptosomes (see Figure 18–8). (C) The anti-apoptotic Bcl2 family protein BclxL, like Bak, is normally bound to the outer mitochondrial membrane, where it can interact via its BH3-binding groove to the exposed BH3 domain on activated Bak, thereby blocking Bak–Bak oligomerization, MOMP, and apoptosis. (D) One way BH3-only proteins such as Bad are thought to indirectly induce MOMP and apoptosis is by inhibiting certain anti-apoptotic Bcl2 family proteins such as BclxL.],
    path: "../fig/image_place_holder.png"
  ),
  "18-11": (
    caption: [How MOMP overcomes XIAP inhibition. In some mammalian cells, the presence of XIAP in the cytosol inhibits initiator caspase-9 and executioner caspases 3 and 7; the XIAP binds to the active site of the three enzymes, blocking their activities. However, as well as releasing cytochrome c, MOMP releases MBoC7 n18.103/18.11 two anti-IAP proteins, Smac and Omi, which inhibit the anti-caspase activity of XIAP, thereby allowing the activation of these caspases in the cytosol during the intrinsic pathway of apoptosis (see Figure 18–8).],
    path: "../fig/image_place_holder.png"
  ),
  "18-12": (
    caption: [How survival factors and apoptosis can help adjust the number of developing nerve cells to the size of the target tissue the nerve cells innervate. In this example, more nerve cells are produced than can be supported by the limited amount of survival factors produced by the cells in a target tissue. As a result, some nerve cells receive an insufficient amount of survival factor to avoid apoptosis. This strategy of overproduction followed by culling during development helps ensure that all the appropriate target cells are contacted by appropriate nerve cells and that surplus nerve cells are automatically eliminated.],
    path: "../fig/image_place_holder.png"
  ),
  "18-13": (
    caption: [Two of the various ways that extracellular survival factors can inhibit apoptosis. (A) Some survival factors suppress apoptosis by stimulating the transcription of genes that encode anti-apoptotic Bcl2 family proteins such as Bcl2 (as shown here) or BclxL. (B) Many others activate the serine/threonine protein kinase Akt, which, among many other targets, phosphorylates and inactivates the pro-apoptotic BH3-only protein Bad (see Figure 18–9). When not phosphorylated, Bad promotes apoptosis by binding to and inhibiting an anti-apoptotic Bcl2 family protein such as Bcl2 itself. Once phosphorylated, Bad dissociates, freeing Bcl2 to suppress apoptosis (see Figure 18–10C and Figure 15–54). Akt can also suppress apoptosis by phosphorylating and inactivating transcription regulatory proteins that stimulate the transcription of genes encoding proteins that promote apoptosis, such as the BH3-only protein Bim (not shown). There are also many other ways that survival factors can inhibit apoptosis that are not illustrated here.],
    path: "../fig/image_place_holder.png"
  ),
  "18-14": (
    caption: [and Movie 18.2. The appearance of PS on the cell surface also occurs in some forms of necrotic cell death, even in the absence of caspase activation; disruption of the plasma membrane is sufficient to do it.],
    path: "../fig/image_place_holder.png"
  ),
  "18-14": (
    caption: [The two caspase-dependent mechanisms responsible for the accumulation of phosphatidylserine on the surface of apoptotic cells. In healthy cells (top half of figure), an ATP-dependent aminophospholipid flippase (ATP11C) actively flips phosphatidylserine (PS) and phosphatidylethanolamine (PE) from the outer to the inner leaflet of the plasma membrane lipid bilayer, keeping these lipids mainly confined to the inner leaflet. During apoptosis (bottom half of figure), activated executioner caspases (caspase-3, caspase-7, or both) cleave and thereby inactivate the ATP11C flippase, preventing its lipid translocation activity; at the same time, the activated executioner caspases cleave and thereby activate a phospholipid scramblase (Xkr8) in the plasma membrane that nonspecifically flips phospholipids between the two lipid leaflets of the membrane, scrambling them between the leaflets. (Although not shown, the ATP11C flippase is tightly associated with a smaller transmembrane protein, CDC50, which is required to chaperone the flippase to the plasma membrane and possibly to assist in the lipid translocation process.)],
    path: "../fig/image_place_holder.png"
  ),
  "12-39": (
    caption: [illustrates the actions of phospholipid scramblases in lipid bilayer synthesis in the ER membrane and of phospholipid scramblases in generating lipid bilayer asymmetry in some other intraceullar membranes. (Modified from S. Nagata et al., Cell Death Differ. 23:952–961, 2016.)],
    path: "../fig/image_place_holder.png"
  ),
  "18-15": (
    caption: [A BH3-mimetic drug that specifically inhibits the Bcl2 anti- apoptotic Bcl2 family protein. As shown in Figure 18–10D, one way BH3-only proteins can promote apoptosis is by binding to the long BH3-binding groove in anti-apoptotic Bcl2 family proteins such as Bcl2 itself, thereby preventing the protein from blocking apoptosis. (A) The chemical structure of venetoclax, which was designed and synthesized to bind tightly and specifically in the BH3-binding groove of Bcl2. (B) Crystal structure of venetoclax (red) bound to the human Bcl2 protein (yellow). By inhibiting the activity of Bcl2, the drug promotes apoptosis in any cell that depends on this protein for survival, as is the case for cells of human chronic lymphocytic leukemia, for which this drug is in clinical use. (PDB code: 60OK.)],
    path: "../fig/image_place_holder.png"
  ),
)