#import "@preview/touying:0.6.1": *
#import themes.stargazer: *
#import "../image_list/02_Adaptations_to_the_Physical_Environment__Water_and_Nutrients_images.typ": images
#import "@preview/typsium:0.3.0": *
#set text(font: "Arial")

#show: stargazer-theme.with(
  config-info(
    title: "Adaptations to the Physical Environment: Water and Nutrients",
    subtitle: "Ecology",
    author: "Author Name",
    date: datetime.today().display("[month repr:long] [day], [year]"),
  )
)

#title-slide()
#outline-slide()

= Chapter Concepts
== Main Ideas
#slide[
- Water has many properties favorable to life
- Many inorganic nutrients are dissolved in water
- Plants obtain water and nutrients from the soil by the osmotic potential of their root cells
- Forces generated by transpiration help to move water from roots to leaves
- Salt balance and water balance go hand in hand
- Animals must excrete excess nitrogen without losing too much water
]

= Water and Life
== Physical Limits and Adaptations
#slide[
- Organisms are restricted by their physical environments (oxygen, temperature)
- Deep-diving mammals and birds have special adaptations for oxygen storage and insulation
- Life depends on water and energy
- Organisms affect and are affected by the physical world
][
#figure(
  image(images.at("2.1").path),
)
]

== Properties of Water Favorable to Life
#slide[
- Water is liquid over most of Earth's surface temperatures
- Water dissolves inorganic compounds, supporting chemical processes
- Water's density and viscosity support organisms but limit movement
- Streamlined shapes and flotation adaptations counteract sinking and drag
][
#figure(
  image(images.at("2.2").path),
)
]

#slide[
- Oil droplets in algae provide buoyancy
- Barracudas have streamlined bodies for efficient swimming
- Appendages in small aquatic animals prevent sinking
][
#figure(
  image(images.at("2.3").path),
)
]

#slide[
- Streamlined shapes reduce drag in water
][
#figure(
  image(images.at("2.4").path),
)
]

#slide[
- Filamentous appendages slow sinking in tiny aquatic animals
][
#figure(
  image(images.at("2.5").path),
)
]

== Thermal Properties of Water
#slide[
- Water resists temperature changes and remains liquid over a broad range
- High energy required for evaporation and freezing stabilizes aquatic environments
- Water expands and becomes less dense as it freezes, so ice floats
]

== Density and Viscosity
#slide[
- Water is 800 times denser than air, providing buoyancy
- High viscosity impedes movement, leading to adaptations in aquatic organisms
]

= Inorganic Nutrients in Water
== Major Nutrients Required
#slide[
- Organisms require hydrogen, carbon, oxygen, nitrogen, phosphorus, sulfur, potassium, calcium, magnesium, iron, sodium
- Diatoms use silicates for shells; tunicates accumulate vanadium; nitrogen-fixing bacteria require molybdenum
][
#figure(
  image(images.at("2.6").path),
)
]

== Solvent Capacity of Water
#slide[
- Water dissolves minerals from rocks and soils, making nutrients available
- Table salt (#ce("NaCl")) dissolves into sodium (#ce("Na^+")) and chloride (#ce("Cl^-")) ions
- Oceans concentrate ions over time; calcium carbonate precipitates as limestone
][
#figure(
  image(images.at("2.7").path),
)
]

== Hydrogen Ions and pH
#slide[
- Hydrogen ions (#ce("H^+")) are highly reactive and affect enzyme activity
- Acidity is measured as pH; pure water has pH 7
- Most natural waters have pH between 6 and 9
][
#figure(
  image(images.at("2.8").path),
)
]

#slide[
- Hydrogen ions help dissolve minerals, making nutrients available but can also mobilize toxic metals
]

= Water and Nutrient Uptake by Plants
== Soil Structure and Water-Holding Capacity
#slide[
- Soil particle size affects water retention; clay holds more water but less is available to plants
- Water potential (matric potential) determines water availability; field capacity is the maximum available water
][
#figure(
  image(images.at("2.9").path),
)
]

== Osmotic Potential and Water Uptake
#slide[
- Water moves from high to low water potential
- Osmosis allows plant roots to draw water from soil
- Osmotic potential depends on solute concentration; desert and salt-adapted plants increase solute concentration to lower water potential
][
#figure(
  image(images.at("2.10").path),
)
]

= Water Movement in Plants
== Transpiration and Cohesion–Tension Theory
#slide[
- Water moves from roots to leaves via xylem, driven by transpiration
- Water potential gradient from leaves to roots pulls water upward
- Stomates (stomata) control water loss and gas exchange
][
#figure(
  image(images.at("2.11").path),
)
]

#slide[
- Plants control water loss by opening and closing stomates on the leaf surface
][
#figure(
  image(images.at("2.12").path),
)
]

= Salt and Water Balance
== Osmoregulation in Plants
#slide[
- Plants pump excess salts back into the soil by active transport
- Mangroves maintain high organic solute concentrations and have salt glands to excrete salt
][
#figure(
  image(images.at("2.13").path),
)
]

== Osmoregulation in Animals
#slide[
- Terrestrial animals retain ions and excrete excess salts in urine
- Desert animals produce highly concentrated urine; birds and reptiles have salt glands
]

== Water Balance in Aquatic Animals
#slide[
- Freshwater fish are hyperosmotic; they gain water and lose solutes, so kidneys and gills retain salts
- Marine fish are hypo-osmotic; they lose water and must drink seawater, excreting excess salts
- Sharks retain urea to match osmotic potential of seawater
][
#figure(
  image(images.at("2.14").path),
)
]

#slide[
- Sharks match their total solute concentration to that of seawater
][
#figure(
  image(images.at("2.15").path),
)
]

#slide[
- Some marine invertebrates (e.g., Tigriopus) rapidly adjust osmotic potential by synthesizing or degrading amino acids
][
#figure(
  image(images.at("2.16").path),
)
]

= Nitrogen Excretion
== Strategies
#slide[
- Aquatic animals excrete ammonia (#ce("NH_3")) rapidly in dilute urine
- Terrestrial animals excrete urea (#ce("CO(NH_2)_2")) or uric acid (#ce("C_5H_4N_4O_3")) to conserve water
- Excreting urea and uric acid is energetically costly
]

= Summary
== Key Points
#slide[
- Water is the basic medium of life and a powerful solvent
- Water resists temperature changes and provides buoyancy
- All natural waters contain dissolved substances
- pH affects nutrient availability and toxicity
- Soil structure and water potential determine water availability to plants
- Plants and animals have adaptations for water and salt balance
- Nitrogen excretion strategies vary by environment
]
