#import "@preview/typsium:0.3.0": *
#import "../image_list/02_Adaptations_to_the_Physical_Environment__Water_and_Nutrients_images.typ": images
#set text(font: "Arial")
#set page(numbering: "1", number-align: center)

#align(center)[
#text(size: 2em)[*Adaptations to the Physical Environment: Water and Nutrients*]
]

= Chapter Concepts

- Water has many properties favorable to life
- Many inorganic nutrients are dissolved in water
- Plants obtain water and nutrients from the soil by the osmotic potential of their root cells
- Forces generated by transpiration help to move water from roots to leaves
- Salt balance and water balance go hand in hand
- Animals must excrete excess nitrogen without losing too much water

= Water and Life

== Physical Limits and Adaptations

- Organisms are restricted by their physical environments (e.g., oxygen and temperature for deep-diving mammals).
- Adaptations such as insulation (fat in seals, air in penguins) help maintain body temperature.
- Life depends on water as the basic medium and energy to power processes.
- Organisms affect and are affected by the physical world (e.g., oxygen in the atmosphere from photosynthesis).

#figure(
  image(images.at("2.1").path, width: 50%),
)

== Properties of Water Favorable to Life

- Water is liquid over most of Earth's surface temperatures.
- Water dissolves inorganic compounds, making it an excellent medium for chemical processes.
- Water's density and viscosity support organisms but also limit movement.
- Streamlined shapes and flotation adaptations (swim bladders, oil droplets, appendages) counteract sinking and drag.

#figure(
  image(images.at("2.2").path, width: 50%),
)
#figure(
  image(images.at("2.3").path, width: 50%),
)
#figure(
  image(images.at("2.4").path, width: 50%),
)
#figure(
  image(images.at("2.5").path, width: 50%),
)

== Thermal Properties of Water

- Water resists temperature changes and remains liquid over a broad range.
- High energy required for evaporation and freezing stabilizes aquatic environments.
- Water expands and becomes less dense as it freezes, so ice floats.

== Density and Viscosity

- Water is 800 times denser than air, providing buoyancy.
- High viscosity impedes movement, leading to adaptations in aquatic organisms.

= Inorganic Nutrients in Water

== Major Nutrients Required

- Organisms require hydrogen, carbon, oxygen, nitrogen, phosphorus, sulfur, potassium, calcium, magnesium, iron, sodium.
- Diatoms use silicates for shells; tunicates accumulate vanadium; nitrogen-fixing bacteria require molybdenum.

#figure(
  image(images.at("2.6").path, width: 50%),
)

== Solvent Capacity of Water

- Water dissolves minerals from rocks and soils, making nutrients available.
- Table salt (#ce("NaCl")) dissolves into sodium (#ce("Na^+")) and chloride (#ce("Cl^-")) ions.
- Oceans concentrate ions over time; calcium carbonate precipitates as limestone.

#figure(
  image(images.at("2.7").path, width: 50%),
)

== Hydrogen Ions and pH

- Hydrogen ions (#ce("H^+")) are highly reactive and affect enzyme activity.
- Acidity is measured as pH; pure water has pH 7.
- Most natural waters have pH between 6 and 9.

#figure(
  image(images.at("2.8").path, width: 50%),
)

- Hydrogen ions help dissolve minerals, making nutrients available but can also mobilize toxic metals.

= Water and Nutrient Uptake by Plants

== Soil Structure and Water-Holding Capacity

- Soil particle size affects water retention; clay holds more water but less is available to plants.
- Water potential (matric potential) determines water availability; field capacity is the maximum available water.

#figure(
  image(images.at("2.9").path, width: 50%),
)

== Osmotic Potential and Water Uptake

- Water moves from high to low water potential.
- Osmosis allows plant roots to draw water from soil.
- Osmotic potential depends on solute concentration; desert and salt-adapted plants increase solute concentration to lower water potential.

#figure(
  image(images.at("2.10").path, width: 50%),
)

= Water Movement in Plants

== Transpiration and Cohesion–Tension Theory

- Water moves from roots to leaves via xylem, driven by transpiration.
- Water potential gradient from leaves to roots pulls water upward.
- Stomates (stomata) control water loss and gas exchange.

#figure(
  image(images.at("2.11").path, width: 50%),
)
#figure(
  image(images.at("2.12").path, width: 50%),
)

= Salt and Water Balance

== Osmoregulation in Plants

- Plants pump excess salts back into the soil by active transport.
- Mangroves maintain high organic solute concentrations and have salt glands to excrete salt.

#figure(
  image(images.at("2.13").path, width: 50%),
)

== Osmoregulation in Animals

- Terrestrial animals retain ions and excrete excess salts in urine.
- Desert animals produce highly concentrated urine; birds and reptiles have salt glands.

== Water Balance in Aquatic Animals

- Freshwater fish are hyperosmotic; they gain water and lose solutes, so kidneys and gills retain salts.
- Marine fish are hypo-osmotic; they lose water and must drink seawater, excreting excess salts.
- Sharks retain urea to match osmotic potential of seawater.

#figure(
  image(images.at("2.14").path, width: 50%),
)
#figure(
  image(images.at("2.15").path, width: 50%),
)

- Some marine invertebrates (e.g., Tigriopus) rapidly adjust osmotic potential by synthesizing or degrading amino acids.

#figure(
  image(images.at("2.16").path, width: 50%),
)

= Nitrogen Excretion

- Aquatic animals excrete ammonia (#ce("NH_3")) rapidly in dilute urine.
- Terrestrial animals excrete urea (#ce("CO(NH_2)_2")) or uric acid (#ce("C_5H_4N_4O_3")) to conserve water.
- Excreting urea and uric acid is energetically costly.

= Summary

- Water is the basic medium of life and a powerful solvent.
- Water resists temperature changes and provides buoyancy.
- All natural waters contain dissolved substances.
- pH affects nutrient availability and toxicity.
- Soil structure and water potential determine water availability to plants.
- Plants and animals have adaptations for water and salt balance.
- Nitrogen excretion strategies vary by environment.
